import { createRouter, createWebHistory } from 'vue-router'

export const router = createRouter({
  history: createWebHistory(),
  scrollBehavior: () => ({ top: 0 }),
  routes: [
    { path: '/', component: () => import('@/views/HomeView.vue') },
    { path: '/projects', component: () => import('@/views/ProjectsView.vue') },
    { path: '/ppt', component: () => import('@/views/PptListView.vue') },
    { path: '/ppt/:id', component: () => import('@/views/PptStudioView.vue') },
    { path: '/knowledge/history', component: () => import('@/views/KnowledgeHistoryView.vue') },
    { path: '/knowledge/:conversationId?', component: () => import('@/views/KnowledgeView.vue') },
    { path: '/designer', component: () => import('@/views/DesignerView.vue') },
    { path: '/designs', component: () => import('@/views/DesignerHistoryView.vue') },
    { path: '/tasks', component: () => import('@/views/TasksView.vue') },
    { path: '/inbox', component: () => import('@/views/InboxView.vue') },
    { path: '/insights', component: () => import('@/views/InsightsDashboardView.vue') },
    { path: '/automations', redirect: '/template-tasks' },
    { path: '/template-tasks', component: () => import('@/views/TemplateTasksView.vue') },
    { path: '/template-tasks/document-runs/:id', component: () => import('@/views/DocumentTemplateView.vue') },
    { path: '/template-tasks/source-runs/:id', component: () => import('@/views/SourceTemplateView.vue') },
    { path: '/tasks/:id', component: () => import('@/views/TaskDetailView.vue') },
    { path: '/tasks/:id/recovery', component: () => import('@/views/RecoveryStudioView.vue') },
    { path: '/tasks/:id/design', component: () => import('@/views/TaskDesignHistoryView.vue') },
    { path: '/runtime', component: () => import('@/views/RuntimeView.vue') },
    { path: '/tools', component: () => import('@/views/ToolsView.vue') },
    { path: '/databases', component: () => import('@/views/DatabaseView.vue') },
    { path: '/settings', component: () => import('@/views/SettingsView.vue') },
    { path: '/settings/roles', redirect: '/roles' },
    { path: '/roles', component: () => import('@/views/RoleManagementView.vue') },
    { path: '/:pathMatch(.*)*', redirect: '/' },
  ],
})
