import { createRouter, createWebHistory } from 'vue-router'
import { designerEntry } from './designerEntry'

export const router = createRouter({
  history: createWebHistory(),
  scrollBehavior: () => ({ top: 0 }),
  routes: [
    { path: '/', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/projects', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/ppt', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/ppt/:id', component: () => import('@/views/PptStudioView.vue') },
    { path: '/knowledge/history', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/knowledge/:conversationId?', component: () => import('@/views/KnowledgeView.vue') },
    { path: '/designer', beforeEnter: designerEntry, props: { historyOnly: true }, component: () => import('@/views/DesignerView.vue') },
    { path: '/requirements', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/requirements/new', component: () => import('@/views/WorkflowRequirementNewView.vue') },
    { path: '/requirements/:id', component: () => import('@/views/WorkflowRequirementView.vue') },
    { path: '/workflows', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/workflows/new', component: () => import('@/views/WorkflowEditorView.vue') },
    { path: '/workflows/:id', component: () => import('@/views/WorkflowEditorView.vue') },
    { path: '/designs', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/tasks', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/inbox', component: () => import('@/views/InboxView.vue') },
    { path: '/insights', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/automations', redirect: '/template-tasks' },
    { path: '/template-tasks', component: () => import('@/views/TemplateTasksView.vue') },
    { path: '/template-tasks/document-runs/:id', component: () => import('@/views/DocumentTemplateView.vue') },
    { path: '/template-tasks/source-runs/:id', component: () => import('@/views/SourceTemplateView.vue') },
    { path: '/tasks/:id', component: () => import('@/views/TaskDetailView.vue') },
    { path: '/tasks/:id/recovery', component: () => import('@/views/RecoveryStudioView.vue') },
    { path: '/tasks/:id/design', component: () => import('@/views/TaskDesignHistoryView.vue') },
    { path: '/runtime', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/tools', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/databases', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/settings', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/settings/roles', redirect: '/roles' },
    { path: '/roles', component: () => import('@/migration/W2RouteBridge.vue') },
    { path: '/:pathMatch(.*)*', redirect: '/' },
  ],
})
