<script setup lang="ts">
import type { WorkflowGraph, WorkflowInput, WorkflowNode, WorkflowOutput } from '@/types/domain'
import WorkflowReviewSourceEditor from './WorkflowReviewSourceEditor.vue'
import WorkflowRolePicker from './WorkflowRolePicker.vue'
import WorkflowVerificationEditor from './WorkflowVerificationEditor.vue'
import WorkflowCommandEditor from './WorkflowCommandEditor.vue'
import WorkflowSourceDesignEditor from './WorkflowSourceDesignEditor.vue'
import WorkflowDocumentReviewEditor from './WorkflowDocumentReviewEditor.vue'
import { outcomeTitle, outcomeTitles } from './graph'
import { computed } from 'vue'
const props = defineProps<{ node: WorkflowNode; graph: WorkflowGraph; disabled?: boolean; removeDisabled?: boolean; readonlyReason?: string }>()
const emit = defineEmits<{ change: [node: WorkflowNode]; remove: []; roleLabel: [id: string, label: string] }>()
const patch = (value: Partial<WorkflowNode>) => { if (!props.disabled) emit('change', { ...props.node, ...value }) }
const sourceDesign = computed(() => ['source.design', 'source.design-review', 'source.test-design'].includes(props.node.moduleId || ''))
const snapshotWork = computed(() => ['snapshot.analyze', 'snapshot.review'].includes(props.node.moduleId || ''))
const historyAnalysis = computed(() => ['history.review', 'history.contribution'].includes(props.node.moduleId || ''))
const documentReview = computed(() => ['document.direct-review', 'document.direct-review-check'].includes(props.node.moduleId || ''))
const testReview = computed(() => props.node.moduleId === 'source.test-review')
const testWriter = computed(() => props.node.moduleId === 'source.test-write')
const output = (index: number, value: Partial<WorkflowOutput>) => patch({ outputs: props.node.outputs.map((o, i) => i === index ? { ...o, ...value } : o) })
const input = (index: number, value: Partial<WorkflowInput>) => patch({ inputs: props.node.inputs.map((o, i) => i === index ? { ...o, ...value } : o) })
const kinds = { TEXT: '文本', JSON: '结构化数据', DOCUMENT: '文档', CODE: '代码', DECISION: '业务判断', PLAN: '候选计划', CONTROL: '控制记录' }
const availableKinds = computed(() => Object.entries(kinds).filter(([kind]) => kind !== 'DOCUMENT' && (kind !== 'PLAN' || props.node.kind === 'WORK' && props.node.moduleId === 'free.readonly') && (kind !== 'CODE' || ['free.write', 'source.test-write'].includes(props.node.moduleId || ''))))
function addOutcome() {
  const key = `result_${crypto.randomUUID().slice(0, 8)}`
  patch({ outcomes: [...props.node.outcomes, key], parameters: { ...props.node.parameters, outcomeTitles: JSON.stringify({ ...outcomeTitles(props.node), [key]: '新业务结果' }) } })
}
function removeOutcome(key: string) {
  if (props.graph.edges.some(edge => edge.from === props.node.id && edge.outcome === key) || props.node.completion.expectedOutcome === key) { window.alert('这个结果仍被完成规则或后续连接使用，请先调整。'); return }
  const labels = outcomeTitles(props.node); delete labels[key]
  const parameters = { ...props.node.parameters, outcomeTitles: JSON.stringify(labels) }
  patch({ outcomes: props.node.outcomes.filter(value => value !== key), parameters })
}
function bind(index: number, selected: string) {
  const [source, id, name] = selected.split('|')
  if (!id || !name) return
  const output = source === 'NODE' ? props.graph.nodes.find(n => n.id === id)?.outputs.find(o => o.name === name) : props.graph.inputs.find(o => o.name === name)
  if (!output) return
  input(index, { source: source === 'NODE' ? 'NODE' : 'REQUIREMENT', sourceId: id, output: source === 'NODE' ? name : null, kind: output.kind })
}
</script>
<template>
  <aside class="workflow-inspector" aria-label="节点设置"><header><h2>节点设置</h2><button :disabled="removeDisabled ?? disabled" class="danger" @click="emit('remove')">删除节点</button></header><p v-if="readonlyReason" class="workflow-inspector-hint">{{ readonlyReason }}</p>
    <fieldset :disabled="disabled" class="workflow-fields"><label>名称<input :value="node.title" maxlength="120" @input="patch({ title: ($event.target as HTMLInputElement).value })" /></label>
      <label>任务说明<textarea :value="node.task" rows="5" placeholder="描述这个节点要完成的具体工作" @input="patch({ task: ($event.target as HTMLTextAreaElement).value })" /></label>
    </fieldset>
    <WorkflowRolePicker v-if="node.kind === 'WORK'" :node="node" :disabled="disabled" @change="(roleId, roleRevisionId) => patch({ roleId, roleRevisionId })" @label="(id, label) => emit('roleLabel', id, label)" />
    <fieldset :disabled="disabled" class="workflow-fields"><legend>输入来源</legend>
      <div v-for="(item, index) in node.inputs" :key="index" class="workflow-binding">
        <label>输入名称<input :value="item.name" @input="input(index, { name: ($event.target as HTMLInputElement).value })" /></label>
        <label>使用交付物<select :value="`${item.source}|${item.sourceId}|${item.output || item.sourceId}`" @change="bind(index, ($event.target as HTMLSelectElement).value)"><option value="">选择前置交付物</option><optgroup v-for="source in graph.nodes.filter(n => n.id !== node.id)" :key="source.id" :label="source.title"><option v-for="out in source.outputs" :key="out.name" :value="`NODE|${source.id}|${out.name}`">{{ out.title || out.name }}</option></optgroup><optgroup v-if="graph.inputs.length" label="任务公共资料"><option v-for="item in graph.inputs" :key="item.name" :value="`REQUIREMENT|${item.name}|${item.name}`">{{ item.title }}</option></optgroup></select></label>
        <div class="workflow-inline"><label><input type="checkbox" :checked="item.required" @change="input(index, { required: ($event.target as HTMLInputElement).checked })" />必需</label><button @click="patch({ inputs: node.inputs.filter((_, i) => i !== index) })">移除输入</button></div>
      </div>
      <button @click="patch({ inputs: [...node.inputs, { name: `input${node.inputs.length + 1}`, source: 'NODE', sourceId: '', output: '', kind: 'TEXT', required: true }] })">＋ 添加输入</button>
    </fieldset>
    <WorkflowCommandEditor v-if="node.moduleId === 'system.verify.command'" :node="node" :disabled="disabled" @change="value => emit('change', value)" />
    <WorkflowVerificationEditor v-if="node.moduleId === 'system.verify.files'" :node="node" :disabled="disabled" @change="value => emit('change', value)" />
    <WorkflowReviewSourceEditor v-if="node.moduleId === 'system.review.snapshot'" :node="node" :disabled="disabled" @change="value => emit('change', value)" />
    <fieldset v-if="node.moduleId === 'system.git.history'" :disabled="disabled" class="workflow-fields"><legend>Git 历史采集</legend><label>采集时限（秒）<input type="number" min="10" max="600" :value="node.parameters.historyTimeoutSeconds || '600'" @input="patch({ parameters: { ...node.parameters, historyTimeoutSeconds: ($event.target as HTMLInputElement).value } })" /></label><p>分支和日期来自所选输入，日期按北京时间计算并包含结束日。重试保留原提交和范围；分析新的历史时新增采集节点。</p></fieldset>
    <fieldset v-if="node.moduleId === 'system.repository.snapshot'" :disabled="disabled" class="workflow-fields"><legend>分支代码采集</legend><label>采集时限（秒）<input type="number" min="10" max="600" :value="node.parameters.repositoryTimeoutSeconds || '180'" @input="patch({ parameters: { ...node.parameters, repositoryTimeoutSeconds: ($event.target as HTMLInputElement).value } })" /></label><p>分支来自所选输入。采集开始时固定提交，重试沿用该提交；需要新版本时新增采集节点。</p></fieldset>
    <fieldset v-if="node.moduleId === 'system.source.snapshot'" :disabled="disabled" class="workflow-fields"><legend>源码采集</legend><label>采集用途<select :value="node.parameters.sourcePurpose || 'DESIGN'" @change="patch({ parameters: { ...node.parameters, sourcePurpose: ($event.target as HTMLSelectElement).value } })"><option value="DESIGN">设计与分析</option><option value="UNIT_TEST">单元测试（已有测试作为上下文）</option></select></label><p>路径来自所选输入资料，支持项目内单文件或目录。重试沿用已冻结版本；需要采集新代码时修改计划并新增节点。</p></fieldset>
    <fieldset v-if="['system.source.design-document', 'system.document.review-report'].includes(node.moduleId || '')" :disabled="disabled" class="workflow-fields"><legend>文档汇总</legend><label>独立复核策略<select :value="node.parameters.reviewPolicy || 'REQUIRED'" @change="patch({ parameters: { ...node.parameters, reviewPolicy: ($event.target as HTMLSelectElement).value } })"><option value="REQUIRED">每份稿件均须复核通过</option><option value="NONE">不要求复核，文档保留实际复核情况</option></select></label><p v-if="node.moduleId === 'system.document.review-report'">须覆盖全部固定原文章节。复核需要读取全部关联稿件；未复核或要求修正的情况会如实保留。</p><p v-else>须覆盖所绑定源码的全部适用目标。多批设计请在输入来源中绑定全部设计稿及对应复核。</p></fieldset>
    <section v-if="node.moduleId === 'system.snapshot.plan'" class="workflow-fields"><h3>版本审查分批</h3><p>在后面连接分析、可选的条件复核和报告配置。程序完整划分固定代码，继承角色、任务、重试和检查点；候选先由你确认。</p></section>
    <fieldset v-if="node.moduleId === 'system.snapshot.report'" :disabled="disabled" class="workflow-fields"><legend>版本审查报告</legend><label>候选问题复核策略<select aria-label="版本报告复核策略" :value="node.parameters.reviewPolicy || 'REQUIRED'" @change="patch({ parameters: { ...node.parameters, reviewPolicy: ($event.target as HTMLSelectElement).value } })"><option value="REQUIRED">有候选问题的批次须完成独立复核</option><option value="NONE">不要求复核，保留候选及实际复核情况</option></select></label><p>绑定全部已完成分析及适用的复核结果。无问题分支跳过复核；取消复核后，未复核的问题仍作为候选保留。</p></fieldset>
    <section v-if="node.moduleId === 'system.history.plan'" class="workflow-fields"><h3>历史分批</h3><p>在后面连接一份审查、可选的一份个人评价和一份报告配置。程序按完整历史生成候选，继承角色、重试和检查点；确认后执行。</p></section>
    <fieldset v-if="node.moduleId === 'system.history.report'" :disabled="disabled" class="workflow-fields"><legend>历史报告</legend><label>报告类型<select aria-label="历史报告类型" :value="node.parameters.historyReportKind || 'CODE_REVIEW'" @change="patch({ parameters: { ...node.parameters, historyReportKind: ($event.target as HTMLSelectElement).value } })"><option value="CODE_REVIEW">历史提交审查</option><option value="CONTRIBUTION_REPORT">项目贡献周报</option></select></label><p>绑定全部已完成审查。贡献周报还需覆盖适用人员的评价；报告格式和计分由程序持有。</p></fieldset>
    <section v-if="node.moduleId === 'system.document.review-plan'" class="workflow-fields"><h3>原文分批</h3><p>在后面连接一份评审、可选的一份复核和一份报告汇总配置。程序完整划分原文章节并继承配置；候选先由你确认。</p></section>
    <section v-if="node.moduleId === 'system.source.design-plan'" class="workflow-fields"><h3>分批规划</h3><p>在后面连接一份编写、可选的一份复核和一份文档汇总配置。程序按全部冻结源码细化批次，保留角色版本、任务、重试和检查点；候选先由你确认。</p></section>
    <section v-if="node.moduleId === 'system.source.test-plan'" class="workflow-fields"><h3>单测分批规划</h3><p>按全部冻结源码与测试模块生成批次，保留后续角色、任务和检查点。代码逐批继承，全部编写后测试最终代码；候选先由你确认。</p></section>
    <fieldset v-if="node.moduleId === 'system.source.test-summary'" :disabled="disabled" class="workflow-fields"><legend>单测汇总</legend><label>独立复核策略<select aria-label="单测独立复核策略" :value="node.parameters.reviewPolicy || 'DUAL'" @change="patch({ parameters: { ...node.parameters, reviewPolicy: ($event.target as HTMLSelectElement).value } })"><option value="DUAL">每批两位独立角色复核通过</option><option value="SINGLE">每批一份独立复核通过</option><option value="NONE">不要求复核</option></select></label><p>汇总完整源码范围。全部模块测试须绑定同一份最终代码；移除复核节点时，请同步选择完成策略。</p></fieldset>
    <fieldset v-if="node.moduleId === 'system.source.test-profile'" :disabled="disabled" class="workflow-fields"><legend>测试配置识别</legend><label>测试输出目录（可选）<input :value="node.parameters.testOutputPath || ''" maxlength="2048" placeholder="留空使用项目原生测试目录" @input="patch({ parameters: { ...node.parameters, testOutputPath: ($event.target as HTMLInputElement).value } })" /></label><p>绑定“单元测试”用途的冻结源码。指定目录只能缩小已识别的测试源码范围；多模块使用各模块原生目录。</p></fieldset>
    <fieldset v-if="node.moduleId === 'system.source.test-run'" :disabled="disabled" class="workflow-fields" aria-label="原生单测设置"><legend>原生单测设置</legend><label>测试模块路径<input aria-label="测试模块路径" :value="node.parameters.testModuleRoot || '.'" maxlength="2048" @input="patch({ parameters: { ...node.parameters, testModuleRoot: ($event.target as HTMLInputElement).value } })" /></label><label>执行时限（秒）<input type="number" min="1" max="3600" :value="node.parameters.testTimeoutSeconds || '600'" @input="patch({ parameters: { ...node.parameters, testTimeoutSeconds: ($event.target as HTMLInputElement).value } })" /></label><p>命令从固定测试配置生成。根模块填写“.”，多模块分别添加节点并填写对应路径；<template v-if="node.moduleVersion === 2">各批场景须属于这份最终代码的继承链，可追加其他场景输入。</template><template v-else>源码、配置和场景须与代码来自同一次单测编写。</template></p></fieldset>
    <section v-if="testReview" class="workflow-fields"><h3>场景覆盖复核</h3><p>绑定同一次原生测试的源码、配置、场景、代码与报告，逐场景核对真实测试和固定断言。可按业务需要选择复核通过后继续，或保留返修意见继续其他分支。</p></section>
    <section v-if="testWriter" class="workflow-fields"><h3>单测编写范围</h3><p>使用所绑定场景设计的源码范围，仅补充原生测试与夹具。已有测试须保留；代码和范围检查由程序在停止后保存。</p></section>
    <fieldset v-if="historyAnalysis" :disabled="disabled" class="workflow-fields"><legend>历史分析范围</legend><label v-if="node.moduleId === 'history.review'">审查批次（从 1 开始）<input aria-label="历史审查批次" type="number" min="1" max="100001" :value="Number(node.parameters.historyBatchOrdinal || '0') + 1" @change="patch({ parameters: { ...node.parameters, historyBatchOrdinal: String(Number(($event.target as HTMLInputElement).value) - 1) } })" /></label><label v-else>贡献者邮箱<input aria-label="贡献者邮箱" :value="node.parameters.historyContributorEmail || ''" maxlength="2000" placeholder="固定历史中经 mailmap 归一化的邮箱" @input="patch({ parameters: { ...node.parameters, historyContributorEmail: ($event.target as HTMLInputElement).value } })" /></label><p>使用前置节点的固定历史资料。贡献评价需绑定覆盖本人全部变更的审查结果；可在输入来源中追加其他审查批次。</p></fieldset>
    <fieldset v-if="snapshotWork" :disabled="disabled" class="workflow-fields"><legend>版本代码审查</legend><label v-if="node.moduleId === 'snapshot.analyze'">分析批次（从 1 开始）<input aria-label="版本分析批次" type="number" min="1" max="100001" :value="Number(node.parameters.snapshotBatchOrdinal || '0') + 1" @change="patch({ parameters: { ...node.parameters, snapshotBatchOrdinal: String(Number(($event.target as HTMLInputElement).value) - 1) } })" /></label><p v-if="node.moduleId === 'snapshot.analyze'">按固定资料的容量批次分析，交付“存在候选问题”或“没有候选问题”。可将前者连接到独立复核。</p><p v-else>绑定同一份固定资料和已完成分析，仅复核其中的候选问题。无需复核时可以删除本节点。</p><template v-if="node.moduleId === 'snapshot.analyze'"><label>历史分析复用<select aria-label="历史分析复用" :value="node.parameters.snapshotReuse || 'ALLOW'" @change="patch({ parameters: { ...node.parameters, snapshotReuse: ($event.target as HTMLSelectElement).value } })"><option value="ALLOW">条件完全一致时复用</option><option value="BYPASS">每次重新分析（返修或资格验收）</option></select></label><p>仅复用固定资料及角色配置完全一致的无问题分析。有可变知识来源授权时自动重新执行。</p></template></fieldset>
    <WorkflowDocumentReviewEditor v-if="documentReview" :node="node" :disabled="disabled" @change="value => emit('change', value)" />
    <WorkflowSourceDesignEditor v-if="sourceDesign" :node="node" :disabled="disabled" @change="value => emit('change', value)" />
    <section v-if="node.kind === 'SYSTEM' || sourceDesign || testWriter || testReview || documentReview || historyAnalysis || snapshotWork" class="workflow-fields workflow-fixed-outputs" :aria-label="sourceDesign || testWriter || testReview || documentReview || historyAnalysis || snapshotWork ? '专业交付物' : '程序交付物'"><h3>{{ sourceDesign || testWriter || testReview || documentReview || historyAnalysis || snapshotWork ? '专业交付物' : '程序交付物' }}</h3><div v-for="item in node.outputs" :key="item.name"><span>{{ item.title }}</span><small>{{ kinds[item.kind] }}</small></div></section>
    <fieldset v-else :disabled="disabled" class="workflow-fields"><legend>预期交付物</legend>
      <div v-for="(item, index) in node.outputs" :key="index" class="workflow-binding"><label>交付名称<input :value="item.title" @input="output(index, { title: ($event.target as HTMLInputElement).value })" /></label><label>引用名称<input :value="item.name" @input="output(index, { name: ($event.target as HTMLInputElement).value })" /></label><label>内容类型<select :value="item.kind" @change="output(index, { kind: ($event.target as HTMLSelectElement).value as WorkflowOutput['kind'] })"><option v-if="!availableKinds.some(([kind]) => kind === item.kind)" :value="item.kind" disabled>{{ kinds[item.kind] }}（需对应工作模块）</option><option v-for="[kind, label] in availableKinds" :key="kind" :value="kind">{{ label }}</option></select></label><div class="workflow-inline"><label><input type="checkbox" :checked="item.required" @change="output(index, { required: ($event.target as HTMLInputElement).checked })" />必需</label><button @click="patch({ outputs: node.outputs.filter((_, i) => i !== index) })">移除交付物</button></div></div>
      <button @click="patch({ outputs: [...node.outputs, { name: `output${node.outputs.length + 1}`, title: '新交付物', kind: 'TEXT', required: true }] })">＋ 添加交付物</button>
    </fieldset>
    <fieldset :disabled="disabled" class="workflow-fields"><legend>完成规则</legend>
      <p v-if="node.moduleId === 'system.review.snapshot'">版本、范围及完整证据保存且采集进程停止后完成；审查结论由后续节点交付。</p><p v-else-if="node.moduleId === 'system.git.history'">完整历史证据保存且采集进程停止后完成；空范围保存无提交说明。</p><p v-else-if="node.moduleId === 'system.repository.snapshot'">固定提交与完整文件清单保存成功，且采集进程停止后完成。</p><p v-else-if="node.moduleId === 'system.source.snapshot'">全部适用目标均已完整采集并冻结后完成。</p><p v-else-if="['system.source.design-plan', 'system.source.test-plan', 'system.document.review-plan', 'system.history.plan', 'system.snapshot.plan'].includes(node.moduleId || '')">完整生成候选计划后完成；应用计划与开始执行由你确认。</p><p v-else-if="node.moduleId === 'system.source.test-profile'">全部目标源码的测试配置识别完成；实际测试由后续节点执行。</p><p v-else-if="['system.source.design-document', 'system.document.review-report'].includes(node.moduleId || '')">生成完整文档后完成，复核是否必需由上方策略决定。</p><p v-else-if="node.moduleId === 'system.snapshot.report'">全部可审查片段分析完成，适用复核符合所选策略，完整报告保存后完成。</p><p v-else-if="node.moduleId === 'system.history.report'">全部适用分析完整覆盖，且固定报告保存成功后完成。</p><label v-else>完成方式<select :value="node.completion.kind" @change="patch({ completion: { ...node.completion, kind: ($event.target as HTMLSelectElement).value as WorkflowNode['completion']['kind'] } })"><option value="DELIVERABLES">{{ node.kind === 'SYSTEM' ? '完成检查后继续（允许检查未通过）' : '提交有效交付物' }}</option><option v-if="node.kind === 'SYSTEM'" value="VERIFIED">全部程序检查通过</option><option v-if="!['source.design', 'source.test-design', 'source.test-write', 'document.direct-review', 'history.review', 'history.contribution', 'snapshot.analyze', 'snapshot.review'].includes(node.moduleId || '')" value="OUTCOME">取得指定业务结果</option><option v-if="node.kind === 'HUMAN'" value="HUMAN">人工确认</option></select></label>
      <label>完成标准<textarea :value="node.completion.criterion" rows="2" @input="patch({ completion: { ...node.completion, criterion: ($event.target as HTMLTextAreaElement).value } })" /></label>
      <div v-for="outcome in node.outcomes" :key="outcome" class="workflow-binding"><label>业务结果名称<input :value="outcomeTitle(node, outcome)" maxlength="120" @input="patch({ parameters: { ...node.parameters, outcomeTitles: JSON.stringify({ ...outcomeTitles(node), [outcome]: ($event.target as HTMLInputElement).value }) } })" /></label><button v-if="node.kind !== 'SYSTEM' && !sourceDesign && !testWriter && !testReview && !documentReview && !historyAnalysis && !snapshotWork" @click="removeOutcome(outcome)">移除结果</button></div><button v-if="node.kind !== 'SYSTEM' && !sourceDesign && !testWriter && !testReview && !documentReview && !historyAnalysis && !snapshotWork" :disabled="node.outcomes.length >= 32" @click="addOutcome">＋ 添加业务结果</button>
      <label v-if="node.completion.kind === 'OUTCOME'">成功结果<select :value="node.completion.expectedOutcome || ''" @change="patch({ completion: { ...node.completion, expectedOutcome: ($event.target as HTMLSelectElement).value } })"><option value="">选择结果</option><option v-for="outcome in node.outcomes" :key="outcome" :value="outcome">{{ outcomeTitle(node, outcome) }}</option></select></label>
      <label>失败自动重试次数<input type="number" min="0" max="10" :value="node.maxRetries" @change="patch({ maxRetries: Number(($event.target as HTMLInputElement).value) })" /></label>
      <label><input type="checkbox" :checked="node.pauseAfter" @change="patch({ pauseAfter: ($event.target as HTMLInputElement).checked })" />执行后暂停检查</label>
    </fieldset>
  </aside>
</template>
