<script setup lang="ts">
import CodeMergeEditor from '@/components/CodeMergeEditor.vue'
import WorkflowDocumentInput from './WorkflowDocumentInput.vue'
import WorkflowBranchInput from './WorkflowBranchInput.vue'
import type { WorkflowOutput } from '@/types/domain'
const props = defineProps<{ fields: WorkflowOutput[]; values: Record<string, string>; disabled?: boolean; dateFields?: string[]; repositoryContext?: { project: string; fields: string[] }; uploadContext?: { requirement: string; version: number; revision: number } }>()
const emit = defineEmits<{ change: [value: Record<string, string>]; busy: [value: boolean]; pending: [value: boolean] }>()
const busy = new Set<string>(), pending = new Set<string>()
function uploadBusy(name: string, value: boolean) { if (value) busy.add(name); else busy.delete(name); emit('busy', busy.size > 0) }
function uploadPending(name: string, value: boolean) { if (value) pending.add(name); else pending.delete(name); emit('pending', pending.size > 0) }
function set(name: string, value: string) { if (!props.disabled) emit('change', { ...props.values, [name]: value }) }
</script>
<template><div class="workflow-fields"><div v-for="field in fields" :key="field.name"><template v-if="field.kind === 'DOCUMENT' && uploadContext"><p>{{ field.title }}{{ field.required ? '（必填）' : '（可选）' }}</p><WorkflowDocumentInput :key="`${uploadContext.requirement}-${field.name}`" v-bind="uploadContext" :value="values[field.name] || ''" :title="field.title" :disabled="disabled" @change="value => emit('change', { ...values, [field.name]: value })" @busy="value => uploadBusy(field.name, value)" @pending="value => uploadPending(field.name, value)" /></template><template v-else-if="field.kind === 'TEXT' && repositoryContext?.fields.includes(field.name)"><p>{{ field.title }}{{ field.required ? '（必填）' : '（可选）' }}</p><WorkflowBranchInput :project="repositoryContext.project" :value="values[field.name] || ''" :title="field.title" :disabled="disabled" @change="value => set(field.name, value)" /></template><label v-else>{{ field.title }}{{ field.required ? '（必填）' : '（可选）' }}<input v-if="field.kind === 'TEXT' && dateFields?.includes(field.name)" type="date" min="1900-01-01" max="9998-12-31" :aria-label="field.title" :aria-required="field.required" :value="values[field.name] || ''" :disabled="disabled" @input="set(field.name, ($event.target as HTMLInputElement).value)" /><textarea v-else-if="field.kind === 'TEXT'" :aria-label="field.title" :aria-required="field.required" :value="values[field.name] || ''" :disabled="disabled" rows="4" @input="set(field.name, ($event.target as HTMLTextAreaElement).value)" /><CodeMergeEditor v-else :model-value="values[field.name] || ''" language="json" :readonly="disabled" :aria-label="field.title" @update:model-value="value => set(field.name, value)" /></label></div></div></template>
