import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ApiError } from '@/api/client'
import { workflowRuns } from '@/api/workflowRuns'
import { workflowPublication } from '@/api/workflowPublication'
import { workflowPush } from '@/api/workflowPush'
import { workflowWriteback } from '@/api/workflowWriteback'
import { createNodeController } from './nodeController'
import { createCandidatesController } from './candidatesController'
import { createFinishController } from './finishController'
import { createPublicationController } from './publicationController'
import { createSaveTemplateController } from './templateController'
import { createRequirementController } from './controller'
import { mockRequirementReads, requirement, attempt, candidate, receipt, deferred, publicationPreview, pushPreview, writebackPreview } from './test-support'

const owners: Array<{ retire(forced: boolean): unknown }> = []
const keep = <T extends { attachView(): () => void; retire(forced: boolean): unknown; setStart(callback: () => void): void }>(owner: T): T => { owners.push(owner); owner.setStart(() => {}); owner.attachView(); return owner }
beforeEach(() => { mockRequirementReads(); vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('unmocked transport forbidden'))) })
afterEach(() => { owners.splice(0).forEach(owner => owner.retire(true)); vi.restoreAllMocks(); vi.unstubAllGlobals() })
const nodeInput = () => ({ version: 7, node: requirement().graph.nodes[0]!, summary: { id: 'review', nodeKey: 'review', state: 'WAITING_INPUT', attemptCount: 1, latestAttemptId: 'run', version: 1, outcome: null } })
async function node() { const owner = keep(createNodeController('req', nodeInput())); await owner.choose('run'); return owner }
async function finish() { const owner = keep(createFinishController('req', { version: 7, state: 'RUNNING' })); await owner.refresh(); owner.show(); owner.change({ target: 'COMPLETED', reason: '原提前结束原因' }); return owner }
function publication() { const owner = keep(createPublicationController('req', 2)); owner.patch({ preview: publicationPreview(), commitLoaded: true, message: '原提交说明', pushLoaded: true, pushPreview, remote: 'origin', writebackLoaded: true, checked: writebackPreview }); return owner }

describe('six child writers retain exact protocol/guard/accepted readback', () => {
  for (const phase of ['SENDING', 'UNKNOWN'] as const) for (const kind of ['human', 'candidate', 'finish', 'commit', 'push', 'writeback'] as const) it(`${kind}/${phase} preserves original body/key and hard-blocks its owner`, async () => {
    const pending = deferred<never>()
    const tick = async () => { await Promise.resolve(); await Promise.resolve() }
    if (kind === 'human') { const owner = await node(); owner.change({ humanSummary: '原人工说明', values: { result: '原交付' } }); const write = vi.spyOn(workflowRuns, 'complete').mockReturnValue(pending.promise); const action = owner.complete(); await tick(); if (phase === 'UNKNOWN') { pending.reject(new Error('lost')); await action }; expect(owner.getSnapshot().command.phase).toBe(phase); expect(owner.canLeave().kind).toBe('BLOCK'); expect(write.mock.calls[0]).toEqual(['req', 'review', { requestKey: expect.any(String), expectedVersion: 7, attemptId: 'run', expectedAttemptVersion: 1, delivery: { summary: '原人工说明', outcome: null, outputs: { result: { kind: 'TEXT', content: '原交付' } } } }]); expect(owner.operationIdentity()!.endpoint).toBe('/workflows/requirements/req/nodes/review/human/complete'); if (phase === 'UNKNOWN') { owner.change({ humanSummary: 'other' }); await owner.recover(); expect(write.mock.calls[1]![2]).toBe(write.mock.calls[0]![2]) } }
    if (kind === 'candidate') { const owner = keep(createCandidatesController('req')); await owner.read('candidate'); owner.changeReason('原退回原因'); const write = vi.spyOn(workflowRuns, 'rejectCandidate').mockReturnValue(pending.promise), action = owner.reject(); await tick(); if (phase === 'UNKNOWN') { pending.reject(new Error('lost')); await action }; expect(owner.canLeave().kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe(phase); expect(write.mock.calls[0]).toEqual(['req', 'candidate', { requestKey: expect.any(String), expectedCandidateVersion: 0, reason: '原退回原因' }]); if (phase === 'UNKNOWN') { await owner.recover(); expect(write.mock.calls[1]![2]).toBe(write.mock.calls[0]![2]) } }
    if (kind === 'finish') { const owner = await finish(), write = vi.spyOn(workflowRuns, 'finish').mockReturnValue(pending.promise), action = owner.submit(); await tick(); if (phase === 'UNKNOWN') { pending.reject(new Error('lost')); await action }; expect(owner.canLeave().kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe(phase); expect(write.mock.calls[0]).toEqual(['req', { requestKey: expect.any(String), expectedVersion: 7, target: 'COMPLETED', reason: '原提前结束原因' }]); if (phase === 'UNKNOWN') { await owner.recover(); expect(write.mock.calls[1]![1]).toBe(write.mock.calls[0]![1]) } }
    if (kind === 'commit') { const owner = publication(), write = vi.spyOn(workflowPublication, 'confirm').mockReturnValue(pending.promise), action = owner.commit(); await tick(); if (phase === 'UNKNOWN') { pending.reject(new Error('lost')); await action }; expect(owner.canLeave().kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe(phase); expect(write.mock.calls[0]).toEqual(['req', { requestKey: expect.any(String), expectedVersion: 7, revision: 2, node: 'work', attempt: 'original-attempt', output: 'code', previewSha256: 'c'.repeat(64), message: '原提交说明' }]); if (phase === 'UNKNOWN') { await owner.recover(); expect(write.mock.calls[1]![1]).toBe(write.mock.calls[0]![1]) } }
    if (kind === 'push') { const owner = publication(), write = vi.spyOn(workflowPush, 'confirm').mockReturnValue(pending.promise), action = owner.push(); await tick(); if (phase === 'UNKNOWN') { pending.reject(new Error('lost')); await action }; expect(owner.canLeave().kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe(phase); expect(write.mock.calls[0]).toEqual(['req', { requestKey: expect.any(String), expectedVersion: 3, remote: 'origin', previewSha256: 'push-sha' }]); if (phase === 'UNKNOWN') { await owner.recover(); expect(write.mock.calls[1]![1]).toBe(write.mock.calls[0]![1]) } }
    if (kind === 'writeback') { const owner = publication(); owner.patch({ preview: publicationPreview('DIRECT') }); const write = vi.spyOn(workflowWriteback, 'confirm').mockReturnValue(pending.promise), action = owner.writeback(); await tick(); if (phase === 'UNKNOWN') { pending.reject(new Error('lost')); await action }; expect(owner.canLeave().kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe(phase); expect(write.mock.calls[0]).toEqual(['req', { requestKey: expect.any(String), expectedVersion: 7, selection: { revision: 2, node: 'work', attempt: 'original-attempt', output: 'code', sourceSha256: 'c'.repeat(64) }, previewSha256: 'writeback-sha' }]); if (phase === 'UNKNOWN') { await owner.recover(); expect(write.mock.calls[1]![1]).toBe(write.mock.calls[0]![1]) } }
  })
  it('actual child registration blocks parent writes and leave while allowing only its own ordinary draft submit', async () => { const parent = keep(createRequirementController('req')); await parent.load(); const child = await finish(); child.bindParent(parent); parent.registerChild(child); expect(parent.canStartWrite()).toBe(false); expect(parent.canStartWrite(child)).toBe(true); vi.spyOn(workflowRuns, 'finish').mockRejectedValue(new Error('unknown')); await child.submit(); expect(parent.canLeave().kind).toBe('BLOCK'); const pause = vi.spyOn(workflowRuns, 'pause'); await parent.pause(); expect(pause).not.toHaveBeenCalled() })
  it('accepted Finish read failure remains accepted and rereads only the real finish endpoint', async () => { const owner = await finish(); const write = vi.spyOn(workflowRuns, 'finish').mockResolvedValue({ ...receipt, state: 'STOPPING', version: 8 }); vi.mocked(workflowRuns.finishStatus).mockRejectedValueOnce(new Error('read')); await owner.submit(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(workflowRuns.finishStatus).toHaveBeenCalledTimes(3) })
  it('human accepted read failure keeps draft until explicit original GET succeeds without completing twice', async () => { const owner = await node(); owner.change({ humanSummary: '原说明', values: { result: '原交付' } }); const write = vi.spyOn(workflowRuns, 'complete').mockResolvedValue(undefined); vi.mocked(workflowRuns.attempt).mockRejectedValueOnce(new Error('read')); await owner.complete(); expect(owner.getSnapshot().humanSummary).toBe('原说明'); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().humanSummary).toBe('') })
  it('command Stop freezes commandVersion 19 rather than requirement or attempt version and never starts a new attempt', async () => { vi.mocked(workflowRuns.attempt).mockResolvedValue(attempt({ state: 'RUNNING', commandState: 'RUNNING', commandVersion: 19, modelVersion: 999 })); const owner = await node(), write = vi.spyOn(workflowRuns, 'commandAction').mockRejectedValue(new Error('lost')), start = vi.spyOn(workflowRuns, 'start'); await owner.process('stop'); expect(write.mock.calls[0]).toEqual(['req', 'review', 'run', 'stop', { requestKey: expect.any(String), expectedVersion: 19 }]); await owner.recover(); expect(write.mock.calls[1]![4]).toBe(write.mock.calls[0]![4]); expect(start).not.toHaveBeenCalled(); expect(owner.canLeave().kind).toBe('BLOCK') })
  it('STOPPING is not success and suspended resume checks the same attempt/modelVersion', async () => { vi.mocked(workflowRuns.attempt).mockResolvedValue(attempt({ state: 'RUNNING', modelState: 'STOPPING', modelVersion: 14, suspended: true })); const owner = await node(), write = vi.spyOn(workflowRuns, 'modelAction').mockRejectedValue(new Error('lost')); await owner.process('stop'); expect(write).not.toHaveBeenCalled(); await owner.process('resume'); expect(write.mock.calls[0]).toEqual(['req', 'review', 'run', 'resume', { requestKey: expect.any(String), expectedVersion: 14 }]) })
  it('manual historic attempt stays selected after a new latest attempt appears; fixed input is cached once', async () => { const owner = await node(); const input = { version: 1, requirementId: 'req', planRevision: 2, nodeId: 'review', objective: 'fixed', values: [] }; const read = vi.spyOn(workflowRuns, 'inputs').mockResolvedValue(input); await owner.loadBody('input'); await owner.loadBody('input'); expect(read).toHaveBeenCalledTimes(1); vi.mocked(workflowRuns.attempt).mockImplementation(async (_req, _node, id) => attempt({ id })); await owner.choose('historic'); owner.updateContext({ ...nodeInput(), summary: { ...nodeInput().summary, latestAttemptId: 'new' } }); expect(owner.getSnapshot().selected).toBe('historic') })
  it('late old attempt definition and command evidence cannot overwrite the selected newer attempt', async () => { const frozen = deferred<ReturnType<typeof requirement>['graph']['nodes'][number]>(); vi.mocked(workflowRuns.definition).mockReturnValueOnce(frozen.promise); const owner = keep(createNodeController('req', nodeInput())), first = owner.choose('run'); await Promise.resolve(); vi.mocked(workflowRuns.attempt).mockResolvedValue(attempt({ id: 'new' })); vi.mocked(workflowRuns.definition).mockResolvedValue({ ...nodeInput().node, title: '新冻结节点' }); await owner.choose('new'); frozen.resolve({ ...nodeInput().node, title: '旧冻结节点' }); await first; expect(owner.details().title).toBe('新冻结节点'); const evidence = deferred<Awaited<ReturnType<typeof workflowRuns.commandEvidence>>>(); vi.spyOn(workflowRuns, 'commandEvidence').mockReturnValue(evidence.promise); const read = owner.loadBody('command'); vi.mocked(workflowRuns.attempt).mockResolvedValue(attempt({ id: 'another' })); await owner.choose('another'); evidence.resolve({ attemptId: 'new', requestSha256: null, resultSha256: null, request: null, registration: null, result: null }); await read; expect(owner.getSnapshot().commandEvidence).toBeNull() })
  it('disconnected activity retains prior actual parts and current disconnect detail', async () => { const owner = await node(); const parts = [{ id: 'part', type: 'text', label: '日志', content: '已保存日志', status: 'done', startedAt: null }]; vi.spyOn(workflowRuns, 'activity').mockResolvedValueOnce({ connected: true, observedAt: '', detail: null, truncated: false, parts }).mockResolvedValue({ connected: false, observedAt: '', detail: '原连接暂断', truncated: true, parts: [] }); await owner.loadBody('activity'); await owner.loadBody('activity'); expect(owner.getSnapshot().activity?.parts).toEqual(parts); expect(owner.getSnapshot().activity?.detail).toBe('原连接暂断') })
  it('keyless blocked retry cannot repeat a POST when status stays ambiguous, then recovers read-only after actual proof', async () => { const pushRead = vi.spyOn(workflowPush, 'status').mockResolvedValue(null), pushWrite = vi.spyOn(workflowPush, 'confirm'); const owner = publication(), original = { requirementId: 'req', state: 'BLOCKED' as const, version: 4, nodeTitle: '实施', outputTitle: '代码', attemptState: 'SUCCEEDED', branch: 'result', message: 'original', commit: null, createdAt: '' }; owner.patch({ commit: original }); const write = vi.spyOn(workflowPublication, 'retry').mockRejectedValue(new Error('lost')); vi.mocked(workflowPublication.status).mockResolvedValue(original); await owner.retry('commit'); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); vi.mocked(workflowPublication.status).mockResolvedValue({ ...original, version: 5, state: 'COMMITTED', commit: 'commit' }); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().command.phase).toBe('SETTLED'); expect(pushRead).toHaveBeenCalledTimes(1); expect(pushRead).toHaveBeenCalledWith('req', expect.any(AbortSignal)); expect(owner.getSnapshot().pushLoaded).toBe(true); expect(owner.getSnapshot().push).toBeNull(); expect(pushWrite).not.toHaveBeenCalled() })
  it('accepted commit GET failure never repeats confirm, and wrong-domain reads preserve accepted BLOCK', async () => { const owner = publication(), committed = { requirementId: 'req', state: 'COMMITTED' as const, version: 1, nodeTitle: '实施', outputTitle: '代码', attemptState: 'SUCCEEDED', branch: 'result', message: 'original', commit: 'commit', createdAt: '' }; const write = vi.spyOn(workflowPublication, 'confirm').mockResolvedValue(committed); vi.mocked(workflowPublication.status).mockResolvedValue({ ...committed, requirementId: 'foreign' }); await owner.commit(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(owner.getSnapshot().commit).toBeNull(); vi.mocked(workflowPublication.status).mockResolvedValue(committed); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().commit?.requirementId).toBe('req') })
  it('reading sources does not inspect network or publish; failed pagination retains the cursor/rows', async () => { const owner = publication(), source = publicationPreview().source; vi.spyOn(workflowPublication, 'sources').mockResolvedValueOnce({ items: [source], nextCursor: 'next' }).mockRejectedValueOnce(new Error('more')).mockResolvedValue({ items: [], nextCursor: null }); const network = vi.spyOn(workflowPush, 'preview'), commit = vi.spyOn(workflowPublication, 'confirm'); await owner.list(); await owner.list(true); expect(owner.getSnapshot().rows).toEqual([source]); expect(owner.getSnapshot().cursor).toBe('next'); owner.retryList(); await Promise.resolve(); expect(workflowPublication.sources).toHaveBeenLastCalledWith('req', 2, 'next', expect.any(AbortSignal)); expect(network).not.toHaveBeenCalled(); expect(commit).not.toHaveBeenCalled() })
  it('unsaved template capture is immutable; mode preview and explicit save retain original preview hash/graph', async () => { const captured = requirement(), owner = keep(createSaveTemplateController('req', { revision: 2, title: captured.title, graph: captured.graph, layout: captured.layout })); const preview = { mode: 'CURRENT' as const, sourceRevision: 2, initialAvailable: false, graph: captured.graph, layout: captured.layout, fixedPlanningNodes: ['review'], sha256: 'template-sha', diagnostics: [] }; vi.spyOn(workflowRuns, 'previewTemplate').mockResolvedValue(preview); const save = vi.spyOn(workflowRuns, 'saveTemplate').mockRejectedValue(new Error('lost')); await owner.read(); captured.graph.nodes[0]!.title = 'external'; owner.mode('INITIAL'); expect(owner.getSnapshot().mode).toBe('CURRENT'); await owner.save(); const original = save.mock.calls[0]![1]; expect(original.selection.graph.nodes[0]!.title).not.toBe('external'); expect(original.previewSha256).toBe('template-sha'); await owner.recover(); expect(save.mock.calls[1]![1]).toBe(original) })
  it('known prewrite Finish version conflict preserves editable reason; unclassified 409 remains unknown', async () => { const owner = await finish(), write = vi.spyOn(workflowRuns, 'finish').mockRejectedValueOnce(new ApiError('版本冲突', 409, { code: 'WORKFLOW_VERSION_CONFLICT' })).mockRejectedValueOnce(new ApiError('无法核对', 409)); await owner.submit(); expect(owner.getSnapshot().command.phase).toBe('SETTLED'); expect(owner.getSnapshot().reason).toBe('原提前结束原因'); expect(owner.canLeave().kind).toBe('CONFIRM_DISCARD'); owner.updateContext({ version: 8, state: 'RUNNING' }); await owner.refresh(); await owner.submit(); expect(write.mock.calls[1]![1].expectedVersion).toBe(8); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); expect(owner.canLeave().kind).toBe('BLOCK') })
  it('known template preview conflict retains text and requires a new legal preview while other 409 stays unknown', async () => { const source = requirement(), owner = keep(createSaveTemplateController('req', { revision: 2, title: source.title, graph: source.graph, layout: source.layout })); vi.spyOn(workflowRuns, 'previewTemplate').mockResolvedValue({ mode: 'CURRENT', sourceRevision: 2, initialAvailable: true, graph: source.graph, layout: source.layout, fixedPlanningNodes: [], sha256: 'preview', diagnostics: [] }); const write = vi.spyOn(workflowRuns, 'saveTemplate').mockRejectedValueOnce(new ApiError('计划变化', 409, { code: 'WORKFLOW_VERSION_CONFLICT' })).mockRejectedValueOnce(new ApiError('unknown', 409)); await owner.read(); owner.change({ title: '原新名称' }); await owner.save(); expect(owner.getSnapshot().title).toBe('原新名称'); expect(owner.getSnapshot().preview).toBeNull(); expect(owner.canLeave().kind).toBe('CONFIRM_DISCARD'); await owner.save(); expect(write).toHaveBeenCalledTimes(1); await owner.read(); await owner.save(); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN') })
  it('closing a safe Publication read aborts original signals and rejects late preview without reshowing context', async () => { const owner = publication(), pending = deferred<ReturnType<typeof publicationPreview>>(), read = vi.spyOn(workflowPublication, 'preview').mockReturnValue(pending.promise); const action = owner.choose(publicationPreview().source); owner.close(); expect(read.mock.calls[0]![3]?.aborted).toBe(true); pending.resolve(publicationPreview()); await action; expect(owner.getSnapshot().open).toBe(false); expect(owner.getSnapshot().preview).toBeNull(); expect(owner.getSnapshot().loading).toBe(false) })
  it('remote changes invalidate an older network preview and ambiguous keyless recovery cannot manufacture success', async () => { const owner = publication(), pending = deferred<typeof pushPreview>(); vi.spyOn(workflowPush, 'preview').mockReturnValue(pending.promise); owner.changeRemote('origin'); const check = owner.checkPush(); owner.changeRemote('other'); pending.resolve(pushPreview); await check; expect(owner.getSnapshot().pushPreview).toBeNull(); expect(owner.getSnapshot().remote).toBe('other') })
  it('two actual registered child drafts remain independently protected after one is settled', async () => { const parent = keep(createRequirementController('req')); await parent.load(); const first = await finish(), second = await node(); second.change({ humanSummary: '第二份草稿' }); first.bindParent(parent); second.bindParent(parent); parent.registerChild(first); parent.registerChild(second); first.discardDraft(); expect(parent.canLeave().kind).toBe('CONFIRM_DISCARD'); expect(parent.canStartWrite()).toBe(false); expect(second.getSnapshot().humanSummary).toBe('第二份草稿'); parent.discardContextDrafts(); expect(second.getSnapshot().humanSummary).toBe(''); expect(parent.contextDecision().kind).toBe('ALLOW') })
  it('candidate historical/stale remains previewable and cannot overwrite live graph without explicit Apply', async () => { const parent = keep(createRequirementController('req')); await parent.load(); const historic = candidate({ state: 'APPLIED', stale: true }); parent.review(historic); expect(parent.proposalReadonly()).toBe(true); const write = vi.spyOn(workflowRuns, 'applyCandidate'); await parent.save(); expect(write).not.toHaveBeenCalled(); expect(parent.getSnapshot().proposal?.state).toBe('APPLIED') })
})
