import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { workflowRuns } from '@/api/workflowRuns'
import { api, ApiError } from '@/api/client'
import { createRequirementController } from './controller'
import { createNewRequirementController } from './newController'
import { requirementFixture, mockRequirementReads, deferred, execution, requirement, receipt } from './test-support'

const owners: Array<{ retire(forced: boolean): unknown }> = [], fixtures: ReturnType<typeof requirementFixture>[] = []
const keep = <T extends { attachView(): () => void; retire(forced: boolean): unknown }>(owner: T): T => { owners.push(owner); owner.attachView(); return owner }
const settle = async () => { for (let i = 0; i < 12; i++) await Promise.resolve() }
beforeEach(() => { mockRequirementReads(); vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('unmocked transport forbidden'))) })
afterEach(() => { owners.splice(0).forEach(owner => owner.retire(true)); fixtures.splice(0).forEach(f => f.dispose()); vi.restoreAllMocks(); vi.unstubAllGlobals() })
describe('new requirement sole frozen create/handoff owner', () => {
  function newOwner() { const fixture = requirementFixture(); fixtures.push(fixture); const owner = keep(createNewRequirementController({ projectId: 'project', navigation: fixture.props.navigation })); return { owner, fixture } }
  it('loads builtin revision/project independently and sends precisely the four fields', async () => { const { owner } = newOwner(); await settle(); owner.change({ title: ' 标题 ', objective: ' 目标 ' }); const write = vi.spyOn(workflowRuns, 'create').mockResolvedValue({ ...receipt, id: 'created' }); await owner.create(); expect(write.mock.calls[0]![0]).toEqual({ requestKey: expect.any(String), title: '标题', objective: '目标', projectId: 'project', templateId: 'example', templateRevision: 3 }); expect(owner.operationIdentity()).toMatchObject({ endpoint: '/workflows/requirements', method: 'POST' }); expect(owner.getSnapshot().knownId).toBe('created') })
  it('independent initial read failures preserve both recoverable errors', async () => { vi.mocked(workflowRuns.project).mockRejectedValue(new Error('project')); const { owner } = newOwner(); await settle(); expect(owner.getSnapshot().projectError).toBeTruthy(); expect(owner.getSnapshot().flow).not.toBeNull() })
  it('unknown ignores changed external fields and retries the identical body reference/key', async () => { const { owner } = newOwner(); await settle(); owner.change({ title: '原标题', objective: '原目标' }); const write = vi.spyOn(workflowRuns, 'create').mockRejectedValue(new Error('lost')); await owner.create(); const original = write.mock.calls[0]![0]; owner.change({ title: '新标题' }); owner.selectProject({ id: 'other', title: '其他项目' }); expect(owner.getSnapshot().title).toBe('原标题'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.recover(); expect(write).toHaveBeenCalledTimes(2); expect(write.mock.calls[1]![0]).toBe(original) })
  for (const outcome of ['false', 'reject'] as const) it(`accepted ${outcome} navigation only recovers original receipt`, async () => { const { owner, fixture } = newOwner(); await settle(); owner.change({ title: '标题', objective: '目标' }); const write = vi.spyOn(workflowRuns, 'create').mockResolvedValue({ ...receipt, id: 'created' }); fixture.props.navigation.goAccepted = outcome === 'false' ? vi.fn().mockResolvedValue(false) : vi.fn().mockRejectedValue(new Error('blocked')); await owner.create(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(owner.getSnapshot().knownId).toBe('created'); fixture.props.navigation.goAccepted = vi.fn().mockResolvedValue(true); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(fixture.props.navigation.goAccepted).toHaveBeenCalledWith('/requirements/created', expect.objectContaining({ destination: '/requirements/created' })) })
  it('retired pending create archives identity and receipt without projecting/starting a second write', async () => { const { owner } = newOwner(); await settle(); owner.change({ title: '标题', objective: '目标' }); const pending = deferred<typeof receipt>(); const write = vi.spyOn(workflowRuns, 'create').mockReturnValue(pending.promise), action = owner.create(); await settle(); const original = owner.operationIdentity(); owner.retire(true); const before = owner.getSnapshot(); pending.resolve(receipt); await action; await owner.create(); expect(owner.operationIdentity()).toBe(original); expect(owner.getSnapshot()).toBe(before); expect(write).toHaveBeenCalledTimes(1) })
})
describe('requirement graph/layout/REST/model/control contracts', () => {
  async function loaded(state: Parameters<typeof execution>[0] = 'PENDING_START') { vi.mocked(workflowRuns.get).mockResolvedValue(requirement({ state })); vi.mocked(workflowRuns.execution).mockResolvedValue(execution(state)); const owner = keep(createRequirementController('req')); owner.setStart(() => {}); await owner.load(); return owner }
  it('confirm and Start stay separate; unsaved viewport survives confirmation', async () => { const owner = await loaded('PLANNING'), viewport = { ...owner.getSnapshot().layout, x: 105, y: 20 }; owner.setLayout(viewport); vi.spyOn(workflowRuns, 'confirm').mockResolvedValue({ ...receipt, version: 4, state: 'PENDING_START' }); vi.mocked(workflowRuns.get).mockResolvedValue(requirement({ version: 4, state: 'PENDING_START' })); const next = execution('PENDING_START'); next.execution.version = 4; next.control.version = 4; vi.mocked(workflowRuns.execution).mockResolvedValue(next); const start = vi.spyOn(workflowRuns, 'start'); await owner.confirm(); expect(start).not.toHaveBeenCalled(); expect(owner.getSnapshot().layout).toEqual(viewport) })
  it('accepted Confirm cannot settle against pre-confirm plan/execution; original receipt only recovers by GET', async () => { const owner = await loaded('PLANNING'); const write = vi.spyOn(workflowRuns, 'confirm').mockResolvedValue({ id: 'req', revision: 2, version: 4, layoutVersion: 4, state: 'PENDING_START' }); await owner.confirm(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.confirm(); expect(write).toHaveBeenCalledTimes(1); vi.mocked(workflowRuns.get).mockResolvedValue(requirement({ state: 'PENDING_START', version: 4 })); const next = execution('PENDING_START'); next.execution.version = 4; next.control.version = 4; vi.mocked(workflowRuns.execution).mockResolvedValue(next); await owner.recover(); expect(write).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().command.phase).toBe('SETTLED') })
  it('presets/local node changes remain drafts and undo/redo never writes', async () => { const owner = await loaded(); const writes = vi.spyOn(workflowRuns, 'revise'); const before = owner.getSnapshot().graph; owner.add('human'); expect(owner.getSnapshot().graph.nodes.length).toBe(before.nodes.length + 1); owner.history(true); expect(owner.getSnapshot().graph).toEqual(before); owner.history(false); expect(owner.getSnapshot().graph.nodes.length).toBe(before.nodes.length + 1); expect(writes).not.toHaveBeenCalled() })
  for (const failure of [new Error('lost layout'), new ApiError('layout rejected', 422)] ) it(`graph receipt survives ${failure.message}; layout recovery uses its exact endpoint/body/key`, async () => { const owner = await loaded(); owner.add('human'); const revise = vi.spyOn(workflowRuns, 'revise').mockResolvedValue({ ...receipt, revision: 3, layoutVersion: 4 }); const layout = vi.spyOn(workflowRuns, 'layout').mockRejectedValue(failure); await owner.save(); expect(revise).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().graphReceipt?.revision).toBe(3); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); const original = layout.mock.calls[0]![1]; expect(owner.operationIdentity()).toMatchObject({ endpoint: '/workflows/requirements/req/layout', method: 'PUT', requestKey: original.requestKey, body: original }); await owner.recover(); expect(revise).toHaveBeenCalledTimes(1); expect(layout.mock.calls[1]![1]).toBe(original) })
  it('accepted graph/layout final read failure only retries GET, preserving both receipts', async () => { const owner = await loaded(); owner.add('human'); const graph = owner.getSnapshot().graph; const revise = vi.spyOn(workflowRuns, 'revise').mockResolvedValue({ ...receipt, revision: 3 }); const layout = vi.spyOn(workflowRuns, 'layout').mockResolvedValue({ ...receipt, revision: 3, layoutVersion: 5, state: 'PENDING_START' }); vi.mocked(workflowRuns.get).mockRejectedValueOnce(new Error('read failed')).mockResolvedValue(requirement({ revision: 3, layoutVersion: 5, graph })); vi.mocked(workflowRuns.execution).mockResolvedValue({ ...execution('PENDING_START'), execution: { ...execution('PENDING_START').execution, revision: 3, version: 7 }, control: { ...execution('PENDING_START').control, revision: 3, version: 7 } }); await owner.save(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.recover(); expect(revise).toHaveBeenCalledTimes(1); expect(layout).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().command.phase).toBe('SETTLED') })
  it('retired first graph receipt cannot issue a late layout or alter a new scope', async () => { const owner = await loaded(); owner.add('human'); const pending = deferred<typeof receipt>(); vi.spyOn(workflowRuns, 'revise').mockReturnValue(pending.promise); const layout = vi.spyOn(workflowRuns, 'layout'), save = owner.save(); await settle(); owner.retire(true); const before = owner.getSnapshot(); pending.resolve(receipt); await save; expect(layout).not.toHaveBeenCalled(); expect(owner.getSnapshot()).toBe(before) })
  it('authority revision mismatch preserves draft and an older same-id response cannot regress version/control', async () => { const owner = await loaded(); owner.add('human'); const graph = owner.getSnapshot().graph; vi.mocked(workflowRuns.execution).mockResolvedValue({ ...execution('RUNNING'), execution: { ...execution('RUNNING').execution, revision: 9, version: 9 } }); await owner.refresh(); expect(owner.getSnapshot().graph).toEqual(graph); expect(owner.getSnapshot().error).toContain('草稿已保留'); owner.discard(); vi.mocked(workflowRuns.execution).mockResolvedValue({ ...execution('RUNNING'), control: { ...execution('RUNNING').control, controlVersion: -2 }, execution: { ...execution('RUNNING').execution, version: 1 } }); await owner.refresh(); expect(owner.getSnapshot().execution!.execution.version).toBe(3) })
  it('checkpoint acknowledgement and SINGLE/UNTIL/CONTINUOUS send the frozen control versions and original values', async () => { const owner = await loaded(); const value = execution('PENDING_START'); value.control.checkpoints = [{ attemptId: 'checkpoint', requirementId: 'req', nodeKey: 'review', createdAt: '', acknowledgedAt: null }]; vi.mocked(workflowRuns.execution).mockResolvedValue(value); await owner.refresh(); const write = vi.spyOn(workflowRuns, 'start').mockRejectedValue(new Error('lost')); await owner.run('SINGLE', 'review'); expect(write).not.toHaveBeenCalled(); owner.checkpoint('checkpoint', true); await owner.run('SINGLE', 'review'); const original = write.mock.calls[0]![1]; expect(original).toMatchObject({ mode: 'SINGLE', targetKey: 'review', expectedVersion: 3, expectedControlVersion: -1, checkpointAttempts: ['checkpoint'] }); expect(owner.operationIdentity()!.endpoint).toBe('/workflows/requirements/req/control/start'); await owner.recover(); expect(write.mock.calls[1]![1]).toBe(original) })
  it('accepted Start with failed execution GET never repeats Start', async () => { const owner = await loaded(); const write = vi.spyOn(workflowRuns, 'start').mockResolvedValue(execution('RUNNING').control); vi.mocked(workflowRuns.execution).mockRejectedValue(new Error('read')); await owner.run('CONTINUOUS'); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); vi.mocked(workflowRuns.execution).mockResolvedValue(execution('RUNNING')); await owner.recover(); expect(write).toHaveBeenCalledTimes(1) })
  it('manual model selection wins over a late default without model catalog reads on load', async () => { const pending = deferred<Awaited<ReturnType<typeof api.getSettings>>>(); vi.mocked(api.getSettings).mockReturnValue(pending.promise); const owner = await loaded(); const graph = owner.getSnapshot().graph; owner.change({ ...graph, nodes: graph.nodes.map(node => ({ ...node, kind: 'WORK' })) }); expect(owner.getSnapshot().modelLoading).toBe(true); owner.chooseModel({ providerId: 'manual', modelId: 'selected', thinking: true }); pending.resolve({ ...await import('@/pages/w2/core/settingsController').then(m => m.defaultSettings()), openCode: { ...(await import('@/pages/w2/core/settingsController')).defaultSettings().openCode, provider: 'late', model: 'late' } }); await settle(); expect(owner.getSnapshot().model).toEqual({ providerId: 'manual', modelId: 'selected', thinking: true }); expect(api.getSettingsModels).not.toHaveBeenCalled() })
  it('persisted model wins default, HUMAN-only execution does not fetch model settings', async () => { const owner = await loaded(); expect(api.getSettings).not.toHaveBeenCalled(); expect(api.getSettingsModels).not.toHaveBeenCalled(); const value = execution('PENDING_START'); value.control.model = { providerId: 'persisted', modelId: 'frozen', thinking: null }; vi.mocked(workflowRuns.execution).mockResolvedValue(value); await owner.refresh(); expect(owner.getSnapshot().model).toEqual(value.control.model) })
  it('active edit pauses once then protects running node/ancestors and requires explicit Apply', async () => { const owner = await loaded('RUNNING'), value = execution('RUNNING'); value.control.configured = true; value.control.state = 'ACTIVE'; value.execution.nodes = [{ id: 'review', nodeKey: 'review', state: 'ACTIVE', attemptCount: 1, latestAttemptId: 'run', version: 1, outcome: null }]; vi.mocked(workflowRuns.execution).mockResolvedValue(value); await owner.refresh(); const pause = vi.spyOn(workflowRuns, 'pause').mockResolvedValue(value.control); await owner.beginEdit(); expect(pause).toHaveBeenCalledTimes(1); expect(owner.getSnapshot().editing).toBe(true); expect(owner.protectedKeys().has('review')).toBe(true); const before = owner.getSnapshot().graph; owner.patchNode({ ...before.nodes[0]!, title: 'changed' }); expect(owner.getSnapshot().graph).toEqual(before); expect(owner.operationIdentity()!.endpoint).toBe('/workflows/requirements/req/control/pause') })
  it('conditional edges remain immutable local edits, legal outcomes only and protected targets cannot change', async () => { const owner = await loaded(); const writes = vi.spyOn(workflowRuns, 'revise'); const graph = structuredClone(owner.getSnapshot().graph); graph.nodes[0]!.outcomes = ['PASS', 'FAIL']; graph.nodes.push({ ...graph.nodes[0]!, id: 'next', title: '后续' }); graph.edges = [{ id: 'edge', from: 'review', to: 'next', outcome: null }]; owner.change(graph); const before = owner.getSnapshot().graph; expect(owner.edgeOutcome('edge', 'PASS')).toBe(true); expect(before.edges[0]!.outcome).toBeNull(); expect(owner.getSnapshot().graph.edges[0]!.outcome).toBe('PASS'); expect(owner.edgeOutcome('edge', 'INVALID')).toBe(false); expect(owner.edgeOutcome('edge', null)).toBe(true); owner.patch({ editing: false, execution: { ...execution('RUNNING'), execution: { ...execution('RUNNING').execution, nodes: [{ id: 'next', nodeKey: 'next', state: 'ACTIVE', attemptCount: 1, latestAttemptId: 'run', version: 1, outcome: null }] } } }); expect(owner.edgeOutcome('edge', 'FAIL')).toBe(false); expect(writes).not.toHaveBeenCalled() })
  it('normal retire refuses draft/pending, forced retire prevents all later explicit writes', async () => { const owner = await loaded(); owner.add('human'); expect(owner.retire().kind).toBe('CONFIRM_DISCARD'); owner.retire(true); const write = vi.spyOn(workflowRuns, 'confirm'); await owner.confirm(); await owner.save(); expect(write).not.toHaveBeenCalled() })
})
