import { useEffect, useMemo } from 'react'
import type { W2PageProps } from '@/pages/w2/shared'
import { workflowPublicationReason, workflowPublicationStateLabel, workflowPushReason, workflowPushStateLabel, workflowWritebackReason, workflowWritebackStateLabel } from '@/utils/displayLabels'
import { WorkflowWritebackPreview } from '@/pages/w5/workflow'
import type { RequirementController } from './controller'
import { createPublicationController, type PublicationController } from './publicationController'
import { Action, CommandNotice, Labeled, ReadNotice, RequirementContextPanel, useRequirementOwner } from './parts'
import { AttemptFiles } from './Content'

export function PublicationPanel({ page, parent, controller, visible, onClose, revision }: { page: W2PageProps; parent?: RequirementController; controller?: PublicationController; visible: boolean; onClose: () => void; revision: number }) {
  const owner = useMemo(() => controller ?? createPublicationController(parent?.id ?? 'req', revision), [controller, parent?.id]), s = useRequirementOwner(page, owner, parent)
  useEffect(() => { if (parent) owner.bindParent(parent); owner.updateRevision(revision) }, [owner, parent, revision])
  const blocked = owner.locked() || s.loading || s.listing || !!parent && !parent.canStartWrite(owner), p = s.preview
  return <RequirementContextPanel open={visible || owner.locked()} title="需求代码成果" readPolicy={owner.canLeave} onClose={onClose} discard={() => { owner.close(true); onClose() }}>
    <CommandNotice command={s.command} recover={() => { void owner.recover() }} /><ReadNotice error={s.error} loading={s.loading || s.listing} retry={() => { void owner.refresh(); owner.retryList() }} />
    <h3>选择代码成果</h3><p>每份成果包含继承的上游改动，不自动合并多个版本。</p><Action action="ui.refresh" target="代码成果" disabled={blocked} onClick={() => { void owner.list() }} />
    <ul className="w5-list">{s.rows.map(source => <li key={`${source.attemptId}/${source.outputName}`}><strong>{source.nodeTitle} · {source.outputTitle}</strong><p>第 {source.ordinal} 次执行 · {source.changedFiles} 个改动文件</p><Action action="selection.select" target={`${source.nodeTitle} · ${source.outputTitle}`} disabled={owner.locked() || s.listing || owner.canLeave().kind !== 'ALLOW' || !!parent && !parent.canStartWrite(owner)} onClick={() => { void owner.choose(source) }} /></li>)}</ul>
    {s.cursor && <Action action="ui.loadMore" target="代码成果" disabled={blocked} onClick={() => { void owner.list(true) }} />}
    {p && <section aria-label="所选代码成果"><h3>{p.source.nodeTitle} · {p.source.outputTitle}</h3><p>{p.workspaceKind === 'GIT' ? 'Git 项目成果' : '普通目录成果'}{p.sourceBranch ? ` · 来源分支 ${p.sourceBranch}` : ''}</p>{p.source.attemptState === 'FAILED' && <p>该节点执行失败；这里展示已经保存的代码及实际执行结果。</p>}<p>新增 {p.added} · 修改 {p.modified} · 删除 {p.deleted}</p><p>固定版本共 {p.source.totalFiles} 个文件 · {(p.totalBytes / 1024).toFixed(1)} KiB</p>
      <AttemptFiles page={page} changes scope={{ requirement: owner.requirement, node: p.source.nodeKey, attempt: p.source.attemptId, direction: 'outputs', name: p.source.outputName }} />
      {!s.writeback && <WorkflowWritebackPreview source={p} result={s.checked} reading={s.loading} error={s.error} disabled={blocked} onInspect={() => { void owner.checkWriteback() }} />}
    </section>}
    <section aria-label="保存代码成果">{s.commit ? <><strong>{workflowPublicationStateLabel(s.commit.state)}</strong><p>{s.commit.nodeTitle} · {s.commit.outputTitle}：{s.commit.message}</p><p>成果分支：<code>{s.commit.branch}</code></p>{s.commit.commit && <p>提交：<code>{s.commit.commit}</code></p>}{s.commit.attemptState === 'FAILED' && <p>所选节点原执行结果为失败，人工完成需求后明确提交了这份成果。</p>}{s.commit.state === 'BLOCKED' && <><p role="alert">{workflowPublicationReason(s.commit.reasonCode)}</p><Action action="receipt.readOriginal" target="原提交" disabled={blocked} onClick={() => { void owner.retry('commit') }} /></>}<Action action="ui.refresh" target="提交状态" busy={s.loading} onClick={() => { void owner.readStatus('commit') }} /></> : s.commitOpen ? <form onSubmit={event => { event.preventDefault(); void owner.commit() }}><h3>保存所选成果为本地提交</h3><p>当前文件、暂存区和来源分支保持原样，成果写入新建成果分支。</p><Labeled label="提交说明"><input maxLength={200} required value={s.message} disabled={blocked} onChange={event => owner.changeMessage(event.target.value)} /></Labeled><Action action="workflow.commitConfirm" disabled={blocked || !s.message.trim()} busy={s.command.busy} onClick={() => { void owner.commit() }} /></form> : owner.commitAvailable() && <Action action="workflow.commit" disabled={blocked} onClick={owner.showCommit} />}</section>
    {s.commit?.state === 'COMMITTED' && <section aria-label="推送代码成果">{s.pushLoaded && !s.push && !s.error && !s.command.busy && ['IDLE', 'SETTLED'].includes(s.command.phase) && <p>尚未推送到远端</p>}{s.push ? <><strong>{workflowPushStateLabel(s.push.state)}</strong><p>{s.push.remote} · {s.push.url}</p><p>成果分支：<code>{s.push.branch}</code></p>{s.push.state === 'PUSHED' && <p>已核对远端成果分支指向提交 <code>{s.push.commit}</code>。</p>}{s.push.state === 'BLOCKED' && <><p role="alert">{workflowPushReason(s.push.reasonCode)}</p><Action action="receipt.readOriginal" target="原推送" disabled={blocked} onClick={() => { void owner.retry('push') }} /></>}<Action action="ui.refresh" target="推送状态" busy={s.loading} onClick={() => { void owner.readStatus('push') }} /></> : s.pushOpen ? <form onSubmit={event => { event.preventDefault(); void owner.push() }}><h3>确认远端推送</h3><Labeled label="推送远端"><select value={s.remote} disabled={blocked} onChange={event => owner.changeRemote(event.target.value)}><option value="">请选择远端</option>{s.remotes.map(remote => <option key={remote} value={remote}>{remote}</option>)}</select></Labeled><Action action="workflow.inspectPush" disabled={blocked || !s.remote} onClick={() => { void owner.checkPush() }} />{s.pushPreview && <><p>目标地址：{s.pushPreview.url}</p><p>成果分支：<code>{s.pushPreview.branch}</code></p><p>固定提交：<code>{s.pushPreview.commit}</code></p><p>{s.pushPreview.remoteCommit ? '远端已有相同提交，确认后登记该结果。' : '将在远端新建这条成果分支；已有不同内容时停止操作。'}</p><Action action="workflow.pushConfirm" disabled={blocked} onClick={() => { void owner.push() }} /></>}</form> : s.pushLoaded && <Action action="workflow.push" disabled={blocked} onClick={() => { void owner.showPush() }} />}</section>}
    <section aria-label="普通目录成果回填">{s.writeback ? <><strong>{workflowWritebackStateLabel(s.writeback.state)}</strong><p>{s.writeback.nodeTitle} · {s.writeback.outputTitle}</p><p>原目录：{s.writeback.preview.directory}</p>{s.writeback.attemptState === 'FAILED' && <p>所选节点原执行结果为失败，人工完成需求后明确选择了这份成果。</p>}{s.writeback.queueState === 'QUEUED' && <p>等待工作区写入权，当前排在第 {s.writeback.queuePosition} 位。</p>}{s.writeback.state === 'CONFIRMED' && <p>正在保存回填前的文件备份。</p>}{s.writeback.state === 'APPLYING' && <p>正在应用已确认的改动，完成核对后会交出工作区写入权。</p>}{s.writeback.state === 'APPLIED' && <p>已核对全部目标文件，回填前的备份已保存。</p>}{s.writeback.state === 'BLOCKED' && <><p role="alert">{workflowWritebackReason(s.writeback.blocker)}</p><Action action="receipt.readOriginal" target="原回填" disabled={blocked} onClick={() => { void owner.retry('writeback') }} /></>}<Action action="ui.refresh" target="回填状态" busy={s.loading} onClick={() => { void owner.readStatus('writeback') }} /></> : s.writebackOpen ? <form onSubmit={event => { event.preventDefault(); void owner.writeback() }}><h3>确认回填原目录</h3><p>{p?.source.nodeTitle} · {p?.source.outputTitle}</p><p>目录：{s.checked?.directory}</p><p>将新增 {s.checked?.added} · 修改 {s.checked?.modified} · 删除 {s.checked?.deleted} 个文件，保留 {s.checked?.preservedChanges} 处已有修改。回填前会保存本次目录备份。</p><p>如果等待期间目录发生变化，回填会停止并保留现场。</p><Action action="workflow.writebackConfirm" disabled={blocked} onClick={() => { void owner.writeback() }} /></form> : owner.writebackAvailable() && <Action action="workflow.writeback" disabled={blocked} onClick={owner.showWriteback} />}</section>
  </RequirementContextPanel>
}
