import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { api } from '@/api/client'
import type { Interaction } from '@/types/domain'
import { createInboxController } from './controller'
import { deferred,flush } from '@/pages/w2/workflow/page.test-support'
export const permission:Interaction={id:'permission',kind:'PERMISSION',state:'PENDING',taskId:'task',sessionId:'session',externalRequestId:'external',version:4,createdAt:'now',updatedAt:'now',payload:{permission:'bash',patterns:['git status'],metadata:{},title:'检查仓库',hardDenied:false}}
let owner:ReturnType<typeof createInboxController>
beforeEach(()=>{vi.useFakeTimers();vi.spyOn(api,'getInteractions').mockResolvedValue([permission]);vi.spyOn(api,'resolveInteraction').mockResolvedValue({...permission,state:'RESOLVED',version:6,resolvedAction:'ONCE'});owner=createInboxController();owner.attachView()})
afterEach(()=>{owner.retire(true);vi.restoreAllMocks();vi.useRealTimers()})
it('submits exact current optimistic version and serializes a slow read',async()=>{await flush();const pending=deferred<Interaction[]>();vi.mocked(api.getInteractions).mockReturnValueOnce(pending.promise);await vi.advanceTimersByTimeAsync(1500);const writing=owner.resolve('permission','ONCE');await flush();await owner.resolve('permission','SESSION');expect(api.resolveInteraction).toHaveBeenCalledTimes(1);expect(api.resolveInteraction).toHaveBeenCalledWith('permission',{action:'ONCE',version:4});expect(api.getInteractions).toHaveBeenCalledTimes(2);pending.resolve([permission]);await writing;expect(api.getInteractions).toHaveBeenCalledTimes(3)})
it('preserves pending projection and command error across failed and successful reads',async()=>{await flush();vi.mocked(api.resolveInteraction).mockRejectedValue(new Error('投递结果尚未确认'));await owner.resolve('permission','ONCE');vi.mocked(api.getInteractions).mockRejectedValueOnce(new Error('OpenCode 暂时不可达'));await owner.refresh();expect(owner.getSnapshot().interactions[0]?.id).toBe('permission');expect(owner.getSnapshot().error).toContain('暂时不可达');await owner.refresh();expect(owner.getSnapshot().command.error).toContain('投递结果尚未确认');expect(owner.canLeave().kind).toBe('BLOCK')})
it('never repeats a keyless unknown POST and only reads the original row',async()=>{await flush();vi.mocked(api.resolveInteraction).mockRejectedValue(new Error('unknown'));await owner.resolve('permission','ONCE');const original=owner.operationIdentity();await owner.resolve('permission','SESSION');await owner.recover();expect(owner.operationIdentity()).toBe(original);expect(api.resolveInteraction).toHaveBeenCalledTimes(1);expect(owner.canLeave().kind).toBe('BLOCK');vi.mocked(api.getInteractions).mockResolvedValue([{...permission,state:'RESOLVED',version:6,resolvedAction:'ONCE'}]);await owner.recover();expect(api.resolveInteraction).toHaveBeenCalledTimes(1);expect(owner.canLeave().kind).toBe('ALLOW')})
it('fails closed on hard-denied permissions and kind-invalid actions',async()=>{await flush();vi.mocked(api.getInteractions).mockResolvedValue([{...permission,state:'HARD_DENIED',payload:{...permission.payload,hardDenied:true}}]);await owner.refresh();await owner.resolve('permission','ONCE');await owner.resolve('permission','REPLY',[['yes']]);expect(api.resolveInteraction).not.toHaveBeenCalled()})
it('does not restart polling on a retired initial read',async()=>{owner.retire(true);const pending=deferred<Interaction[]>();vi.mocked(api.getInteractions).mockReturnValue(pending.promise);owner=createInboxController();owner.attachView();await flush();const calls=vi.mocked(api.getInteractions).mock.calls.length;owner.retire(true);const snapshot=owner.getSnapshot();pending.resolve([permission]);await flush();await vi.advanceTimersByTimeAsync(6000);expect(api.getInteractions).toHaveBeenCalledTimes(calls);expect(owner.getSnapshot()).toBe(snapshot);expect(vi.getTimerCount()).toBe(0)})
it('keeps accepted result read failure in readback and retries no POST',async()=>{await flush();vi.mocked(api.getInteractions).mockRejectedValueOnce(new Error('readback unavailable'));await owner.resolve('permission','ONCE');expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK');await owner.recover();expect(api.resolveInteraction).toHaveBeenCalledTimes(1);expect(owner.canLeave().kind).toBe('ALLOW')})
it('a detached in-flight read cannot suppress a new view lease read and poll',async()=>{
  owner.retire(true);const old=deferred<Interaction[]>();vi.mocked(api.getInteractions).mockReturnValueOnce(old.promise).mockResolvedValue([permission]);owner=createInboxController()
  const detach=owner.attachView();await flush();detach();const nextDetach=owner.attachView();await flush()
  expect(owner.getSnapshot().interactions[0]?.id).toBe('permission');const calls=vi.mocked(api.getInteractions).mock.calls.length
  old.resolve([]);await flush();expect(owner.getSnapshot().interactions[0]?.id).toBe('permission');await vi.advanceTimersByTimeAsync(1500);expect(api.getInteractions).toHaveBeenCalledTimes(calls+1)
  nextDetach();expect(vi.getTimerCount()).toBe(0)
})
