import { StrictMode } from 'react'
import { act,cleanup,fireEvent,render,screen,within } from '@testing-library/react'
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { api } from '@/api/client'
import { semanticName } from '@/foundation/semanticRegistry'
import { FoundationProvider } from '@/foundation/provider'
import { skins } from '@/themes/registry'
import { foundationDOM,pageProps,flush } from '@/pages/w2/workflow/page.test-support'
import { InboxPage } from './index'
import { permissionFixture,deniedFixture,questionFixture } from './fixtures'
let dispose:(()=>void)[]=[]
async function settle(){await act(async()=>{await flush()})}
async function frame(strict=false){const props=pageProps('/inbox');const owners=new Map<object,()=>void>();props.lifecycle.retain=(owner,release)=>owners.set(owner,release);const children=<FoundationProvider skin={props.skin} reducedMotion><InboxPage {...props}/></FoundationProvider>;const view=render(strict?<StrictMode>{children}</StrictMode>:children);dispose.push(()=>owners.forEach(release=>release()));await settle();return {view,props}}
const click=async(name:string)=>{await act(async()=>{fireEvent.click(screen.getByRole('button',{name}));await flush()})}
beforeEach(()=>{foundationDOM();vi.spyOn(api,'getInteractions').mockResolvedValue([permissionFixture,deniedFixture]);vi.spyOn(api,'resolveInteraction').mockResolvedValue({...permissionFixture,state:'RESOLVED',version:6,resolvedAction:'ONCE'})})
afterEach(()=>{cleanup();dispose.forEach(release=>release());dispose=[];vi.restoreAllMocks();vi.useRealTimers()})
it('actual selected inbox preserves hard-denied warning and submits exact current version',async()=>{await frame();expect(screen.getByText('1 项等待处理')).toBeTruthy();expect(screen.getByText('git push 不可由运行会话授权')).toBeTruthy();expect(screen.queryByRole('button',{name:semanticName('inbox.allowOnce')})).toBeNull();await click(semanticName('selection.select','检查仓库'));expect(screen.getAllByRole('button',{name:semanticName('inbox.allowSession')})).toHaveLength(1);await click(semanticName('inbox.allowOnce'));expect(api.resolveInteraction).toHaveBeenCalledWith('permission',{action:'ONCE',version:4})})
it('actual unknown read is visible, close is blocked and no repeated action POST occurs',async()=>{vi.mocked(api.resolveInteraction).mockRejectedValue(new Error('投递结果尚未确认'));const {props}=await frame();await click(semanticName('selection.select','检查仓库'));await click(semanticName('inbox.allowOnce'));fireEvent.change(screen.getByLabelText(semanticName('settings.changeSkin')),{target:{value:skins[1]!.id}});expect(props.setSkin).toHaveBeenCalledWith(skins[1]!.id);expect(screen.getByRole('button',{name:semanticName('inbox.allowOnce')}).hasAttribute('disabled')).toBe(true);const panel=screen.getByRole('complementary',{name:'检查仓库'});fireEvent.keyDown(panel,{key:'Escape'});await settle();expect(screen.getByRole('complementary',{name:'检查仓库'})).toBeTruthy();await click(semanticName('receipt.readOriginal'));expect(api.resolveInteraction).toHaveBeenCalledTimes(1);expect(screen.getAllByRole('alert').some(alert=>alert.textContent?.includes('结果尚未确认'))).toBe(true)})
it('actual multi/single/custom answers preserve order and explicit recommended submission',async()=>{vi.mocked(api.getInteractions).mockResolvedValue([questionFixture]);vi.mocked(api.resolveInteraction).mockResolvedValue({...questionFixture,state:'RESOLVED',version:9,resolvedAction:'REPLY'});await frame();await click(semanticName('selection.select','OpenCode 需要你的回答'));fireEvent.click(screen.getByRole('checkbox',{name:/文档/}));fireEvent.change(screen.getByLabelText('问题 1 自定义回答'),{target:{value:'  补充  '}});fireEvent.click(screen.getByRole('radio',{name:/人工检查/}));fireEvent.change(screen.getByLabelText('问题 2 自定义回答'),{target:{value:'  原始范围  '}});await click(semanticName('inbox.answer'));expect(api.resolveInteraction).toHaveBeenCalledWith('question',{action:'REPLY',version:7,answers:[['文档','补充'],['原始范围']]})})
it('actual dirty close needs confirmation and three skins preserve the same draft and original question',async()=>{vi.mocked(api.getInteractions).mockResolvedValue([questionFixture]);const {view,props}=await frame();await click(semanticName('selection.select','OpenCode 需要你的回答'));const input=screen.getByLabelText('问题 1 自定义回答');fireEvent.change(input,{target:{value:'冻结回答'}});for(const skin of skins){view.rerender(<FoundationProvider skin={skin} reducedMotion><InboxPage {...props} skin={skin}/></FoundationProvider>);await settle();expect(screen.getByLabelText('问题 1 自定义回答')).toBe(input);expect((input as HTMLTextAreaElement).value).toBe('冻结回答')}await click(semanticName('ui.close','OpenCode 需要你的回答'));expect(screen.getByRole('dialog')).toBeTruthy();expect(api.resolveInteraction).not.toHaveBeenCalled();await act(async()=>{fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:semanticName('ui.stay')}));await flush()});expect((screen.getByLabelText('问题 1 自定义回答') as HTMLTextAreaElement).value).toBe('冻结回答')})
it('actual recommend is explicit, respects first-option fallback and never replies while mounting StrictMode',async()=>{vi.mocked(api.getInteractions).mockResolvedValue([questionFixture]);vi.mocked(api.resolveInteraction).mockResolvedValue({...questionFixture,state:'RESOLVED',version:9,resolvedAction:'REPLY'});await frame(true);expect(api.resolveInteraction).not.toHaveBeenCalled();await click(semanticName('selection.select','OpenCode 需要你的回答'));await click(semanticName('inbox.recommend'));expect(api.resolveInteraction).toHaveBeenCalledWith('question',{action:'REPLY',version:7,answers:[['代码（推荐）'],['原合同']]})})
it('poll disappearance retains the actual original question draft and visible discard confirmation',async()=>{
  vi.mocked(api.getInteractions).mockResolvedValue([questionFixture]);await frame();await click(semanticName('selection.select','OpenCode 需要你的回答'))
  fireEvent.change(screen.getByLabelText('问题 1 自定义回答'),{target:{value:'原输入'}})
  vi.mocked(api.getInteractions).mockResolvedValue([]);await click(semanticName('ui.refresh'))
  expect((screen.getByLabelText('问题 1 自定义回答') as HTMLTextAreaElement).value).toBe('原输入');expect(screen.getByRole('alert').textContent).toContain('原输入和操作身份已保留')
  expect(screen.getByRole('button',{name:semanticName('inbox.answer')}).hasAttribute('disabled')).toBe(true)
  await click(semanticName('ui.close','OpenCode 需要你的回答'));expect(screen.getByRole('dialog')).toBeTruthy();expect(api.resolveInteraction).not.toHaveBeenCalled()
})
it('poll disappearance retains UNKNOWN permission details and only reads its original identity',async()=>{
  vi.mocked(api.resolveInteraction).mockRejectedValue(new Error('unknown'));await frame();await click(semanticName('selection.select','检查仓库'));await click(semanticName('inbox.allowOnce'))
  vi.mocked(api.getInteractions).mockResolvedValue([]);await click(semanticName('ui.refresh'))
  expect(screen.getByRole('complementary',{name:'检查仓库'})).toBeTruthy();expect(screen.getByText('git status')).toBeTruthy();expect(screen.getAllByRole('alert').some(item=>item.textContent?.includes('原输入和操作身份已保留'))).toBe(true)
  await click(semanticName('receipt.readOriginal'));expect(api.resolveInteraction).toHaveBeenCalledTimes(1);expect(screen.getByRole('complementary',{name:'检查仓库'})).toBeTruthy()
})
