import { afterEach, describe, expect, it, vi } from 'vitest'
import { ApplicationOwnership, routeFromLocation, targetPath } from './ownership'
import { createApplicationRouter, applicationRoutes } from '@/router'
import { createStoryAccountingOwner } from './storyAccounting'
import { api } from '@/api/client'
import type { StoryAccountingCall } from '@/types/domain'
import { flushPromises } from '@/test/async'
const events=vi.hoisted(()=>({ready:()=>{},close:vi.fn()}))
vi.mock('@/api/client',async original=>({...await original<typeof import('@/api/client')>(),subscribeStoryAccountingEvents:(_change:()=>void,ready:()=>void)=>{events.ready=ready;return {close:events.close}}}))
const owners:Array<{dispose(force?:boolean):unknown}>=[]
afterEach(()=>{owners.splice(0).forEach(owner=>owner.dispose(true));vi.restoreAllMocks();vi.useRealTimers();sessionStorage.clear()})
function app(path='/projects'){const value=new ApplicationOwnership();owners.push(value);const scope=value.scope(routeFromLocation({pathname:path,search:'',hash:''}));value.commit(scope);return {value,scope}}
function record(id='original',state:StoryAccountingCall['state']='PREPARED'):StoryAccountingCall{return {id,state,operation:'start',systemCode:'SYS-MOCK',storyCode:'demo',role:'ROUTER',startedAt:'2026-10-03T00:00:00Z',parts:[],retryAvailable:true}}
async function accounting(state:StoryAccountingCall['state']='PREPARED'){vi.spyOn(api,'getStoryAccountingCalls').mockResolvedValue([record('original',state)]);vi.spyOn(api,'getStoryAccountingCall').mockResolvedValue(record('original',state));const owner=createStoryAccountingOwner();owners.push(owner);owner.start();events.ready();await flushPromises();return owner}
describe('W6 single application ownership',()=>{
 it('preserves destination query arrays, hash and encoded original params without creating commands',()=>{expect(targetPath({path:'/tasks/A',query:{kind:'1',omit:null},hash:'#evidence'})).toBe('/tasks/A?kind=1#evidence');expect(routeFromLocation({pathname:'/tasks/A',search:'?key=x&key=y',hash:'#evidence'},{id:'A'})).toEqual({path:'/tasks/A',fullPath:'/tasks/A?key=x&key=y#evidence',query:{key:['x','y']},params:{id:'A'}})})
 it.each(['pending','unknown','File','dirty'] as const)('root safe disposal retains %s and all resource/command identities',kind=>{const {value,scope}=app();const cleanup=vi.fn();scope.lifecycle.retain({},cleanup);scope.navigation.registerGuard(()=>kind==='dirty'?{kind:'CONFIRM_DISCARD',description:'原草稿',draftRevision:1}:{kind:'BLOCK',reason:`原${kind}`,recoveryAction:'原身份恢复'});expect(value.dispose()).toBe(false);expect(value.active).toBe(true);expect(scope.active).toBe(true);expect(cleanup).not.toHaveBeenCalled();value.dispose(true);expect(cleanup).toHaveBeenCalledOnce()})
 it('global pending without a page also blocks root disposal; guard exceptions fail closed',()=>{const value=new ApplicationOwnership();owners.push(value);const cleanup=vi.fn();value.cleanup.add(cleanup);const guard=()=>({kind:'BLOCK' as const,reason:'原全局操作',recoveryAction:'读取原记录'});value.globalGuards.add(guard);expect(value.dispose()).toBe(false);expect(value.canPass('/')).toBe(false);value.globalGuards.delete(guard);value.globalGuards.add(()=>{throw new Error('invalid projection')});expect(value.dispose()).toBe(false);expect(value.canPass('/')).toBe(false);expect(cleanup).not.toHaveBeenCalled()})
 it('new pending while dirty confirmation is open blocks confirm, preserving the same scope',async()=>{const {value,scope}=app();let pending=false;scope.navigation.registerGuard(()=>pending?{kind:'BLOCK',reason:'原请求已发送',recoveryAction:'读取原请求'}:{kind:'CONFIRM_DISCARD',description:'原草稿',draftRevision:1});const navigation=scope.navigation.go('/tasks');await flushPromises();expect(scope.dialog.getSnapshot().open).toBe(true);pending=true;scope.dialog.choose(true);expect(scope.dialog.getSnapshot()).toMatchObject({open:true,blocked:true,reason:'原请求已发送'});scope.dialog.choose(false);expect(await navigation).toBe(false);expect(value.current).toBe(scope);expect(scope.active).toBe(true)})
 it('a blocked concurrent destination invalidates an older accepted navigation before history changes',async()=>{const {value,scope}=app();let resolve!:(yes:boolean)=>void;const navigate=vi.fn();value.driver={navigate,location:()=>'/tasks'};value.navigationInterceptor=()=>new Promise<boolean>(r=>{resolve=r});const old=scope.navigation.go('/tasks');await flushPromises();scope.navigation.registerGuard(()=>({kind:'BLOCK',reason:'新pending',recoveryAction:'核对'}));expect(await scope.navigation.go('/settings')).toBe(false);resolve(true);expect(await old).toBe(false);expect(navigate).not.toHaveBeenCalled();expect(value.current).toBe(scope)})
 it('retired scopes dispose every owner once and reject late navigation without throwing or writing',async()=>{const {value,scope}=app();const first=vi.fn(()=>{throw new Error('owned failure')}),second=vi.fn();scope.lifecycle.retain({},first);scope.lifecycle.retain({},second);const next=value.scope(routeFromLocation({pathname:'/tasks',search:'',hash:''}));value.commit(next);expect(first).toHaveBeenCalledOnce();expect(second).toHaveBeenCalledOnce();expect(value.healthy).toBe(false);expect(await scope.navigation.go('/settings')).toBe(false);value.dispose(true);expect(first).toHaveBeenCalledOnce();expect(second).toHaveBeenCalledOnce()})
 it('all 31 route records exist, redirects preserve query/hash and fallback returns home',async()=>{expect(applicationRoutes).toHaveLength(31);const {value}=app();const router=createApplicationRouter(value,{initialEntries:['/automations?archive=A#old'],shell:false});await vi.waitFor(()=>expect(router.state.initialized).toBe(true));expect(router.state.location).toMatchObject({pathname:'/template-tasks',search:'?archive=A',hash:'#old'});await router.navigate('/settings/roles?role=A#prompt');expect(router.state.location).toMatchObject({pathname:'/roles',search:'?role=A',hash:'#prompt'});await router.navigate('/not-found?unused=A#old');expect(router.state.location).toMatchObject({pathname:'/',search:'',hash:''})})
})
describe('W6 global accounting original operation protection',()=>{
 it('unknown cancel retains original id, blocks navigation, reads only original authoritative proof',async()=>{const owner=await accounting();const write=vi.spyOn(api,'cancelStoryAccountingCall').mockRejectedValue(new Error('unknown'));await owner.cancel();await owner.cancel();expect(write).toHaveBeenCalledExactlyOnceWith('original');expect(owner.getSnapshot().command).toMatchObject({phase:'UNKNOWN',id:'original',action:'cancel'});expect(owner.canLeave().kind).toBe('BLOCK');await owner.recover();expect(owner.canLeave().kind).toBe('BLOCK');vi.mocked(api.getStoryAccountingCall).mockResolvedValue(record('original','CANCELLING'));await owner.recover();expect(owner.canLeave().kind).toBe('ALLOW');expect(owner.getSnapshot().calls[0]?.state).toBe('CANCELLING');expect(write).toHaveBeenCalledOnce()})
 it('wrong-id GET cannot release original unknown; disposal invalidates late completion and all timers',async()=>{vi.useFakeTimers();const owner=await accounting();let finish!:(value:StoryAccountingCall)=>void;const write=vi.spyOn(api,'cancelStoryAccountingCall').mockImplementation(()=>new Promise(r=>{finish=r}));const pending=owner.cancel();expect(owner.canLeave().kind).toBe('BLOCK');const snapshot=owner.getSnapshot();owner.dispose();finish(record('original','CANCELLED'));await pending;await vi.advanceTimersByTimeAsync(20000);expect(owner.getSnapshot()).toBe(snapshot);expect(write).toHaveBeenCalledOnce();expect(vi.getTimerCount()).toBe(0);expect(events.close).toHaveBeenCalled()})
 it('unkeyed retry never silently rewrites: list read cannot prove its receipt',async()=>{const owner=await accounting('FAILED');const write=vi.spyOn(api,'retryStoryAccountingCall').mockRejectedValue(new Error('unknown'));await owner.retry();await owner.recover();await owner.retry();expect(owner.getSnapshot().command).toMatchObject({phase:'UNKNOWN',id:'original',action:'retry'});expect(owner.canLeave().kind).toBe('BLOCK');expect(write).toHaveBeenCalledExactlyOnceWith('original')})
 it('partial dismiss removes accepted first receipt; second unknown never resends either write',async()=>{const owner=await accounting('FAILED');vi.mocked(api.getStoryAccountingCalls).mockResolvedValue([record('original','FAILED'),record('second','FAILED')]);events.ready();await flushPromises();const write=vi.spyOn(api,'dismissStoryAccountingCall').mockResolvedValueOnce().mockRejectedValueOnce(new Error('unknown'));await owner.close();await owner.close();expect(write.mock.calls).toEqual([['original'],['second']]);expect(owner.getSnapshot().calls.some(row=>row.id==='original')).toBe(false);expect(owner.getSnapshot().command).toMatchObject({phase:'UNKNOWN',id:'second',action:'dismiss'});vi.mocked(api.getStoryAccountingCalls).mockResolvedValue([]);await owner.recover();expect(owner.canLeave().kind).toBe('ALLOW');expect(write).toHaveBeenCalledTimes(2)})
})
