import { beforeEach,expect,it,vi } from 'vitest'
import { api } from '@/api/client'
import { DocumentSupplementForm } from '@/pages/w6-tests/knowledge-ppt-template/template-react'
import { flushPromises,mount } from '@/pages/w6-tests/knowledge-ppt-template/react-test-root'
import { documentRun } from '@/pages/w3/templates/runs/test-support'
vi.mock('@/api/client',async original=>{const actual=await original<typeof import('@/api/client')>();return {...actual,api:{...actual.api,documentSupplementOptions:vi.fn(),uploadDocumentSupplement:vi.fn()}}})
const run=documentRun('run',3),request={requestKey:'supplement-request-key',expectedVersion:3,expectedTaskVersion:-1}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.documentSupplementOptions).mockResolvedValue({available:true,message:'补充与原文一起复核',request})})
it('retries a lost response using the same upload identity and suppresses duplicate clicks',async()=>{const w=mount(DocumentSupplementForm,{props:{run}});await w.get('[data-semantic="template.supplement"]').trigger('click');const input=w.get('input'),file=new File(['审批规则'],'审批.md');Object.defineProperty(input.element,'files',{value:[file]});await input.trigger('change');vi.mocked(api.uploadDocumentSupplement).mockRejectedValueOnce(new Error('响应丢失'));await w.get('[data-semantic="template.uploadSupplement"]').trigger('click');expect(w.text()).toContain('响应丢失');let done!:(value:typeof run)=>void;vi.mocked(api.uploadDocumentSupplement).mockReturnValueOnce(new Promise(resolve=>{done=resolve}));await w.get('[data-semantic="receipt.retryOriginal"]').trigger('click');await w.get('[data-semantic="template.uploadSupplement"]').trigger('click');expect(api.uploadDocumentSupplement).toHaveBeenCalledTimes(2);expect(vi.mocked(api.uploadDocumentSupplement).mock.calls[1]).toEqual(['run',request,[file]]);done({...run,state:'ANALYZING'});await flushPromises();expect(w.emitted('updated')).toHaveLength(1)})
it('shows an unavailable server action and rejects a late response after navigation',async()=>{vi.mocked(api.documentSupplementOptions).mockResolvedValueOnce({available:false,message:'需要先停止当前执行',request:null});const w=mount(DocumentSupplementForm,{props:{run}});await w.get('[data-semantic="template.supplement"]').trigger('click');expect(w.text()).toContain('需要先停止当前执行');expect(w.find('input').exists()).toBe(false);await w.setProps({run:{...run,id:'next'}});expect(w.text()).not.toContain('需要先停止当前执行');expect(api.uploadDocumentSupplement).not.toHaveBeenCalled()})
