import { describe,expect,it,vi } from 'vitest'
import { SessionMonitorPanel } from '@/pages/w4/task/SessionMonitorPanel'
import { api,ApiError } from '@/api/client'
import type {TaskSessionRoleSummary as Summary} from '@/types/domain'
import {mountPanel,sessionReads,taskFixture,flushPromises} from '@/pages/w6-tests/ordinary/task'
const configured:Summary={configured:true,roleId:'builtin.package-designer',revisionId:'revision-2',revisionSha256:'a'.repeat(64),slot:'PACKAGE_DESIGN_CANDIDATE_V2_READ_ONLY',adapterProfile:'PACKAGE_DESIGN_CANDIDATE_V2_READ_ONLY',adapterVersion:'v1',permissions:[{permission:'read',pattern:'*',action:'allow'},{permission:'bash',pattern:'*git*push*',action:'deny'}],permissionSha256:'b'.repeat(64)}
const toggle='.w4-role-summary button[data-semantic="ui.expand"],.w4-role-summary button[data-semantic="ui.collapse"]'
describe('SessionRoleSummary',()=>{
 it('queries only after expansion and shows frozen rule summaries with technical IDs collapsed',async()=>{sessionReads();const get=vi.spyOn(api,'getTaskSessionRole').mockResolvedValue(configured);const {view}=mountPanel(SessionMonitorPanel,taskFixture('task-1'),{});await flushPromises();expect(get).not.toHaveBeenCalled();expect(view.get(toggle).attributes('aria-expanded')).toBe('false');await view.get(toggle).trigger('click');expect(get).toHaveBeenCalledOnce();expect(get).toHaveBeenCalledWith('task-1','execution:local-1');expect(view.text()).toContain('冻结快照');expect(view.text()).toContain('读取文件');expect(view.text()).toContain('拒绝');expect(view.get('.w4-role-summary details').attributes('open')).toBeUndefined();await view.get(toggle).trigger('click');await view.get(toggle).trigger('click');expect(get).toHaveBeenCalledOnce()})
 it('explains a legacy Session without inventing a configured role',async()=>{sessionReads('execution:legacy');vi.spyOn(api,'getTaskSessionRole').mockResolvedValue({...configured,configured:false,permissions:[]});const{view}=mountPanel(SessionMonitorPanel,taskFixture('task-1'),{});await flushPromises();await view.get(toggle).trigger('click');expect(view.text()).toContain('历史会话未保存角色快照');expect(view.find('.w4-role-summary ul').exists()).toBe(false)})
 it('retains the selected Session and offers an explicit retry after a read failure',async()=>{sessionReads();const get=vi.spyOn(api,'getTaskSessionRole').mockRejectedValueOnce(new ApiError('请求失败 (503)',503)).mockResolvedValueOnce(configured);const{view}=mountPanel(SessionMonitorPanel,taskFixture('task-1'),{});await flushPromises();await view.get(toggle).trigger('click');expect(view.get('.w4-role-summary [role="alert"]').text()).toContain('请求失败');await view.get('.w4-role-summary [data-semantic="ui.retry"]').trigger('click');expect(get).toHaveBeenCalledTimes(2);expect(view.find('.w4-role-summary [role="alert"]').exists()).toBe(false);expect(view.text()).toContain('冻结快照');expect(get).toHaveBeenLastCalledWith('task-1','execution:local-1')})
})
