import { fireEvent,screen } from '@testing-library/react'
import { afterEach,describe,expect,it,vi } from 'vitest'
import { api } from '@/api/client'
import type { SkillDocument,SkillInventory } from '@/types/domain'
import { toolsFixture,skillsTab,project,action } from '@/pages/w6-tests/ordinary/tools'
import { flushPromises } from '@/pages/w6-tests/ordinary/render'
import { deferred } from '@/pages/w2/core/coreTestHelpers'
const skill={name:'review',description:'检查代码行为',location:'/skills/review/SKILL.md'}
const inventory={skills:[skill],complete:true,checkedAt:'2026-09-10T00:00:00Z'}
afterEach(()=>vi.restoreAllMocks())
describe('Skill 浏览器',()=>{
 it('按需读取 Markdown，可切换完整源文且不执行 HTML',async()=>{vi.spyOn(api,'getSkills').mockResolvedValue(inventory);const content='# 使用说明\n\n**检查行为**\n\n<script>alert(1)</script>',read=vi.spyOn(api,'getSkillDocument').mockResolvedValue({...skill,content});const {view}=await toolsFixture();await skillsTab();expect(read).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:/review/}));await flushPromises();expect(read).toHaveBeenCalledWith('','review');expect(view.container.querySelector('script')).toBeNull();expect(screen.getByRole('heading',{name:'使用说明'})).toBeTruthy();await action('tools.rawSkill');const lines=screen.getByLabelText('Markdown 源文').textContent!.split('\n').map(line=>line.replace(/^\d+  /,''));expect(lines.join('\n')).toBe(content);expect(view.container.querySelector('script')).toBeNull();fireEvent.change(screen.getByLabelText('搜索 Skill'),{target:{value:'不存在'}});expect(screen.getByText('没有匹配的 Skill')).toBeTruthy()})
 it('清空旧项目文档并丢弃迟到的列表和文档',async()=>{const pendingList=deferred<SkillInventory>(),pendingDocument=deferred<SkillDocument>();const readList=vi.spyOn(api,'getSkills').mockResolvedValueOnce(inventory).mockReturnValueOnce(pendingList.promise).mockResolvedValueOnce({skills:[],complete:true,checkedAt:''});vi.spyOn(api,'getSkillDocument').mockReturnValue(pendingDocument.promise);vi.spyOn(api,'getProjects').mockResolvedValue(['second','third'].map(id=>({id,name:id,rootPath:'/tmp',status:'READY',updatedAt:'',taskCount:0,openDesignerSessionCount:0})));const {view}=await toolsFixture();await skillsTab();fireEvent.click(screen.getByRole('button',{name:/review/}));await project('second');await project('third');pendingList.resolve(inventory);pendingDocument.resolve({...skill,content:'旧项目文档'});await flushPromises();expect(readList).toHaveBeenLastCalledWith('third');expect(screen.getByText('当前范围暂无 Skill')).toBeTruthy();expect(view.container.textContent).not.toContain('旧项目文档');expect(screen.queryByRole('button',{name:/review/})).toBeNull()})
 it('列表与文档失败均可重试，不把读取失败当成空清单',async()=>{vi.spyOn(api,'getSkills').mockRejectedValueOnce(new Error('读取失败')).mockResolvedValue(inventory);vi.spyOn(api,'getSkillDocument').mockRejectedValueOnce(new Error('文档读取失败')).mockResolvedValue({...skill,content:'# 重试成功'});const {view}=await toolsFixture();await skillsTab();expect(screen.getByRole('alert').textContent).toContain('读取失败');expect(view.container.textContent).not.toContain('当前范围暂无 Skill');await action('ui.retry');fireEvent.click(screen.getByRole('button',{name:/review/}));await flushPromises();expect(screen.getByRole('alert').textContent).toContain('文档读取失败');await action('ui.retry');expect(screen.getByRole('heading',{name:'重试成功'})).toBeTruthy()})
})
