import {act,fireEvent,screen} from '@testing-library/react'
import {describe,it,expect,vi,afterEach} from 'vitest'
import {api} from '@/api/client'
import {DesignerPage} from '@/pages/w5/designer/DesignerPage'
import {createDesignerController} from '@/pages/w5/designer/controller'
import {mockDesigner,pageProps} from '@/pages/w5/designer/test-support'
import {mount,flushPromises} from '@/pages/w6-tests/knowledge-ppt-template/react-test-root'
import type {StoryBindingCapability} from '@/types/domain'
vi.mock('@/api/client',async importOriginal=>({...await importOriginal<typeof import('@/api/client')>(),subscribeDesignerEvents:vi.fn()}))
const available:StoryBindingCapability={available:true,state:'AVAILABLE',reason:'已检测到 aicoding',checkedAt:'now'}
afterEach(()=>vi.restoreAllMocks())
function setup(){const p=pageProps();p.props.route={path:'/designer',fullPath:'/designer',params:{},query:{}};const owner=createDesignerController({historyOnly:false,navigation:p.props.navigation});const view=mount(DesignerPage,{props:{...p.props,controller:owner,historyOnly:false}});return {view,owner}}
describe('StoryBindingSetup',()=>{
 it('disables while detecting or absent and allows explicit recheck after installation',async()=>{mockDesigner();let finish!:(value:StoryBindingCapability)=>void;const probe=vi.mocked(api.getStoryBindingCapability).mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve}));const {view}=setup();await flushPromises();expect(screen.getByLabelText('故事绑定').matches(':disabled')).toBe(true);finish({...available,available:false,reason:'当前 OpenCode 未注册 aicoding 命令'});await flushPromises();expect(view.text()).toContain('未注册');expect(screen.getByLabelText('故事绑定').matches(':disabled')).toBe(true);probe.mockResolvedValue(available);await view.get('button[data-semantic="ui.refresh"][aria-label*="故事绑定"]').trigger('click');await flushPromises();expect(screen.getByLabelText('故事绑定').matches(':disabled')).toBe(false);view.unmount()})
 it('preserves identifier leading zeros and only shows fields after enabling',async()=>{mockDesigner();vi.mocked(api.getStoryBindingCapability).mockResolvedValue(available);const {view,owner}=setup();await flushPromises();expect(view.text()).toContain('仅统计设计师和执行者的 AI 工作量');expect(screen.queryByLabelText('故事编号')).toBeNull();await act(async()=>owner.setStory({enabled:true,systemCode:'SYS-001',storyCode:'000123'}));expect((screen.getByLabelText('故事编号') as HTMLInputElement).value).toBe('000123');await act(async()=>fireEvent.change(screen.getByLabelText('故事编号'),{target:{value:'000456'}}));expect(owner.getSnapshot().story).toEqual({enabled:true,systemCode:'SYS-001',storyCode:'000456'});view.unmount()})
 it('rejects stale project results, refreshes for runtime generation changes, and exposes failures',async()=>{mockDesigner();let first!:(value:StoryBindingCapability)=>void;const probe=vi.mocked(api.getStoryBindingCapability).mockImplementationOnce(()=>new Promise(resolve=>{first=resolve})).mockResolvedValueOnce({...available,available:false,reason:'第二个项目无插件'});const {view,owner}=setup();await flushPromises();await act(async()=>owner.setProject('p2'));await flushPromises();first(available);await flushPromises();expect(view.text()).toContain('第二个项目无插件');probe.mockRejectedValueOnce(new Error('连接断开'));await act(async()=>owner.detectStory());await flushPromises();expect(view.text()).toContain('连接断开');expect(screen.getByLabelText('故事绑定').matches(':disabled')).toBe(true);expect(probe).toHaveBeenLastCalledWith('p2');view.unmount()})
})
