import {beforeEach,describe,expect,it,vi} from 'vitest'
import {api} from '@/api/client'
import {TaskDecisionPanel} from '@/pages/w4/actions/decision'
import type {TaskDecision,RecoveryDraft} from '@/types/domain'
import {mountPanel,taskFixture} from '@/pages/w6-tests/ordinary/task'
import {action,confirm,change,body,flushPromises} from '@/pages/w6-tests/ordinary/actions'
import {deferred,decision} from '@/pages/w4/actions/test-support'
const failedDecision:TaskDecision={...decision('task-1'),cycle:{...decision().cycle!,id:'cycle-2'},stages:[{id:'stage-1',ordinal:0,objective:'修复接口',state:'FAILED'}],availableActions:['CONTINUE_CURRENT_TASK','DERIVE_INHERIT_CHANGES','DERIVE_REWORK_ALL','READ_ONLY_AUDIT','CANCEL']}
const page=(id='task-1')=>mountPanel(TaskDecisionPanel,taskFixture(id,{status:'AWAITING_DECISION',version:7}),{})
beforeEach(()=>{vi.spyOn(api,'getTaskDecision').mockResolvedValue(structuredClone(failedDecision));vi.spyOn(api,'continueTaskDecision').mockResolvedValue(failedDecision)})
describe('TaskDecisionPanel',()=>{
 it('shows every safe failure disposition and starts a fresh execution cycle on the same task',async()=>{const p=page();await flushPromises();expect(p.view.text()).toContain('第 2 轮 · 执行失败');for(const key of ['decision.inherit','decision.rework','decision.audit'])expect(p.view.find(`[data-semantic="${key}"]`).exists()).toBe(true);await action('decision.continue');expect(api.continueTaskDecision).not.toHaveBeenCalled();await confirm('decision.continue');expect(api.continueTaskDecision).toHaveBeenCalledWith('task-1',{expectedTaskVersion:7,expectedCycleVersion:3,stageId:undefined,supplementalRequirement:undefined})})
 it('requires a supplemental requirement before continuing a successful result',async()=>{vi.mocked(api.getTaskDecision).mockResolvedValue({...failedDecision,cycle:{...failedDecision.cycle!,result:'SUCCEEDED',kind:'CONTINUE_SUCCESS'},availableActions:['CONTINUE_CURRENT_TASK','CANCEL']});const p=page();await flushPromises();await action('decision.continue');expect(p.view.text()).toContain('起始阶段并填写补充要求');expect(api.continueTaskDecision).not.toHaveBeenCalled()})
 it('does not present an unknown historical change count as a file count or an acceptance action',async()=>{vi.mocked(api.getTaskDecision).mockResolvedValue({...failedDecision,cycle:{...failedDecision.cycle!,result:'SUCCEEDED'},checkpoint:{...failedDecision.checkpoint!,changedFileCount:-1},availableActions:['CONTINUE_CURRENT_TASK','CANCEL']});const p=page();await flushPromises();expect(p.view.text()).toContain('变更数量未确认');expect(p.view.text()).not.toContain('-1 个变更文件');expect(p.view.find('[data-semantic="decision.accept"]').exists()).toBe(false)})
 it('submits the frozen result versions through the dedicated cancellation endpoint',async()=>{const stopping={...failedDecision,taskState:'STOPPING' as const,taskVersion:8,availableActions:[]};const cancel=vi.spyOn(api,'cancelTaskDecision').mockImplementation(async()=>{vi.mocked(api.getTaskDecision).mockResolvedValue(stopping);return stopping});const p=page();await flushPromises();await action('task.cancel');await confirm('task.cancel');expect(cancel).toHaveBeenCalledWith('task-1',{expectedTaskVersion:7,expectedCycleVersion:3});expect(p.view.text()).toContain('取消请求已保存，正在等待远端写入者停止确认')})
 it.each([['继续当前任务','continueTaskDecision','decision.continue'],['新任务继承修改','deriveTaskDecision','decision.inherit'],['新任务全部重做','deriveTaskDecision','decision.rework'],['直接审计','auditTaskDecision','decision.audit'],['接受结果','acceptTaskDecision','decision.accept'],['取消任务','cancelTaskDecision','task.cancel']] as const)('invalidates %s confirmation after changing the task',async(_label,method,key)=>{vi.mocked(api.getTaskDecision).mockResolvedValue({...failedDecision,cycle:{...failedDecision.cycle!,result:'SUCCEEDED'},availableActions:[...failedDecision.availableActions,'ACCEPT_RESULT']});const write=vi.spyOn(api,method),p=page();await flushPromises();await change('补充要求','原任务补充要求');await action(key);expect(body().find('[role=dialog]').exists()).toBe(true);p.view.unmount();p.dispose();vi.mocked(api.getTaskDecision).mockResolvedValue({...failedDecision,taskId:'task-2',taskVersion:9,cycle:{...failedDecision.cycle!,result:'SUCCEEDED'}});const next=page('task-2');await flushPromises();expect(write).not.toHaveBeenCalled();expect(next.parent.refresh).not.toHaveBeenCalled();expect((next.view.get('textarea').element as HTMLTextAreaElement).value).toBe('');expect(body().find('[role=dialog]').exists()).toBe(false)})
 it('freezes continuation versions, selected stage and supplemental requirement before confirmation',async()=>{const snapshot:TaskDecision={...failedDecision,cycle:{...failedDecision.cycle!,result:'SUCCEEDED'},stages:[...failedDecision.stages,{id:'stage-2',ordinal:1,objective:'另一阶段',state:'SUCCEEDED'}]};vi.mocked(api.getTaskDecision).mockResolvedValue(snapshot);page();await flushPromises();await change('补充要求','  已确认范围  ');await action('decision.continue');snapshot.taskVersion=99;snapshot.cycle!.version=99;expect((body().get('textarea').element as HTMLTextAreaElement).value).toBe('  已确认范围  ');await confirm('decision.continue');expect(api.continueTaskDecision).toHaveBeenCalledWith('task-1',{expectedTaskVersion:7,expectedCycleVersion:3,stageId:'stage-1',supplementalRequirement:'已确认范围'})})
 it.each(['resolve','reject'] as const)('ignores a former task load that settles late (%s)',async settlement=>{const old=deferred<TaskDecision>();vi.mocked(api.getTaskDecision).mockReturnValueOnce(old.promise).mockReturnValueOnce(old.promise);const p=page();p.view.unmount();p.dispose();vi.mocked(api.getTaskDecision).mockResolvedValue({...failedDecision,taskId:'task-2',checkpoint:{...failedDecision.checkpoint!,changedFileCount:8},cycle:{...failedDecision.cycle!,ordinal:8,result:'SUCCEEDED'}});const next=page('task-2');await flushPromises();if(settlement==='resolve')old.resolve(failedDecision);else old.reject(new Error('旧任务读取失败'));await flushPromises();expect(next.view.text()).toContain('第 8 轮 · 执行成功');expect(next.view.text()).toContain('8 个变更文件');expect(next.view.text()).not.toContain('旧任务读取失败')})
 it('keeps a command failure visible after successfully refreshing the decision',async()=>{const cancel=vi.spyOn(api,'cancelTaskDecision').mockRejectedValue(new Error('任务结果已变化，请核对新的轮次后重试'));const p=page();await flushPromises();await action('task.cancel');await confirm('task.cancel');await action('ui.refresh');expect(api.getTaskDecision).toHaveBeenCalledTimes(3);expect(body().text()).toContain('任务结果已变化，请核对新的轮次后重试');expect(p.view.text()).toContain('第 2 轮 · 执行失败');expect(cancel).toHaveBeenCalledOnce()})
 it('discards confirmation after unmount without a command',async()=>{const cancel=vi.spyOn(api,'cancelTaskDecision'),p=page();await flushPromises();await action('task.cancel');expect(body().find('[role=dialog]').exists()).toBe(true);p.view.unmount();p.dispose();await flushPromises();expect(cancel).not.toHaveBeenCalled();expect(p.parent.refresh).not.toHaveBeenCalled()})
 it('does not navigate when a former task derivation finishes after switching tasks',async()=>{const late=deferred<RecoveryDraft>(),derive=vi.spyOn(api,'deriveTaskDecision').mockReturnValue(late.promise),p=page();await flushPromises();await action('decision.inherit');await confirm('decision.inherit');expect(derive).toHaveBeenCalledWith('task-1',{expectedTaskVersion:7,expectedCycleVersion:3,mode:'INHERIT_CHANGES'});p.view.unmount();p.dispose();vi.mocked(api.getTaskDecision).mockResolvedValue({...failedDecision,taskId:'task-2'});const next=page('task-2');await flushPromises();late.resolve({taskId:'child-of-former-task',parentTaskId:'task-1',mode:'INHERIT_CHANGES',workspaceFingerprint:'original-fingerprint',writableSession:false});await flushPromises();expect(p.props.page.navigation.goAccepted).not.toHaveBeenCalled();expect(next.props.page.navigation.goAccepted).not.toHaveBeenCalled();expect(next.view.find('[data-semantic="task.open"]').exists()).toBe(false)})
})
