import {afterEach,describe,expect,it,vi} from 'vitest'
import {ApiError,api} from '@/api/client'
import {TaskPublicationActions} from '@/pages/w4/publication/TaskPublicationActions'
import {fixture,task,content} from '@/pages/w4/publication/test-support'
import {mountPanel} from '@/pages/w6-tests/ordinary/task'
import {action,confirm,change,body,flushPromises,fireEvent,act} from '@/pages/w6-tests/ordinary/actions'
const page=(state=task())=>mountPanel(TaskPublicationActions,state,{})
async function openCommit(local=false){await action(local?'publication.commitLocal':'publication.commit');await flushPromises()}
async function submit(local=false){await action(local?'publication.commitLocal':'publication.commit',body().get('.ui-context-panel:not([hidden])').element!);await confirm(local?'publication.commitLocal':'publication.commit')}
afterEach(()=>vi.useRealTimers())
describe('TaskPublicationActions',()=>{
 it('generates the default subject, enforces four digits, then offers a merge request after push',async()=>{const f=fixture();f.suggestion.mockResolvedValue({subject:'完善任务发布流程',aiGenerated:true});const p=page(task({id:'task-1',title:'完善任务发布流程'}));await flushPromises();await openCommit();expect(f.suggestion).toHaveBeenCalledWith('task-1');expect(body().text()).toContain('完善任务发布流程');await change('4 位数字工单号','30a32');expect((body().get('input[aria-label="4 位数字工单号"]').element as HTMLInputElement).value).toBe('3032');expect(body().text()).toContain('#3032_完善任务发布流程');await submit();expect(f.publish).toHaveBeenCalledWith('task-1','#3032_完善任务发布流程');expect(p.view.find('[data-semantic="publication.createMergeRequest"]').exists()).toBe(true)})
 it.each(['suggestion','fallback','edited'] as const)('submits the exact single-line preview for a multiline %s',async source=>{const multiline='目标：创建arch网页\r\n使用场景：旧代码梳理\n验收标准：打开网页搜索',f=fixture();if(source==='fallback')f.suggestion.mockRejectedValue(new ApiError('生成失败',422));else f.suggestion.mockResolvedValue({subject:multiline,aiGenerated:true});page(task({id:'task-1',title:multiline}));await flushPromises();await openCommit();await change('4 位数字工单号','2026');if(source==='edited')await change('AI 提交说明',multiline);const expected='#2026_目标：创建arch网页 使用场景：旧代码梳理 验收标准：打开网页搜索';expect(body().get('.ui-context-panel:not([hidden]) code').text()).toBe(expected);await submit();expect(f.publish).toHaveBeenCalledWith('task-1',expected)})
 it('opens the merge request dialog directly from the pushed-state button',async()=>{fixture({state:'PUSHED',deliveryState:'PUSHED',branch:'loopper/task-1',targetBranch:'develop',targetBranches:['develop','main']});page();await flushPromises();await action('publication.createMergeRequest');expect(body().get('.ui-context-panel:not([hidden])').text()).toContain('创建合并请求');expect(body().text()).toContain('loopper/task-1');expect(body().text()).toContain('develop')})
 it('keeps the merge request action available after a successful task is confirmed completed',async()=>{const f=fixture({state:'PUSHED',deliveryState:'PUSHED'}),p=page(task({status:'COMPLETED',executionResult:'SUCCEEDED'}));await flushPromises();expect(f.get).toHaveBeenCalledWith('task');expect(p.view.find('[data-semantic="publication.createMergeRequest"]').exists()).toBe(true)})
 it('shows an immutable merged result without another create action',async()=>{fixture({state:'MERGED',deliveryState:'MERGED',deliveryFinal:true,mergeRequest:{provider:'GITLAB',iid:1686,url:'http://gitlab.example/group/project/-/merge_requests/1686',state:'merged'}});const p=page();await flushPromises();expect(p.view.text()).toContain('交付：已合并');expect(p.view.find('[data-semantic="publication.createMergeRequest"]').isVisible()).toBe(false)})
 it('checks on entry and focus with a thirty-second cooldown',async()=>{const now=vi.spyOn(Date,'now').mockReturnValue(100_000),f=fixture({state:'PUSHED',deliveryState:'PUSHED'});const p=page();await flushPromises();expect(f.get).toHaveBeenCalledOnce();expect(f.reconcile).not.toHaveBeenCalled();act(()=>fireEvent.focus(window));await flushPromises();expect(f.get).toHaveBeenCalledOnce();now.mockReturnValue(130_001);act(()=>fireEvent.focus(window));await flushPromises();expect(f.get).toHaveBeenCalledTimes(2);expect(f.reconcile).not.toHaveBeenCalled();p.view.unmount()})
 it('shows opened and closed merge request actions',async()=>{const f=fixture({state:'MERGE_REQUEST_OPENED',deliveryState:'MERGE_REQUEST_OPENED',mergeRequest:{provider:'GITLAB',iid:1686,url:'http://gitlab.example/merge/1686',state:'opened'}}),p=page();await flushPromises();expect(p.view.find('[data-semantic="publication.viewMergeRequest"]').exists()).toBe(true);expect(p.view.find('[data-semantic="publication.checkMerge"]').exists()).toBe(true);f.reconcile.mockImplementation(async()=>{f.setPublication({state:'MERGE_REQUEST_CLOSED',deliveryState:'MERGE_REQUEST_CLOSED'});return{...await api.getTaskPublication('task'),state:'MERGE_REQUEST_CLOSED',deliveryState:'MERGE_REQUEST_CLOSED'}});await action('publication.checkMerge');expect(p.view.text()).toContain('合并请求已关闭');expect(p.view.find('[data-semantic="publication.reopenMergeRequest"]').exists()).toBe(true)})
 it('explains unavailable GitLab credentials and GitHub reconciliation',async()=>{const f=fixture({state:'PUSHED',deliveryState:'PUSHED',reconciliationAvailable:false}),p=page();await flushPromises();expect(p.view.text()).toContain('无法自动确认合并');p.view.unmount();p.dispose();f.setPublication({provider:'GITHUB'});const next=page();await flushPromises();expect(next.view.text()).toContain('GitHub合并状态暂未接入自动确认')})
 it('explains local task branch submission when no remote exists',async()=>{const f=fixture({remoteName:undefined,provider:'UNKNOWN'}),p=page(task({id:'task-1'}));f.suggestion.mockResolvedValue({subject:'完善任务发布流程',aiGenerated:true});await flushPromises();expect(p.view.find('[data-semantic="publication.commitLocal"]').exists()).toBe(true);await openCommit(true);await change('4 位数字工单号','3032');await action('publication.commitLocal',body().get('.ui-context-panel:not([hidden])').element!);expect(body().text()).toContain('原项目目录中当前任务分支');expect(f.publish).not.toHaveBeenCalled();await confirm('publication.commitLocal');expect(f.publish).toHaveBeenCalledWith('task-1','#3032_完善任务发布流程');expect(p.view.text()).toContain('已提交本地任务分支')})
 it('opens the conflict center, keeps apply disabled, then enables it after an explicit resolution',async()=>{const f=fixture({state:'LOCAL_SYNC_CONFLICT',conflictSessionId:'session',conflictCount:1,commitSha:'commit'}),p=page();await flushPromises();await action('publication.resolveLocal');expect(body().get('[aria-label="合并结果编辑器"]').exists()).toBe(true);expect((body().get('[data-semantic="publication.applyLocal"]').element as HTMLButtonElement).disabled).toBe(true);await action('publication.acceptTask');expect(f.save).toHaveBeenCalledWith('task','session',expect.objectContaining({path:content().path,resolution:'TASK',expectedVersion:4}));expect((p.view.get('[data-semantic="publication.applyLocal"]').element as HTMLButtonElement).disabled).toBe(false)})
 it('keeps AI output as an unselected suggestion until the user loads and saves it',async()=>{const f=fixture({state:'LOCAL_SYNC_CONFLICT',conflictSessionId:'session',conflictCount:1});page();await flushPromises();await action('publication.resolveLocal');const before=(body().get('[aria-label="合并结果编辑器"]').element as HTMLTextAreaElement).value;await action('publication.requestSuggestion');expect(f.ai).not.toHaveBeenCalled();await confirm('publication.requestSuggestion');expect(f.ai).toHaveBeenCalledOnce();expect((body().get('[aria-label="合并结果编辑器"]').element as HTMLTextAreaElement).value).toBe(before);expect(f.save).not.toHaveBeenCalled();await action('publication.loadSuggestion');expect((body().get('[aria-label="合并结果编辑器"]').element as HTMLTextAreaElement).value).toContain('int value = 3');expect(f.save).not.toHaveBeenCalled();await action('publication.saveMerge');expect(f.save).toHaveBeenCalledWith('task','session',expect.objectContaining({resolution:'MANUAL',expectedVersion:5,content:expect.stringContaining('int value = 3')}))})
 it('blocks unresolved git markers and shows verifier output after rollback',async()=>{const f=fixture({state:'LOCAL_SYNC_CONFLICT',conflictSessionId:'session',conflictCount:1});f.setSession({state:'ROLLED_BACK',resolvedCount:1,verificationEvidence:JSON.stringify({checks:[{type:'BUILD',passed:false,summary:'构建失败',evidence:{output:'compiler real error'}}]})});page();await flushPromises();await action('publication.resolveLocal');expect(body().text()).toContain('compiler real error');expect((body().get('[aria-label="合并结果编辑器"]').element as HTMLTextAreaElement).value).toContain('<<<<<<<');expect((body().get('[data-semantic="publication.applyLocal"]').element as HTMLButtonElement).disabled).toBe(true);expect(f.apply).not.toHaveBeenCalled()})
 it('shows stale and rolled-back states as recoverable actions',async()=>{const f=fixture({state:'LOCAL_SYNC_CONFLICT',conflictSessionId:'session',conflictCount:1});f.setSession({state:'STALE'});const p=page();await flushPromises();await action('publication.resolveLocal');expect(p.view.find('[data-semantic="publication.refreshConflicts"]').exists()).toBe(true);p.view.unmount();p.dispose();f.setSession({state:'ROLLED_BACK'});const next=page();await flushPromises();await action('publication.resolveLocal');expect(next.view.find('[data-semantic="publication.applyLocal"]').exists()).toBe(true);expect(f.apply).not.toHaveBeenCalled()})
})
