import type { Task, TaskPublicationStatus, LocalSyncConflictSession, LocalSyncConflictFile, LocalSyncConflictContent, RecoveryDraft } from '@/types/domain'

export const task = (patch: Partial<Task> = {}): Task => ({ id: 'task', projectId: 'project', projectName: '示例项目', title: '完成真实改动', goal: '保留原验收目标', branch: 'loopper/task', worktreePath: '/mock/task', status: 'SUCCEEDED', version: 3, executionResult: 'SUCCEEDED', attemptCount: 1, maxAttempts: 3, createdAt: '2026-10-03', updatedAt: '2026-10-03', ...patch })
export const publication = (patch: Partial<TaskPublicationStatus> = {}): TaskPublicationStatus => ({ state: 'READY', available: true, branch: 'loopper/task', remoteName: 'origin', remoteUrl: 'https://example.test/repo.git', targetBranch: 'main', targetBranches: ['main', 'develop'], provider: 'GITLAB', conflictCount: 0, resolvedCount: 0, hasChanges: true, deliveryState: 'NOT_STARTED', deliveryFinal: false, reconciliationAvailable: true, ...patch })
export const session = (patch: Partial<LocalSyncConflictSession> = {}): LocalSyncConflictSession => ({ id: 'session', taskId: 'task', state: 'OPEN', sourceRoot: '/mock/project', sourceHead: 'source', taskCommit: 'commit', baselineCommit: 'base', conflictCount: 1, resolvedCount: 0, createdAt: '2026-10-03', updatedAt: '2026-10-03', version: 3, ...patch })
export const conflictText = 'class Sample {\n<<<<<<< source\n  int value = 1;\n=======\n  int value = 2;\n>>>>>>> task\n}\n'
export const content = (patch: Partial<LocalSyncConflictContent> = {}): LocalSyncConflictContent => ({ path: 'src/Sample.java', contentType: 'TEXT', baseContent: 'class Sample {\n  int value = 0;\n}\n', sourceContent: 'class Sample {\n  int value = 1;\n}\n', taskContent: 'class Sample {\n  int value = 2;\n}\n', mergedContent: conflictText, baseHash: 'basehash', sourceHash: 'sourcehash', taskHash: 'taskhash', aiEligible: true, version: 4, ...patch })
export const file = (patch: Partial<LocalSyncConflictFile> = {}): LocalSyncConflictFile => ({ path: 'src/Sample.java', sourcePath: 'src/Sample.java', taskPath: 'src/Sample.java', changeType: 'MODIFY', contentType: 'TEXT', resolved: false, hasAiSuggestion: false, baseHash: 'basehash', sourceHash: 'sourcehash', taskHash: 'taskhash', version: 4, ...patch })
export const recovery = (patch: Partial<RecoveryDraft> = {}): RecoveryDraft => ({ taskId: 'child', parentTaskId: 'task', mode: 'FROM_FAILED_STAGE', parentStageId: 'failed', workspaceFingerprint: 'frozenhash', writableSession: true, ...patch })
