import { StrictMode } from 'react'
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { api } from '@/api/client'
import { FoundationProvider } from '@/foundation/provider'
import { semanticName } from '@/foundation/semanticRegistry'
import { skins } from '@/themes/registry'
import { TaskPublicationActions } from './TaskPublicationActions'
import { content, deferred, fixture, pageProps, task } from './test-support'

const live: ReturnType<typeof pageProps>[] = []
beforeEach(() => { vi.stubGlobal('matchMedia', () => ({ matches: false, addEventListener: vi.fn(), removeEventListener: vi.fn(), addListener: vi.fn(), removeListener: vi.fn() })) })
afterEach(() => { cleanup(); for (const p of live) p.retire(); live.length = 0; vi.restoreAllMocks(); vi.unstubAllGlobals() })
function page(strict = false, initial = task()) { const p = pageProps(); live.push(p); const child = <FoundationProvider skin={p.props.skin} reducedMotion><main className="ui-shell-main" tabIndex={-1}><TaskPublicationActions task={initial} page={p.props} parent={p.parent} /></main></FoundationProvider>; return { ...p, view: render(strict ? <StrictMode>{child}</StrictMode> : child) } }
const click = (key: Parameters<typeof semanticName>[0], target?: string) => fireEvent.click(screen.getByRole('button', { name: semanticName(key, target) }))
async function commit() { await screen.findByRole('button', { name: semanticName('publication.commit') }); click('publication.commit'); return screen.findByRole('complementary', { name: '提交任务变更' }) }

describe('W4 full React publication UI', () => {
  it('uses root StrictMode leases without implicit writes and releases its actual owned focus listener', async () => {
    const f = fixture(), add = vi.spyOn(window, 'addEventListener'), remove = vi.spyOn(window, 'removeEventListener'), p = page(true); await screen.findByRole('button', { name: semanticName('publication.commit') }); const focus = add.mock.calls.filter(row => row[0] === 'focus'); expect(focus).toHaveLength(1); expect(f.suggestion).not.toHaveBeenCalled(); expect(f.publish).not.toHaveBeenCalled(); expect(f.reconcile).not.toHaveBeenCalled(); expect(p.children.size).toBe(1); p.view.unmount(); p.retire(); expect(remove.mock.calls.filter(row => row[0] === 'focus' && row[1] === focus[0]![1])).toHaveLength(1); expect(p.children.size).toBe(0)
  })
  it('defaults the publish confirmation to Stay and only confirms the exact normalized preview once', async () => {
    const f = fixture(); page(); const panel = await commit(); await waitFor(() => expect((screen.getByLabelText('AI 提交说明') as HTMLTextAreaElement).value).toBe('根据已验收差异更新接口')); fireEvent.change(screen.getByLabelText('4 位数字工单号'), { target: { value: '1234' } }); fireEvent.change(screen.getByLabelText('AI 提交说明'), { target: { value: '修改\n真实接口' } }); fireEvent.click(within(panel).getByRole('button', { name: semanticName('publication.commit') })); const dialog = await screen.findByRole('dialog'); expect(within(dialog).getByRole('button', { name: semanticName('ui.stay') })).toBeTruthy(); fireEvent.click(within(dialog).getByRole('button', { name: semanticName('ui.stay') })); expect(f.publish).not.toHaveBeenCalled(); fireEvent.click(within(panel).getByRole('button', { name: semanticName('publication.commit') })); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: semanticName('publication.commit') })); await waitFor(() => expect(f.publish).toHaveBeenCalledExactlyOnceWith('task', '#1234_修改 真实接口'))
  })
  it('blocks an old publication confirmation after a legitimate focus read changes its branch, and requires a new confirmation', async () => {
    const f = fixture(); page(); const panel = await commit()
    await waitFor(() => expect((screen.getByLabelText('AI 提交说明') as HTMLTextAreaElement).disabled).toBe(false))
    fireEvent.change(screen.getByLabelText('4 位数字工单号'), { target: { value: '1234' } })
    fireEvent.click(within(panel).getByRole('button', { name: semanticName('publication.commit') }))
    const dialog = await screen.findByRole('dialog'), originalReads = f.get.mock.calls.length
    f.setPublication({ branch: 'loopper/new-task-branch' }); vi.spyOn(Date, 'now').mockReturnValue(Date.now() + 31_000); fireEvent.focus(window)
    await waitFor(() => expect(f.get).toHaveBeenCalledTimes(originalReads + 1))
    await waitFor(() => expect(within(dialog).getByRole('button', { name: semanticName('publication.commit') }).hasAttribute('disabled')).toBe(true))
    expect(f.publish).not.toHaveBeenCalled(); expect((screen.getByLabelText('4 位数字工单号') as HTMLInputElement).value).toBe('1234')
    fireEvent.click(within(dialog).getByRole('button', { name: semanticName('ui.stay') }))
    fireEvent.click(within(panel).getByRole('button', { name: semanticName('publication.commit') }))
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: semanticName('publication.commit') }))
    await waitFor(() => expect(f.publish).toHaveBeenCalledOnce())
    expect(f.publish.mock.calls[0]).toEqual(['task', '#1234_根据已验收差异更新接口'])
  })
  it('keeps unknown body, controls, owner DOM and parent blocking through all three in-place skins', async () => {
    const f = fixture(); f.suggestion.mockRejectedValueOnce(new Error('lost')); const p = page(); await commit(); await waitFor(() => expect(document.querySelector('[data-operation-phase="UNKNOWN"]')).toBeTruthy()); const root = document.querySelector('[data-task-publication]'), input = screen.getByLabelText('AI 提交说明'); expect((input as HTMLTextAreaElement).disabled).toBe(true); for (const skin of skins) p.view.rerender(<FoundationProvider skin={skin} reducedMotion><main className="ui-shell-main"><TaskPublicationActions task={task()} page={{ ...p.props, skin }} parent={p.parent} /></main></FoundationProvider>); expect(document.querySelector('[data-task-publication]')).toBe(root); expect(screen.getByLabelText('AI 提交说明')).toBe(input); expect(f.suggestion).toHaveBeenCalledOnce(); expect(f.publish).not.toHaveBeenCalled(); expect(p.parent.canStartWrite()).toBe(false); expect(p.leave()[0]?.kind).toBe('BLOCK')
  })
  it('preserves native manual draft with dirty Stay then explicit discard and restores the original trigger', async () => {
    fixture(); const p = page(); const trigger = await screen.findByRole('button', { name: semanticName('publication.commit') }); trigger.focus(); const panel = await commit(); await waitFor(() => expect((screen.getByLabelText('AI 提交说明') as HTMLTextAreaElement).disabled).toBe(false)); fireEvent.change(screen.getByLabelText('4 位数字工单号'), { target: { value: '1234' } }); fireEvent.click(within(panel).getByRole('button', { name: semanticName('ui.close', '提交任务变更') })); const dialog = await screen.findByRole('dialog'); fireEvent.click(within(dialog).getByRole('button', { name: semanticName('ui.stay') })); expect((screen.getByLabelText('4 位数字工单号') as HTMLInputElement).value).toBe('1234'); expect(p.leave()[0]?.kind).toBe('CONFIRM_DISCARD'); fireEvent.click(within(panel).getByRole('button', { name: semanticName('ui.close', '提交任务变更') })); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: semanticName('ui.discardChanges') })); await waitFor(() => expect(screen.queryByRole('complementary', { name: '提交任务变更' })).toBeNull()); expect(p.leave()[0]?.kind).toBe('ALLOW'); await waitFor(() => expect(document.activeElement).toBe(trigger))
  })
  it('opens MR directly for a successful completed task and preserves creation link after popup and clipboard are unavailable', async () => {
    const f = fixture({ state: 'PUSHED', deliveryState: 'PUSHED', commitSha: 'commit' }); const open = vi.spyOn(window, 'open').mockReturnValue(null); page(false, task({ status: 'COMPLETED' })); await screen.findByRole('button', { name: semanticName('publication.createMergeRequest') }); click('publication.createMergeRequest'); const panel = await screen.findByRole('complementary', { name: '创建合并请求' }); fireEvent.change(within(panel).getByLabelText('合并请求标题'), { target: { value: '复核标题' } }); fireEvent.click(within(panel).getByRole('button', { name: semanticName('publication.createMergeRequest') })); await screen.findByText('浏览器阻止了新窗口，请使用下面的创建页链接。'); expect(open).toHaveBeenCalledWith('https://example.test/merge/new', '_blank', 'noopener,noreferrer'); expect(screen.getByRole('link', { name: '打开已确认创建页' }).getAttribute('rel')).toBe('noopener noreferrer'); expect(f.mr).toHaveBeenCalledOnce()
  })
  it('projects opened/closed/merged states and token/provider explanations without implicit reconcile', async () => {
    const f = fixture({ state: 'MERGE_REQUEST_OPENED', deliveryState: 'MERGE_REQUEST_OPENED', reconciliationAvailable: false, mergeRequest: { provider: 'GITLAB', iid: 12, url: 'https://example.test/merge/12' } }); page(); await screen.findByRole('button', { name: semanticName('publication.viewMergeRequest') }); expect(screen.getByText('未配置GitLab Token，无法自动确认合并状态')).toBeTruthy(); expect(f.reconcile).not.toHaveBeenCalled(); f.setPublication({ state: 'MERGED', deliveryState: 'MERGED', deliveryFinal: true }); vi.spyOn(Date, 'now').mockReturnValue(Date.now() + 31_000); fireEvent.focus(window); await screen.findByText('已合并'); expect(screen.queryByRole('button', { name: semanticName('publication.createMergeRequest') })).toBeNull(); expect(f.reconcile).not.toHaveBeenCalled();
  })
  it('shows real three-way code with Java language and adopts a block into the controlled manual editor before saving', async () => {
    const f = fixture({ state: 'LOCAL_SYNC_CONFLICT', deliveryState: 'COMMITTED', conflictSessionId: 'session', commitSha: 'commit', conflictCount: 1 }); page(); await screen.findByRole('button', { name: semanticName('publication.resolveLocal', '1个文件') }); click('publication.resolveLocal', '1个文件'); await screen.findByRole('textbox', { name: '合并结果编辑器' }); expect(document.querySelector('.w4-merge-editor')?.getAttribute('data-language')).toBe('java'); expect(screen.getByRole('textbox', { name: '源项目内容' }).textContent).toContain('int value = 1'); expect(screen.getByRole('textbox', { name: '任务内容' }).textContent).toContain('int value = 2'); click('publication.acceptTaskBlock'); expect((screen.getByLabelText('合并结果编辑器') as HTMLTextAreaElement).value).not.toContain('<<<<<<<'); expect(f.save).not.toHaveBeenCalled(); click('publication.saveMerge'); await waitFor(() => expect(f.save).toHaveBeenCalledOnce()); expect(f.save.mock.calls[0]![2]).toMatchObject({ resolution: 'MANUAL', expectedVersion: 4 }); expect(screen.getByRole('button', { name: semanticName('publication.applyLocal') }).hasAttribute('disabled')).toBe(false)
  })
  it('exposes verifier failure output and rollback backup while prohibiting source writes', async () => {
    const f = fixture({ state: 'LOCAL_SYNC_CONFLICT', conflictSessionId: 'session', conflictCount: 1 }); f.setSession({ state: 'ROLLBACK_FAILED', backupDir: '/mock/backup', verificationEvidence: JSON.stringify({ checks: [{ type: 'BUILD', passed: false, summary: '构建失败', path: 'src', evidence: { output: 'compiler real error' } }] }) }); page(); await screen.findByRole('button', { name: semanticName('publication.resolveLocal', '1个文件') }); click('publication.resolveLocal', '1个文件'); await screen.findByText(/自动恢复失败/); expect(screen.getByText(/compiler real error/)).toBeTruthy(); expect(screen.getByRole('button', { name: semanticName('publication.applyLocal') }).hasAttribute('disabled')).toBe(true); expect(f.apply).not.toHaveBeenCalled()
  })
  it('declares unknown explicit AI as external but preserves the editor until load and blocks edits while pending', async () => {
    const f = fixture({ state: 'LOCAL_SYNC_CONFLICT', conflictSessionId: 'session', conflictCount: 1 }); const late = deferred<{ path: string; suggestion: string; automaticallySelected: boolean; version: number }>(); f.ai.mockReturnValueOnce(late.promise); page(); await screen.findByRole('button', { name: semanticName('publication.resolveLocal', '1个文件') }); click('publication.resolveLocal', '1个文件'); const editor = await screen.findByRole('textbox', { name: '合并结果编辑器' }); const before = (editor as HTMLTextAreaElement).value; click('publication.requestSuggestion'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: semanticName('publication.requestSuggestion') })); await waitFor(() => expect(f.ai).toHaveBeenCalledOnce()); expect((editor as HTMLTextAreaElement).disabled).toBe(true); await act(async () => { late.resolve({ path: content().path, suggestion: 'manual AI result', automaticallySelected: false, version: 5 }) }); expect((editor as HTMLTextAreaElement).value).toBe(before); expect(f.save).not.toHaveBeenCalled(); click('publication.loadSuggestion'); expect((editor as HTMLTextAreaElement).value).toBe('manual AI result'); expect(f.save).not.toHaveBeenCalled()
  })
  it('does not render executable publication commands for template reports or failed tasks', async () => {
    fixture(); page(false, task({ executionMode: 'TEMPLATE_REPORT' })); await Promise.resolve(); expect(screen.queryByRole('button', { name: semanticName('publication.commit') })).toBeNull(); expect(api.getTaskPublication).not.toHaveBeenCalled()
  })
  it('does not carry an old pending scope into a newly rendered task or let its late receipt project there', async () => {
    const f = fixture(), late = deferred<{ subject: string; aiGenerated: boolean }>(); f.suggestion.mockReturnValueOnce(late.promise); const p = page(); await commit(); await waitFor(() => expect(document.querySelector('[data-operation-phase="SENDING"]')).toBeTruthy()); p.view.rerender(<FoundationProvider skin={p.props.skin} reducedMotion><main className="ui-shell-main" tabIndex={-1}><TaskPublicationActions task={task({ id: 'other' })} page={p.props} parent={p.parent} /></main></FoundationProvider>); expect(document.querySelector('[data-task-publication]')?.getAttribute('data-task-publication')).toBe('task'); await act(async () => { late.resolve({ subject: 'late original', aiGenerated: true }) }); await waitFor(() => expect(document.querySelector('[data-task-publication]')?.getAttribute('data-task-publication')).toBe('other')); expect(screen.queryByRole('textbox', { name: 'AI 提交说明' })).toBeNull(); expect((screen.getByLabelText('AI 提交说明') as HTMLTextAreaElement).value).toBe(''); expect(api.publishTask).not.toHaveBeenCalled()
  })
})
