import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { api, ApiError } from '@/api/client'
import type { DesignerMessage } from '@/types/domain'
import { taskFixture } from '@/pages/w4/task/test-support'
import { createDesignerController } from './controller'
import { deferred, draft, flush, mockDesigner, pageProps, session, spec } from './test-support'
vi.mock('@/api/client', async original => ({ ...await original<typeof import('@/api/client')>(), subscribeDesignerEvents: vi.fn() }))
const releases: (() => void)[] = []
beforeEach(() => sessionStorage.clear())
afterEach(() => { releases.splice(0).forEach(release => release()); vi.restoreAllMocks(); vi.useRealTimers(); vi.unstubAllGlobals() })
async function mounted(value = session()) { mockDesigner(value); const navigation = pageProps().props.navigation; const owner = createDesignerController({ sessionId: value.id, historyOnly: true, navigation }); const detach = owner.attachView(); releases.push(() => { detach(); owner.retire(true) }); await flush(); return { owner, navigation } }
const message = (id: string, text: string): DesignerMessage => ({ id, role: 'ASSISTANT', actor: 'DESIGNER', content: text, createdAt: '2026-10-03' })
describe('Designer original frozen command and read capabilities', () => {
  it('same-session old poll cannot overwrite accepted new revision, permissions or persisted messages', async () => {
    const { owner } = await mounted(), old = deferred<ReturnType<typeof session>>(); vi.mocked(api.getDesignerSession).mockReturnValueOnce(old.promise); const staleRead = owner.refresh(); await flush()
    const accepted = message('new', '已接受的新设计'); const latest = session('A', { discussionRevision: 2, messages: [accepted], permissionSummary: '最新权限', taskProfile: { ...session().taskProfile, version: 8 }, draft: { ...draft(), version: 1 } })
    vi.mocked(api.sendRequirementMessage).mockResolvedValue({ sessionId: 'A', state: 'REVIEWING', persistedMessages: [accepted], notice: '' }); vi.mocked(api.getDesignerSession).mockResolvedValue(latest); owner.setMessage('原消息'); await owner.send(); old.resolve(session('A', { permissionSummary: '旧权限', messages: [message('old', '旧正文')] })); await staleRead
    expect(owner.getSnapshot().session?.discussionRevision).toBe(2); expect(owner.getSnapshot().session?.taskProfile.version).toBe(8); expect(owner.getSnapshot().draft?.version).toBe(1); expect(owner.getSnapshot().session?.permissionSummary).toBe('最新权限'); expect(owner.getSnapshot().session?.messages).toEqual([accepted])
  })
  it('explicit refresh refuses a lower version without replacing the dirty baseline', async () => { const { owner } = await mounted(session('A', { discussionRevision: 3, draft: { ...draft(), version: 4 } })); owner.setEditor(JSON.stringify(spec('本地编辑'))); vi.mocked(api.getDesignerSession).mockResolvedValue(session('A', { discussionRevision: 2, draft: { ...draft(), version: 3 } })); expect(await owner.refresh()).toBe(false); expect(owner.getSnapshot().baseline).toBe(4); expect(owner.getSnapshot().editor).toContain('本地编辑'); expect(owner.getSnapshot().session?.discussionRevision).toBe(3) })
  it('CAS draft rejection retains local spec and permits only explicit latest GET without retry PUT', async () => {
    const { owner } = await mounted(); owner.setEditor(JSON.stringify(spec('本地保留'))); const update = vi.spyOn(api, 'updateDraft').mockRejectedValue(new ApiError('draft conflict', 409, { code: 'DRAFT_VERSION_CONFLICT' })); await owner.saveDraft(); expect(owner.getSnapshot().command.phase).toBe('SETTLED'); expect(owner.getSnapshot().conflict).toBe(true); expect(owner.getSnapshot().editor).toContain('本地保留'); expect(owner.canLeave().kind).toBe('CONFIRM_DISCARD')
    const latest = { ...draft(spec('服务端规范')), version: 2 }; vi.mocked(api.getDraft).mockResolvedValue(latest); vi.mocked(api.getDesignerSession).mockResolvedValue(session('A', { draft: latest })); await owner.reloadDraft(); expect(owner.getSnapshot().baseline).toBe(2); expect(owner.getSnapshot().conflict).toBe(false); expect(owner.getSnapshot().editor).toContain('服务端规范'); expect(update).toHaveBeenCalledOnce()
  })
  it('unrelated 409 retains UNKNOWN and cannot unlock or replace the original write', async () => { const { owner } = await mounted(); owner.setEditor(JSON.stringify(spec('原编辑'))); vi.spyOn(api, 'updateDraft').mockRejectedValue(new ApiError('uncertain', 409, { code: 'OTHER_CONFLICT' })); await owner.saveDraft(); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.reloadDraft(); expect(api.updateDraft).toHaveBeenCalledOnce(); expect(owner.getSnapshot().editor).toContain('原编辑') })
  it('profile CAS rejection refreshes latest settings and preserves informational recovery', async () => {
    const { owner } = await mounted(); vi.spyOn(api, 'previewDesignerTaskProfileUpdate').mockResolvedValue({ selectionChanged: true, updateRequired: true, sessionRestartRequired: true, targetWorkflowTemplate: 'FULL_PACKAGE_DESIGN' }); owner.editProfile(); const proposal = await owner.previewProfile(); expect(proposal).toBeDefined(); vi.spyOn(api, 'updateDesignerTaskProfile').mockRejectedValue(new ApiError('profile conflict', 409, { code: 'TASK_PROFILE_VERSION_CONFLICT' })); vi.mocked(api.getDesignerSession).mockResolvedValue(session('A', { taskProfile: { ...session().taskProfile, version: 8 } })); await owner.applyProfile(proposal!); expect(owner.getSnapshot().command.phase).toBe('SETTLED'); expect(owner.getSnapshot().session?.taskProfile.version).toBe(8); expect(owner.getSnapshot().error).toBe(''); expect(owner.getSnapshot().notice).toContain('已刷新最新结果'); expect(api.updateDesignerTaskProfile).toHaveBeenCalledOnce()
  })
  it.each(['missing-task', 'other-draft', 'other-task'])('accepted confirmation %s remains readback-only with no repeat POST or handoff', async kind => {
    const { owner, navigation } = await mounted(session('A', { state: 'COMPLETED', workflowPhase: 'COMPLETED', finalConfirmationEligible: true })); vi.spyOn(api, 'confirmDraft').mockResolvedValue({ taskId: kind === 'missing-task' ? '' : 'accepted' }); vi.mocked(api.getDraft).mockResolvedValue({ ...draft(), id: kind === 'other-draft' ? 'another' : 'draft-A', status: 'CONFIRMED' }); vi.spyOn(api, 'getTaskOverview').mockResolvedValue(taskFixture(kind === 'other-task' ? 'another' : 'accepted')); vi.spyOn(api, 'getTaskAudit').mockResolvedValue({ attempts: [], artifacts: [], errors: [], judges: [] }); await owner.confirm(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(navigation.goAccepted).not.toHaveBeenCalled(); await owner.openTask(); expect(api.confirmDraft).toHaveBeenCalledOnce(); expect(navigation.goAccepted).not.toHaveBeenCalled(); expect(owner.canLeave().kind).toBe('BLOCK')
  })
  it('already-confirmed task uses exact GET evidence and one temporary destination with zero POST', async () => {
    const { owner, navigation } = await mounted(session('A', { taskId: 'existing', draft: { ...draft(), status: 'CONFIRMED' }, state: 'COMPLETED', workflowPhase: 'COMPLETED' })); const confirm = vi.spyOn(api, 'confirmDraft'); vi.spyOn(api, 'getTaskOverview').mockResolvedValue(taskFixture('existing')); vi.spyOn(api, 'getTaskAudit').mockResolvedValue({ attempts: [], artifacts: [], errors: [], judges: [] }); vi.mocked(navigation.go).mockImplementation(async () => { expect(owner.canLeave({ destination: '/tasks/existing' }).kind).toBe('ALLOW'); expect(owner.canLeave({ destination: '/tasks/other' }).kind).toBe('BLOCK'); return false }); expect(await owner.openTask()).toBe(false); expect(owner.getSnapshot().acceptedTask).toBe('existing'); expect(owner.canLeave({ destination: '/tasks/existing' }).kind).toBe('BLOCK'); expect(confirm).not.toHaveBeenCalled(); expect(navigation.goAccepted).not.toHaveBeenCalled(); expect(api.getTaskOverview).toHaveBeenCalledWith('existing'); expect(api.getTaskAudit).toHaveBeenCalledWith('existing')
  })
  it('wrong known-task GET and later composer input both refuse the read-only handoff', async () => { const { owner, navigation } = await mounted(session('A', { taskId: 'existing', draft: { ...draft(), status: 'CONFIRMED' } })); vi.spyOn(api, 'getTaskOverview').mockResolvedValue(taskFixture('other')); vi.spyOn(api, 'getTaskAudit').mockResolvedValue({ attempts: [], artifacts: [], errors: [], judges: [] }); expect(await owner.openTask()).toBe(false); expect(navigation.go).not.toHaveBeenCalled(); expect(api.getTaskAudit).not.toHaveBeenCalled(); owner.setMessage('后来草稿'); expect(await owner.openTask()).toBe(false); expect(api.getTaskOverview).toHaveBeenCalledOnce() })
  it('accepted failed readback cannot hand off merely because the receipt is present', async () => { const { owner, navigation } = await mounted(session('A', { state: 'COMPLETED', workflowPhase: 'COMPLETED', finalConfirmationEligible: true })); vi.spyOn(api, 'confirmDraft').mockResolvedValue({ taskId: 'accepted' }); vi.mocked(api.getDraft).mockRejectedValue(new Error('get failed')); await owner.confirm(); expect(owner.getSnapshot().acceptedTask).toBe('accepted'); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(navigation.goAccepted).not.toHaveBeenCalled(); expect(api.confirmDraft).toHaveBeenCalledOnce() })
  it('stop without archive proof cannot clear original identity or navigate', async () => { const { owner, navigation } = await mounted(); vi.spyOn(api, 'stopDesignerSession').mockResolvedValue({ stopStatus: 'STOPPING', archived: false, stoppedSessions: 0, failedSessions: 0, pendingFinalizations: 1 }); expect(await owner.reset()).toBe(false); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(navigation.go).not.toHaveBeenCalled(); expect(owner.getSnapshot().session?.id).toBe('A'); await owner.recover(); expect(api.stopDesignerSession).toHaveBeenCalledOnce() })
  it('initial StoryBinding needs an actual available capability read', async () => { mockDesigner(); const owner = createDesignerController({ historyOnly: false, navigation: pageProps().props.navigation }); const detach = owner.attachView(); releases.push(() => { detach(); owner.retire(true) }); await flush(); expect(api.getStoryBindingCapability).toHaveBeenCalledWith('project'); owner.setStory({ enabled: true, systemCode: 'sys', storyCode: 'story' }); expect(owner.getSnapshot().story.enabled).toBe(false); vi.mocked(api.getStoryBindingCapability).mockResolvedValue({ available: true, state: 'AVAILABLE', reason: '可用', checkedAt: '2026-10-03' }); owner.detectStory(); await flush(); owner.setStory({ enabled: true, systemCode: 'sys', storyCode: 'story' }); owner.setPrompt('原目标'); await owner.initialSubmit(); expect(api.createDesignerSession).toHaveBeenCalledWith('project', 'draft-A', '原目标', false, { enabled: true, systemCode: 'sys', storyCode: 'story' }) })
  it('requirement confirmation requires service confirmationReady', async () => { const { owner } = await mounted(session('A', { taskProfile: { ...session().taskProfile, confirmationReady: false } })); const confirm = vi.spyOn(api, 'confirmDesignerRequirement').mockResolvedValue(); await owner.action('confirmRequirement'); expect(confirm).not.toHaveBeenCalled() })
  it('accepted report conversion with failed navigation retains the original receipt and does not repeat POST', async () => {
    const { owner, navigation } = await mounted(); const report = { id: 'report', title: '冻结报告', state: 'COMPLETED', markdown: '# 报告', contentSha256: 'a', sourceSnapshotSha256: 'b', evidence: [], stale: false, createdAt: '2026-10-03', updatedAt: '2026-10-03', findings: [] }; vi.spyOn(api, 'getAnalysisReport').mockResolvedValue(report); await owner.loadReport('report'); vi.spyOn(api, 'convertAnalysisReportToDesign').mockResolvedValue(session('converted', { draft: { ...draft(), id: 'converted-draft' } })); vi.mocked(navigation.goAccepted).mockResolvedValue(false); await owner.convertReport(); expect(owner.getSnapshot().acceptedDesign).toEqual({ sessionId: 'converted', draftId: 'converted-draft' }); expect(owner.getSnapshot().session?.id).toBe('A'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.openDesign(); expect(api.convertAnalysisReportToDesign).toHaveBeenCalledOnce(); expect(navigation.goAccepted).toHaveBeenCalledTimes(2)
  })
  it('copy-v2 keeps the two original commands distinct and blocks keyless session creation uncertainty', async () => {
    const legacy = { ...spec(), schemaVersion: 'v1' as const }, { owner } = await mounted(session('A', { draft: draft(legacy) })); const copied = { ...draft(), id: 'copy', version: 0 }; vi.spyOn(api, 'copyDraftAsV2').mockResolvedValue(copied); vi.mocked(api.createDesignerSession).mockRejectedValue(new Error('uncertain second command')); await owner.copyV2(); expect(api.copyDraftAsV2).toHaveBeenCalledWith('draft-A'); expect(api.createDesignerSession).toHaveBeenCalledWith('project', 'copy'); expect(owner.getSnapshot().draft?.id).toBe('copy'); expect(owner.getSnapshot().session?.id).toBe('A'); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); await owner.recover(); await owner.copyV2(); expect(api.copyDraftAsV2).toHaveBeenCalledOnce(); expect(api.createDesignerSession).toHaveBeenCalledOnce()
  })

})
