import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { api, subscribeDesignerEvents } from '@/api/client'
import { taskFixture } from '@/pages/w4/task/test-support'
import { createDesignerController } from './controller'
import { deferred, draft, flush, mockDesigner, pageProps, session, spec } from './test-support'
vi.mock('@/api/client', async original => ({ ...await original<typeof import('@/api/client')>(), subscribeDesignerEvents: vi.fn() }))
let cleanup: (() => void)[] = []
afterEach(() => { cleanup.forEach(f => f()); cleanup = []; vi.useRealTimers(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
beforeEach(() => { sessionStorage.clear() })
async function mount(value = session(), options: { initial?: boolean; focus?: () => void } = {}) { mockDesigner(value); const navigation = pageProps().props.navigation; const owner = createDesignerController({ sessionId: options.initial ? undefined : value.id, historyOnly: !options.initial, navigation, focusComposer: options.focus }); const detach = owner.attachView(); cleanup.push(() => { detach(); owner.retire(true) }); await flush(); return { owner, navigation, detach } }
describe('Designer pure single owner', () => {
  it('completed historical auto receipt opens the exact started task through GET only', async () => {
    const value = session('A', { autoMode: { enabled: false, state: 'COMPLETED', lastAction: 'TASK_START_REQUESTED', taskId: 'auto-original', version: 7 } })
    mockDesigner(value)
    vi.spyOn(api, 'getTaskOverview').mockResolvedValue(taskFixture('auto-original'))
    vi.spyOn(api, 'getTaskAudit').mockResolvedValue({ attempts: [], errors: [], judges: [], artifacts: [] })
    const navigation = pageProps().props.navigation, owner = createDesignerController({ sessionId: value.id, historyOnly: true, navigation })
    const detach = owner.attachView(); cleanup.push(() => { detach(); owner.retire(true) }); await flush()
    expect(api.getTaskOverview).toHaveBeenCalledWith('auto-original'); expect(api.getTaskAudit).toHaveBeenCalledWith('auto-original')
    expect(navigation.go).toHaveBeenCalledWith('/tasks/auto-original')
    expect(api.createDraft).not.toHaveBeenCalled(); expect(api.createDesignerSession).not.toHaveBeenCalled(); expect(api.createDesignerContextTurn).not.toHaveBeenCalled()
  })
  it.each(['dirty', 'unknown'] as const)('completed historical auto receipt retains %s composer and never hands off that protected owner', async phase => {
    const { owner, navigation } = await mount()
    owner.setMessage('原消息')
    if (phase === 'unknown') { owner.stageFiles([new File(['original bytes'], 'original.txt')]); vi.mocked(api.sendDesignerContextTurn).mockRejectedValueOnce(new Error('unknown')); await owner.send() }
    const original = owner.getSnapshot().command, files = owner.fileRefs().followup
    vi.spyOn(api, 'getTaskOverview').mockResolvedValue(taskFixture('auto-original')); vi.spyOn(api, 'getTaskAudit').mockResolvedValue({ attempts: [], errors: [], judges: [], artifacts: [] })
    vi.mocked(api.getDesignerSession).mockResolvedValue(session('A', { autoMode: { enabled: false, state: 'COMPLETED', lastAction: 'TASK_START_REQUESTED', taskId: 'auto-original', version: 7 } }))
    await owner.refresh(); await flush()
    expect(navigation.go).not.toHaveBeenCalled(); expect(api.getTaskOverview).not.toHaveBeenCalled(); expect(api.getTaskAudit).not.toHaveBeenCalled()
    expect(owner.getSnapshot().message).toBe('原消息'); expect(owner.fileRefs().followup).toEqual(files)
    // The task already exists: its unfinished handoff remains protected even
    // when the only local input is an ordinary unsent message.
    expect(owner.canLeave().kind).toBe('BLOCK')
    if (phase === 'unknown') { expect(owner.getSnapshot().command).toEqual(original); expect(api.sendDesignerContextTurn).toHaveBeenCalledOnce() }
    else expect(api.sendRequirementMessage).not.toHaveBeenCalled()
  })
  it('attaches reads only and keeps saved READ_ONLY design editable', async () => { const { owner } = await mount(); expect(owner.canLeave().kind).toBe('ALLOW'); owner.setMessage('未发送'); expect(owner.canLeave().kind).toBe('CONFIRM_DISCARD'); expect(api.createDesignerSession).not.toHaveBeenCalled(); expect(subscribeDesignerEvents).toHaveBeenCalledOnce() })
  it.each(['initial', 'followup'])('keeps %s ordered real File refs and exact operation body in UNKNOWN', async channel => { const { owner } = await mount(session(), { initial: channel === 'initial' }); const file = new File(['original'], 'original.txt'), extra = new File(['later'], 'extra.txt'); owner.stageFiles([file]); if (channel === 'initial') { owner.setPrompt('原目标'); vi.mocked(api.createDesignerContextTurn).mockRejectedValueOnce(new Error('unknown')); await owner.initialSubmit() } else { owner.setMessage('原消息'); vi.mocked(api.sendDesignerContextTurn).mockRejectedValueOnce(new Error('unknown')); await owner.send() }
    expect(owner.canLeave().kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); const original = channel === 'initial' ? vi.mocked(api.createDesignerContextTurn).mock.calls[0]! : vi.mocked(api.sendDesignerContextTurn).mock.calls[0]!
    owner.setMessage('后来编辑'); owner.stageFiles([extra]); await owner.recover(); const retry = channel === 'initial' ? vi.mocked(api.createDesignerContextTurn).mock.calls[1]! : vi.mocked(api.sendDesignerContextTurn).mock.calls[1]!
    expect(retry[channel === 'initial' ? 0 : 1]).toEqual(original[channel === 'initial' ? 0 : 1]); expect(retry[channel === 'initial' ? 1 : 2]).toEqual([file]); expect((retry[channel === 'initial' ? 1 : 2] as File[])[0]).toBe(file); expect(owner.getSnapshot().message).toBe('后来编辑'); expect(owner.fileRefs().followup).toEqual([extra])
  })
  it('keyless uncertain write cannot repeat even after read snapshot', async () => { const { owner } = await mount(); owner.setMessage('原消息'); vi.mocked(api.sendRequirementMessage).mockRejectedValue(new Error('unknown')); await owner.send(); await owner.refresh(); await owner.recover(); await owner.send(); expect(api.sendRequirementMessage).toHaveBeenCalledOnce(); expect(owner.canLeave().kind).toBe('BLOCK') })
  it('preserves later composer input after accepted original send', async () => { const { owner } = await mount(), pending = deferred<Awaited<ReturnType<typeof api.sendRequirementMessage>>>(); vi.mocked(api.sendRequirementMessage).mockReturnValue(pending.promise); owner.setMessage('原消息'); const send = owner.send(); await flush(); owner.setMessage('后来编辑'); pending.resolve({ sessionId: 'A', state: 'REVIEWING', persistedMessages: [], notice: '' }); await send; expect(owner.getSnapshot().message).toBe('后来编辑') })
  it('late question receipt launches no retired GET', async () => { const { owner } = await mount(), pending = deferred<void>(); vi.spyOn(api, 'replyDesignerQuestion').mockReturnValue(pending.promise); const reply = owner.replyQuestion('q', [['原答案']]); await flush(); const reads = vi.mocked(api.getDesignerSession).mock.calls.length; owner.retire(true); pending.resolve(); await reply; expect(api.getDesignerSession).toHaveBeenCalledTimes(reads) })
  it('profile preview does not survive scope retirement', async () => { const { owner } = await mount(), pending = deferred<Awaited<ReturnType<typeof api.previewDesignerTaskProfileUpdate>>>(); vi.spyOn(api, 'previewDesignerTaskProfileUpdate').mockReturnValue(pending.promise); vi.spyOn(api, 'updateDesignerTaskProfile').mockResolvedValue(session().taskProfile); owner.editProfile(); owner.changeProfile({ ...owner.getSnapshot().profile!, largeTask: true }); const preview = owner.previewProfile(); await flush(); owner.retire(true); pending.resolve({ selectionChanged: true, updateRequired: true, sessionRestartRequired: true, targetWorkflowTemplate: 'FULL_PACKAGE_DESIGN' }); expect(await preview).toBeUndefined(); expect(api.updateDesignerTaskProfile).not.toHaveBeenCalled() })
  it('profile modal checks exact revision at execution', async () => { const { owner } = await mount(); vi.spyOn(api, 'previewDesignerTaskProfileUpdate').mockResolvedValue({ selectionChanged: true, updateRequired: true, sessionRestartRequired: true, targetWorkflowTemplate: 'FULL_PACKAGE_DESIGN' }); vi.spyOn(api, 'updateDesignerTaskProfile').mockResolvedValue(session().taskProfile); owner.editProfile(); const proposal = (await owner.previewProfile())!; owner.setMessage('后来编辑'); await owner.applyProfile(proposal); expect(api.updateDesignerTaskProfile).not.toHaveBeenCalled() })
  it('accepted save readback failure retains original editor then retries only GET', async () => { const { owner } = await mount(); const next = spec('更新后的规范'); owner.setEditor(JSON.stringify(next)); vi.spyOn(api, 'updateDraft').mockResolvedValue({ ...draft(next), version: 1 }); vi.mocked(api.getDesignerSession).mockRejectedValueOnce(new Error('read failed')); await owner.saveDraft(); expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK'); expect(owner.getSnapshot().editor).toBe(JSON.stringify(next)); vi.mocked(api.getDesignerSession).mockResolvedValue(session('A', { draft: { ...draft(next), version: 1 } })); await owner.recover(); expect(api.updateDraft).toHaveBeenCalledOnce(); expect(owner.getSnapshot().command.phase).toBe('SETTLED') })
  it.each([false, 'reject'])('accepted task failed navigation %s stays receipt-only', async failure => { const { owner, navigation } = await mount(session('A', { workflowPhase: 'COMPLETED', state: 'COMPLETED', finalConfirmationEligible: true })); vi.spyOn(api, 'confirmDraft').mockResolvedValue({ taskId: 'accepted' }); vi.spyOn(api, 'getTaskOverview').mockResolvedValue(taskFixture('accepted')); vi.spyOn(api, 'getTaskAudit').mockResolvedValue({ attempts: [], artifacts: [], errors: [], judges: [] }); vi.mocked(navigation.goAccepted).mockImplementation(async () => { if (failure === 'reject') throw new Error('blocked navigation'); return false }); await owner.confirm(); expect(owner.getSnapshot().acceptedTask).toBe('accepted'); expect(owner.getSnapshot().session?.id).toBe('A'); expect(owner.canLeave().kind).toBe('BLOCK'); await owner.openTask(); expect(api.confirmDraft).toHaveBeenCalledOnce(); expect(api.getTaskOverview).toHaveBeenCalledWith('accepted') })
  it('optional storage failures do not revoke accepted initial receipt', async () => { const { owner } = await mount(session(), { initial: true }); vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('storage denied') }); owner.setPrompt('原目标'); owner.stageFiles([new File(['bytes'], 'original.txt')]); await owner.initialSubmit(); expect(owner.getSnapshot().session?.id).toBe('A'); expect(owner.getSnapshot().command.phase).toBe('SETTLED'); expect(owner.getSnapshot().error).toBe('') })
  it('cancels owned focus RAF immediately and rejects manually late callback', async () => { let callback!: FrameRequestCallback; const cancel = vi.fn(); vi.stubGlobal('requestAnimationFrame', vi.fn(cb => { callback = cb; return 42 })); vi.stubGlobal('cancelAnimationFrame', cancel); const focus = vi.fn(), { owner } = await mount(session(), { focus }); expect(requestAnimationFrame).toHaveBeenCalledOnce(); owner.retire(true); expect(cancel).toHaveBeenCalledWith(42); callback(0); expect(focus).not.toHaveBeenCalled() })
  it('normal retire refusal leaves UNKNOWN stream and original retry alive', async () => { const { owner } = await mount(); owner.setMessage('原消息'); owner.stageFiles([new File(['x'], 'x.txt')]); vi.mocked(api.sendDesignerContextTurn).mockRejectedValueOnce(new Error('unknown')); await owner.send(); expect(owner.retire(false).kind).toBe('BLOCK'); expect(owner.getSnapshot().command.phase).toBe('UNKNOWN'); await owner.recover(); expect(api.sendDesignerContextTurn).toHaveBeenCalledTimes(2) })
})
