import { StrictMode } from 'react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { api } from '@/api/client'
import { semanticName } from '@/foundation/semanticRegistry'
import { foundationDOM } from '@/pages/w2/workflow/page.test-support'
import { DesignerPage } from './DesignerPage'
import { createDesignerController } from './controller'
import { deferred, flush, frame, mockDesigner, pageProps, session } from './test-support'
import { timeline } from './model'
vi.mock('@/api/client', async original => ({ ...await original<typeof import('@/api/client')>(), subscribeDesignerEvents: vi.fn() }))
let retire = () => {}
beforeEach(() => { sessionStorage.clear(); foundationDOM() })
afterEach(() => { cleanup(); retire(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
async function page(value = session(), initial = false, strict = false) { const mock = mockDesigner(value), harness = pageProps(), props = { ...harness.props, route: { path: '/designer', fullPath: initial ? '/designer' : '/designer?sessionId=A', query: initial ? {} : { sessionId: value.id }, params: {} } }; const owner = createDesignerController({ navigation: props.navigation, historyOnly: !initial, sessionId: initial ? undefined : value.id }); retire = () => owner.retire(true); const content = frame(<DesignerPage {...props} historyOnly={!initial} controller={owner} />); const root = render(strict ? <StrictMode>{content}</StrictMode> : content); await flush(); return { root, owner, props, streams: mock.streams } }
describe('Designer real React historical production page', () => {
  it('production default has no initial create form or hidden writer', async () => { mockDesigner(); const props = pageProps().props; const root = render(frame(<DesignerPage {...props} />)); await flush(); expect(screen.getByRole('heading', { name: '请选择历史设计会话' })).toBeTruthy(); expect(root.container.querySelector('textarea[aria-label="草案设计目标"]')).toBeNull(); expect(api.createDesignerSession).not.toHaveBeenCalled(); expect(root.container.querySelectorAll('[data-react-page]')).toHaveLength(1) })
  it('Strict root replay leaves one stream and does not write', async () => { const { streams, root } = await page(session(), false, true); expect(streams).toHaveLength(1); root.unmount(); expect(streams[0]!.close).toHaveBeenCalledOnce(); expect(api.createDesignerSession).not.toHaveBeenCalled() })
  it('native recommended question submits frozen original answers and never exposes reject', async () => { const pending = { id: 'q', questions: [{ question: '选择实现范围', header: '范围', options: [{ label: '原答案（推荐）', description: '原选择' }], multiple: false, custom: true }] }; vi.spyOn(api, 'replyDesignerQuestion').mockResolvedValue(); await page(session('A', { pendingQuestions: [pending] })); const card = screen.getByLabelText('设计师等待回答'); expect(within(card).queryByRole('button', { name: '拒绝' })).toBeNull(); fireEvent.click(within(card).getByRole('button', { name: '采用全部推荐项' })); await flush(); expect(api.replyDesignerQuestion).toHaveBeenCalledWith('A', 'q', [['原答案（推荐）']]) })
  it('unknown multipart Send remains reachable and repeats only original Files/body', async () => { const { owner } = await page(); const file = new File(['original'], 'original.txt'), extra = new File(['later'], 'extra.txt'); vi.mocked(api.sendDesignerContextTurn).mockRejectedValueOnce(new Error('unknown')); fireEvent.change(screen.getByLabelText('设计消息'), { target: { value: '原消息' } }); fireEvent.change(screen.getByLabelText('添加资料'), { target: { files: [file] } }); fireEvent.click(screen.getByRole('button', { name: '发送' })); await flush(); const original = vi.mocked(api.sendDesignerContextTurn).mock.calls[0]!; expect((screen.getByLabelText('设计消息') as HTMLTextAreaElement).disabled).toBe(false); fireEvent.change(screen.getByLabelText('设计消息'), { target: { value: '后来编辑' } }); fireEvent.change(screen.getByLabelText('添加资料'), { target: { files: [extra] } }); fireEvent.click(screen.getByRole('button', { name: '发送' })); await flush(); const retry = vi.mocked(api.sendDesignerContextTurn).mock.calls[1]!; expect(retry[1]).toEqual(original[1]); expect(retry[2]).toEqual([file]); expect(retry[2][0]).toBe(file); expect((screen.getByLabelText('设计消息') as HTMLTextAreaElement).value).toBe('后来编辑'); expect(owner.fileRefs().followup).toEqual([extra]) })
  it('pending keyless send keeps the actual textarea editable and preserves later input', async () => { const pending = deferred<Awaited<ReturnType<typeof api.sendRequirementMessage>>>(); await page(); vi.mocked(api.sendRequirementMessage).mockReturnValue(pending.promise); fireEvent.change(screen.getByLabelText('设计消息'), { target: { value: '原消息' } }); fireEvent.click(screen.getByRole('button', { name: '发送' })); await flush(); fireEvent.change(screen.getByLabelText('设计消息'), { target: { value: '后来编辑' } }); await act(async () => pending.resolve({ sessionId: 'A', state: 'REVIEWING', persistedMessages: [], notice: '' })); await flush(); expect((screen.getByLabelText('设计消息') as HTMLTextAreaElement).value).toBe('后来编辑') })
  it('closes profile presentation without dropping owner dirty draft', async () => { const { owner } = await page(); fireEvent.click(screen.getByRole('button', { name: '修改任务设置' })); await flush(); const panel = screen.getByRole('complementary'); fireEvent.click(within(panel).getByRole('button', { name: '修改任务设置' })); await flush(); fireEvent.click(screen.getByLabelText('大型任务模式')); await flush(); fireEvent.click(within(panel).getByRole('button', { name: semanticName('ui.close', '任务设置') })); await flush(); expect(owner.getSnapshot().profile?.largeTask).toBe(true); expect(owner.canLeave().kind).toBe('CONFIRM_DISCARD'); expect(screen.getByText('尚有未提交的设计草稿或附件，关闭详情仍保留当前输入。')).toBeTruthy() })
  it('keeps direct final design free of package rail and reopens the approved design only after a current explicit confirmation', async () => {
    const value = session('A', { workflowPhase: 'FINAL_REVIEW', finalConfirmationEligible: true, activeWorkPackageId: 'WP-1', taskProfile: { ...session().taskProfile, workflowTemplate: 'DIRECT_SOFTWARE_DESIGN' }, workPackages: [{ id: 'WP-1', ordinal: 0, title: '默认单包设计', objective: '完整需求', dependencies: [], state: 'APPROVED', redesignCount: 0, compilerRepairCount: 0, compilerPlanningRepairCount: 0, designRevision: 4, approvedDesignRevision: 3, discussionRoundCount: 1 }] })
    const { owner, streams } = await page(value), reopen = vi.spyOn(api, 'reopenWorkPackage').mockResolvedValue([]), redesign = vi.spyOn(api, 'redesignWorkPackage')
    expect(screen.queryByLabelText('工作包设计轨道')).toBeNull(); expect(screen.getByRole('heading', { name: '设计工作室' })).toBeTruthy()
    const button = screen.getByRole('button', { name: semanticName('designer.reopenPackage') })
    fireEvent.click(button); await flush(); expect(reopen).not.toHaveBeenCalled()
    vi.mocked(api.getDesignerSession).mockResolvedValue({ ...value, discussionRevision: 2 })
    act(() => streams[0]!.event({ sequence: 1, sessionId: 'A', type: 'STATUS', state: value.state, workflowPhase: value.workflowPhase, activeActor: value.activeActor, runtimeConnected: false, content: '', detail: '', at: '2026-10-03', modelCallsUsed: 0, maxModelCalls: 3 })); await flush()
    let dialog = screen.getByRole('dialog'); expect((within(dialog).getByRole('button', { name: semanticName('designer.reopenPackage') }) as HTMLButtonElement).disabled).toBe(true)
    expect(reopen).not.toHaveBeenCalled(); fireEvent.click(within(dialog).getByRole('button', { name: semanticName('ui.stay') })); await flush()
    fireEvent.click(button); await flush(); dialog = screen.getByRole('dialog')
    fireEvent.click(within(dialog).getByRole('button', { name: semanticName('designer.reopenPackage') })); await flush()
    expect(reopen).toHaveBeenCalledExactlyOnceWith('A', 'WP-1', 2, 3); expect(redesign).not.toHaveBeenCalled()
    expect(owner.getSnapshot().command.phase).toBe('SETTLED')
  })
  it('preserves persisted full actor ordering, grouped validators/system and hidden compiler/snapshot', () => { const value = session(); const message = (id: string, actor: typeof value.activeActor, content: string): typeof value.messages[number] => ({ id, actor, content, role: actor === 'USER' ? 'USER' : actor === 'SYSTEM' ? 'SYSTEM' : 'ASSISTANT', createdAt: '2026-10-03' }); value.messages = [message('u', 'USER', '用户'), message('s', 'SYSTEM', '系统1'), message('s2', 'SYSTEM', '系统2'), message('d', 'DESIGNER', '设计正文'), message('v', 'VALIDATOR', '验证'), message('v2', 'VALIDATOR', '验证2'), message('compiler', 'COMPILER', 'LOOPSPEC_COMPILATION_JSON_START secret')]; const items = timeline(value); expect(items.map(item => item.kind)).toEqual(['message', 'system', 'message', 'validators']); expect(items.find(item => item.kind === 'system')?.messages).toHaveLength(2); expect(items.find(item => item.kind === 'validators')?.messages).toHaveLength(2) })
  it('safe same-route query replacement retires A before B attaches and drops late A reads', async () => {
    const streams = mockDesigner().streams, pending = deferred<ReturnType<typeof session>>(); vi.mocked(api.getDesignerSession).mockReturnValueOnce(pending.promise).mockResolvedValue(session('B'))
    const props = pageProps().props, route = (id: string) => ({ path: '/designer', fullPath: `/designer?sessionId=${id}`, query: { sessionId: id }, params: {} })
    const root = render(frame(<DesignerPage {...props} route={route('A')} />)); await flush(); expect(streams).toHaveLength(1)
    root.rerender(frame(<DesignerPage {...props} route={route('B')} />)); expect(streams[0]!.close).toHaveBeenCalledOnce(); await flush(); expect(streams).toHaveLength(2); expect(streams[1]!.id).toBe('B')
    pending.resolve(session('A', { messages: [{ id: 'late-A', actor: 'DESIGNER', role: 'ASSISTANT', content: '迟到的 A 内容', createdAt: '2026-10-03' }] })); await flush(); expect(screen.queryByText('迟到的 A 内容')).toBeNull(); root.unmount(); expect(streams[1]!.close).toHaveBeenCalledOnce()
  })
  it('query replacement cannot replace an UNKNOWN original File owner or start a B stream', async () => {
    const streams = mockDesigner().streams, props = pageProps().props, route = (id: string) => ({ path: '/designer', fullPath: `/designer?sessionId=${id}`, query: { sessionId: id }, params: {} })
    const root = render(frame(<DesignerPage {...props} route={route('A')} />)); await flush(); vi.mocked(api.sendDesignerContextTurn).mockRejectedValueOnce(new Error('unknown')); const file = new File(['original'], 'original.txt'); fireEvent.change(screen.getByLabelText('设计消息'), { target: { value: '原消息' } }); fireEvent.change(screen.getByLabelText('添加资料'), { target: { files: [file] } }); fireEvent.click(screen.getByRole('button', { name: '发送' })); await flush(); const original = vi.mocked(api.sendDesignerContextTurn).mock.calls[0]!
    root.rerender(frame(<DesignerPage {...props} route={route('B')} />)); await flush(); expect(streams).toHaveLength(1); expect(streams[0]!.close).not.toHaveBeenCalled(); expect(screen.getByText(/original.txt/)).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: '发送' })); await flush(); expect(vi.mocked(api.sendDesignerContextTurn).mock.calls[1]![1]).toEqual(original[1]); expect(vi.mocked(api.sendDesignerContextTurn).mock.calls[1]![2][0]).toBe(file); root.unmount()
  })
  it('hidden snapshot retains its question anchor before later system history', async () => {
    await page(session('A', { answeredQuestions: [{ id: 'q', scope: 'REQUIREMENT', discussionRevision: 1, designMessageId: 'hidden', answeredAt: '2026-10-03', questions: [{ question: '需要覆盖哪些边界？', header: '范围', multiple: false, custom: false, options: [{ label: '恢复', description: '保留' }], answers: ['恢复'] }] }], messages: [{ id: 'u', role: 'USER', actor: 'USER', content: '原目标', createdAt: '2026-10-03' }, { id: 'hidden', role: 'SYSTEM', actor: 'SYSTEM', content: '不可显示的快照', deliveryState: 'SERVER_REQUIREMENT_SNAPSHOT', createdAt: '2026-10-03' }, { id: 's', role: 'SYSTEM', actor: 'SYSTEM', content: '后续系统记录', createdAt: '2026-10-03' }] }))
    const history = screen.getByLabelText('设计讨论记录'), items = [...history.children]; expect(screen.queryByText('不可显示的快照')).toBeNull(); expect(items.findIndex(item => item.textContent?.includes('需要覆盖哪些边界？'))).toBeLessThan(items.findIndex(item => item.textContent?.includes('后续系统记录')))
  })
  it('attachment stop uses a real confirmation and rejects a proposal after scope/draft changes', async () => {
    const stop = vi.spyOn(api, 'stopDesignerAttachment').mockResolvedValue({ stopped: true })
    await page(session('A', { messages: [{ id: 'user', role: 'USER', actor: 'USER', content: '原资料', createdAt: '2026-10-03', attachments: [{ id: 'file', filename: 'original.txt', mediaType: 'text/plain', sizeBytes: 8, sha256: 'abc', scopeKey: 'REQUIREMENT', extractorId: 'plain', previewKind: 'TEXT', state: 'ACTIVE' }] }] }))
    fireEvent.click(screen.getByRole('button', { name: semanticName('designer.stopAttachment', 'original.txt') })); await flush(); expect(stop).not.toHaveBeenCalled(); const dialog = screen.getByRole('dialog', { name: '停止资料未来使用？' }); fireEvent.change(screen.getByLabelText('设计消息'), { target: { value: '后来草稿' } }); await flush(); expect(within(dialog).getByRole('button', { name: semanticName('designer.stopAttachment') }).matches(':disabled')).toBe(true); expect(stop).not.toHaveBeenCalled()
  })

})
