import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import type { AvailableModel } from '@/types/domain'
import { api } from '@/api/client'
import { PageChrome, PageLink, queryString, SkinControl, useLeaveGuard, useOwnerSnapshot, useRetainedOwner } from '@/pages/w2/shared'
import type { W2PageProps } from '@/pages/w2/shared/types'
import { UiActionButton, UiConfirmDialog, UiContextPanel } from '@/foundation/components'
import { semanticLabel, type UiActionKey } from '@/foundation/semanticRegistry'
import { CommandNotice, ReadNotice, selectionTrigger, useProtectedOwner } from '@/pages/w4/shared/parts'
import { RichDocument } from '@/pages/w3/shared/RichDocument'
import { ReadOnlyCode } from '@/pages/w3/shared/ReadOnlyCode'
import { artifactKindLabel, displayLabel, executionStrategyLabel, profileResolutionLabel, rolePackLabel, statusLabel, taskIntentLabel, testPolicyLabel, workflowTemplateLabel, userFacingError } from '@/utils/displayLabels'
import { createDesignerController, type DesignerController } from './controller'
import { composerAvailable, directMode, mutationGap } from './model'
import { ActivityProjection, Discussion, PackageGapNotice } from './Discussion'
import { ExecutionAcceptancePanel } from '@/pages/w4/task/ExecutionAcceptancePanel'
import { LoopSpecEditor } from './LoopSpecEditor'
import './designer.css'
export type DesignerPageProps = W2PageProps & { historyOnly?: boolean; controller?: DesignerController }
type Confirmation = { title: string; description: string; actionKey: UiActionKey; token: string; action: () => void }
export function DesignerPage(props: DesignerPageProps) {
  const composer = useRef<HTMLTextAreaElement>(null), trigger = useRef<HTMLElement | null>(null)
  const id = queryString(props.route, 'sessionId'), historyOnly = props.historyOnly !== false
  const candidate = useMemo(() => props.controller ?? createDesignerController({ sessionId: id || undefined, historyOnly, navigation: props.navigation, focusComposer: queryString(props.route, 'mode') === 'edit' ? () => composer.current?.focus() : undefined }), [props.controller, id, historyOnly, props.navigation])
  const owner = useProtectedOwner(candidate)
  useRetainedOwner(props, owner, () => { owner.retire(true) })
  useLeaveGuard(props, request => owner.canLeave(request))
  const previousOwner = useRef(owner)
  useLayoutEffect(() => { if (previousOwner.current !== owner && previousOwner.current.canLeave().kind === 'ALLOW') previousOwner.current.retire(true); previousOwner.current = owner; return owner.attachView() }, [owner])
  const state = useOwnerSnapshot(owner.base)
  const [context, setContext] = useState<'profile' | 'spec' | 'report' | undefined>(), [expanded, setExpanded] = useState(false), [confirmation, setConfirmation] = useState<Confirmation>(), [models, setModels] = useState<AvailableModel[]>([])
  useEffect(() => { let active = true; if (context === 'spec') void api.getSettingsModels().then(value => { if (active) setModels(value) }).catch(() => {}); return () => { active = false } }, [context])
  const session = state.session, busy = state.command.busy, locked = ['SENDING', 'UNKNOWN', 'ACCEPTED_READBACK'].includes(state.command.phase), auto = session?.autoMode.enabled && session.autoMode.state === 'ACTIVE'
  const blockedMessage = session && ['WAITING_INPUT', 'SESSION_ERROR'].includes(session.state)
    ? [...session.messages].reverse().find(message => (session.state === 'SESSION_ERROR' ? ['SESSION_ERROR', 'TERMINAL_ERROR'] : ['TERMINAL_ERROR', 'DESIGN_INCOMPLETE', 'RETRYABLE_ERROR']).includes(message.deliveryState ?? ''))
    : undefined
  const final = session && ['FINAL_REVIEW', 'COMPLETED'].includes(session.workflowPhase), pkg = session?.workPackages?.find(item => item.id === (state.selectedPackage || session.activeWorkPackageId)), gap = mutationGap(session)
  const available = (okay = true) => !locked && okay ? { kind: 'enabled' as const } : { kind: 'disabled' as const, reason: locked ? '请先核对原操作结果。' : '当前服务端状态不允许此操作。' }
  function open(value: typeof context) { selectionTrigger(trigger); setContext(value) }
  function ask(actionKey: UiActionKey, title: string, description: string, action: () => void) { selectionTrigger(trigger); setConfirmation({ actionKey, title, description, action, token: owner.captureConfirmation() }) }
  function action(key: Parameters<DesignerController['action']>[0], actionKey: UiActionKey, description = '此动作按原会话与冻结版本提交。') { ask(actionKey, semanticLabel(actionKey), description, () => { void owner.action(key, pkg?.id) }) }
  async function profileSave() { const proposal = await owner.previewProfile(); if (!proposal) return; if (!proposal.preview.updateRequired) { owner.editProfile(false); return } if (proposal.preview.sessionRestartRequired) ask('designer.save', '修改任务设置？', '这会重建当前设计会话，并保留历史记录。请核对当前任务设置。', () => { void owner.applyProfile(proposal) }); else void owner.applyProfile(proposal) }
  const panelTitle = context === 'spec' ? '最终执行规范' : context === 'report' ? '只读分析报告' : '任务设置'
  return <PageChrome title="设计工作室" objectKey="nav.designs" actions={<><SkinControl {...props} /><PageLink navigation={props.navigation} to="/designs">设计历史</PageLink>{session && <UiActionButton actionKey="designer.reset" busy={busy} availability={available()} onAction={() => ask('designer.reset', '重新开始设计？', '先停止当前会话并核对归档结果；尚未证明停止时保留原身份。', () => { void owner.reset() })} />}</>}
    status={<><CommandNotice command={state.command} recover={() => { void owner.recover() }} />{blockedMessage && <section className="w3-critical" role="status" aria-label="设计工作流恢复"><strong>{session?.state === 'WAITING_INPUT' ? '设计工作流需要人工恢复' : '设计工作流已停止'}</strong><p>{userFacingError(blockedMessage.content)}</p></section>}<ReadNotice error={state.error} loading={state.loading} retry={() => { void owner.refresh() }} />{state.notice && <p role="status">{state.notice}</p>}{(state.profileEditing || state.message || state.files.length > 0 || state.draft && state.editor !== JSON.stringify(state.draft.spec, null, 2)) && <p role="status">尚有未提交的设计草稿或附件，关闭详情仍保留当前输入。</p>}{state.acceptedDesign && <section className="w3-critical" role="status"><p>新设计会话已创建，原交接尚未完成。</p><UiActionButton actionKey="ui.open" target="已创建设计" onAction={() => { void owner.openDesign() }} /></section>}{state.acceptedTask && <section className="w3-critical" role="status"><p>已创建任务，原交接尚未完成。</p><UiActionButton actionKey="designer.openTask" onAction={() => { void owner.openTask() }} /></section>}{session?.autoMode.enabled && <section className="designer-card" role="status"><strong>全自动模式 · {statusLabel(session.autoMode.state)}</strong><p>{session.autoMode.errorDetail || session.autoMode.lastAction}</p></section>}{state.conflict && <section className="w3-critical" role="alert">执行规范版本已变化，请保留本地编辑并明确重新载入。<UiActionButton actionKey="designer.reloadDraft" availability={available()} onAction={() => ask('designer.reloadDraft', '重新载入规范？', '当前本地规范将被服务端最新版本替换。', () => { void owner.reloadDraft() })} /></section>}</>}
    context={<UiContextPanel open={!!context} title={panelTitle} onClose={() => setContext(undefined)} returnFocus={trigger} expanded={expanded} onExpandedChange={setExpanded}>
      {context === 'profile' && session && <ProfileSettings owner={owner} state={state} save={() => { void profileSave() }} locked={locked} />}
      {context === 'spec' && state.draft && <section><h3>最终执行规范</h3><p>{state.draft.spec.stages.length} 个阶段 · {state.draft.spec.limits.maxDuration}</p>{state.draft.spec.schemaVersion === 'v1' && <UiActionButton actionKey="designer.copyV2" availability={available()} onAction={() => ask('designer.copyV2', '复制为新规范？', '保留旧冻结规范并显式创建新版草稿及设计会话。', () => { void owner.copyV2() })} />}{!final ? <><p>候选执行规范只读；总体确认后可编辑。</p><ReadOnlyCode content={session?.candidate?.spec ? JSON.stringify(session.candidate.spec, null, 2) : state.editor} language="json" label="只读候选执行规范" /></> : <><LoopSpecEditor source={state.editor} onChange={owner.setEditor} models={models} afterStages={<ExecutionAcceptancePanel source={state.editor} />} disabled={locked || auto || state.draft.status === 'CONFIRMED'} /><div className="w2-actions"><UiActionButton actionKey="designer.validate" busy={busy} availability={available()} onAction={() => { void owner.assess() }} /><UiActionButton actionKey="designer.save" busy={busy} availability={available(state.draft.status !== 'CONFIRMED' && !state.conflict)} onAction={() => { void owner.saveDraft() }} /><UiActionButton actionKey="designer.reloadDraft" availability={available()} onAction={() => ask('designer.reloadDraft', '重新载入规范？', '本地未保存编辑将被替换。', () => { void owner.reloadDraft() })} /></div></>}{state.assessment && <section aria-label="双重验收计划矩阵"><h4>双重验收计划 · {state.assessment.valid ? '计划有效' : `${state.assessment.errors.length} 项阻断`}</h4>{state.assessment.errors.map((error, i) => <p role="alert" key={i}>{error}</p>)}{state.assessment.stageAssessments.map(stage => <article key={stage.stageIndex}><h5>阶段 {stage.stageIndex + 1}</h5>{stage.criteria.map(criterion => <div key={criterion.id} className="matrix-criterion-row"><p className="matrix-criterion-description">{criterion.description}</p><p className="matrix-criterion-statuses">{displayLabel(criterion.verificationMode)} · {criterion.machineCovered ? `机器：验收器 ${criterion.verifierIndexes.map(i => i + 1).join(', ')}` : '机器：不适用'} · {criterion.judgePlanned ? 'AI：计划评审' : 'AI：不适用'}</p></div>)}{stage.verifiers.map(verifier => <p key={verifier.index}>#{verifier.index + 1} {verifier.category} · {verifier.reason}</p>)}</article>)}</section>}
      <ArtifactPreview owner={owner} skin={props.skin} /></section>}
      {context === 'report' && state.report && <section><h3>{state.report.title}</h3><p>{statusLabel(state.report.state)} · {state.report.stale ? '原证据已变化' : '冻结证据'}</p><RichDocument content={state.report.markdown} skin={props.skin} /><ul>{state.report.findings.map((finding, i) => <li key={i}><strong>{finding.title}</strong>{finding.detail}<p>{finding.path}:{finding.line} · {finding.recommendation}</p></li>)}</ul><ul>{state.report.evidence.map((evidence, i) => <li key={i}>{evidence.path}:{evidence.line} · SHA-256 {evidence.sha256}{evidence.stale && ' · 已变化'}</li>)}</ul><UiActionButton actionKey="designer.convertReport" availability={available()} onAction={() => ask('designer.convertReport', '转换为可写设计？', '新设计会话保留原报告关联；尚未创建任务。', () => { void owner.convertReport() })} /></section>}
    </UiContextPanel>}>
    <div className="designer-page" onDragOver={e => { if (e.dataTransfer.types.includes('Files')) e.preventDefault() }} onDrop={e => { if (e.dataTransfer.files.length) { e.preventDefault(); e.stopPropagation(); owner.stageFiles([...e.dataTransfer.files]) } }}>
      {!session && !state.loading && historyOnly && <section className="designer-card"><h2>请选择历史设计会话</h2><PageLink to="/designs" navigation={props.navigation}>打开设计历史</PageLink><PageLink to="/requirements/new" navigation={props.navigation}>新建需求</PageLink></section>}
      {!session && !historyOnly && <section className="designer-card" aria-label="独立初始设计合同夹具"><h2>设计目标与约束</h2><label className="designer-field">项目<select aria-label="项目" value={state.projectId} onChange={e => owner.setProject(e.target.value)}>{state.projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="designer-field">草案设计目标<textarea aria-label="草案设计目标" value={state.prompt} onChange={e => owner.setPrompt(e.target.value)} /></label><label><input type="checkbox" aria-label="全自动创建" checked={state.autoMode} onChange={e => { if (e.target.checked) ask('designer.autoMode', '开启全自动模式？', '允许自动采用任务设置、确认设计、创建并启动任务；执行权限和发布仍须人工边界。', () => owner.setInitialAuto(true)); else owner.setInitialAuto(false) }} />全自动模式</label><StorySettings owner={owner} />
        <StagedFiles owner={owner} initial /><UiActionButton actionKey="designer.start" busy={busy} availability={state.command.phase === 'UNKNOWN' && state.command.recovery === 'RETRY_IDENTICAL' ? { kind: 'enabled' } : available(!!state.prompt.trim() && !!state.projectId)} onAction={() => { void owner.initialSubmit() }} /></section>}
      {session && <>
        <section className="designer-card" aria-label="设计状态"><h2>{session.projectName || '设计会话'} · {statusLabel(session.state)}</h2><p>{workflowTemplateLabel(session.taskProfile.workflowTemplate)} · {statusLabel(session.workflowPhase)} · {state.stream === 'reconnecting' ? '正在重连' : state.stream === 'connected' ? '实时连接' : '连接中'}</p><p>设计讨论 R{session.discussionRevision} · {session.designConversations?.map(item => `第 ${item.generation} 代：${statusLabel(item.state)}`).join('；')}</p><p>{session.permissionSummary}</p>{session.storyBinding?.enabled && <p>故事绑定 {session.storyBinding.systemCode} / {session.storyBinding.storyCode}</p>}<div className="w2-actions"><UiActionButton actionKey="designer.editSettings" onAction={() => open('profile')} /><UiActionButton actionKey="ui.open" target="最终执行规范" onAction={() => open('spec')} /><UiActionButton actionKey="designer.autoMode" availability={available()} onAction={() => action('autoMode', 'designer.autoMode', '全自动会自动采用任务设置、确认并启动任务。人工执行许可与发布边界保持。')} /></div></section>
        {session.taskProfile.decisionState === 'ROUTING' && <section className="designer-card" role="status"><h3>正在判定任务设置</h3><p>{statusLabel(session.routerRun?.state)} · {session.routerRun?.errorDetail}</p><UiActionButton actionKey="ui.open" target="任务设置判定" onAction={() => owner.setRouterOpen(true)} /></section>}
        {session.reports.map(report => <section className="designer-card" key={report.id}><h3>{report.title}</h3><p>{statusLabel(report.state)}{report.stale && ' · 原证据已变化'}</p><UiActionButton actionKey="ui.open" target={report.title} onAction={() => { open('report'); void owner.loadReport(report.id) }} /></section>)}
        {session.compiler && <details className="designer-card" aria-label="规范编译状态"><summary>规范编译状态</summary><p>{session.compiler.serverCompiled ? '服务端直接编译，无远程活动会话' : '规范编译'} · {statusLabel(session.compiler.state)} · 修复 {session.compiler.repairCount} · 规划修复 {session.compiler.planningRepairCount}</p><p>{session.compiler.lastErrorDetail && displayLabel(session.compiler.lastErrorDetail)}</p></details>}
        {session.decomposition && <section className="designer-card" aria-label="工作包拆分状态"><h3>工作包拆分</h3><p>{statusLabel(session.decomposition.state)} · {session.decomposition.lastErrorDetail} · 修复 {session.decomposition.repairCount} · 传输重试 {session.decomposition.transportRetryCount} · 候选会话 {session.decomposition.candidateSessions ?? 0}{(session.decomposition.candidateSubmissions ?? 0) > 0 && ` · 候选提交 ${session.decomposition.candidateSubmissions}`}</p>{session.decomposition.state === 'FAILED' && <UiActionButton actionKey="designer.retryDecomposition" availability={available()} onAction={() => action('retryDecomposition', 'designer.retryDecomposition')} />}</section>}
        {!directMode(session) && !!session.workPackages?.length && <section className="designer-packages" aria-label="工作包设计轨道">{session.workPackages.map(item => <article className="designer-card" key={item.id}><UiActionButton actionKey="selection.select" target={item.title} onAction={() => owner.selectPackage(item.id)} /><p>第 {item.ordinal + 1} 包 · {statusLabel(item.state)} · 讨论 {item.discussionRoundCount}/5 · 设计 R{item.designRevision} · 已接受 R{item.approvedDesignRevision ?? 0}</p><p>依赖 {item.dependencies.join('、') || '无'} · {rolePackLabel(item.rolePackId ?? '')} · {item.technologies?.join('/')} · {item.testPolicy ? testPolicyLabel(item.testPolicy) : '测试策略未提供'}</p><details><summary>工作包候选与角色</summary><CandidateFacts item={item} /></details>{item.state === 'APPROVED' && <UiActionButton actionKey="designer.reopenPackage" target={item.title} availability={available(session.state !== 'RUNNING')} onAction={() => ask('designer.reopenPackage', '重新讨论工作包？', '该工作包及下游依赖的接受版本将失效，历史记录保留。', () => { void owner.action('reopenPackage', item.id) })} />}</article>)}</section>}
        {directMode(session) && session.workPackages?.[0] && <section className="designer-card" aria-label="单工作包候选状态"><h3>单工作包设计</h3><details><summary>候选状态</summary><CandidateFacts item={session.workPackages[0]} /></details></section>}
        <PackageGapNotice code={pkg?.lastErrorCode} detail={pkg?.lastErrorDetail} />
        {pkg?.acceptancePlanning && <section className="designer-card" aria-label="验收意图覆盖"><h3>验收意图覆盖</h3><p>{statusLabel(pkg.acceptancePlanning.state)} · {pkg.acceptancePlanning.unresolvedCount} 项待覆盖</p>{(pkg.acceptancePlanning.state === 'FAILED' || gap) && <p role="alert">{pkg.acceptancePlanning.issues.join('；')} · {pkg.acceptancePlanning.mutationBindingReasons.join('、')}</p>}{pkg.acceptancePlanning.scenarios.map((proof, i) => <p key={i}>{proof.title} · {displayLabel(proof.coverage)}</p>)}{pkg.acceptancePlanning.routingReasons?.length ? <details><summary>历史消歧说明</summary>{[...new Set(pkg.acceptancePlanning.routingReasons)].map(reason => <p key={reason}>{reason}</p>)}</details> : null}</section>}
        {session.requirement && <p role="status">模型调用 {session.requirement.modelCallsUsed}/{session.requirement.maxModelCalls}</p>}<Discussion state={state} owner={owner} skin={props.skin} stopAttachment={(id, filename) => ask('designer.stopAttachment', '停止资料未来使用？', `停止后不影响已冻结的历史证据。请核对资料：${filename}。`, () => { void owner.stopAttachment(id) })} />
        {composerAvailable(session) && <section className="designer-card" aria-label="设计消息输入"><label className="designer-field">{gap ? '补充路径归属与改动计划' : '给设计师的补充消息'}<textarea ref={composer} id="designer-message" aria-label="设计消息" rows={10} value={state.message} onChange={e => owner.setMessage(e.target.value)} onKeyDown={e => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); if (!locked || state.command.phase === 'UNKNOWN' && state.command.recovery === 'RETRY_IDENTICAL') void owner.send() } }} /></label><StagedFiles owner={owner} /><UiActionButton actionKey="designer.send" busy={busy} availability={state.command.phase === 'UNKNOWN' && state.command.recovery === 'RETRY_IDENTICAL' ? { kind: 'enabled' } : available(!!state.message.trim())} onAction={() => { void owner.send() }} /></section>}
        <div className="designer-card w2-actions" aria-label="设计阶段动作">
          {session.workflowPhase === 'DISCUSSING_REQUIREMENT' && session.state === 'REVIEWING' && !auto && <UiActionButton actionKey="designer.confirmRequirement" availability={available(session.taskProfile.confirmationReady)} onAction={() => action('confirmRequirement', 'designer.confirmRequirement')} />}
          {!['DISCUSSING_REQUIREMENT', 'COMPLETED'].includes(session.workflowPhase) && !auto && <UiActionButton actionKey="designer.reopenRequirement" availability={available()} onAction={() => action('reopenRequirement', 'designer.reopenRequirement', '已有工作包接受状态将失效，历史讨论保留。')} />}
          {!directMode(session) && session.workflowPhase === 'REVIEWING_PACKAGE' && pkg?.state === 'REVIEWING' && !auto && <UiActionButton actionKey="designer.approvePackage" availability={available()} onAction={() => action('approvePackage', 'designer.approvePackage')} />}
          {['WAITING_INPUT', 'SESSION_ERROR'].includes(session.state) && session.compiler && <><UiActionButton actionKey="designer.retryCompiler" availability={available(!gap)} onAction={() => action('retryCompiler', 'designer.retryCompiler')} /><UiActionButton actionKey="designer.redesign" availability={available()} onAction={() => action('redesign', 'designer.redesign')} /></>}
          {pkg?.state === 'WAITING_INPUT' && <><UiActionButton actionKey="designer.retryPackageCompiler" availability={available(!gap)} onAction={() => action('retryPackageCompiler', 'designer.retryPackageCompiler')} /><UiActionButton actionKey="designer.redesignPackage" availability={available()} onAction={() => action('redesignPackage', 'designer.redesignPackage')} /></>}
          {directMode(session) && ['WAITING_INPUT', 'SESSION_ERROR'].includes(session.state) && session.messages.some(message => message.content.includes('LARGE_TASK_MODE_REQUIRED')) && <UiActionButton actionKey="designer.largeTask" availability={available()} onAction={() => action('largeTask', 'designer.largeTask')} />}
          {directMode(session) && final && state.draft?.status !== 'CONFIRMED' && session.workPackages?.[0]?.approvedDesignRevision && <UiActionButton actionKey="designer.reopenPackage" availability={available()} onAction={() => ask('designer.reopenPackage', '重新讨论设计？', '重新讨论当前已接受设计，原历史记录仍保留。', () => { void owner.action('reopenPackage', session.workPackages![0]!.id) })} />}{final && <><p role={session.finalConfirmationEligible ? 'status' : 'alert'}>{session.finalConfirmationEligible ? '设计已进入总体确认' : session.confirmationBlocker || '当前设计尚不满足确认条件。'}</p><UiActionButton actionKey="designer.confirm" availability={available(session.finalConfirmationEligible && !state.conflict && !auto)} onAction={() => ask('designer.confirm', '确认设计并创建任务？', '按当前冻结规范创建待启动任务；此动作不会自行启动执行。', () => { void owner.confirm() })} /></>}
        </div>
      </>}
    </div>
    <UiConfirmDialog open={!!confirmation} title={confirmation?.title ?? ''} confirmActionKey={confirmation?.actionKey ?? 'ui.save'} returnFocus={trigger} onCancel={() => setConfirmation(undefined)} policy={confirmation && !owner.confirmationCurrent(confirmation.token) ? { kind: 'block', reason: '原会话、版本或草稿已经变化，请关闭后重新确认。' } : { kind: 'allow' }} onConfirm={() => { if (!confirmation || !owner.confirmationCurrent(confirmation.token)) return; const run = confirmation.action; setConfirmation(undefined); run() }}><p>{confirmation?.description}</p></UiConfirmDialog>
    <UiConfirmDialog open={state.routerOpen && !!session} title="任务设置判定" confirmActionKey="designer.confirmProfile" returnFocus={trigger} busy={busy} policy={session?.routerRun && ['PENDING', 'RUNNING'].includes(session.routerRun.state) || locked ? { kind: 'block', reason: '正在判定，或原命令尚未结清。' } : { kind: 'allow' }} onCancel={() => { if (!session?.routerRun || !['PENDING', 'RUNNING'].includes(session.routerRun.state)) owner.setRouterOpen(false) }} onConfirm={() => { void owner.action('confirmProfile') }}>
      {session && <>{session.routerRun && ['PENDING', 'RUNNING'].includes(session.routerRun.state) && <><p>{statusLabel(session.routerRun.externalState || session.routerRun.state)} · 已用 {Math.max(0, Math.floor((state.now - Date.parse(session.routerRun.createdAt)) / 1000) || 0)} 秒</p>{state.activity && <ActivityProjection activity={state.activity} skin={props.skin} label="任务设置识别活动" totalTokens={state.activityTokens} delta={state.activityDelta} error={state.activityError} />}{!state.activity && state.activityError && <p role="alert">{state.activityError}</p>}</>}<div aria-label="任务设置识别字段"><article>识别置信度<strong>{session.taskProfile.confidenceAvailable !== true ? '未产生' : `${session.taskProfile.confidence}%`}</strong></article><article>技术栈<strong>{session.taskProfile.technologies.join('、') || '尚未提供'}</strong></article></div><p>{taskIntentLabel(session.taskProfile.intent)} · {workflowTemplateLabel(session.taskProfile.workflowTemplate)}</p><details><summary>识别依据</summary><p>{session.taskProfile.evidence.join('；')}</p>{session.taskProfile.previousConfirmedChoice && <p>原设置：{taskIntentLabel(session.taskProfile.previousConfirmedChoice.intent)} · {artifactKindLabel(session.taskProfile.previousConfirmedChoice.primaryArtifactKind)}</p>}{session.taskProfile.previousConfirmedChoice && <p>本次识别结果：{taskIntentLabel(session.taskProfile.intent)} · {session.taskProfile.artifactKinds.map(artifactKindLabel).join('、')}</p>}</details><p>{session.routerRun?.errorDetail}</p>{session.routerRun?.state === 'FAILED' && <p role="alert">本次识别未能可靠完成，当前显示服务端降级设置；可重新识别或手动修改后显式采用。</p>}{session.routerRun?.errorCode === 'ROUTER_USER_CANCELLED' && <p role="status">已取消 AI 识别，请手动选择任务设置。</p>}<ProfileSettings owner={owner} state={state} locked={locked} save={() => { void profileSave() }} />{session.routerRun?.retryAvailable && <UiActionButton actionKey="designer.rerouteProfile" availability={available()} onAction={() => { void owner.action('rerouteProfile') }} />}{session.routerRun && ['PENDING', 'RUNNING'].includes(session.routerRun.state) && <UiActionButton actionKey="designer.cancelRouter" availability={available()} onAction={() => { void owner.action('cancelRouter') }} />}</>}
    </UiConfirmDialog>
  </PageChrome>
}
function ProfileSettings({ owner, state, save, locked }: { owner: DesignerController; state: ReturnType<DesignerController['getSnapshot']>; save(): void; locked: boolean }) {
  const session = state.session, profile = state.profile; if (!session || !profile) return null
  return <section className="designer-card" aria-label="任务设置"><h3>任务设置</h3><p>{taskIntentLabel(session.taskProfile.intent)} · {session.taskProfile.artifactKinds.map(artifactKindLabel).join('、')} · {workflowTemplateLabel(session.taskProfile.workflowTemplate)} · {executionStrategyLabel(session.taskProfile.executionStrategy)}</p><p>{rolePackLabel(session.taskProfile.rolePackId)} · {testPolicyLabel(session.taskProfile.testPolicy)} · {profileResolutionLabel(session.taskProfile.resolutionSource)}</p>{!state.profileEditing ? <UiActionButton actionKey="designer.editSettings" availability={locked ? { kind: 'disabled', reason: '先核对原命令。' } : { kind: 'enabled' }} onAction={() => owner.editProfile()} /> : <fieldset disabled={locked}>
    <label className="designer-field">任务类型<select aria-label="任务类型" value={profile.intent} onChange={e => owner.changeProfile({ ...profile, intent: e.target.value as typeof profile.intent })}>{session.availableProfileOverrides.map(intent => <option key={intent} value={intent}>{taskIntentLabel(intent)}</option>)}</select></label><label className="designer-field">交付物类型<select aria-label="交付物类型" value={profile.artifact} onChange={e => owner.changeProfile({ ...profile, artifact: e.target.value as typeof profile.artifact })}>{session.availableArtifactOverrides.map(artifact => <option key={artifact} value={artifact}>{artifactKindLabel(artifact)}</option>)}</select></label>
    {profile.intent === 'SOFTWARE_CHANGE' && <label><input aria-label="大型任务模式" type="checkbox" checked={profile.largeTask} onChange={e => owner.changeProfile({ ...profile, largeTask: e.target.checked })} />大型任务模式：仅显式启用后拆分多个工作包。</label>}
    {session.taskProfile.componentSelectionRequired && <fieldset><legend>选择相关项目组件</legend>{session.taskProfile.candidateComponents?.map(component => <label key={component.key}><input type="checkbox" checked={profile.components.includes(component.key)} onChange={e => owner.changeProfile({ ...profile, components: e.target.checked ? [...profile.components, component.key] : profile.components.filter(key => key !== component.key) })} />{component.relativeRoot === '.' ? '项目根目录' : component.relativeRoot} · {component.technologies.join(' / ') || '通用'}</label>)}</fieldset>}
    <UiActionButton actionKey="designer.save" onAction={save} /><UiActionButton actionKey="ui.cancelEditing" onAction={() => owner.editProfile(false)} />
  </fieldset>}</section>
}
function StagedFiles({ owner, initial = false }: { owner: DesignerController; initial?: boolean }) {
  const state = owner.getSnapshot(), files = initial ? state.initialFiles : state.files
  return <section className="designer-staged" onDragOver={e => { if (e.dataTransfer.types.includes('Files')) e.preventDefault() }} onDrop={e => { if (e.dataTransfer.files.length) { e.preventDefault(); e.stopPropagation(); owner.stageFiles([...e.dataTransfer.files]) } }}><label className="designer-field">添加资料<input type="file" multiple aria-label="添加资料" disabled={state.command.busy} onChange={e => { if (e.target.files) owner.stageFiles([...e.target.files]); e.target.value = '' }} /></label>{!!files.length && <div aria-label="待发送附件"><strong>待发送附件</strong>{files.map((file, i) => <div key={`${i}-${file.name}`}><span>{file.name} · {file.size} bytes</span><UiActionButton actionKey="ui.delete" target={file.name} availability={state.command.busy ? { kind: 'disabled', reason: '正在发送原文件' } : { kind: 'enabled' }} onAction={() => owner.removeFile(i, initial)} /></div>)}</div>}</section>
}
function StorySettings({ owner }: { owner: DesignerController }) { const state = owner.getSnapshot(); return <fieldset><legend>故事绑定（可选）</legend><p>仅统计设计师和执行者的 AI 工作量</p><p>{state.storyCapability?.reason || '故事绑定能力尚未核对'}</p><UiActionButton actionKey="ui.refresh" target="故事绑定能力" busy={state.storyChecking} onAction={() => owner.detectStory()} /><label><input aria-label="故事绑定" type="checkbox" checked={state.story.enabled} disabled={state.storyChecking || state.storyCapability?.available !== true || state.command.busy} onChange={e => owner.setStory({ ...state.story, enabled: e.target.checked })} />启用故事绑定</label>{state.story.enabled && <><label className="designer-field">系统编号<input value={state.story.systemCode ?? ''} onChange={e => owner.setStory({ ...state.story, systemCode: e.target.value })} /></label><label className="designer-field">故事编号<input value={state.story.storyCode ?? ''} onChange={e => owner.setStory({ ...state.story, storyCode: e.target.value })} /></label></>}</fieldset> }
function CandidateFacts({ item }: { item: import('@/types/domain').DesignWorkPackageStatus }) { return <><p>{item.candidateRunState && `候选状态：${candidateRunStateLabel(item.candidateRunState)}`} · {item.compilationSource && displayLabel(item.compilationSource)} {item.serverCompiled && '· 服务端已编译'}</p>{item.fallbackReason && <p>兜底原因：{displayLabel(item.fallbackReason)}</p>}<p>候选会话 {item.candidateSessions ?? 0}{(item.candidateSubmissions ?? 0) > 0 && ` · 候选提交 ${item.candidateSubmissions}`}</p></> }
function ArtifactPreview({ owner, skin }: { owner: DesignerController; skin: W2PageProps['skin'] }) { const spec = owner.getSnapshot().draft?.spec, stage = spec?.stages.find(item => item.executionStrategy?.startsWith('SERVER_')); if (!stage || !spec) return null; return <section aria-label="服务端制品预览"><h4>{stage.stageKind === 'TABULAR_CONVERSION' ? '表格转换预览' : stage.deliverables[0]?.endsWith('.docx') ? 'DOCX 结构摘要' : 'Markdown 预览'}</h4><p>{stage.deliverables.join('、')}</p>{stage.stageKind === 'TABULAR_CONVERSION' ? <p>{stage.verifiers.find(v => v.type === 'TABULAR_DATA')?.tabularAssertions?.find(a => a.type === 'EQUIVALENT_TO')?.sourcePath} → {stage.deliverables[0]}；公式使用缓存显示值，合并区域仅保留左上角，仅移除尾部全空行列。</p> : <RichDocument content={spec.context} skin={skin} />}</section> }
export default DesignerPage

function candidateRunStateLabel(value: NonNullable<import('@/types/domain').DesignWorkPackageStatus['candidateRunState']>) { return ({ OPEN: '提交中', ACCEPTED: '已接受', WAITING_INPUT: '等待输入', FALLBACK_REQUIRED: '需要兜底', CLOSED: '已关闭' })[value] }
