import { useState } from 'react'
import { api } from '@/api/client'
import type { DesignerActivity, TaskSessionPendingQuestion } from '@/types/domain'
import type { SkinDefinition } from '@/themes/types'
import { UiActionButton } from '@/foundation/components'
import { RichDocument } from '@/pages/w3/shared/RichDocument'
import { ReadOnlyCode } from '@/pages/w3/shared/ReadOnlyCode'
import { designerActorLabel, displayLabel, statusLabel, userFacingError } from '@/utils/displayLabels'
import { formatDateTime } from '@/utils/dateTime'
import type { DesignerController, DesignerSnapshot } from './controller'
import { timeline } from './model'
export function PendingQuestion({ pending, busy, submit }: { pending: TaskSessionPendingQuestion; busy: boolean; submit(answers: string[][]): void }) {
  const [draft, setDraft] = useState<string[][]>(pending.questions.map(() => [])), [custom, setCustom] = useState<string[]>(pending.questions.map(() => ''))
  const answers = pending.questions.map((prompt, i) => custom[i]?.trim() ? prompt.multiple ? [...(draft[i] ?? []), custom[i]!.trim()] : [custom[i]!.trim()] : draft[i] ?? [])
  return <section className="designer-card" aria-label="设计师等待回答"><h3>需要你的回答</h3><fieldset disabled={busy}>{pending.questions.map((prompt, i) => <section key={i}><h4>{prompt.header || `问题 ${i + 1}`}</h4><p>{prompt.question}</p>{prompt.options.map(option => <label className="designer-option" key={option.label}><input type={prompt.multiple ? 'checkbox' : 'radio'} name={`${pending.id}-${i}`} checked={draft[i]?.includes(option.label) ?? false} value={option.label} onChange={event => { setDraft(old => old.map((values, index) => index === i ? prompt.multiple ? event.target.checked ? [...values, option.label] : values.filter(value => value !== option.label) : [option.label] : values)); if (!prompt.multiple) setCustom(old => old.map((value, index) => index === i ? '' : value)) }} /><b>{option.label}</b><span>{option.description}</span></label>)}{prompt.custom && <label className="designer-field">自定义回答<textarea aria-label={`问题 ${i + 1} 自定义回答`} value={custom[i]} onChange={e => setCustom(old => old.map((value, index) => index === i ? e.target.value : value))} /></label>}</section>)}
    <UiActionButton actionKey="designer.recommendAnswers" busy={busy} onAction={() => { const recommended = pending.questions.map(prompt => { const option = prompt.options.find(item => /Recommended|推荐/.test(item.label)) ?? prompt.options[0]; return option ? [option.label] : [] }); if (recommended.every(item => item.length)) submit(recommended) }} />
    <UiActionButton actionKey="designer.replyQuestion" busy={busy} availability={answers.every(value => value.length) ? { kind: 'enabled' } : { kind: 'disabled', reason: '请回答所有问题' }} onAction={() => submit(answers)} />
  </fieldset></section>
}
export function Discussion({ state, owner, skin, stopAttachment }: { state: Readonly<DesignerSnapshot>; owner: DesignerController; skin: SkinDefinition; stopAttachment(id: string, filename: string): void }) {
  const session = state.session; if (!session) return null
  return <div className="designer-history" aria-label="设计讨论记录">
    {session.requirementSnapshot && <section className="designer-card" aria-label="整体需求"><h3>整体需求 · R{session.requirementSnapshot.discussionRevision}</h3><small>{session.requirementSnapshot.source === 'SERVER_ASSEMBLED' ? '服务端整理' : '历史 AI 整理'}</small><RichDocument content={session.requirementSnapshot.markdown} skin={skin} /></section>}
    {session.questionInteraction.mode === 'CHAT_FALLBACK' && <p role="status">对话回答模式：{session.questionInteraction.awaitingAnswer ? '请阅读设计师问题并直接在输入框回答。' : '当前 OpenCode 不提供选项式提问。'}</p>}
    {timeline(session, state.selectedPackage).map(entry => entry.kind === 'discussion' ? <details key={entry.key} className="designer-card"><summary>需求讨论</summary>{entry.entries.map(question => <article key={question.id}><p>{question.scope || '整体需求'} · R{question.discussionRevision}</p>{question.questions.map((prompt, i) => <section key={i}><h4>{prompt.header || `问题 ${i + 1}`}</h4><p>{prompt.question}</p><ul>{prompt.options.map(option => <li key={option.label} data-selected={prompt.answers.includes(option.label)}>{option.label} · {option.description}</li>)}</ul><p>用户最终回答：{prompt.answers.join('、') || '未记录'}</p></section>)}</article>)}</details> : entry.kind === 'system' || entry.kind === 'validators' ? <details className="designer-card" key={entry.key}><summary>{entry.kind === 'system' ? '系统记录' : '验收记录'} · {entry.messages.length}</summary>{entry.messages.map(message => <p key={message.id}><time>{formatDateTime(message.createdAt)}</time> · {message.content.includes('SYSTEM_ERROR') ? userFacingError(message.content) : message.content}</p>)}</details> : <article className="designer-card" key={entry.key} data-designer-actor={entry.message.actor}><header><strong>{designerActorLabel(entry.message.actor)}</strong><span>{entry.message.workPackageId}</span><time>{formatDateTime(entry.message.createdAt)}</time>{entry.message.deliveryState && <small>{statusLabel(entry.message.deliveryState)}</small>}</header>{entry.message.actor === 'DESIGNER' ? <RichDocument content={entry.message.content} skin={skin} collapsible /> : <p className="designer-plain">{['RETRYABLE_ERROR', 'TERMINAL_ERROR', 'SESSION_ERROR'].includes(entry.message.deliveryState ?? '') || entry.message.content.includes('SYSTEM_ERROR') ? userFacingError(entry.message.content) : entry.message.content}</p>}
      {entry.message.attachments?.map(attachment => <section key={attachment.id} className="designer-attachment"><strong>{attachment.filename}</strong><small>{attachment.sizeBytes} bytes · {attachment.scopeKey} · SHA-256 {attachment.sha256}</small><UiActionButton actionKey="designer.previewAttachment" target={attachment.filename} onAction={() => { void owner.loadPreview(attachment.id) }} /><a href={api.designerAttachmentContentUrl(session.id, attachment.id)} target="_blank" rel="noopener noreferrer">打开原文件：{attachment.filename}</a>{attachment.state === 'ACTIVE' && session.state === 'REVIEWING' && <UiActionButton actionKey="designer.stopAttachment" target={attachment.filename} busy={state.command.busy} availability={['SENDING', 'UNKNOWN', 'ACCEPTED_READBACK'].includes(state.command.phase) ? { kind: 'disabled', reason: '先核对原操作。' } : { kind: 'enabled' }} onAction={() => stopAttachment(attachment.id, attachment.filename)} />}{state.previews[attachment.id] && <ReadOnlyCode content={state.previews[attachment.id]!} label={`附件预览 ${attachment.filename}`} />}</section>)}
    </article>)}
    {session.pendingQuestions?.map(pending => <PendingQuestion key={pending.id} pending={pending} busy={state.command.busy || session.autoMode.enabled && session.autoMode.state === 'ACTIVE' || ['UNKNOWN', 'ACCEPTED_READBACK'].includes(state.command.phase)} submit={answers => { void owner.replyQuestion(pending.id, answers) }} />)}
    {state.activity && session.state === 'RUNNING' && !session.compiler?.serverCompiled && <ActivityProjection activity={state.activity} skin={skin} label="当前角色活动" />}

  </div>
}

export function ActivityProjection({ activity, skin, label }: { activity: DesignerActivity; skin: SkinDefinition; label: string }) {
  const content = (activity.parts.at(-1)?.content ?? '').replace(/<!--\s*TASK_PROFILE_ROUTER_JSON_START\s*-->[\s\S]*?(?:<!--\s*TASK_PROFILE_ROUTER_JSON_END\s*-->|$)/gi, '').trim()
  return <section className="designer-card" aria-label={label} role="status"><h3>{designerActorLabel(activity.actor)}正在处理</h3><p>{displayLabel(activity.remoteState)} · {activity.connected ? '已连接' : '正在重连'} · {formatDateTime(activity.observedAt)}</p><p>{activity.structuredStep && displayLabel(activity.structuredStep)}</p>{content && <div className="designer-activity-content"><RichDocument content={content} skin={skin} /></div>}<p>累计 Token {activity.usage.totalTokens ?? '未提供'}</p></section>
}
