import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { useState } from 'react'
import type { LoopSpec, LoopVerifierSpec } from '@/types/domain'
import { foundationDOM } from '@/pages/w2/workflow/page.test-support'
import { changeVerifierType, LoopSpecEditor, verifierTypes } from './LoopSpecEditor'
import { frame, spec } from './test-support'
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
function editor(input = spec()) { foundationDOM(); let current = input; function Fixture() { const [source, change] = useState(JSON.stringify(input)); return <LoopSpecEditor source={source} onChange={value => { current = JSON.parse(value) as LoopSpec; change(value) }} /> } const root = render(frame(<Fixture />)); return { root, value: () => current } }
describe('React full structured LoopSpec editor', () => {
  it('does not emit normalization on mount and roundtrips stage identities and all thresholds', () => { const initial = { ...spec(), stages: [{ ...spec().stages[0]!, workPackageId: 'WP-7', stageKind: 'DOCUMENT_AUTHORING' as const, artifactPlanId: 'plan', executionStrategy: 'SERVER_DOCUMENT_MATERIALIZATION' as const }], limits: { ...spec().limits, sessionErrorLimit: 4, stagnationLimit: 5, verifierTimeout: 'PT2M' }, model: { providerId: 'fixture', modelId: 'model', thinking: true }, sessionPolicy: { reuseHealthySession: false, createFreshOnVerifierFailure: true }, nextAttemptPromptTemplate: '{{FAILURE_SUMMARY}}' }; const view = editor(initial); expect(view.value()).toBe(initial); fireEvent.change(screen.getByRole('textbox', { name: '任务目标' }), { target: { value: '新目标' } }); expect(view.value()).toEqual({ ...initial, goal: '新目标' }) })
  it('adds an empty NON_JAVA stage without synthetic paths or Git verifier', () => { const view = editor(); fireEvent.click(screen.getByRole('button', { name: '添加阶段' })); const added = view.value().stages[1]!; expect(added.allowedPaths).toEqual([]); expect(added.forbiddenPaths).toEqual([]); expect(added.verifiers).toEqual([]); expect(added.implementationKind).toBe('NON_JAVA') })
  it.each(verifierTypes)('supports %s native verifier shape without removing immutable sibling metadata', type => { const original: LoopVerifierSpec = { type: 'PROCESS', command: ['old'], criterionIds: ['AC-1'] }; const next = changeVerifierType(original, type); expect(next.type).toBe(type); expect(next.criterionIds).toEqual(['AC-1']); if (type !== 'PROCESS') expect(next.command).toBeUndefined() })
  it('rejects unknown verifier type explicitly', () => { expect(() => changeVerifierType({ type: 'PROCESS', command: [] }, 'UNKNOWN')).toThrow('未知验收器类型') })
  it('preserves criterion mapping, runtime and artifact assertions when editing unrelated context', () => { const value = spec(); value.stages[0]!.acceptanceCriteria = [{ id: 'WP-1-AC-1', description: '保留文本', verificationMode: 'BOTH', judgeRubric: '证据' }]; value.stages[0]!.verificationRuntime = { startCommand: ['java', '--port={{LOOPPER_PORT}}'], readiness: { path: '/health', expectedStatus: 200, jsonPath: '$.status', expectedValue: 'UP', matchMode: 'EXACT' }, startupTimeoutSeconds: 60, shutdownTimeoutSeconds: 10 }; value.stages[0]!.verifiers = [{ type: 'DOCUMENT_STRUCTURE', path: 'output.docx', criterionIds: ['WP-1-AC-1'], documentAssertions: [{ type: 'HEADING_EXISTS', value: '标题', headingLevel: 1 }] }, { type: 'TABULAR_DATA', path: 'output.xlsx', tabularAssertions: [{ type: 'EQUIVALENT_TO', sourcePath: 'original.csv' }] }]; const view = editor(value); fireEvent.change(screen.getByRole('textbox', { name: '执行上下文' }), { target: { value: '新上下文' } }); expect(view.value().stages).toEqual(value.stages); expect(screen.getAllByLabelText(/断言.*类型/)).toHaveLength(2) })
  it('edits AI-only acceptance and fresh-session policy with native controls', () => { const value = spec(); value.stages[0]!.acceptanceCriteria = [{ id: 'AC-1', description: '评审行为', verificationMode: 'MACHINE' }]; const view = editor(value); fireEvent.change(screen.getByLabelText('阶段 1 验收方式 1'), { target: { value: 'JUDGE' } }); fireEvent.change(screen.getByLabelText('阶段 1 AI 评审准则 1'), { target: { value: '逐证据核对' } }); fireEvent.change(screen.getByLabelText('阶段 1 仅使用 AI 的原因 1'), { target: { value: '视觉可用性' } }); fireEvent.click(screen.getByLabelText('验证失败后自动新建会话')); expect(view.value().stages[0]!.acceptanceCriteria![0]).toMatchObject({ verificationMode: 'JUDGE', judgeRubric: '逐证据核对', judgeOnlyReason: '视觉可用性' }); expect(view.value().sessionPolicy?.createFreshOnVerifierFailure).toBe(false) })
  it.each([{ label: '每阶段最大尝试次数', maximum: 20, limit: 'maxStageAttempts' }, { label: '阶段 1 启动超时秒数', maximum: 300, runtime: 'startupTimeoutSeconds' }, { label: '阶段 1 停止超时秒数', maximum: 60, runtime: 'shutdownTimeoutSeconds' }])('preserves native domain maximum for $label through actual control change', ({ label, maximum, limit, runtime }) => {
    const value = spec(); value.stages[0]!.verificationRuntime = { startCommand: ['java'], readiness: { path: '/health', expectedStatus: 200 }, startupTimeoutSeconds: 60, shutdownTimeoutSeconds: 10 }; const view = editor(value), input = screen.getByLabelText(label) as HTMLInputElement; expect(input.max).toBe(String(maximum)); fireEvent.change(input, { target: { value: maximum + 1 } }); expect(limit ? view.value().limits.maxStageAttempts : runtime === 'startupTimeoutSeconds' ? view.value().stages[0]!.verificationRuntime!.startupTimeoutSeconds : view.value().stages[0]!.verificationRuntime!.shutdownTimeoutSeconds).toBe(maximum)
  })

})
