import type { AvailableModel, BrowserAssertion, DocumentAssertion, LoopSpec, LoopVerifierSpec, TabularAssertion } from '@/types/domain'
import { UiActionButton } from '@/foundation/components'
import { ReadOnlyCode } from '@/pages/w3/shared/ReadOnlyCode'
import { json } from './model'
export const verifierTypes = ['PROCESS', 'FILE_EXISTS', 'FILE_NOT_EXISTS', 'GIT_DIFF', 'HTTP_STATUS', 'JSON_PATH', 'FILE_CONTENT', 'FILE_HASH', 'JUNIT_XML', 'BROWSER', 'DATABASE_QUERY', 'DOCUMENT_STRUCTURE', 'TABULAR_DATA'] as const
const verifierLabels: Record<string, string> = { PROCESS: '命令验证', FILE_EXISTS: '旧版文件存在提示', FILE_NOT_EXISTS: '文件必须不存在', GIT_DIFF: 'Git 差异检查', HTTP_STATUS: 'HTTP 状态码', JSON_PATH: 'JSON 内容', FILE_CONTENT: '文件内容', FILE_HASH: '文件 SHA-256', JUNIT_XML: 'JUnit XML 报告', BROWSER: '浏览器交互', DATABASE_QUERY: '数据库查询', DOCUMENT_STRUCTURE: '文档结构', TABULAR_DATA: '表格数据' }
const allowed: Record<string, string[]> = { PROCESS: ['command', 'processPurpose', 'testTargets', 'outputContains'], FILE_EXISTS: ['path'], FILE_NOT_EXISTS: ['path'], GIT_DIFF: ['requireChanges', 'allowedPaths', 'forbiddenPaths', 'forbidDeletes'], HTTP_STATUS: ['url', 'httpMethod', 'expectedStatus'], JSON_PATH: ['url', 'httpMethod', 'jsonPath', 'matchMode', 'expectedValue'], FILE_CONTENT: ['path', 'expectedContent', 'matchMode'], FILE_HASH: ['path', 'expectedSha256'], JUNIT_XML: ['path'], BROWSER: ['url', 'assertions'], DATABASE_QUERY: ['path', 'sql', 'expectedRowCount'], DOCUMENT_STRUCTURE: ['path', 'documentAssertions'], TABULAR_DATA: ['path', 'tabularAssertions'] }
export function changeVerifierType(old: LoopVerifierSpec, type: string): LoopVerifierSpec {
  if (!verifierTypes.includes(type as typeof verifierTypes[number])) throw new Error('未知验收器类型')
  const fields = { type, criterionIds: old.criterionIds } as Record<string, unknown>
  for (const key of allowed[type]!) if (key in old) fields[key] = old[key as keyof LoopVerifierSpec]
  const defaults: Record<typeof verifierTypes[number], LoopVerifierSpec> = { PROCESS: { type: 'PROCESS', command: [], processPurpose: 'TEST', testTargets: [] }, FILE_EXISTS: { type: 'FILE_EXISTS', path: '' }, FILE_NOT_EXISTS: { type: 'FILE_NOT_EXISTS', path: '' }, GIT_DIFF: { type: 'GIT_DIFF', requireChanges: true, forbidDeletes: true }, HTTP_STATUS: { type: 'HTTP_STATUS', url: '', httpMethod: 'GET', expectedStatus: 200 }, JSON_PATH: { type: 'JSON_PATH', url: '', httpMethod: 'GET', jsonPath: '$', matchMode: 'EXACT' }, FILE_CONTENT: { type: 'FILE_CONTENT', path: '', expectedContent: '' }, FILE_HASH: { type: 'FILE_HASH', path: '', expectedSha256: '' }, JUNIT_XML: { type: 'JUNIT_XML', path: '' }, BROWSER: { type: 'BROWSER', url: '', assertions: [] }, DATABASE_QUERY: { type: 'DATABASE_QUERY', path: '', sql: '' }, DOCUMENT_STRUCTURE: { type: 'DOCUMENT_STRUCTURE', path: '', documentAssertions: [] }, TABULAR_DATA: { type: 'TABULAR_DATA', path: '', tabularAssertions: [] } }
  const base = defaults[type as typeof verifierTypes[number]]
  return Object.assign({}, base, fields)
}
function Text({ label, value = '', change, multiline = false }: { label: string; value?: string; change(value: string): void; multiline?: boolean }) { return <label className="designer-field"><span>{label}</span>{multiline ? <textarea aria-label={label} value={value} onChange={e => change(e.target.value)} rows={3} /> : <input aria-label={label} value={value} onChange={e => change(e.target.value)} />}</label> }
function NumberField({ label, value, change, min = 0, max }: { label: string; value?: number; change(value: number | undefined): void; min?: number; max?: number }) { return <label className="designer-field"><span>{label}</span><input type="number" min={min} max={max} aria-label={label} value={value ?? ''} onChange={e => change(e.target.value === '' ? undefined : Math.min(max ?? Infinity, Math.max(min, Number(e.target.value))))} /></label> }
function Choice({ label, value, options, change }: { label: string; value?: string; options: readonly string[] | Record<string, string>; change(value: string): void }) { return <label className="designer-field"><span>{label}</span><select aria-label={label} value={value ?? ''} onChange={e => change(e.target.value)}><option value="">请选择</option>{(Array.isArray(options) ? options.map(key => [key, key]) : Object.entries(options)).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label> }
function Check({ label, value, change }: { label: string; value?: boolean; change(value: boolean): void }) { return <label className="designer-check"><input type="checkbox" aria-label={label} checked={value === true} onChange={e => change(e.target.checked)} />{label}</label> }
function Lines({ label, value, change }: { label: string; value?: string[]; change(value: string[]): void }) { return <Text label={label} multiline value={(value ?? []).join('\n')} change={text => change(text.split('\n').filter(Boolean))} /> }
export function LoopSpecEditor({ source, onChange, disabled = false, models = [] }: { source: string; onChange(value: string): void; disabled?: boolean; models?: AvailableModel[] }) {
  let spec: LoopSpec
  try { spec = JSON.parse(source) as LoopSpec; if (!Array.isArray(spec.stages) || !spec.limits) throw new Error('缺少阶段或调度限制') } catch (cause) { return <p role="alert">执行规范无法展示：{String(cause)}</p> }
  function edit(change: (next: LoopSpec) => void) { if (disabled) return; const next = JSON.parse(source) as LoopSpec; change(next); onChange(json(next)) }
  function updateStage(index: number, change: (stage: LoopSpec['stages'][number]) => void) { edit(next => change(next.stages[index]!)) }
  return <fieldset className="designer-spec" disabled={disabled} aria-label="LoopSpec 中文结构化编辑器">
    <legend>最终执行规范 · {spec.schemaVersion}</legend>
    <Text label="任务目标" multiline value={spec.goal} change={value => edit(next => { next.goal = value })} />
    <Text label="执行上下文" multiline value={spec.context} change={value => edit(next => { next.context = value })} />
    <UiActionButton actionKey="designer.addStage" onAction={() => edit(next => { next.stages.push({ objective: '', allowedPaths: [], forbiddenPaths: [], deliverables: ['可验证实现'], implementationKind: 'NON_JAVA', acceptanceCriteria: [], verifiers: [] }) })} />
    {spec.stages.map((stage, index) => <article className="designer-card" key={index} aria-label={`阶段 ${index + 1}`}><h3>阶段 {index + 1}</h3>
      {stage.workPackageId && <p>工作包：{stage.workPackageId}</p>}{stage.stageKind && <p>阶段类型：{stage.stageKind} · {stage.executionStrategy} · {stage.artifactPlanId}</p>}
      <Text label={`阶段 ${index + 1} 目标`} multiline value={stage.objective} change={value => updateStage(index, next => { next.objective = value })} />
      {spec.schemaVersion === 'v2' && <Choice label={`阶段 ${index + 1} 实现类型`} value={stage.implementationKind} options={{ JAVA_PRODUCTION: '生产 Java（必须有聚焦单元测试）', JAVA_TEST_ONLY: '仅 Java 测试', NON_JAVA: '不涉及生产 Java' }} change={value => updateStage(index, next => { next.implementationKind = value as NonNullable<typeof next.implementationKind> })} />}
      {(['allowedPaths', 'forbiddenPaths', 'deliverables'] as const).map(key => <Lines key={key} label={`阶段 ${index + 1} ${{ allowedPaths: '建议修改路径', forbiddenPaths: '建议避让路径', deliverables: '交付物' }[key]}`} value={stage[key]} change={value => updateStage(index, next => { next[key] = value })} />)}
      <UiActionButton actionKey="ui.delete" target={`阶段 ${index + 1}`} availability={spec.stages.length > 1 ? { kind: 'enabled' } : { kind: 'disabled', reason: '至少保留一个阶段' }} onAction={() => edit(next => { next.stages.splice(index, 1) })} />
      {spec.schemaVersion === 'v2' && <><h4>行为验收条件</h4><UiActionButton actionKey="designer.addCriterion" onAction={() => updateStage(index, next => { const criteria = next.acceptanceCriteria ??= []; let ordinal = criteria.length + 1; while (criteria.some(c => c.id === `${next.workPackageId ? next.workPackageId + '-' : ''}AC-${ordinal}`)) ordinal++; criteria.push({ id: `${next.workPackageId ? next.workPackageId + '-' : ''}AC-${ordinal}`, description: '', verificationMode: 'MACHINE' }) })} />
        {stage.acceptanceCriteria?.map((criterion, i) => <div className="designer-card" key={criterion.id}><p>{criterion.id}</p><Text label={`阶段 ${index + 1} 验收条件 ${i + 1}`} multiline value={criterion.description} change={value => updateStage(index, next => { next.acceptanceCriteria![i]!.description = value })} /><Choice label={`阶段 ${index + 1} 验收方式 ${i + 1}`} value={criterion.verificationMode ?? 'MACHINE'} options={{ MACHINE: '机器验证', JUDGE: 'AI 评审', BOTH: '机器 + AI' }} change={value => updateStage(index, next => { next.acceptanceCriteria![i]!.verificationMode = value as 'MACHINE' | 'JUDGE' | 'BOTH' })} />
          {['JUDGE', 'BOTH'].includes(criterion.verificationMode ?? '') && <Text label={`阶段 ${index + 1} AI 评审准则 ${i + 1}`} multiline value={criterion.judgeRubric} change={value => updateStage(index, next => { next.acceptanceCriteria![i]!.judgeRubric = value })} />}{criterion.verificationMode === 'JUDGE' && <Text label={`阶段 ${index + 1} 仅使用 AI 的原因 ${i + 1}`} multiline value={criterion.judgeOnlyReason} change={value => updateStage(index, next => { next.acceptanceCriteria![i]!.judgeOnlyReason = value })} />}
          <UiActionButton actionKey="ui.delete" target={`验收条件 ${i + 1}`} onAction={() => updateStage(index, next => { next.acceptanceCriteria!.splice(i, 1) })} /></div>)}
        <Check label={`阶段 ${index + 1} 启用托管临时运行时`} value={!!stage.verificationRuntime} change={value => updateStage(index, next => { if (value) next.verificationRuntime = { startCommand: [], readiness: { path: '/actuator/health', expectedStatus: 200 }, startupTimeoutSeconds: 60, shutdownTimeoutSeconds: 10 }; else delete next.verificationRuntime })} />
        {stage.verificationRuntime && <section><Lines label={`阶段 ${index + 1} 启动命令`} value={stage.verificationRuntime.startCommand} change={value => updateStage(index, next => { next.verificationRuntime!.startCommand = value })} />{(['path', 'jsonPath', 'expectedValue'] as const).map(key => <Text key={key} label={`阶段 ${index + 1} 就绪${{ path: '路径', jsonPath: ' JSON Path', expectedValue: '期望值' }[key]}`} value={stage.verificationRuntime!.readiness[key]} change={value => updateStage(index, next => { next.verificationRuntime!.readiness[key] = value })} />)}<NumberField label={`阶段 ${index + 1} 就绪状态码`} min={100} max={599} value={stage.verificationRuntime.readiness.expectedStatus} change={value => updateStage(index, next => { next.verificationRuntime!.readiness.expectedStatus = value })} /><Choice label={`阶段 ${index + 1} 就绪匹配方式`} options={['EXISTS', 'EXACT', 'CONTAINS']} value={stage.verificationRuntime.readiness.matchMode} change={value => updateStage(index, next => { next.verificationRuntime!.readiness.matchMode = value as 'EXISTS' | 'EXACT' | 'CONTAINS' })} />{(['startupTimeoutSeconds', 'shutdownTimeoutSeconds'] as const).map(key => <NumberField key={key} label={`阶段 ${index + 1} ${key === 'startupTimeoutSeconds' ? '启动超时秒数' : '停止超时秒数'}`} min={1} max={key === 'startupTimeoutSeconds' ? 300 : 60} value={stage.verificationRuntime![key]} change={value => updateStage(index, next => { next.verificationRuntime![key] = value })} />)}</section>}
      </>}
      <h4>机器执行验收</h4><UiActionButton actionKey="designer.addVerifier" onAction={() => updateStage(index, next => { next.verifiers.push({ type: 'PROCESS', command: [], processPurpose: 'TEST', testTargets: [] }) })} />
      {stage.verifiers.map((verifier, i) => <VerifierEditor key={i} verifier={verifier} criteria={stage.acceptanceCriteria ?? []} label={`阶段 ${index + 1} 验收器 ${i + 1}`} change={value => updateStage(index, next => { next.verifiers[i] = value })} remove={() => updateStage(index, next => { next.verifiers.splice(i, 1) })} />)}
      {!stage.verifiers.some(v => v.type !== 'GIT_DIFF') && <p role="alert">缺少功能验收，暂时无法确认。</p>}
    </article>)}
    <section className="designer-card"><h3>调度限制与会话策略</h3>{(['maxStageAttempts', 'maxTaskAttempts', 'sessionErrorLimit', 'stagnationLimit'] as const).map(key => <NumberField key={key} label={{ maxStageAttempts: '每阶段最大尝试次数', maxTaskAttempts: '整个任务最大尝试次数', sessionErrorLimit: '会话错误阈值', stagnationLimit: '连续停滞阈值' }[key]} value={spec.limits[key]} min={1} max={key === 'maxTaskAttempts' ? 100 : key === 'maxStageAttempts' || key === 'stagnationLimit' ? 20 : undefined} change={value => edit(next => { if (key === 'maxStageAttempts' || key === 'maxTaskAttempts') next.limits[key] = value ?? 1; else next.limits[key] = value })} />)}
      <Check label="任务超时限制" value={spec.limits.timeoutEnabled} change={value => edit(next => { next.limits.timeoutEnabled = value })} />{(['maxDuration', 'attemptTimeout', 'verifierTimeout'] as const).map(key => <Text key={key} label={{ maxDuration: '任务最长运行时间', attemptTimeout: '单次尝试超时', verifierTimeout: '验证器超时' }[key]} value={spec.limits[key]} change={value => edit(next => { next.limits[key] = value })} />)}
      <Check label="复用健康会话" value={spec.sessionPolicy?.reuseHealthySession ?? true} change={value => edit(next => { next.sessionPolicy = { reuseHealthySession: value, createFreshOnVerifierFailure: next.sessionPolicy?.createFreshOnVerifierFailure ?? true } })} /><Check label="验证失败后自动新建会话" value={spec.sessionPolicy?.createFreshOnVerifierFailure ?? true} change={value => edit(next => { next.sessionPolicy = { reuseHealthySession: next.sessionPolicy?.reuseHealthySession ?? true, createFreshOnVerifierFailure: value } })} />
      <Text label="下一轮提示模板" multiline value={spec.nextAttemptPromptTemplate} change={value => edit(next => { next.nextAttemptPromptTemplate = value })} />
      <Text label="模型 Provider" value={spec.model?.providerId} change={value => edit(next => { next.model = { ...next.model, providerId: value } })} /><Text label="模型 ID" value={spec.model?.modelId} change={value => edit(next => { next.model = { ...next.model, modelId: value } })} />{models.length > 0 && <Choice label="可用模型" value={models.find(m => m.provider === spec.model?.providerId && m.model === spec.model?.modelId)?.id} options={Object.fromEntries(models.map(m => [m.id, m.label]))} change={id => edit(next => { const model = models.find(m => m.id === id); if (model) next.model = { ...next.model, providerId: model.provider, modelId: model.model } })} />}<Check label="模型深度思考" value={spec.model?.thinking} change={value => edit(next => { next.model = { ...next.model, thinking: value } })} />
      <NumberField label="最大 Token 预算" value={spec.budget?.maxTotalTokens} change={value => edit(next => { next.budget = { ...next.budget, maxTotalTokens: value } })} /><Text label="最大费用" value={spec.budget?.maxCostAmount} change={value => edit(next => { next.budget = { ...next.budget, maxCostAmount: value } })} /><Text label="预算币种" value={spec.budget?.currency} change={value => edit(next => { next.budget = { ...next.budget, currency: value } })} />
    </section>
    <details><summary>只读原始规范</summary><ReadOnlyCode content={source} language="json" label="LoopSpec 原文" /></details>
  </fieldset>
}
function VerifierEditor({ verifier, criteria, label, change, remove }: { verifier: LoopVerifierSpec; criteria: NonNullable<LoopSpec['stages'][number]['acceptanceCriteria']>; label: string; change(value: LoopVerifierSpec): void; remove(): void }) {
  const set = (key: keyof LoopVerifierSpec, value: unknown) => change({ ...verifier, [key]: value } as LoopVerifierSpec)
  const fields = allowed[verifier.type]
  return <section className="designer-card"><h5>{label}</h5><Choice label={`${label} 类型`} value={verifier.type} options={verifierLabels} change={type => change(changeVerifierType(verifier, type))} />{!fields && <p role="alert">未知验收器类型；请显式选择合法类型。</p>}
    {fields?.filter(key => !['assertions', 'documentAssertions', 'tabularAssertions'].includes(key)).map(key => {
      const value = verifier[key as keyof LoopVerifierSpec]
      const labels: Record<string, string> = { command: '命令参数', processPurpose: '命令用途', testTargets: '聚焦测试目标', outputContains: '输出必须包含', path: '目标路径', url: 'URL', httpMethod: 'HTTP 方法', expectedStatus: '期望状态码', jsonPath: 'JSON Path', matchMode: '匹配方式', expectedValue: '期望值', expectedContent: '期望内容', expectedSha256: 'SHA-256', sql: '只读 SQL', expectedRowCount: '期望行数', requireChanges: '要求实际改动', forbidDeletes: '禁止删除', allowedPaths: '验收允许路径', forbiddenPaths: '验收禁止路径' }
      const name = `${label} ${labels[key] ?? key}`
      if (['command', 'testTargets', 'allowedPaths', 'forbiddenPaths'].includes(key)) return <Lines key={key} label={name} value={value as string[] | undefined} change={next => set(key as keyof LoopVerifierSpec, next)} />
      if (['requireChanges', 'forbidDeletes'].includes(key)) return <Check key={key} label={name} value={value as boolean | undefined} change={next => set(key as keyof LoopVerifierSpec, next)} />
      if (['expectedStatus', 'expectedRowCount'].includes(key)) return <NumberField key={key} label={name} value={value as number | undefined} change={next => set(key as keyof LoopVerifierSpec, next)} />
      if (['httpMethod', 'matchMode', 'processPurpose'].includes(key)) return <Choice key={key} label={name} value={value as string | undefined} options={key === 'httpMethod' ? ['GET', 'HEAD'] : key === 'matchMode' ? ['EXACT', 'CONTAINS', 'EXISTS'] : { TEST: '聚焦测试', SELF_CHECK: '自检', BUILD: '构建/静态检查' }} change={next => set(key as keyof LoopVerifierSpec, next)} />
      return <Text key={key} label={name} multiline={['sql', 'expectedContent', 'outputContains'].includes(key)} value={value as string | undefined} change={next => set(key as keyof LoopVerifierSpec, next)} />
    })}
    <fieldset><legend>覆盖的验收条件</legend>{criteria.map(c => <Check key={c.id} label={`${label} 覆盖 ${c.description}`} value={verifier.criterionIds?.includes(c.id)} change={selected => set('criterionIds', selected ? [...(verifier.criterionIds ?? []), c.id] : verifier.criterionIds?.filter(id => id !== c.id) ?? [])} />)}</fieldset>
    {verifier.type === 'BROWSER' && <Assertions kind="browser" values={verifier.assertions} label={label} change={values => set('assertions', values)} />}{verifier.type === 'DOCUMENT_STRUCTURE' && <Assertions kind="document" values={verifier.documentAssertions} label={label} change={values => set('documentAssertions', values)} />}{verifier.type === 'TABULAR_DATA' && <Assertions kind="tabular" values={verifier.tabularAssertions} label={label} change={values => set('tabularAssertions', values)} />}
    <UiActionButton actionKey="ui.delete" target={label} onAction={remove} />
  </section>
}
type Assertion = BrowserAssertion | DocumentAssertion | TabularAssertion
function Assertions({ kind, values, change, label }: { kind: 'browser' | 'document' | 'tabular'; values: Assertion[]; change(values: Assertion[]): void; label: string }) {
  const choices: Record<string, string> = kind === 'browser' ? { EXISTS: '元素存在', VISIBLE: '元素可见', TEXT_CONTAINS: '包含文本', COUNT: '元素数量', ATTRIBUTE_EQUALS: '属性相等' } : kind === 'document' ? { HEADING_EXISTS: '包含标题', TEXT_EXISTS: '包含正文', TEXT_NON_EMPTY: '文本非空', TABLE_COUNT: '表格数量', LOCAL_LINKS_VALID: '本地链接有效' } : { SHEET_EXISTS: '包含工作表', ROW_COUNT: '行数', COLUMN_COUNT: '列数', HEADER_EQUALS: '表头相等', CELL_EQUALS: '单元格相等', EQUIVALENT_TO: '与源表等价' }
  function set(index: number, key: string, value: unknown) { change(values.map((item, i) => i === index ? { ...item, [key]: value } as Assertion : item)) }
  return <div aria-label="制品验收断言"><UiActionButton actionKey="designer.addAssertion" availability={values.length < 64 ? { kind: 'enabled' } : { kind: 'disabled', reason: '最多 64 条断言' }} onAction={() => change([...values, kind === 'browser' ? { type: 'VISIBLE', selector: 'body' } : kind === 'document' ? { type: 'TEXT_EXISTS', value: '' } : { type: 'EQUIVALENT_TO', sourcePath: '' }])} />
    {values.map((item, index) => { const value = item as unknown as Record<string, unknown>; const fields = kind === 'browser' ? ['selector', ...(item.type === 'TEXT_CONTAINS' ? ['value'] : item.type === 'ATTRIBUTE_EQUALS' ? ['attribute', 'value'] : item.type === 'COUNT' ? ['expectedCount'] : [])] : kind === 'document' ? item.type === 'HEADING_EXISTS' ? ['value', 'headingLevel'] : item.type === 'TEXT_EXISTS' ? ['value'] : item.type === 'TABLE_COUNT' ? ['expectedCount'] : [] : item.type === 'EQUIVALENT_TO' ? ['sourcePath'] : ['sheet', ...(item.type === 'ROW_COUNT' || item.type === 'COLUMN_COUNT' ? ['expectedCount'] : item.type === 'CELL_EQUALS' ? ['row', 'column', 'expectedValue'] : item.type === 'HEADER_EQUALS' ? ['expectedValue'] : [])]
      return <div className="designer-card" key={index}><Choice label={`${label} 断言 ${index + 1} 类型`} value={item.type} options={choices} change={next => set(index, 'type', next)} />{fields.map(key => ['expectedCount', 'headingLevel', 'row', 'column'].includes(key) ? <NumberField key={key} label={`${label} 断言 ${index + 1} ${key}`} value={value[key] as number | undefined} change={next => set(index, key, next)} /> : <Text key={key} label={`${label} 断言 ${index + 1} ${{ selector: '选择器', value: '期望文本', attribute: '属性', sourcePath: '源文件路径', sheet: '工作表', expectedValue: '期望值' }[key as 'selector'] ?? key}`} value={value[key] as string | undefined} change={next => set(index, key, next)} />)}<UiActionButton actionKey="ui.delete" target={`断言 ${index + 1}`} onAction={() => change(values.filter((_, i) => i !== index))} /></div>
    })}
  </div>
}
