/** Shared appearance interface. Values can reference component-local CSS variables. */
export const appearanceDefaults: Record<string, string> = {
  "home-primary-hover": "var(--skin-primary-hover-background)",
  "ai-activity-panel-ai-activity-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 9%), rgb(var(--shade-cyan-01-rgb) / 5%), rgb(var(--shade-ai-01-rgb) / 9%))",
  "ai-activity-panel-thinking-orbit-span-background": "linear-gradient(135deg, var(--shade-ai-02), var(--color-accent-cyan))",
  "designer-current-activity-thinking-message-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 9%), rgb(var(--shade-cyan-01-rgb) / 5%), rgb(var(--shade-ai-01-rgb) / 9%))",
  "designer-current-activity-thinking-message-box-shadow": "none",
  "designer-current-activity-thinking-message-after-background": "linear-gradient(90deg, transparent, rgb(var(--shade-cyan-01-rgb) / 55%), transparent)",
  "designer-current-activity-thinking-orbit-box-shadow": "none",
  "designer-current-activity-thinking-orbit-span-background": "linear-gradient(135deg, var(--shade-ai-02), var(--color-accent-cyan))",
  "designer-current-activity-thinking-orbit-span-box-shadow": "none",
  "designer-current-activity-thinking-compiler-background": "linear-gradient(100deg, rgb(var(--shade-cyan-01-rgb) / 10%), rgb(var(--shade-elevated-01-rgb) / 5%), rgb(var(--shade-cyan-01-rgb) / 10%))",
  "designer-current-activity-thinking-decomposer-background": "linear-gradient(100deg, rgb(var(--shade-primary-01-rgb) / 11%), rgb(var(--shade-elevated-02-rgb) / 5%), rgb(var(--shade-primary-01-rgb) / 11%))",
  "designer-current-activity-thinking-validator-background": "linear-gradient(100deg, rgb(var(--shade-success-01-rgb) / 9%), rgb(var(--shade-success-02-rgb) / 5%), rgb(var(--shade-success-01-rgb) / 9%))",
  "designer-validator-history-designer-validator-history-box-shadow": "inset 2px 0 rgb(var(--shade-success-01-rgb) / 58%)",
  "git-diff-scope-approval-dialog-global-scope-approval-dialog-box-shadow": "none",
  "git-diff-scope-approval-dialog-file-open-active-box-shadow": "inset 2px 0 var(--color-accent-cyan)",
  "judge-review-card-judge-card-background": "linear-gradient(145deg, rgb(var(--shade-surface-10-rgb) / 88%), rgb(var(--shade-canvas-01-rgb) / 72%))",
  "judge-review-card-judge-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 2%)",
  "layered-error-panel-judge-attention-panel-background": "linear-gradient(135deg, rgb(var(--shade-warning-02-rgb) / 7%), rgb(var(--shade-surface-10-rgb) / 82%) 42%, rgb(var(--shade-canvas-01-rgb) / 76%))",
  "layered-error-panel-judge-attention-panel-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 2%)",
  "loop-spec-editor-form-section-background": "linear-gradient(145deg, rgb(var(--shade-surface-01-rgb) / 82%), rgb(var(--shade-canvas-06-rgb) / 72%))",
  "loop-spec-editor-form-section-box-shadow": "none",
  "loop-spec-editor-stage-header-background": "linear-gradient(90deg, rgb(var(--shade-primary-03-rgb) / 10%), transparent)",
  "loop-spec-editor-verifier-card-background": "linear-gradient(135deg, rgb(var(--shade-ai-01-rgb) / 7%), rgb(var(--shade-canvas-07-rgb) / 22%))",
  "markdown-document-markdown-thinking-card-background": "linear-gradient(135deg, rgb(var(--shade-ai-01-rgb) / 10%), rgb(var(--shade-surface-01-rgb) / 72%) 58%, rgb(var(--shade-cyan-01-rgb) / 6%))",
  "markdown-document-markdown-thinking-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%)",
  "markdown-document-markdown-thinking-card-before-background": "linear-gradient(180deg, var(--shade-ai-02), var(--color-accent-cyan))",
  "markdown-document-markdown-thinking-symbol-before-box-shadow": "none",
  "markdown-document-markdown-document-deep-pre-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 2%)",
  "markdown-document-markdown-document-deep-markdown-mermaid-background": "radial-gradient(circle at 50% 0, rgb(var(--shade-primary-03-rgb) / 10%), transparent 55%), var(--shade-canvas-10)",
  "markdown-document-markdown-document-deep-evidence-highlight-box-shadow": "inset 3px 0 var(--color-accent-cyan)",
  "open-code-todo-progress-todo-track-todo-track-in-progress-box-shadow": "none",
  "page-header-page-title-hover-box-shadow": "none",
  "pending-question-card-designer-question-card-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 9%), rgb(var(--shade-ai-01-rgb) / 7%))",
  "pending-question-card-designer-question-card-box-shadow": "none",
  "session-lifecycle-panel-lifecycle-background": "linear-gradient(135deg, rgb(var(--shade-surface-01-rgb) / 92%), rgb(var(--shade-surface-13-rgb) / 66%))",
  "session-monitor-panel-session-monitor-background": "linear-gradient(145deg, rgb(var(--shade-ai-01-rgb) / 5%), transparent 42%), var(--color-bg-surface)",
  "session-monitor-panel-session-monitor-box-shadow": "none",
  "session-monitor-panel-live-indicator-active-span-box-shadow": "none",
  "session-monitor-panel-session-option-selected-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 14%), rgb(var(--shade-cyan-01-rgb) / 5%))",
  "session-monitor-panel-session-option-selected-box-shadow": "inset 2px 0 var(--shade-ai-01)",
  "session-monitor-panel-transport-dot-live-box-shadow": "none",
  "session-monitor-panel-question-card-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 9%), rgb(var(--shade-ai-01-rgb) / 7%))",
  "session-monitor-panel-question-card-box-shadow": "none",
  "session-monitor-panel-live-thinking-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 10%), rgb(var(--shade-cyan-01-rgb) / 4%), rgb(var(--shade-ai-01-rgb) / 10%))",
  "session-monitor-panel-thinking-orbit-span-box-shadow": "none",
  "stage-rail-stage-node-background": "linear-gradient(145deg, var(--shade-surface-14), var(--shade-canvas-14))",
  "stage-rail-stage-node-box-shadow": "0 0 0 5px var(--color-bg-surface), inset 0 1px rgb(var(--shade-border-03-rgb) / 6%)",
  "stage-rail-stage-node-is-succeeded-background": "linear-gradient(145deg, rgb(var(--shade-success-01-rgb) / 24%), var(--shade-surface-15))",
  "stage-rail-stage-node-is-succeeded-box-shadow": "0 0 0 5px var(--color-bg-surface), 0 0 22px rgb(var(--shade-success-01-rgb) / 17%)",
  "stage-rail-stage-node-is-running-background": "linear-gradient(145deg, rgb(var(--shade-cyan-01-rgb) / 22%), var(--shade-surface-16))",
  "stage-rail-stage-node-is-running-box-shadow": "0 0 0 5px var(--color-bg-surface), 0 0 24px rgb(var(--shade-cyan-01-rgb) / 20%)",
  "stage-rail-stage-connector-i-background": "linear-gradient(90deg, transparent, currentcolor, transparent)",
  "stage-rail-connector-complete-box-shadow": "none",
  "stage-rail-phase-card-background": "linear-gradient(150deg, rgb(var(--shade-surface-17-rgb) / 96%), rgb(var(--shade-canvas-10-rgb) / 94%))",
  "stage-rail-phase-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%), 0 12px 30px rgb(var(--shade-shadow-01-rgb) / 13%)",
  "stage-rail-phase-card-before-background-image": "linear-gradient(rgb(var(--shade-cyan-01-rgb) / 2%) 1px, transparent 1px), linear-gradient(90deg, rgb(var(--shade-cyan-01-rgb) / 2%) 1px, transparent 1px)",
  "stage-rail-phase-card-is-running-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%), 0 0 28px rgb(var(--shade-cyan-01-rgb) / 7%)",
  "staged-file-context-card-file-context-card-background": "linear-gradient(155deg, rgb(var(--shade-surface-18-rgb) / 94%), rgb(var(--shade-canvas-10-rgb) / 96%))",
  "staged-file-context-card-file-context-card-box-shadow": "none",
  "task-audit-evidence-panel-global-diff-preview-dialog-box-shadow": "none",
  "task-decision-panel-decision-panel-background": "linear-gradient(125deg, rgb(var(--shade-warning-02-rgb) / 8%), rgb(var(--shade-surface-01-rgb) / 42%))",
  "task-publication-actions-global-publication-dialog-box-shadow": "none",
  "task-publication-actions-global-local-sync-dialog-box-shadow": "none",
  "token-usage-window-token-usage-window-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 11%), rgb(var(--shade-ai-01-rgb) / 13%)), rgb(var(--shade-canvas-01-rgb) / 88%)",
  "token-usage-window-token-usage-window-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 4%), 0 0 22px rgb(var(--shade-cyan-01-rgb) / 8%)",
  "token-usage-window-token-usage-window-after-background": "linear-gradient(90deg, transparent, rgb(var(--shade-cyan-01-rgb) / 70%), transparent)",
  "token-usage-window-token-delta-text-shadow": "none",
  "app-app-sidebar-background": "var(--color-bg-surface)",
  "app-brand-mark-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 20%), rgb(var(--shade-ai-01-rgb) / 21%))",
  "app-brand-mark-box-shadow": "none",
  "app-nav-item-router-link-active-background": "linear-gradient(90deg, rgb(var(--shade-cyan-01-rgb) / 12%), rgb(var(--shade-ai-01-rgb) / 6%))",
  "app-app-main-background": "radial-gradient(ellipse 760px 480px at 85% -10%, rgb(var(--shade-primary-03-rgb) / 9%), transparent 70%), var(--color-bg-canvas)",
  "app-card-background": "linear-gradient(145deg, rgb(var(--shade-surface-17-rgb) / 96%), rgb(var(--shade-canvas-13-rgb) / 96%))",
  "app-card-box-shadow": "none",
  "app-metric-card-background": "linear-gradient(135deg, rgb(var(--shade-surface-17-rgb) / 94%), rgb(var(--shade-canvas-26-rgb) / 94%))",
  "app-status-badge-before-box-shadow": "none",
  "app-error-panel-session-background": "linear-gradient(90deg, rgb(var(--shade-warning-02-rgb) / 12%), rgb(var(--shade-warning-02-rgb) / 3%))",
  "app-error-panel-task-background": "linear-gradient(90deg, rgb(var(--shade-danger-01-rgb) / 13%), rgb(var(--shade-danger-01-rgb) / 3%))",
  "app-stage-step-is-running-stage-dot-box-shadow": "none",
  "app-skeleton-block-background": "linear-gradient(90deg, var(--shade-surface-21) 20%, var(--shade-elevated-10) 38%, var(--shade-surface-21) 52%)",
  "app-el-button-primary-box-shadow": "none",
  "app-el-input-wrapper-box-shadow": "0 0 0 1px var(--color-border-default) inset",
  "app-el-input-wrapper-is-focus-box-shadow": "0 0 0 1px var(--color-action-primary) inset",
  "knowledge-knowledge-orb-box-shadow": "none",
  "knowledge-knowledge-composer-box-shadow": "none",
  "knowledge-knowledge-history-box-shadow": "none",
  "knowledge-knowledge-model-popover-box-shadow": "none",
  "knowledge-knowledge-thinking-is-active-background": "linear-gradient(120deg,color-mix(in srgb,var(--color-accent-cyan) 4%,var(--color-bg-surface)),var(--color-bg-surface))",
  "knowledge-knowledge-panel-box-shadow": "none",
  "knowledge-knowledge-usage-popover-box-shadow": "none",
  "knowledge-knowledge-result-table-tr-is-highlighted-th-box-shadow": "inset 3px 0 var(--color-accent-cyan)",
  "designer-view-designer-onboarding-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 8%), rgb(var(--shade-ai-01-rgb) / 7%))",
  "designer-view-designer-start-mark-background": "linear-gradient(145deg, rgb(var(--shade-cyan-01-rgb) / 13%), rgb(var(--shade-ai-01-rgb) / 12%))",
  "designer-view-designer-start-mark-box-shadow": "none",
  "designer-view-brief-composer-background": "linear-gradient(155deg, rgb(var(--shade-surface-23-rgb) / 98%), rgb(var(--shade-canvas-29-rgb) / 98%))",
  "designer-view-brief-composer-box-shadow": "none",
  "designer-view-draft-goal-input-deep-el-textarea-inner-box-shadow": "inset 0 1px 0 rgb(var(--shade-border-03-rgb) / 2%)",
  "designer-view-draft-goal-input-deep-el-textarea-inner-focus-box-shadow": "0 0 0 3px rgb(var(--shade-primary-03-rgb) / 10%)",
  "designer-view-project-context-card-background": "linear-gradient(160deg, rgb(var(--shade-surface-18-rgb) / 96%), rgb(var(--shade-canvas-12-rgb) / 96%))",
  "designer-view-connection-dot-connected-box-shadow": "none",
  "designer-view-connection-dot-reconnecting-box-shadow": "none",
  "designer-view-work-package-chip-active-box-shadow": "inset 2px 0 var(--shade-link-03), 0 0 16px rgb(var(--shade-primary-01-rgb) / 13%)",
  "designer-view-chat-decomposer-box-shadow": "inset 2px 0 rgb(var(--shade-primary-01-rgb) / 72%)",
  "designer-view-chat-designer-background": "radial-gradient(circle at 8% 0, rgb(var(--shade-ai-01-rgb) / 10%), transparent 32%), rgb(var(--shade-canvas-01-rgb) / 68%)",
  "designer-view-chat-designer-box-shadow": "inset 2px 0 rgb(var(--shade-ai-01-rgb) / 55%), 0 14px 38px rgb(var(--shade-shadow-01-rgb) / 13%)",
  "designer-view-chat-compiler-box-shadow": "inset 2px 0 rgb(var(--shade-cyan-01-rgb) / 62%)",
  "designer-view-chat-validator-box-shadow": "inset 2px 0 rgb(var(--shade-success-01-rgb) / 58%)",
  "designer-view-chat-validator-validator-retryable-error-box-shadow": "inset 2px 0 rgb(var(--shade-warning-02-rgb) / 65%)",
  "designer-view-chat-validator-validator-normalized-box-shadow": "inset 2px 0 rgb(var(--shade-cyan-01-rgb) / 62%)",
  "designer-view-chat-validator-validator-terminal-error-box-shadow": "inset 2px 0 rgb(var(--shade-danger-01-rgb) / 68%)",
  "home-view-home-hero-after-background": "none",
  "home-view-home-workspace-link-background": "linear-gradient(145deg, var(--color-bg-elevated), var(--color-bg-surface))",
  "home-view-home-hero-after-background-2": "none",
  "inbox-view-inbox-item-background": "linear-gradient(145deg, rgb(var(--shade-surface-17-rgb) / 96%), rgb(var(--shade-canvas-13-rgb) / 92%))",
  "insights-dashboard-view-insight-metrics-article-background": "linear-gradient(145deg,rgb(var(--shade-surface-17-rgb) / 96%),rgb(var(--shade-canvas-32-rgb) / 92%))",
  "insights-dashboard-view-quality-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%),0 5px 18px rgb(var(--shade-shadow-01-rgb) / 12%)",
  "projects-view-convention-action-hover-not-disabled-box-shadow": "none",
  "projects-view-danger-action-hover-not-disabled-box-shadow": "none",
  "recovery-studio-view-context-card-background": "linear-gradient(145deg, rgb(var(--shade-surface-25-rgb) / 92%), rgb(var(--shade-canvas-33-rgb) / 86%))",
  "recovery-studio-view-context-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 5%), 0 18px 44px rgb(var(--shade-shadow-01-rgb) / 18%)",
  "recovery-studio-view-mode-option-selected-box-shadow": "none",
  "runtime-view-runtime-hero-background": "radial-gradient(circle at 65% 22%, rgb(var(--shade-cyan-01-rgb) / 16%), transparent 35%), linear-gradient(145deg, var(--shade-surface-17), var(--shade-canvas-13))",
  "runtime-view-runtime-orb-box-shadow": "none",
  "task-detail-view-result-summary-background": "linear-gradient(125deg, rgb(var(--shade-cyan-01-rgb) / 6%), rgb(var(--shade-ai-01-rgb) / 4%))",
  "task-detail-view-retry-wait-card-background": "linear-gradient(120deg, rgb(var(--shade-warning-02-rgb) / 8%), rgb(var(--shade-surface-01-rgb) / 25%))",
  "task-detail-view-queue-blocker-background": "linear-gradient(120deg, rgb(var(--shade-warning-02-rgb) / 7%), rgb(var(--shade-surface-01-rgb) / 25%))",
  "tasks-view-onboarding-card-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 8%), rgb(var(--shade-ai-01-rgb) / 7%))"
}

/** Preserve the original gradients and shadows for 科技蓝. */
export const techBlueAppearance: Record<string, string> = {
  "home-primary-hover": "var(--shade-primary-05)",
  "ai-activity-panel-ai-activity-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 9%), rgb(var(--shade-cyan-01-rgb) / 5%), rgb(var(--shade-ai-01-rgb) / 9%))",
  "ai-activity-panel-thinking-orbit-span-background": "linear-gradient(135deg, var(--shade-ai-02), var(--color-accent-cyan))",
  "designer-current-activity-thinking-message-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 9%), rgb(var(--shade-cyan-01-rgb) / 5%), rgb(var(--shade-ai-01-rgb) / 9%))",
  "designer-current-activity-thinking-message-box-shadow": "0 12px 36px rgb(var(--shade-shadow-01-rgb) / 12%)",
  "designer-current-activity-thinking-message-after-background": "linear-gradient(90deg, transparent, rgb(var(--shade-cyan-01-rgb) / 55%), transparent)",
  "designer-current-activity-thinking-orbit-box-shadow": "0 0 18px rgb(var(--shade-ai-01-rgb) / 18%)",
  "designer-current-activity-thinking-orbit-span-background": "linear-gradient(135deg, var(--shade-ai-02), var(--color-accent-cyan))",
  "designer-current-activity-thinking-orbit-span-box-shadow": "0 0 12px rgb(var(--shade-cyan-01-rgb) / 55%)",
  "designer-current-activity-thinking-compiler-background": "linear-gradient(100deg, rgb(var(--shade-cyan-01-rgb) / 10%), rgb(var(--shade-elevated-01-rgb) / 5%), rgb(var(--shade-cyan-01-rgb) / 10%))",
  "designer-current-activity-thinking-decomposer-background": "linear-gradient(100deg, rgb(var(--shade-primary-01-rgb) / 11%), rgb(var(--shade-elevated-02-rgb) / 5%), rgb(var(--shade-primary-01-rgb) / 11%))",
  "designer-current-activity-thinking-validator-background": "linear-gradient(100deg, rgb(var(--shade-success-01-rgb) / 9%), rgb(var(--shade-success-02-rgb) / 5%), rgb(var(--shade-success-01-rgb) / 9%))",
  "designer-validator-history-designer-validator-history-box-shadow": "inset 2px 0 rgb(var(--shade-success-01-rgb) / 58%)",
  "git-diff-scope-approval-dialog-global-scope-approval-dialog-box-shadow": "0 28px 90px rgb(var(--shade-shadow-01-rgb) / 58%)",
  "git-diff-scope-approval-dialog-file-open-active-box-shadow": "inset 2px 0 var(--color-accent-cyan)",
  "judge-review-card-judge-card-background": "linear-gradient(145deg, rgb(var(--shade-surface-10-rgb) / 88%), rgb(var(--shade-canvas-01-rgb) / 72%))",
  "judge-review-card-judge-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 2%)",
  "layered-error-panel-judge-attention-panel-background": "linear-gradient(135deg, rgb(var(--shade-warning-02-rgb) / 7%), rgb(var(--shade-surface-10-rgb) / 82%) 42%, rgb(var(--shade-canvas-01-rgb) / 76%))",
  "layered-error-panel-judge-attention-panel-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 2%)",
  "loop-spec-editor-form-section-background": "linear-gradient(145deg, rgb(var(--shade-surface-01-rgb) / 82%), rgb(var(--shade-canvas-06-rgb) / 72%))",
  "loop-spec-editor-form-section-box-shadow": "0 12px 34px rgb(var(--shade-shadow-01-rgb) / 14%)",
  "loop-spec-editor-stage-header-background": "linear-gradient(90deg, rgb(var(--shade-primary-03-rgb) / 10%), transparent)",
  "loop-spec-editor-verifier-card-background": "linear-gradient(135deg, rgb(var(--shade-ai-01-rgb) / 7%), rgb(var(--shade-canvas-07-rgb) / 22%))",
  "markdown-document-markdown-thinking-card-background": "linear-gradient(135deg, rgb(var(--shade-ai-01-rgb) / 10%), rgb(var(--shade-surface-01-rgb) / 72%) 58%, rgb(var(--shade-cyan-01-rgb) / 6%))",
  "markdown-document-markdown-thinking-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%)",
  "markdown-document-markdown-thinking-card-before-background": "linear-gradient(180deg, var(--shade-ai-02), var(--color-accent-cyan))",
  "markdown-document-markdown-thinking-symbol-before-box-shadow": "0 0 7px rgb(var(--shade-ai-02-rgb) / 55%)",
  "markdown-document-markdown-document-deep-pre-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 2%)",
  "markdown-document-markdown-document-deep-markdown-mermaid-background": "radial-gradient(circle at 50% 0, rgb(var(--shade-primary-03-rgb) / 10%), transparent 55%), var(--shade-canvas-10)",
  "markdown-document-markdown-document-deep-evidence-highlight-box-shadow": "inset 3px 0 var(--color-accent-cyan)",
  "open-code-todo-progress-todo-track-todo-track-in-progress-box-shadow": "0 0 12px rgb(var(--shade-cyan-01-rgb) / 30%)",
  "page-header-page-title-hover-box-shadow": "0 14px 34px rgb(var(--shade-shadow-01-rgb) / 38%)",
  "pending-question-card-designer-question-card-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 9%), rgb(var(--shade-ai-01-rgb) / 7%))",
  "pending-question-card-designer-question-card-box-shadow": "0 14px 36px rgb(var(--shade-shadow-01-rgb) / 22%)",
  "session-lifecycle-panel-lifecycle-background": "linear-gradient(135deg, rgb(var(--shade-surface-01-rgb) / 92%), rgb(var(--shade-surface-13-rgb) / 66%))",
  "session-monitor-panel-session-monitor-background": "linear-gradient(145deg, rgb(var(--shade-ai-01-rgb) / 5%), transparent 42%), var(--color-bg-surface)",
  "session-monitor-panel-session-monitor-box-shadow": "0 18px 48px rgb(var(--shade-shadow-01-rgb) / 18%)",
  "session-monitor-panel-live-indicator-active-span-box-shadow": "0 0 12px currentColor",
  "session-monitor-panel-session-option-selected-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 14%), rgb(var(--shade-cyan-01-rgb) / 5%))",
  "session-monitor-panel-session-option-selected-box-shadow": "inset 2px 0 var(--shade-ai-01)",
  "session-monitor-panel-transport-dot-live-box-shadow": "0 0 9px rgb(var(--shade-success-01-rgb) / 60%)",
  "session-monitor-panel-question-card-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 9%), rgb(var(--shade-ai-01-rgb) / 7%))",
  "session-monitor-panel-question-card-box-shadow": "0 14px 36px rgb(var(--shade-shadow-01-rgb) / 22%)",
  "session-monitor-panel-live-thinking-background": "linear-gradient(100deg, rgb(var(--shade-ai-01-rgb) / 10%), rgb(var(--shade-cyan-01-rgb) / 4%), rgb(var(--shade-ai-01-rgb) / 10%))",
  "session-monitor-panel-thinking-orbit-span-box-shadow": "0 0 10px rgb(var(--shade-cyan-01-rgb) / 55%)",
  "stage-rail-stage-node-background": "linear-gradient(145deg, var(--shade-surface-14), var(--shade-canvas-14))",
  "stage-rail-stage-node-box-shadow": "0 0 0 5px var(--color-bg-surface), inset 0 1px rgb(var(--shade-border-03-rgb) / 6%)",
  "stage-rail-stage-node-is-succeeded-background": "linear-gradient(145deg, rgb(var(--shade-success-01-rgb) / 24%), var(--shade-surface-15))",
  "stage-rail-stage-node-is-succeeded-box-shadow": "0 0 0 5px var(--color-bg-surface), 0 0 22px rgb(var(--shade-success-01-rgb) / 17%)",
  "stage-rail-stage-node-is-running-background": "linear-gradient(145deg, rgb(var(--shade-cyan-01-rgb) / 22%), var(--shade-surface-16))",
  "stage-rail-stage-node-is-running-box-shadow": "0 0 0 5px var(--color-bg-surface), 0 0 24px rgb(var(--shade-cyan-01-rgb) / 20%)",
  "stage-rail-stage-connector-i-background": "linear-gradient(90deg, transparent, currentcolor, transparent)",
  "stage-rail-connector-complete-box-shadow": "0 0 10px rgb(var(--shade-success-01-rgb) / 22%)",
  "stage-rail-phase-card-background": "linear-gradient(150deg, rgb(var(--shade-surface-17-rgb) / 96%), rgb(var(--shade-canvas-10-rgb) / 94%))",
  "stage-rail-phase-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%), 0 12px 30px rgb(var(--shade-shadow-01-rgb) / 13%)",
  "stage-rail-phase-card-before-background-image": "linear-gradient(rgb(var(--shade-cyan-01-rgb) / 2%) 1px, transparent 1px), linear-gradient(90deg, rgb(var(--shade-cyan-01-rgb) / 2%) 1px, transparent 1px)",
  "stage-rail-phase-card-is-running-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%), 0 0 28px rgb(var(--shade-cyan-01-rgb) / 7%)",
  "staged-file-context-card-file-context-card-background": "linear-gradient(155deg, rgb(var(--shade-surface-18-rgb) / 94%), rgb(var(--shade-canvas-10-rgb) / 96%))",
  "staged-file-context-card-file-context-card-box-shadow": "0 14px 34px rgb(var(--shade-shadow-01-rgb) / 18%)",
  "task-audit-evidence-panel-global-diff-preview-dialog-box-shadow": "0 24px 80px rgb(var(--shade-shadow-01-rgb) / 55%)",
  "task-decision-panel-decision-panel-background": "linear-gradient(125deg, rgb(var(--shade-warning-02-rgb) / 8%), rgb(var(--shade-surface-01-rgb) / 42%))",
  "task-publication-actions-global-publication-dialog-box-shadow": "0 24px 80px rgb(var(--shade-shadow-01-rgb) / 55%)",
  "task-publication-actions-global-local-sync-dialog-box-shadow": "0 30px 100px rgb(var(--shade-shadow-01-rgb) / 65%)",
  "token-usage-window-token-usage-window-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 11%), rgb(var(--shade-ai-01-rgb) / 13%)), rgb(var(--shade-canvas-01-rgb) / 88%)",
  "token-usage-window-token-usage-window-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 4%), 0 0 22px rgb(var(--shade-cyan-01-rgb) / 8%)",
  "token-usage-window-token-usage-window-after-background": "linear-gradient(90deg, transparent, rgb(var(--shade-cyan-01-rgb) / 70%), transparent)",
  "token-usage-window-token-delta-text-shadow": "0 0 12px rgb(var(--shade-cyan-01-rgb) / 75%)",
  "app-app-sidebar-background": "linear-gradient(180deg, var(--shade-canvas-13) 0%, var(--shade-canvas-25) 72%, var(--shade-canvas-01) 100%)",
  "app-brand-mark-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 20%), rgb(var(--shade-ai-01-rgb) / 21%))",
  "app-brand-mark-box-shadow": "0 0 20px rgb(var(--shade-cyan-01-rgb) / 16%)",
  "app-nav-item-router-link-active-background": "linear-gradient(90deg, rgb(var(--shade-cyan-01-rgb) / 12%), rgb(var(--shade-ai-01-rgb) / 6%))",
  "app-app-main-background": "radial-gradient(ellipse 760px 480px at 85% -10%, rgb(var(--shade-primary-03-rgb) / 9%), transparent 70%), var(--color-bg-canvas)",
  "app-card-background": "linear-gradient(145deg, rgb(var(--shade-surface-17-rgb) / 96%), rgb(var(--shade-canvas-13-rgb) / 96%))",
  "app-card-box-shadow": "var(--shadow-card)",
  "app-metric-card-background": "linear-gradient(135deg, rgb(var(--shade-surface-17-rgb) / 94%), rgb(var(--shade-canvas-26-rgb) / 94%))",
  "app-status-badge-before-box-shadow": "0 0 8px currentcolor",
  "app-error-panel-session-background": "linear-gradient(90deg, rgb(var(--shade-warning-02-rgb) / 12%), rgb(var(--shade-warning-02-rgb) / 3%))",
  "app-error-panel-task-background": "linear-gradient(90deg, rgb(var(--shade-danger-01-rgb) / 13%), rgb(var(--shade-danger-01-rgb) / 3%))",
  "app-stage-step-is-running-stage-dot-box-shadow": "var(--shadow-glow)",
  "app-skeleton-block-background": "linear-gradient(90deg, var(--shade-surface-21) 20%, var(--shade-elevated-10) 38%, var(--shade-surface-21) 52%)",
  "app-el-button-primary-box-shadow": "0 0 18px rgb(var(--shade-primary-03-rgb) / 8%)",
  "app-el-input-wrapper-box-shadow": "0 0 0 1px var(--color-border-default) inset",
  "app-el-input-wrapper-is-focus-box-shadow": "0 0 0 1px var(--color-action-primary) inset",
  "knowledge-knowledge-orb-box-shadow": "var(--shadow-glow)",
  "knowledge-knowledge-composer-box-shadow": "var(--shadow-card)",
  "knowledge-knowledge-history-box-shadow": "var(--shadow-card)",
  "knowledge-knowledge-model-popover-box-shadow": "var(--shadow-card)",
  "knowledge-knowledge-thinking-is-active-background": "linear-gradient(120deg,color-mix(in srgb,var(--color-accent-cyan) 4%,var(--color-bg-surface)),var(--color-bg-surface))",
  "knowledge-knowledge-panel-box-shadow": "var(--shadow-card)",
  "knowledge-knowledge-usage-popover-box-shadow": "var(--shadow-card)",
  "knowledge-knowledge-result-table-tr-is-highlighted-th-box-shadow": "inset 3px 0 var(--color-accent-cyan)",
  "designer-view-designer-onboarding-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 8%), rgb(var(--shade-ai-01-rgb) / 7%))",
  "designer-view-designer-start-mark-background": "linear-gradient(145deg, rgb(var(--shade-cyan-01-rgb) / 13%), rgb(var(--shade-ai-01-rgb) / 12%))",
  "designer-view-designer-start-mark-box-shadow": "0 12px 34px rgb(var(--shade-shadow-01-rgb) / 22%)",
  "designer-view-brief-composer-background": "linear-gradient(155deg, rgb(var(--shade-surface-23-rgb) / 98%), rgb(var(--shade-canvas-29-rgb) / 98%))",
  "designer-view-brief-composer-box-shadow": "0 24px 70px rgb(var(--shade-shadow-01-rgb) / 25%)",
  "designer-view-draft-goal-input-deep-el-textarea-inner-box-shadow": "inset 0 1px 0 rgb(var(--shade-border-03-rgb) / 2%)",
  "designer-view-draft-goal-input-deep-el-textarea-inner-focus-box-shadow": "0 0 0 3px rgb(var(--shade-primary-03-rgb) / 10%)",
  "designer-view-project-context-card-background": "linear-gradient(160deg, rgb(var(--shade-surface-18-rgb) / 96%), rgb(var(--shade-canvas-12-rgb) / 96%))",
  "designer-view-connection-dot-connected-box-shadow": "0 0 9px rgb(var(--shade-success-01-rgb) / 60%)",
  "designer-view-connection-dot-reconnecting-box-shadow": "0 0 9px rgb(var(--shade-warning-02-rgb) / 45%)",
  "designer-view-work-package-chip-active-box-shadow": "inset 2px 0 var(--shade-link-03), 0 0 16px rgb(var(--shade-primary-01-rgb) / 13%)",
  "designer-view-chat-decomposer-box-shadow": "inset 2px 0 rgb(var(--shade-primary-01-rgb) / 72%)",
  "designer-view-chat-designer-background": "radial-gradient(circle at 8% 0, rgb(var(--shade-ai-01-rgb) / 10%), transparent 32%), rgb(var(--shade-canvas-01-rgb) / 68%)",
  "designer-view-chat-designer-box-shadow": "inset 2px 0 rgb(var(--shade-ai-01-rgb) / 55%), 0 14px 38px rgb(var(--shade-shadow-01-rgb) / 13%)",
  "designer-view-chat-compiler-box-shadow": "inset 2px 0 rgb(var(--shade-cyan-01-rgb) / 62%)",
  "designer-view-chat-validator-box-shadow": "inset 2px 0 rgb(var(--shade-success-01-rgb) / 58%)",
  "designer-view-chat-validator-validator-retryable-error-box-shadow": "inset 2px 0 rgb(var(--shade-warning-02-rgb) / 65%)",
  "designer-view-chat-validator-validator-normalized-box-shadow": "inset 2px 0 rgb(var(--shade-cyan-01-rgb) / 62%)",
  "designer-view-chat-validator-validator-terminal-error-box-shadow": "inset 2px 0 rgb(var(--shade-danger-01-rgb) / 68%)",
  "home-view-home-hero-after-background": "linear-gradient(90deg, var(--color-bg-canvas) 12%, rgb(var(--shade-canvas-01-rgb) / 96%) 30%, rgb(var(--shade-canvas-01-rgb) / 40%) 52%, transparent 72%)",
  "home-view-home-workspace-link-background": "linear-gradient(145deg, var(--color-bg-elevated), var(--color-bg-surface))",
  "home-view-home-hero-after-background-2": "linear-gradient(90deg, var(--color-bg-canvas), rgb(var(--shade-canvas-01-rgb) / 45%))",
  "inbox-view-inbox-item-background": "linear-gradient(145deg, rgb(var(--shade-surface-17-rgb) / 96%), rgb(var(--shade-canvas-13-rgb) / 92%))",
  "insights-dashboard-view-insight-metrics-article-background": "linear-gradient(145deg,rgb(var(--shade-surface-17-rgb) / 96%),rgb(var(--shade-canvas-32-rgb) / 92%))",
  "insights-dashboard-view-quality-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 3%),0 5px 18px rgb(var(--shade-shadow-01-rgb) / 12%)",
  "projects-view-convention-action-hover-not-disabled-box-shadow": "0 0 18px rgb(var(--shade-ai-01-rgb) / 13%)",
  "projects-view-danger-action-hover-not-disabled-box-shadow": "0 0 18px rgb(var(--shade-danger-05-rgb) / 10%)",
  "recovery-studio-view-context-card-background": "linear-gradient(145deg, rgb(var(--shade-surface-25-rgb) / 92%), rgb(var(--shade-canvas-33-rgb) / 86%))",
  "recovery-studio-view-context-card-box-shadow": "inset 0 1px rgb(var(--shade-border-03-rgb) / 5%), 0 18px 44px rgb(var(--shade-shadow-01-rgb) / 18%)",
  "recovery-studio-view-mode-option-selected-box-shadow": "0 0 18px rgb(var(--shade-cyan-01-rgb) / 8%)",
  "runtime-view-runtime-hero-background": "radial-gradient(circle at 65% 22%, rgb(var(--shade-cyan-01-rgb) / 16%), transparent 35%), linear-gradient(145deg, var(--shade-surface-17), var(--shade-canvas-13))",
  "runtime-view-runtime-orb-box-shadow": "var(--shadow-glow)",
  "task-detail-view-result-summary-background": "linear-gradient(125deg, rgb(var(--shade-cyan-01-rgb) / 6%), rgb(var(--shade-ai-01-rgb) / 4%))",
  "task-detail-view-retry-wait-card-background": "linear-gradient(120deg, rgb(var(--shade-warning-02-rgb) / 8%), rgb(var(--shade-surface-01-rgb) / 25%))",
  "task-detail-view-queue-blocker-background": "linear-gradient(120deg, rgb(var(--shade-warning-02-rgb) / 7%), rgb(var(--shade-surface-01-rgb) / 25%))",
  "tasks-view-onboarding-card-background": "linear-gradient(135deg, rgb(var(--shade-cyan-01-rgb) / 8%), rgb(var(--shade-ai-01-rgb) / 7%))"
}
