import { documentFindingSeverityLabel, workflowHistorySideLabel, workflowSnapshotAttributionLabel, workflowSnapshotVerdictLabel } from '@/utils/displayLabels'
import * as v from './validators'
import { Invalid, Lines, References, type ReportProps } from './ReportParts'
export function WorkflowSnapshotReport({ content }: ReportProps) {
  const r = v.parseSnapshotReport(content); if (!r) return <Invalid label="版本审查结果" />
  return <section className="workflow-professional-report workflow-snapshot-report">{r.kind === 'analysis' ? <p><strong>第 {r.batch} / {r.total} 批版本分析</strong> · {r.coverage.length} 个片段 · {r.findings.length} 个候选问题</p> : <><h4>候选问题独立复核</h4><p>{r.conclusion}</p></>}<p>静态代码审查；未运行的测试不能视为通过。</p>
    {r.kind === 'analysis' ? <>{r.reuse && <p className="reuse-provenance">已复用历史分析，本次没有创建模型会话。来源：<a href={`/requirements/${encodeURIComponent(r.reuse.sourceRequirementId)}`}>{r.reuse.sourceTitle}</a> · {r.reuse.sourceNodeTitle}</p>}{!r.findings.length && <p>本批未提出候选问题，未进行问题独立复核；不代表代码没有缺陷。</p>}{r.findings.map(finding => <article key={finding.key}><h4>{finding.title}</h4><p>{documentFindingSeverityLabel(finding.severity)}影响 · {workflowSnapshotAttributionLabel(finding.attribution)}</p><p>触发条件：{finding.trigger}</p><p>{finding.behavior}</p><p>建议：{finding.recommendation}</p><References values={finding.evidence} /></article>)}<details><summary>本批片段覆盖</summary>{r.coverage.map((item, i) => <article key={item.unitId}><h4>{item.path} · 片段 {i + 1}</h4><p>{item.conclusion}</p><Lines values={item.limitations} /></article>)}</details></> : r.decisions.map(decision => <article key={decision.findingKey}><h4>{decision.finding.title}</h4><strong>{workflowSnapshotVerdictLabel(decision.verdict)}</strong><p>{decision.reason}</p>{decision.duplicateOf && <p>已关联对应问题，完整报告保留合并关系。</p>}<References values={decision.evidence} /></article>)}<Lines values={r.limitations} />
  </section>
}
export function WorkflowHistoryAnalysisReport({ content }: ReportProps) {
  const r = v.parseHistoryAnalysisReport(content); if (!r) return <Invalid label="历史分析结果" />
  return <section className="workflow-professional-report">{r.kind === 'review' ? <><p><strong>第 {r.batch} / {r.total} 批历史审查</strong> · {r.reviews.length} 项变更</p><p>静态审查记录；未运行的测试不能视为通过。</p>{r.reviews.map((item, i) => <details key={item.unitId}><summary>{item.location.path || '无文件变更'} · 证据项 {i + 1} · {item.findings.length} 个问题</summary><p>提交：<code>{item.location.commitSha}</code></p><p>{item.summary}</p>{item.findings.map((finding, j) => <article key={j}><h4>{finding.title}</h4><p>{documentFindingSeverityLabel(finding.severity)}影响 · {workflowHistorySideLabel(finding.side)}第 {finding.line} 行</p><p>{finding.detail}</p><p>建议：{finding.recommendation}</p></article>)}<Lines values={item.limitations} /></details>)}</> : <><h4>{r.name} · 个人贡献评价</h4><p>{r.email}{r.robot && ' · 机器人，报告不参与排名'}</p><p>{r.commits} 个提交 · 变更 {r.raw} 行 · 有效 {r.effective} 行</p><p>{r.summary}</p><p>以下为有依据的四维等级；完整报告另行计算分数与排名。</p>{r.dimensions.map(d => <article key={d.title}><h4>{d.title} · {d.level} / 4</h4><p>{d.reason}</p><small>引用 {d.evidenceIds.length} 项本人证据</small></article>)}</>}</section>
}
