import { documentFindingKindLabel, documentFindingSeverityLabel, requirementConclusionLabel } from '@/utils/displayLabels'
import * as v from './validators'
import { Badge, Invalid, Limits, Lines, Markdown, References, type ReportProps } from './ReportParts'
const sourceLabel = (source: { fileId: string; section: number }) => `文档 ${source.fileId.slice(4)} · 第 ${source.section} 章`
export function WorkflowSourceDesignReport({ content, review, skin }: ReportProps) {
  const { design, opinion, citations } = v.parseSourceDesignReport(content, review)
  return <section className="workflow-professional-report">{design ? <><h3>{design.title}</h3><p>{design.summary}</p>{design.sections.map(section => <article key={section.key}><h4>{section.title}</h4><p>{section.paths.join('、')}</p><Markdown content={section.markdown} skin={skin} /></article>)}<Limits values={design.limitations} /></> : opinion ? <><Badge good={opinion.verdict === 'PASS'}>{opinion.verdict === 'PASS' ? '复核通过' : '需要返修'}</Badge><p>{opinion.reason}</p><p>已复核 {opinion.paths.length} 个源码文件</p><Lines values={opinion.paths} />{opinion.issues.map((issue, i) => <article key={i}><strong>问题 {i + 1} · {issue.sectionKey}</strong><p>{issue.detail}</p><p>修订建议：{issue.recommendation}</p></article>)}</> : <Invalid label="专业设计交付" />}<References values={citations} /></section>
}
export function WorkflowDocumentReviewReport({ content, review }: ReportProps) {
  const { assessment, opinion } = v.parseDocumentReviewReport(content, review)
  return <section className="workflow-professional-report">{assessment ? <><p>静态代码评审 · 未运行测试</p><p>{assessment.entries.length} 项需求结论 · {assessment.findings.length} 项问题</p>{assessment.entries.map((entry, i) => <article key={i}><h4>{entry.title}</h4><Badge good={entry.assessment.conclusion === 'SATISFIED'}>{requirementConclusionLabel(entry.assessment.conclusion)}</Badge><p>{entry.statement}</p><p>{entry.assessment.rationale}</p><p>{entry.sources.map(sourceLabel).join('；')}</p><Lines values={entry.issues.map(issue => `待澄清：${issue}`)} /><details><summary>依据与局限</summary><References values={entry.assessment.evidence} /><p>已检查：{entry.assessment.checkedPaths.join('、')}</p>{entry.assessment.missingEntryEvidence && <p>未实现依据：{entry.assessment.missingEntryEvidence}</p>}<p>测试源码情况：{entry.assessment.testSourceCoverage}</p><Lines values={entry.assessment.limitations} /></details></article>)}{!!assessment.findings.length && <details><summary>问题明细</summary>{assessment.findings.map(finding => <article key={finding.key}><h4>{finding.title}</h4><p>{documentFindingKindLabel(finding.kind)} · {documentFindingSeverityLabel(finding.severity)}影响</p><p>触发条件：{finding.trigger}</p><p>影响：{finding.impact}</p><p>建议：{finding.recommendation}</p><References values={finding.evidence} /></article>)}</details>}{!!assessment.skipped.length && <details><summary>未适用章节（{assessment.skipped.length}）</summary>{assessment.skipped.map((item, i) => <p key={i}>{sourceLabel(item.source)}：{item.reason}</p>)}</details>}<Limits values={assessment.limitations} /></> : opinion ? <><Badge good={opinion.approved}>{opinion.approved ? '复核通过' : '需要返修'}</Badge><p>独立核对 {opinion.requirements} 项结论、{opinion.findings} 项问题和 {opinion.sections.length} 个章节。</p><p>复核意见不代表已运行测试。</p>{opinion.corrections.map((correction, i) => <article key={i}><strong>修正意见 {i + 1}</strong>{correction.requirementKey && /^RQ-[1-9][0-9]*$/.test(correction.requirementKey) && <p>关联需求 {correction.requirementKey.slice(3)}</p>}{correction.findingKey && <p>关联问题：{correction.findingKey}</p>}{correction.source && <p>{sourceLabel(correction.source)}</p>}<p>{correction.detail}</p></article>)}<details><summary>已核对原文</summary><Lines values={opinion.sections.map(sourceLabel)} /></details></> : <Invalid label="需求代码评审" />}</section>
}
