import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import {knowledgeApi} from '@/api/knowledge'
import {deferred} from '@/pages/w2/core/coreTestHelpers'
import {createKnowledgeBrowser} from './browser'
import {sourceFixture} from './fixtures'
import type {KnowledgeSearch} from '@/types/domain'
const owners:ReturnType<typeof createKnowledgeBrowser>[]=[]
function browser(){const o=createKnowledgeBrowser();owners.push(o);o.configure('p',undefined,[sourceFixture],['code']);return o}
const search:KnowledgeSearch={matches:[{sourceId:'code',path:'src/Main.java',name:'Main.java',sha256:'original',snippet:'原词',startLine:12}],coverage:[{sourceId:'code',name:'代码',kind:'CODE',state:'PARTIAL',examined:20,matched:1,limited:true,limitations:['范围有限']}],nextCursor:'next',incomplete:true,limitations:['待继续'],detail:'部分范围'}
beforeEach(()=>{vi.spyOn(knowledgeApi,'searchProject').mockResolvedValue(search);vi.spyOn(knowledgeApi,'read').mockResolvedValue({kind:'CODE',sourceId:'code',name:'Main.java',path:'src/Main.java',sha256:'original',text:'class Main {}'});vi.spyOn(knowledgeApi,'database').mockResolvedValue({kind:'DATABASE',sourceId:'db',name:'表',path:'',sha256:'',schemas:['public'],columns:['name'],rows:[['value']]});vi.spyOn(knowledgeApi,'browse').mockResolvedValue({items:[],nextCursor:null,incomplete:false,detail:''});vi.spyOn(knowledgeApi,'git').mockResolvedValue({kind:'GIT',sourceId:'git',path:'',name:'Git',sha256:'',items:[]})})
afterEach(()=>{owners.splice(0).forEach(o=>o.retire(true));vi.restoreAllMocks()})
it('searches only selected READY sources with exact mode and appends pages/coverage',async()=>{const o=browser();o.filter('query',' 原句 ');o.filter('mode','PHRASE');await o.search();expect(knowledgeApi.searchProject).toHaveBeenCalledWith('p',{conversationId:undefined,sourceIds:'code',query:'原句',mode:'PHRASE',cursor:'',limit:20});await o.search('next');expect(o.getSnapshot().results!.matches).toHaveLength(2);expect(o.getSnapshot().results!.coverage![0]!.limited).toBe(true);await o.match(search.matches[0]!);expect(knowledgeApi.read).toHaveBeenCalledWith('p','code',expect.objectContaining({path:'src/Main.java',expectedSha:'original',startLine:12}))})
it('changed query/project/closed panel invalidates deferred search without retired projection',async()=>{const p=deferred<KnowledgeSearch>();vi.mocked(knowledgeApi.searchProject).mockReturnValue(p.promise);const o=browser();o.filter('query','A');const read=o.search();o.filter('query','B');o.pauseReads();p.resolve(search);await read;expect(o.getSnapshot().results).toBeUndefined();expect(o.getSnapshot().busy).toBe(false)})
it('refuses empty selected scope and never falls back to all project sources',async()=>{const o=browser();o.configure('p',undefined,[sourceFixture],[]);o.filter('query','term');await o.search();expect(knowledgeApi.searchProject).not.toHaveBeenCalled();expect(o.getSnapshot().error).toContain('勾选')})
it('conversation scope freezes sources and database result uses original schema/table/offset',async()=>{const db={...sourceFixture,id:'db',kind:'DATABASE' as const};const o=browser();o.configure('p','conversation',[db],[]);await o.match({sourceId:'db',kind:'DATABASE',name:'table',path:'',schema:'public',table:'orders',column:'name',sha256:'',snippet:'',read:{tool:'read',arguments:{offset:40}}});expect(knowledgeApi.database).toHaveBeenCalledWith('p','db',expect.objectContaining({conversationId:'conversation',schema:'public',table:'orders',kind:'columns',offset:40}));expect(o.getSnapshot().content!.rows).toEqual([['value']]);await o.match({sourceId:'db',kind:'DATABASE',name:'table',path:'',schema:'public',table:'orders',sha256:'',snippet:''});expect(knowledgeApi.database).toHaveBeenLastCalledWith('p','db',expect.objectContaining({kind:'tables'}))})
it('document reads preserve parsed section/textOffset/hash rather than invented filesystem identity',async()=>{const doc={...sourceFixture,id:'doc',kind:'UPLOAD' as const},o=browser();o.configure('p',undefined,[doc],['doc']);await o.match({sourceId:'doc',kind:'DOCUMENT',name:'需求',path:'requirements.md',section:2,startLine:31,sha256:'frozen',snippet:'',read:{tool:'read',arguments:{textOffset:400}}});expect(knowledgeApi.read).toHaveBeenCalledWith('p','doc',expect.objectContaining({section:2,startLine:31,expectedSha:'frozen',textOffset:400}))})
it('git filters and commit pagination use readonly documented tools and source id',async()=>{const git={...sourceFixture,id:'git',kind:'GIT' as const},o=browser();o.configure('p','conversation',[git],[]);await o.browse(git);o.setField('author','author');o.setField('gitQuery','fix');await o.git();await o.git('read_knowledge_git_commit','sha','',30);expect(knowledgeApi.git).toHaveBeenLastCalledWith('p','git',{conversationId:'conversation',tool:'read_knowledge_git_commit',author:undefined,query:undefined,commit:'sha',cursor:'',startLine:30})})
