import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest'
import { webcrypto } from 'node:crypto'
import { api,ApiError } from '@/api/client'
import { knowledgeApi } from '@/api/knowledge'
import { defaultSettings } from '@/pages/w2/core/settingsController'
import { deferred } from '@/pages/w2/core/coreTestHelpers'
import { createKnowledgeController } from './controller'
import { conversationFixture,messageFixture,questionFixture,sourceFixture } from './fixtures'
import type { KnowledgeConversation } from '@/types/domain'
const owners:ReturnType<typeof createKnowledgeController>[]=[]
const streams:{close:ReturnType<typeof vi.fn>;onmessage:any;onopen:any;onerror:any}[]=[]
function owner(id='conversation'){const o=createKnowledgeController({conversationId:id});owners.push(o);return o}
beforeEach(()=>{
  sessionStorage.clear();vi.useFakeTimers();vi.stubGlobal('crypto',webcrypto);streams.length=0
  vi.spyOn(api,'getProjects').mockResolvedValue([{id:'p',name:'项目',rootPath:'/project',status:'READY',updatedAt:'now',taskCount:0,openDesignerSessionCount:0}]);vi.spyOn(api,'getSettings').mockResolvedValue({...defaultSettings(),openCode:{...defaultSettings().openCode,provider:'deepseek',model:'shared-model',mode:'managed'}});vi.spyOn(api,'getSettingsModels').mockResolvedValue([])
  vi.spyOn(knowledgeApi,'get').mockImplementation(async id=>conversationFixture(id));vi.spyOn(knowledgeApi,'messages').mockResolvedValue({items:[],facets:{}});vi.spyOn(knowledgeApi,'updates').mockResolvedValue({items:[],facets:{}});vi.spyOn(knowledgeApi,'sources').mockResolvedValue({items:[sourceFixture],facets:{}});vi.spyOn(knowledgeApi,'receipt').mockResolvedValue({accepted:false});vi.spyOn(knowledgeApi,'send').mockResolvedValue({} as never)
  vi.spyOn(knowledgeApi,'create').mockImplementation(async input=>({...conversationFixture(input.id),model:input.model}));vi.spyOn(knowledgeApi,'events').mockImplementation(()=>{const s={close:vi.fn(),onmessage:null,onopen:null,onerror:null};streams.push(s);return s as unknown as EventSource})
})
afterEach(()=>{owners.splice(0).forEach(o=>o.retire(true));vi.restoreAllMocks();vi.unstubAllGlobals();vi.useRealTimers();sessionStorage.clear()})
describe('single knowledge command/read owner',()=>{
  it('foreign fulfilled creation receipt cannot read/send to a different conversation',async()=>{vi.mocked(knowledgeApi.create).mockResolvedValue(conversationFixture('foreign'));const o=owner('');await o.initialize();o.editText('原问题');await o.send();expect.soft(knowledgeApi.send).not.toHaveBeenCalled();expect.soft(knowledgeApi.get).not.toHaveBeenCalledWith('foreign');expect.soft(o.getSnapshot().conversation).toBeNull();expect.soft(o.getSnapshot().mutation.phase).toBe('ACCEPTED_READBACK');expect.soft(o.canLeave().kind).toBe('BLOCK')})
  it('foreign fulfilled stop receipt cannot replace or refresh a different conversation',async()=>{vi.mocked(knowledgeApi.get).mockResolvedValue({...conversationFixture(),state:'RUNNING'});vi.spyOn(knowledgeApi,'stop').mockResolvedValue(conversationFixture('foreign'));const o=owner();await o.initialize();await o.stop();expect.soft(o.getSnapshot().conversation?.id).toBe('conversation');expect.soft(knowledgeApi.get).not.toHaveBeenCalledWith('foreign');expect.soft(o.getSnapshot().mutation.phase).toBe('ACCEPTED_READBACK');expect.soft(o.canLeave().kind).toBe('BLOCK')})
  it('throwing SSE close still clears its pending 180ms timer and all interval resources',async()=>{const o=createKnowledgeController({conversationId:'conversation',storage:null});owners.push(o);const detach=o.attachView();await o.initialize();streams[0]!.onmessage();streams[0]!.close.mockImplementation(()=>{throw new Error('close failed')});expect(()=>detach()).toThrow();expect(vi.getTimerCount()).toBe(0)})
  it('uses configured provider/model without waiting for other catalogue choices',async()=>{const pending=deferred<any[]>();vi.mocked(api.getSettingsModels).mockReturnValue(pending.promise);const o=owner('');await o.initialize();o.editText('问题');expect(o.getSnapshot().model).toBe('deepseek/shared-model');expect(o.canSend()).toBe(true);await o.send();expect(knowledgeApi.create).toHaveBeenCalledWith(expect.objectContaining({model:'deepseek/shared-model',sourceIds:['code'],projectId:'p'}));expect(knowledgeApi.send).toHaveBeenCalledTimes(1);pending.resolve([])})
  it('a lost message response freezes original text/key and explicit retry uses exactly those fields',async()=>{vi.mocked(knowledgeApi.send).mockRejectedValueOnce(new Error('lost'));const o=owner();await o.initialize();o.editText('原问题');expect(await o.send()).toBe(false);const first=vi.mocked(knowledgeApi.send).mock.calls[0];expect(o.canLeave().kind).toBe('BLOCK');expect(o.editText('新问题')).toBe(false);expect(await o.send()).toBe(false);await o.retryOriginal();expect(vi.mocked(knowledgeApi.send).mock.calls[1]).toEqual(first);expect(o.getSnapshot().text).toBe('');expect(o.canLeave().kind).toBe('ALLOW')})
  it('restored unknown message never POSTs on mount, and read failure preserves identity and BLOCK',async()=>{sessionStorage.setItem('loopper.knowledge.pending.conversation',JSON.stringify({key:'original-key',text:'原问题'}));vi.mocked(knowledgeApi.receipt).mockRejectedValueOnce(new Error('read lost'));const o=owner();await o.initialize();expect(o.getSnapshot().text).toBe('原问题');expect(o.canLeave().kind).toBe('BLOCK');expect(knowledgeApi.send).not.toHaveBeenCalled();await o.retryOriginal();expect(knowledgeApi.send).toHaveBeenCalledWith('conversation','original-key','原问题')})
  it('restored acknowledged message permits a new explicit question with a new key',async()=>{sessionStorage.setItem('loopper.knowledge.pending.conversation',JSON.stringify({key:'old',text:'原问题'}));vi.mocked(knowledgeApi.receipt).mockResolvedValue({accepted:true});const o=owner();await o.initialize();o.editText('新问题');await o.send();expect(vi.mocked(knowledgeApi.send).mock.calls[0]![1]).not.toBe('old');expect(sessionStorage.getItem('loopper.knowledge.pending.conversation')).toBeNull()})
  it('accepted send with failed readback retries only GET, keeps draft and original operation',async()=>{const o=owner();await o.initialize();vi.mocked(knowledgeApi.get).mockRejectedValueOnce(new Error('read failed'));o.editText('原问题');await o.send();expect(o.getSnapshot().mutation.phase).toBe('ACCEPTED_READBACK');expect(o.getSnapshot().text).toBe('原问题');await o.retryOriginal();expect(knowledgeApi.send).toHaveBeenCalledTimes(1);expect(o.getSnapshot().text).toBe('')})
  it('unknown conversation create uses actual client-id lookup, never a second keyless POST',async()=>{vi.mocked(knowledgeApi.create).mockRejectedValue(new Error('lost'));const o=owner('');await o.initialize();o.editText('问题');await o.send();const input=vi.mocked(knowledgeApi.create).mock.calls[0]![0];vi.mocked(knowledgeApi.get).mockRejectedValueOnce(new ApiError('not found',404));await o.recover();expect(o.canLeave().kind).toBe('BLOCK');expect(knowledgeApi.create).toHaveBeenCalledTimes(1);await o.recover();expect(knowledgeApi.get).toHaveBeenCalledWith(input.id);expect(o.getSnapshot().conversation?.id).toBe(input.id);expect(knowledgeApi.create).toHaveBeenCalledTimes(1)})
  it('late conversation A cannot replace B after a safe route change',async()=>{const delayed=deferred<KnowledgeConversation>();vi.mocked(knowledgeApi.get).mockReturnValueOnce(delayed.promise);const o=owner(),a=o.load('A');await o.load('B');delayed.resolve(conversationFixture('A'));await a;expect(o.getSnapshot().conversation?.id).toBe('B')})
  it('late mutation receipt after forced retirement never refreshes or projects into a new owner',async()=>{const delayed=deferred<any>();vi.mocked(knowledgeApi.send).mockReturnValueOnce(delayed.promise);const o=owner();await o.initialize();o.editText('A');const send=o.send(),identity=o.originalIdentity();o.retire(true);const next=owner('B');await next.initialize();const reads=vi.mocked(knowledgeApi.get).mock.calls.length;delayed.resolve({});await send;expect(knowledgeApi.get).toHaveBeenCalledTimes(reads);expect(next.getSnapshot().conversation?.id).toBe('B');expect(o.originalIdentity()).toEqual(identity)})
  it('SSE one-owner leases coalesce bursts and close exactly once immediately on detach',async()=>{const o=owner();const detach=o.attachView();await o.initialize();expect(streams).toHaveLength(1);const second=o.attachView();streams[0]!.onmessage();streams[0]!.onmessage();await vi.advanceTimersByTimeAsync(180);expect(knowledgeApi.updates).toHaveBeenCalledTimes(1);detach();expect(streams[0]!.close).not.toHaveBeenCalled();second();expect(streams[0]!.close).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);const replay=o.attachView();expect(streams).toHaveLength(2);replay();expect(streams[1]!.close).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0)})
  it('incremental REST merges history, repeats last ordinal safely, and never shrinks token usage',async()=>{vi.mocked(knowledgeApi.messages).mockResolvedValue({items:[messageFixture(1),messageFixture(9,'旧回答')],facets:{},nextCursor:'older'});vi.mocked(knowledgeApi.get).mockResolvedValue({...conversationFixture(),usage:{inputTokens:80,outputTokens:40}});const o=owner();await o.initialize();vi.mocked(knowledgeApi.get).mockResolvedValue({...conversationFixture(),usage:{inputTokens:10,outputTokens:null}});vi.mocked(knowledgeApi.updates).mockResolvedValue({items:[messageFixture(9,'新回答')],facets:{}});await o.refresh();expect(knowledgeApi.updates).toHaveBeenCalledWith('conversation',8,'');expect(o.getSnapshot().messages.map(m=>m.ordinal)).toEqual([1,9]);expect(o.getSnapshot().messages[1]!.answer).toBe('新回答');expect(o.getSnapshot().conversation!.usage).toEqual({inputTokens:80,outputTokens:40});expect(o.getSnapshot().nextCursor).toBe('older')})
  it('keyless upload UNKNOWN retains original File but offers no invented lookup or write retry',async()=>{vi.spyOn(knowledgeApi,'upload').mockRejectedValue(new Error('lost'));const o=owner('');await o.initialize();const f=new File(['文档'],'a.md');await o.sourceMutation('upload',[f]);expect((o.originalIdentity() as any).files[0]).toBe(f);expect(o.getSnapshot().mutation.canRetry).toBe(false);expect(o.getSnapshot().mutation.canRead).toBe(false);await o.retryOriginal();await o.recover();expect(knowledgeApi.upload).toHaveBeenCalledTimes(1);expect(o.canLeave().kind).toBe('BLOCK')})
  it('source write accepted but failed source read is readonly recoverable',async()=>{vi.spyOn(knowledgeApi,'directory').mockResolvedValue({...sourceFixture,kind:'DIRECTORY'});const o=owner('');await o.initialize();vi.mocked(knowledgeApi.sources).mockRejectedValueOnce(new Error('read'));await o.sourceMutation('directory','/docs');expect(o.getSnapshot().mutation.phase).toBe('ACCEPTED_READBACK');await o.recover();expect(knowledgeApi.directory).toHaveBeenCalledTimes(1);expect(o.getSnapshot().mutation.phase).toBe('SETTLED')})
  it('question unknown freezes exact answers/version/key across explicit retry',async()=>{vi.mocked(knowledgeApi.messages).mockResolvedValue({items:[{...messageFixture(),questions:[questionFixture]}],facets:{}});const reply=vi.spyOn(knowledgeApi,'reply').mockRejectedValueOnce(new Error('lost')).mockResolvedValue({...questionFixture,state:'ANSWERED'});const o=owner();await o.initialize();o.editQuestion(questionFixture,{choices:[['代码']],custom:['附加']});await o.reply(questionFixture);const first=reply.mock.calls[0]![2];expect(first.answers).toEqual([['代码','附加']]);expect(first.version).toBe(7);expect(o.canLeave().kind).toBe('BLOCK');await o.retryOriginal();expect(reply.mock.calls[1]![2]).toEqual(first)})
  it('restored prepared answer is visibly UNKNOWN, readonly lookup preserves identity until accepted',async()=>{sessionStorage.setItem('loopper.knowledge.reply.conversation.question',JSON.stringify({idempotencyKey:'question-key',version:7,answers:[['文档']]}));vi.mocked(knowledgeApi.messages).mockResolvedValue({items:[{...messageFixture(),questions:[questionFixture]}],facets:{}});const reply=vi.spyOn(knowledgeApi,'reply').mockResolvedValue({...questionFixture,state:'ANSWERED'});const o=owner();await o.initialize();expect(o.canLeave().kind).toBe('BLOCK');expect(o.getSnapshot().mutation.phase).toBe('UNKNOWN');expect(reply).not.toHaveBeenCalled();await o.retryOriginal();expect(reply).toHaveBeenCalledWith('conversation','question',{idempotencyKey:'question-key',version:7,answers:[['文档']]})})
  it('ordinary unsent question draft confirms leave, including optional storage failure',async()=>{const o=owner();await o.initialize();o.editText('未提交');expect(o.canLeave().kind).toBe('CONFIRM_DISCARD');expect(knowledgeApi.send).not.toHaveBeenCalled()})
})
