import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react'
import {StrictMode} from 'react'
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest'
import {webcrypto} from 'node:crypto'
import {api} from '@/api/client'
import {knowledgeApi} from '@/api/knowledge'
import {semanticName} from '@/foundation/semanticRegistry'
import {coreFixture,coreFrame,setupCoreDom,deferred} from '@/pages/w2/core/coreTestHelpers'
import {defaultSettings} from '@/pages/w2/core/settingsController'
import {KnowledgePage} from './KnowledgePage'
import {KnowledgeActivity} from './Activity'
import {KnowledgeEvidence} from './Evidence'
import {conversationFixture,messageFixture,questionFixture,sourceFixture} from './fixtures'
import {skins} from '@/themes/registry'
import type {AvailableModel,KnowledgeMessage} from '@/types/domain'
const fixtures:ReturnType<typeof coreFixture>[]=[]
const streams:{close:ReturnType<typeof vi.fn>;onmessage:any;onopen:any;onerror:any}[]=[]
const model=(provider:string,name:string):AvailableModel=>({id:`${provider}/${name}`,provider,model:name,label:`${provider} ${name}`})
function page(id=''){const f=coreFixture();f.props.route={path:id?`/knowledge/${id}`:'/knowledge',fullPath:id?`/knowledge/${id}`:'/knowledge',params:id?{conversationId:id}:{},query:{}};fixtures.push(f);return {f,view:render(coreFrame(<KnowledgePage {...f.props}/>))}}
const button=(key:Parameters<typeof semanticName>[0],target?:string)=>screen.getByRole('button',{name:semanticName(key,target)})
beforeEach(()=>{setupCoreDom();sessionStorage.clear();localStorage.clear();streams.length=0;vi.stubGlobal('crypto',webcrypto);vi.spyOn(api,'getProjects').mockResolvedValue([{id:'p',name:'项目',rootPath:'/project',status:'READY',updatedAt:'now',taskCount:0,openDesignerSessionCount:0}]);vi.spyOn(api,'getSettings').mockResolvedValue({...defaultSettings(),openCode:{...defaultSettings().openCode,provider:'deepseek',model:'shared-model',mode:'managed'}});vi.spyOn(api,'getSettingsModels').mockResolvedValue([model('deepseek','shared-model'),model('other','shared-model')]);vi.spyOn(knowledgeApi,'get').mockImplementation(async id=>{const input=vi.mocked(knowledgeApi.create).mock.calls.find(call=>call[0].id===id)?.[0];return {...conversationFixture(id),...(input?{model:input.model,projectId:input.projectId}:{})}});vi.spyOn(knowledgeApi,'messages').mockResolvedValue({items:[],facets:{}});vi.spyOn(knowledgeApi,'updates').mockResolvedValue({items:[],facets:{}});vi.spyOn(knowledgeApi,'sources').mockResolvedValue({items:[sourceFixture],facets:{}});vi.spyOn(knowledgeApi,'create').mockImplementation(async input=>({...conversationFixture(input.id),model:input.model}));vi.spyOn(knowledgeApi,'send').mockResolvedValue(messageFixture());vi.spyOn(knowledgeApi,'receipt').mockResolvedValue({accepted:false});vi.spyOn(knowledgeApi,'events').mockImplementation(()=>{const s={close:vi.fn(),onmessage:null,onopen:null,onerror:null};streams.push(s);return s as unknown as EventSource})})
afterEach(()=>{cleanup();fixtures.splice(0).forEach(f=>f.dispose());vi.restoreAllMocks();vi.unstubAllGlobals();sessionStorage.clear()})
describe('real React knowledge page and retained owner',()=>{
  it('renders catalogue/default provider identity and sends exact selected model through one writer',async()=>{const {f}=page();await waitFor(()=>expect(screen.getByText('deepseek/shared-model · 全局')).toBeTruthy());fireEvent.click(button('knowledge.selectModel'));const select=await screen.findByLabelText('问答模型');expect((select as HTMLSelectElement).value).toBe('deepseek/shared-model');fireEvent.change(select,{target:{value:'other/shared-model'}});fireEvent.change(screen.getByLabelText('向项目提问'),{target:{value:'问题'}});fireEvent.click(button('knowledge.send'));await waitFor(()=>expect(knowledgeApi.send).toHaveBeenCalledTimes(1));expect(knowledgeApi.create).toHaveBeenCalledWith(expect.objectContaining({model:'other/shared-model',projectId:'p',sourceIds:['code']}));expect(f.props.navigation.go).toHaveBeenCalledWith(expect.stringMatching(/^\/knowledge\//),true,expect.any(Object))})
  it('pending catalogue does not disable default-model send or erase an early typed draft',async()=>{const pending=deferred<AvailableModel[]>();vi.mocked(api.getSettingsModels).mockReturnValue(pending.promise);page();fireEvent.change(screen.getByLabelText('向项目提问'),{target:{value:'读取前输入'}});await waitFor(()=>expect((button('knowledge.send') as HTMLButtonElement).disabled).toBe(false));expect((screen.getByLabelText('向项目提问') as HTMLTextAreaElement).value).toBe('读取前输入');fireEvent.click(button('knowledge.send'));await waitFor(()=>expect(knowledgeApi.create).toHaveBeenCalled());expect(vi.mocked(knowledgeApi.create).mock.calls[0]![0].model).toBe('deepseek/shared-model');await act(async()=>pending.resolve([]))})
  it('catalogue failure keeps global model usable and visible retry does not overwrite explicit choice',async()=>{vi.mocked(api.getSettingsModels).mockRejectedValue(new Error('offline'));page();await waitFor(()=>expect(screen.getByText('deepseek/shared-model · 全局')).toBeTruthy());fireEvent.click(button('knowledge.selectModel'));await screen.findByText('暂时无法读取其他模型，仍可使用全局默认模型。');vi.mocked(api.getSettingsModels).mockResolvedValue([model('deepseek','shared-model'),model('other','shared-model')]);fireEvent.click(button('ui.refresh','模型目录'));await waitFor(()=>expect(screen.getByRole('option',{name:'other shared-model'})).toBeTruthy());fireEvent.change(screen.getByLabelText('问答模型'),{target:{value:'other/shared-model'}});vi.mocked(api.getSettings).mockResolvedValue({...defaultSettings(),openCode:{...defaultSettings().openCode,provider:'new',model:'default',mode:'managed'}});fireEvent.click(button('ui.refresh','知识库'));await waitFor(()=>expect((screen.getByLabelText('问答模型') as HTMLSelectElement).value).toBe('other/shared-model'))})
  it('existing conversation freezes model and sources, reads stream once and preserves native history/project links',async()=>{const {view}=page('saved');await waitFor(()=>expect(streams).toHaveLength(1));expect(screen.queryByRole('button',{name:semanticName('knowledge.selectModel')})).toBeNull();expect(api.getSettingsModels).not.toHaveBeenCalled();expect((screen.getByLabelText('选择项目') as HTMLSelectElement).disabled).toBe(true);expect(screen.getByRole('link',{name:'历史对话'}).getAttribute('href')).toBe('/knowledge/history?project=p');expect(screen.getByRole('link',{name:'项目管理'}).getAttribute('href')).toBe('/projects?project=p');view.unmount();expect(streams[0]!.close).toHaveBeenCalledTimes(1)})
  it('real lost response keeps original composer disabled and route BLOCK while local panel close never cancels command',async()=>{vi.mocked(knowledgeApi.send).mockRejectedValueOnce(new Error('lost'));const {f}=page('saved');await waitFor(()=>expect(streams).toHaveLength(1));fireEvent.change(screen.getByLabelText('向项目提问'),{target:{value:'原问题'}});fireEvent.click(button('knowledge.send'));await screen.findByText(/结果尚未确认，原操作身份与输入已保留/);expect((screen.getByLabelText('向项目提问') as HTMLTextAreaElement).disabled).toBe(true);expect([...f.guards][0]!().kind).toBe('BLOCK');fireEvent.click(button('knowledge.openSources'));const panel=screen.getByRole('complementary',{name:'资料来源'});fireEvent.click(within(panel).getByRole('button',{name:semanticName('ui.close','资料来源')}));expect(knowledgeApi.send).toHaveBeenCalledTimes(1);fireEvent.click(button('receipt.retryOriginal'));await waitFor(()=>expect(knowledgeApi.send).toHaveBeenCalledTimes(2));expect(vi.mocked(knowledgeApi.send).mock.calls[1]).toEqual(vi.mocked(knowledgeApi.send).mock.calls[0])})
  it('actual question form restores custom/multiple draft and POST captures original answers/version exactly once',async()=>{vi.mocked(knowledgeApi.messages).mockResolvedValue({items:[{...messageFixture(),questions:[questionFixture]}],facets:{}});const reply=vi.spyOn(knowledgeApi,'reply').mockResolvedValue({...questionFixture,state:'ANSWERED',answers:[['代码','自定义']]});page('saved');await screen.findByRole('group',{name:'范围？'});fireEvent.click(screen.getByRole('checkbox',{name:'代码 当前实现'}));fireEvent.change(screen.getByLabelText('问题 1 的自定义回答'),{target:{value:'自定义'}});fireEvent.click(button('knowledge.reply'));await waitFor(()=>expect(reply).toHaveBeenCalledTimes(1));expect(reply.mock.calls[0]![2]).toEqual(expect.objectContaining({answers:[['代码','自定义']],version:7,idempotencyKey:expect.any(String)}));expect(knowledgeApi.send).not.toHaveBeenCalled()})
  it('source browser is read-only for existing conversations and source checkbox selection stays explicit on new ones',async()=>{page();await waitFor(()=>expect(screen.getByText('deepseek/shared-model · 全局')).toBeTruthy());fireEvent.click(button('knowledge.openSources'));const code=screen.getByRole('checkbox',{name:'使用项目代码'});expect((code as HTMLInputElement).checked).toBe(true);fireEvent.click(code);fireEvent.change(screen.getByLabelText('向项目提问'),{target:{value:'问题'}});expect((button('knowledge.send') as HTMLButtonElement).disabled).toBe(true);fireEvent.click(code);expect((button('knowledge.send') as HTMLButtonElement).disabled).toBe(false);expect(knowledgeApi.create).not.toHaveBeenCalled()})
  it('failed empty answer exposes retry draft with zero automatic POST; restored question UNKNOWN is locked',async()=>{vi.mocked(knowledgeApi.messages).mockResolvedValue({items:[{...messageFixture(),state:'FAILED',detail:'模型连接失败'}],facets:{}});page('saved');await screen.findByText('模型连接失败');fireEvent.click(button('knowledge.retryQuestion'));expect((screen.getByLabelText('向项目提问') as HTMLTextAreaElement).value).toBe('核心流程是什么？');expect(knowledgeApi.send).not.toHaveBeenCalled();expect(knowledgeApi.create).not.toHaveBeenCalled()})
  it('file links are view actions, absent images cannot load external content, and evidence closes locally',async()=>{vi.mocked(knowledgeApi.messages).mockResolvedValue({items:[messageFixture(1,'[当前代码](file:///project/Main.java#L2-L3) ![隐藏图](https://external.invalid/image.png)')],facets:{}});vi.spyOn(knowledgeApi,'file').mockResolvedValue({kind:'CODE',sourceId:'code',path:'/project/Main.java',name:'Main.java',sha256:'file-sha',text:'line2\nline3',startLine:2,endLine:3});page('saved');const link=await screen.findByRole('link',{name:'当前代码'});expect(link.getAttribute('href')).toBe('#knowledge-file-file%3A%2F%2F%2Fproject%2FMain.java%23L2-L3');fireEvent.click(link);await waitFor(()=>expect(knowledgeApi.file).toHaveBeenCalledWith('saved','/project/Main.java',2,3,0));const panel=screen.getByRole('complementary',{name:'文件预览'});expect(within(panel).getByText('Main.java')).toBeTruthy();expect(screen.queryByRole('img',{name:'隐藏图'})).toBeNull();fireEvent.click(within(panel).getByRole('button',{name:semanticName('ui.close','文件预览')}));expect(knowledgeApi.send).not.toHaveBeenCalled()})
  it('StrictMode replays release prior stream, single live owner restores zero late writes on route disposal',async()=>{const f=coreFixture();f.props.route={path:'/knowledge/saved',fullPath:'/knowledge/saved',params:{conversationId:'saved'},query:{}};fixtures.push(f);const view=render(coreFrame(<StrictMode><KnowledgePage {...f.props}/></StrictMode>));await waitFor(()=>expect(streams.filter(s=>!s.close.mock.calls.length)).toHaveLength(1));expect(knowledgeApi.send).not.toHaveBeenCalled();view.unmount();f.dispose();expect(streams.every(s=>s.close.mock.calls.length===1)).toBe(true)})
})
describe('React activity/evidence projection parity',()=>{
  it('code evidence with non-one start preserves absolute highlighted lines while Markdown uses relative lines',()=>{const view=render(coreFrame(<KnowledgeEvidence body={{kind:'DOCUMENT',sourceId:'doc',path:'a.md',name:'a.md',sha256:'sha',text:'first\nsecond\nthird',startLine:50,endLine:52}} focusRange={{unit:'L',first:51,last:51}} skin={skins[0]!}/>));expect(view.container.querySelector('.w3-code-line.evidence-highlight[data-line="51"] .w3-code-text')?.textContent).toBe('second');expect(view.container.querySelector('.w3-code-line[data-line="50"] .w3-code-number')?.textContent).toBe('50');fireEvent.click(button('knowledge.readingView'));expect(view.container.querySelector('.rich-document,.markdown-document,.w3-rich-document')).not.toBeNull()})
  for(const state of ['PREPARED','CREATING','SENDING','RUNNING'])it(`${state} empty active turn displays exact waiting feedback`,()=>{render(coreFrame(<KnowledgeActivity message={{...messageFixture(),state}} thinking="" answer="" skin={skins[0]!}/>));expect(screen.getByRole('status').textContent).toBe(state==='RUNNING'?'正在思考':state==='SENDING'?'正在发送问题':'正在准备回答')})
  for(const state of ['COMPLETED','FAILED','STOPPED','UNKNOWN'])it(`${state} never displays active waiting animation`,()=>{render(coreFrame(<KnowledgeActivity message={{...messageFixture(),state}} thinking="" answer="" skin={skins[0]!}/>));expect(screen.queryByRole('status')).toBeNull()})
  it('thinking and tool content remain user-expanded with only last 30 calls and terminal status',()=>{const message:KnowledgeMessage={...messageFixture(),state:'RUNNING',calls:Array.from({length:31},(_,i)=>({id:String(i),tool:'read_file',state:i===30?'RUNNING':'SUCCEEDED',detail:`调用${i}`}))};render(coreFrame(<KnowledgeActivity message={message} thinking="内部推理" answer="已有答案" skin={skins[0]!}/>));expect(screen.queryByRole('status')).toBeNull();const thought=screen.getByRole('region',{name:'思考'});fireEvent.click(within(thought).getByRole('button'));expect(thought.querySelector('p')?.textContent).toBe('内部推理');const tools=screen.getByRole('region',{name:'工具调用'});fireEvent.click(within(tools).getByRole('button'));expect(within(tools).getAllByRole('listitem')).toHaveLength(30);expect(within(tools).queryByText('调用0',{exact:true})).toBeNull()})
  it('database evidence preserves NULL/rows/range and safe raw result, document toggles actual readonly text and Markdown',()=>{render(coreFrame(<KnowledgeEvidence body={{kind:'DATABASE',sourceId:'db',path:'',name:'表结果',sha256:'hash',columns:['name','value'],rows:[['one',null],['two',2]]}} focusRange={{unit:'R',first:2,last:2}} skin={skins[0]!}/>));expect(screen.getByText('NULL')).toBeTruthy();expect(screen.getByText('two').closest('tr')!.className).toBe('is-highlighted');expect(screen.getByText('one').closest('tr')!.className).not.toBe('is-highlighted');fireEvent.click(button('knowledge.rawResult'));expect(screen.getByLabelText('数据库或 Git 读取结果')).toBeTruthy()})
})
