import { useEffect, useState } from 'react'
import { Alert, Input } from 'antd'
import { UiActionButton, UiConfirmDialog } from '@/foundation/components'
import { useOwnerSnapshot, useRetainedOwner } from '@/pages/w2/shared'
import type { W2PageProps } from '@/pages/w2/shared/types'
import { knowledgeMatchLabel, knowledgeSearchStateLabel, knowledgeStateLabel } from '@/utils/displayLabels'
import type { KnowledgeContent, KnowledgeSource } from '@/types/domain'
import type { KnowledgeController } from './controller'
import { createKnowledgeBrowser } from './browser'
import { KnowledgeEvidence } from './Evidence'

export function KnowledgeSourcesPanel({owner,props,open}:{owner:KnowledgeController;props:W2PageProps;open:boolean}) {
  const current=useOwnerSnapshot(owner),[browser]=useState(createKnowledgeBrowser),s=useOwnerSnapshot(browser)
  const [filter,setFilter]=useState('ALL'),[external,setExternal]=useState(''),[showExternal,setShowExternal]=useState(false),[removing,setRemoving]=useState<KnowledgeSource>()
  useRetainedOwner(props,browser,() => browser.retire(true))
  const sources=current.conversation?.sources || current.sources,project=current.conversation?.projectId || current.project
  useEffect(() => {browser.configure(project,current.conversation?.id,sources,current.selected)},[browser,project,current.conversation?.id,sources,current.selected])
  useEffect(() => {if (!open) browser.pauseReads()},[browser,open])
  const groups=[{label:'代码',type:'CODE',items:sources.filter(v => v.kind === 'CODE')},{label:'文档',type:'DOCUMENTS',items:sources.filter(v => ['DOCUMENTS','DIRECTORY','UPLOAD'].includes(v.kind))},{label:'Git',type:'GIT',items:sources.filter(v => v.kind === 'GIT')},{label:'数据库',type:'DATABASE',items:sources.filter(v => v.kind === 'DATABASE')}].filter(g => filter === 'ALL' || filter === g.type)
  const mutable=!current.conversation && !owner.locked(),disabled={kind:'disabled' as const,reason:'已有会话的资料范围已冻结，或原操作结果尚未确认。'}
  const commits=Array.isArray(s.commits?.items) ? s.commits!.items as Record<string,unknown>[] : Array.isArray(s.commits?.commits) ? s.commits!.commits as Record<string,unknown>[] : []
  function nextContent(body:KnowledgeContent) { if (!s.active) return; if (body.kind === 'DATABASE') void browser.database(s.active,s.schema,Number(body.nextOffset || 0)); else void browser.file(body.path ?? s.path,Number(body.nextSection ?? body.section ?? -1),Number(body.nextLine ?? body.startLine ?? 1),body.sha256,Number(body.nextOffset ?? 0),typeof body.nextTextOffset === 'number' ? body.nextTextOffset : undefined) }
  return <div className="knowledge-source-browser"><div className="knowledge-source-filters">{[{id:'ALL',label:'全部'},{id:'CODE',label:'代码'},{id:'DOCUMENTS',label:'文档'},{id:'GIT',label:'Git'},{id:'DATABASE',label:'数据库'}].map(g => <button type="button" key={g.id} aria-pressed={filter===g.id} onClick={() => setFilter(g.id)}>{g.label}</button>)}</div>
    <form className="knowledge-search" onSubmit={event => {event.preventDefault();void browser.search()}}><Input aria-label="来源搜索" maxLength={200} value={s.query} onChange={event => browser.filter('query',event.target.value)} placeholder="搜索字段、原句或关键词…"/><UiActionButton actionKey="knowledge.searchSources" busy={s.busy} availability={s.query.trim() ? {kind:'enabled'} : {kind:'disabled',reason:'请填写检索内容。'}} onAction={() => {void browser.search()}}/></form>
    <select aria-label="检索方式" value={s.mode} onChange={event => browser.filter('mode',event.target.value)}><option value="AUTO">自动匹配</option><option value="FIELD">字段命名</option><option value="PHRASE">原句</option><option value="EXACT">原词</option></select><select aria-label="检索范围" value={s.searchSource} onChange={event => browser.filter('searchSource',event.target.value)}><option value="">{current.conversation ? '本会话全部资料' : '全部已选资料'}</option>{browser.searchable().map(source => <option key={source.id} value={source.id}>{source.name}</option>)}</select>
    {s.error && <Alert role="alert" title={s.error} type="error"/>}{s.busy && <p role="status">正在读取…</p>}
    {!s.results && groups.map(group => <section key={group.type} className="knowledge-source-group"><h3>{group.label} <small>{group.items.length}</small></h3>{!group.items.length && <p>尚未绑定</p>}{group.items.map(source => <div className="knowledge-source-row" key={source.id}>
      {!current.conversation && <input type="checkbox" aria-label={`使用${source.name}`} checked={current.selected.includes(source.id)} disabled={source.state !== 'READY' || !mutable} onChange={event => owner.selectSources(event.target.checked ? [...current.selected,source.id] : current.selected.filter(id => id !== source.id))}/>}
      <button type="button" className="knowledge-source-title" disabled={s.busy || source.state !== 'READY'} aria-pressed={s.active?.id===source.id} onClick={() => {void browser.browse(source)}}>{source.name}<small>{knowledgeStateLabel(source.state)} · {source.detail}</small></button>
      {!current.conversation && ['DIRECTORY','UPLOAD'].includes(source.kind) && <details><summary aria-label="资料操作">资料操作</summary><UiActionButton actionKey="knowledge.refreshSource" target={source.name} availability={mutable ? {kind:'enabled'} : disabled} onAction={() => {void owner.sourceMutation('refresh',source)}}/><UiActionButton actionKey="knowledge.removeSource" target={source.name} variant="danger" availability={mutable ? {kind:'enabled'} : disabled} onAction={() => setRemoving(source)}/></details>}
      {source.state !== 'READY' && source.detail && <p role="status">{source.detail}</p>}
    </div>)}</section>)}
    {current.sourceCursor && <UiActionButton actionKey="ui.loadMore" target="资料来源" onAction={() => {void owner.loadSources(true)}}/>}
    {!current.conversation && <section><UiActionButton actionKey="knowledge.addSource" expanded={showExternal} availability={mutable ? {kind:'enabled'} : disabled} onAction={() => setShowExternal(!showExternal)}/>{showExternal && <><Input aria-label="外部资料目录" value={external} disabled={!mutable} onChange={event => setExternal(event.target.value)}/><UiActionButton actionKey="knowledge.addDirectory" availability={mutable && external.trim() ? {kind:'enabled'} : {kind:'disabled',reason:'请填写目录并先处理原操作。'}} onAction={() => {void owner.sourceMutation('directory',external)}}/><label>上传文档<input aria-label="上传文档" type="file" multiple disabled={!mutable} onChange={event => {const files=Array.from(event.target.files ?? []);event.target.value='';if (files.length) void owner.sourceMutation('upload',files)}}/></label></>}</section>}
    {s.results && <section aria-label="检索结果"><UiActionButton actionKey="nav.back" onAction={browser.backResults}/><p>{s.results.detail}</p>{s.results.incomplete && <p>结果未覆盖全部资料</p>}{s.results.limitations.map(v => <p key={v}>{v}</p>)}{s.results.coverage?.map(row => <p key={row.sourceId}>{row.name} · {knowledgeSearchStateLabel(row.state)} · 已查 {row.examined} · 匹配 {row.matched} {row.limitations.join('；')}</p>)}{s.results.matches.map((match,i) => <button type="button" key={`${match.sourceId}:${match.path}:${i}`} className="knowledge-search-match" onClick={() => {void browser.match(match)}}><strong>{match.name}</strong><span>{match.location || match.path}</span><small>{knowledgeMatchLabel(match.matchType || '')} {match.matchedTerm}</small><p>{match.snippet}</p></button>)}{s.results.nextCursor && <UiActionButton actionKey="ui.loadMore" target="检索结果" busy={s.busy} onAction={() => {void browser.search(s.results!.nextCursor!)}}/>}</section>}
    {s.active && <section aria-label="当前资料"><h3>{s.active.name}</h3><UiActionButton actionKey="nav.back" target="资料来源" onAction={browser.back}/>
      {s.active.kind === 'DATABASE' && <><select aria-label="数据库 Schema" value={s.schema} onChange={event => {browser.setField('schema',event.target.value);void browser.database(s.active!,event.target.value)}}><option value="">默认 Schema</option>{s.schemas.map(schema => <option key={schema}>{schema}</option>)}</select><Input aria-label="数据库表" value={s.table} onChange={event => browser.setField('table',event.target.value)}/><UiActionButton actionKey="ui.open" target="表结构" busy={s.busy} onAction={() => {void browser.database(s.active!)}}/></>}
      {s.active.kind === 'GIT' && <section aria-label="Git 提交查询"><Input aria-label="提交作者" value={s.author} onChange={event => browser.setField('author',event.target.value)}/><Input aria-label="提交搜索" value={s.gitQuery} onChange={event => browser.setField('gitQuery',event.target.value)}/><UiActionButton actionKey="knowledge.queryGit" busy={s.busy} onAction={() => {void browser.git()}}/>{commits.map((commit,i) => <button key={i} type="button" onClick={() => {void browser.git('read_knowledge_git_commit',String(commit.sha || commit.commit))}}>{String(commit.subject || commit.sha || commit.commit)} · {String(commit.author || '')}</button>)}{typeof s.commits?.nextCursor === 'string' && <UiActionButton actionKey="ui.loadMore" target="Git 提交" onAction={() => {void browser.git('search_knowledge_git_commits',undefined,String(s.commits!.nextCursor))}}/>}{s.commit && <><KnowledgeEvidence body={s.commit} skin={props.skin}/><UiActionButton actionKey="nav.back" target="提交列表" onAction={browser.backCommits}/>{Number(s.commit.nextLine)>0 && <UiActionButton actionKey="ui.next" target="提交内容" onAction={() => {void browser.git('read_knowledge_git_commit',String(s.commit!.sha || s.commit!.commit),'',Number(s.commit!.nextLine))}}/>}</>}</section>}
      {s.listing && <><p>{s.listing.detail}</p>{s.path && <UiActionButton actionKey="nav.back" target="上级目录" onAction={() => {void browser.browse(s.active!,s.path.split('/').slice(0,-1).join('/'))}}/>}{s.listing.items.map(item => <button type="button" key={item.path} onClick={() => {if (item.directory) void browser.browse(s.active!,item.path);else void browser.file(item.path)}}>{item.name} {item.directory ? '目录' : `${item.bytes} bytes`}</button>)}{s.listing.incomplete && <p>结果未覆盖全部资料</p>}{s.listing.nextCursor && <UiActionButton actionKey="ui.loadMore" target="目录" onAction={() => {void browser.browse(s.active!,s.path,s.listing!.nextCursor!)}}/>}</>}
      {s.content && <><KnowledgeEvidence body={s.content} skin={props.skin}/>{s.content.sections && <select aria-label="文档章节" value={s.content.section ?? -1} onChange={event => {void browser.file(s.content!.path,Number(event.target.value),1,s.content!.sha256)}}>{s.content.sections.map(section => <option key={section.section} value={section.section}>{section.title}</option>)}</select>}{(Number(s.content.nextLine)>0 || Number(s.content.nextSection)>=0 || Number(s.content.nextOffset)>0 || Number(s.content.nextTextOffset)>0) && <UiActionButton actionKey="ui.next" target="资料内容" busy={s.busy} onAction={() => nextContent(s.content!)}/>}</>}
    </section>}
    <UiConfirmDialog open={!!removing} title={`移除“${removing?.name || ''}”的资料绑定？`} confirmActionKey="knowledge.removeSource" policy={!mutable ? {kind:'block',reason:'原操作结果尚未确认。'} : {kind:'allow'}} onCancel={() => setRemoving(undefined)} onConfirm={() => {if (!removing || !mutable) return;void owner.sourceMutation('remove',removing);setRemoving(undefined)}}>原始文件和历史引用将保留。</UiConfirmDialog>
  </div>
}
