import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { api,ApiError } from '@/api/client'
import type { TaskDecision,RollingPackageDetail } from '@/types/domain'
import { createJudgeController } from './judge'
import { createDecisionController } from './decision'
import { createDirtyController } from './dirty'
import { createScopeController,parsePatch } from './scope'
import { createRollingController } from './rollingController'
import { createPanelOwner,panelState } from './owner'
import { judge,decision,dirty,approval,patch,workbench,frozen,reviewing,proposal,task,parentPort,flush,deferred } from './test-support'
type Owner={retire(forced?:boolean):unknown;attachView():()=>void;bindParent(port:ReturnType<typeof parentPort>):void}
let owners:Owner[]=[]
async function mount<T extends Owner>(owner:T){owners.push(owner);const parent=parentPort();owner.bindParent(parent);parent.registerChild(owner as T&{canLeave():ReturnType<ReturnType<typeof createJudgeController>['canLeave']>});owner.attachView();await flush();return owner}
beforeEach(()=>{
  vi.spyOn(api,'getJudgeApproval').mockResolvedValue(judge);vi.spyOn(api,'approveJudges').mockResolvedValue({...judge,available:false,approved:true})
  vi.spyOn(api,'getTaskDecision').mockResolvedValue(decision());vi.spyOn(api,'continueTaskDecision').mockResolvedValue(decision());vi.spyOn(api,'acceptTaskDecision').mockResolvedValue(decision());vi.spyOn(api,'cancelTaskDecision').mockResolvedValue({...decision(),taskState:'STOPPING'})
  vi.spyOn(api,'deriveTaskDecision').mockResolvedValue({taskId:'child',parentTaskId:'task',mode:'INHERIT_CHANGES',workspaceFingerprint:'frozen',writableSession:false});vi.spyOn(api,'auditTaskDecision').mockResolvedValue({taskId:'audit',parentTaskId:'task',mode:'VERIFY_ONLY',workspaceFingerprint:'frozen',writableSession:false})
  vi.spyOn(api,'getDirtyWorkspace').mockResolvedValue(dirty);vi.spyOn(api,'resolveDirtyWorkspace').mockResolvedValue({task:{...task(),status:'READY'},workspace:{...dirty,clean:true,files:[]}});vi.spyOn(api,'cancelDirtyWorkspace').mockResolvedValue({...task(),status:'CANCELLED'});vi.spyOn(api,'getTask').mockResolvedValue({...task(),status:'READY'})
  vi.spyOn(api,'getGitDiffScopeApproval').mockResolvedValue(approval);vi.spyOn(api,'getGitDiffScopeApprovalPreview').mockResolvedValue({path:'src/Main.java',changeType:'MODIFIED',patch,truncated:false});vi.spyOn(api,'resolveGitDiffScopeApproval').mockResolvedValue(task())
  vi.spyOn(api,'getRollingPackageWorkbench').mockResolvedValue(workbench);vi.spyOn(api,'getRollingPackageDetail').mockImplementation(async(_id,runId):Promise<RollingPackageDetail>=>({packageRun:runId===frozen.id?frozen:reviewing,objective:'接入真实接口',deliverablesJson:'[]',acceptanceIntentJson:'[]',designMarkdown:'# 当前设计',fact:runId===frozen.id?{id:'fact',packageRunId:frozen.id,checkpointId:'checkpoint',successfulAttemptId:'attempt',provenJson:'{"tree":"abc"}',acceptedContractJson:'{"designRevision":2}',navigationSummary:'仅用于定位',createdAt:'now'}:undefined}))
  for(const method of ['approveRollingPackageDesign','startRollingPackage','redesignRollingPackage','resumeRollingPackageDesign','retryRollingPackageCheckpoint','discussRollingPackage','resolveRollingPackageFailure'] as const)vi.spyOn(api,method).mockResolvedValue(undefined)
  vi.spyOn(api,'proposeRollingPlan').mockResolvedValue(proposal());vi.spyOn(api,'suggestRollingPlan').mockResolvedValue(proposal('GENERATING'));vi.spyOn(api,'addRollingCorrection').mockResolvedValue(proposal());vi.spyOn(api,'getRollingPlanRevisions').mockResolvedValue([proposal()]);vi.spyOn(api,'confirmRollingPlan').mockResolvedValue(proposal('ACTIVE'))
})
afterEach(()=>{owners.forEach(owner=>owner.retire(true));owners=[];vi.restoreAllMocks();vi.useRealTimers()})
it('judge confirmation freezes Task/Cycle/batch and preserves human source without replacing AI results',async()=>{const owner=await mount(createJudgeController('task'));owner.approve();expect(api.approveJudges).not.toHaveBeenCalled();vi.mocked(api.getJudgeApproval).mockResolvedValue({...judge,approved:true,available:false});await owner.acceptConfirmation();expect(api.approveJudges).toHaveBeenCalledWith('task',{expectedTaskVersion:7,cycleId:'cycle',expectedCycleVersion:3,reviewBatchId:'batch'});expect(owner.getSnapshot().approval?.approved).toBe(true)})
it('judge canceled or version-changed confirmation cannot write',async()=>{const owner=await mount(createJudgeController('task'));owner.approve();owner.cancelConfirmation();await owner.acceptConfirmation();owner.approve();vi.mocked(api.getJudgeApproval).mockResolvedValue({...judge,taskVersion:9});await owner.load();await owner.acceptConfirmation();expect(api.approveJudges).not.toHaveBeenCalled()})
it('judge accepted/read failure restores by GET with no second approval',async()=>{const owner=await mount(createJudgeController('task'));owner.approve();vi.mocked(api.getJudgeApproval).mockRejectedValueOnce(new Error('读取失败'));await owner.acceptConfirmation();expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK');vi.mocked(api.getJudgeApproval).mockResolvedValue({...judge,approved:true});await owner.recover();expect(api.approveJudges).toHaveBeenCalledTimes(1);expect(owner.canLeave().kind).toBe('ALLOW')})
it.each(['CONTINUE_CURRENT_TASK','DERIVE_INHERIT_CHANGES','DERIVE_REWORK_ALL','READ_ONLY_AUDIT','ACCEPT_RESULT','CANCEL'] as const)('decision %s uses original CAS and rejects a retired confirmation',async action=>{const owner=await mount(createDecisionController('task'));owner.act(action);expect(owner.getSnapshot().confirmation).toBeDefined();owner.retire(true);await owner.acceptConfirmation();expect(api.continueTaskDecision).not.toHaveBeenCalled();expect(api.deriveTaskDecision).not.toHaveBeenCalled();expect(api.auditTaskDecision).not.toHaveBeenCalled();expect(api.acceptTaskDecision).not.toHaveBeenCalled();expect(api.cancelTaskDecision).not.toHaveBeenCalled()})
it('failure continuation sends unchanged original task/cycle versions',async()=>{const owner=await mount(createDecisionController('task'));owner.act('CONTINUE_CURRENT_TASK');await owner.acceptConfirmation();expect(api.continueTaskDecision).toHaveBeenCalledWith('task',{expectedTaskVersion:7,expectedCycleVersion:3,stageId:undefined,supplementalRequirement:undefined})})
it('success continuation requires stage and supplement; newer draft invalidates old confirmation',async()=>{vi.mocked(api.getTaskDecision).mockResolvedValue({...decision(),cycle:{...decision().cycle!,result:'SUCCEEDED'}});const owner=await mount(createDecisionController('task'));owner.act('CONTINUE_CURRENT_TASK');expect(owner.getSnapshot().error).toContain('填写补充要求');owner.edit({supplement:' 原已确认范围 '});owner.act('CONTINUE_CURRENT_TASK');owner.edit({supplement:'新范围'});await owner.acceptConfirmation();expect(api.continueTaskDecision).not.toHaveBeenCalled();owner.cancelConfirmation();owner.act('CONTINUE_CURRENT_TASK');await owner.acceptConfirmation();expect(api.continueTaskDecision).toHaveBeenCalledWith('task',{expectedTaskVersion:7,expectedCycleVersion:3,stageId:'stage',supplementalRequirement:'新范围'})})
it('unknown historical change count remains unknown and never invents ACCEPT capability',async()=>{vi.mocked(api.getTaskDecision).mockResolvedValue({...decision(),checkpoint:{...decision().checkpoint!,changedFileCount:-1},availableActions:['CANCEL']});const owner=await mount(createDecisionController('task'));owner.act('ACCEPT_RESULT');expect(api.acceptTaskDecision).not.toHaveBeenCalled();expect(owner.getSnapshot().confirmation).toBeUndefined();expect(owner.getSnapshot().decision?.checkpoint?.changedFileCount).toBe(-1)})
it('dedicated cancellation preserves STOPPING stop-proof message',async()=>{const owner=await mount(createDecisionController('task'));owner.act('CANCEL');await owner.acceptConfirmation();expect(api.cancelTaskDecision).toHaveBeenCalledWith('task',{expectedTaskVersion:7,expectedCycleVersion:3});expect(owner.getSnapshot().error).toContain('等待远端写入者停止确认')})
it('accepted child is stored with exact parent/mode and never rewritten after parent read failure',async()=>{const owner=await mount(createDecisionController('task')),parent=parentPort();parent.refresh=vi.fn().mockRejectedValueOnce(new Error('父读取失败')).mockResolvedValue(undefined);owner.bindParent(parent);owner.act('DERIVE_INHERIT_CHANGES');await owner.acceptConfirmation();expect(owner.getSnapshot().destination).toBe('/tasks/child');expect(owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK');expect(owner.prepareHandoff()?.destination).toBe('/tasks/child');await owner.recover();expect(api.deriveTaskDecision).toHaveBeenCalledTimes(1)})
it('decision ignores a retired load and does not emit child navigation from a late command',async()=>{const reading=deferred<TaskDecision>();vi.mocked(api.getTaskDecision).mockReturnValueOnce(reading.promise);const owner=await mount(createDecisionController('task'));owner.retire(true);const before=owner.getSnapshot();reading.resolve(decision('foreign'));await flush();expect(owner.getSnapshot()).toBe(before)})
it('dirty workspace validates every file and sends per-path actions plus commit message',async()=>{const owner=await mount(createDirtyController('task'));owner.resolve();expect(owner.getSnapshot().error).toContain('每个文件');owner.edit({actions:{'README.md':'COMMIT','notes.txt':'STASH'}});owner.resolve();await flush();expect(api.resolveDirtyWorkspace).toHaveBeenCalledWith('task',{snapshotId:'snapshot',resolutions:[{path:'README.md',action:'COMMIT'},{path:'notes.txt',action:'STASH'}],commitMessage:'chore: 保存任务开始前的本地改动'});expect(owner.getSnapshot().visible).toBe(false)})
it('dirty workspace requires a second destructive confirmation and invalidates it after a new draft',async()=>{const owner=await mount(createDirtyController('task'));owner.edit({actions:{'README.md':'REMOVE','notes.txt':'STASH'}});owner.resolve();expect(api.resolveDirtyWorkspace).not.toHaveBeenCalled();owner.edit({actions:{'README.md':'STASH','notes.txt':'STASH'}});await owner.acceptConfirmation();expect(api.resolveDirtyWorkspace).not.toHaveBeenCalled()})
it('dirty workspace cancel remains reachable when file read fails and never resolves files',async()=>{vi.mocked(api.getDirtyWorkspace).mockRejectedValue(new Error('列表不可达'));vi.mocked(api.getTask).mockResolvedValue({...task(),status:'CANCELLED'});const owner=await mount(createDirtyController('task'));owner.cancel();expect(api.cancelDirtyWorkspace).not.toHaveBeenCalled();await owner.acceptConfirmation();expect(api.cancelDirtyWorkspace).toHaveBeenCalledWith('task');expect(api.resolveDirtyWorkspace).not.toHaveBeenCalled()})
it('dirty unknown keeps original snapshot/body and blocks editing/new POST despite successful legal reads',async()=>{vi.mocked(api.resolveDirtyWorkspace).mockRejectedValue(new Error('未知'));const owner=await mount(createDirtyController('task'));owner.edit({actions:{'README.md':'STASH','notes.txt':'STASH'}});owner.resolve();await flush();const identity=owner.operationIdentity();expect(owner.edit({actions:{'README.md':'REMOVE'}})).toBe(false);await owner.recover();owner.resolve();await flush();expect(api.resolveDirtyWorkspace).toHaveBeenCalledTimes(1);expect(owner.operationIdentity()).toBe(identity);expect(owner.canLeave().kind).toBe('BLOCK')})
it('patch review shows original old/new line numbers and hash-bound decisions',async()=>{const owner=await mount(createScopeController('task'));expect(parsePatch(patch)).toEqual(expect.arrayContaining([expect.objectContaining({kind:'removed',oldLine:10,content:'-old value'}),expect.objectContaining({kind:'added',newLine:10,content:'+new value'})]));owner.submit();expect(api.resolveGitDiffScopeApproval).not.toHaveBeenCalled();owner.edit({decisions:{'src/Main.java':'ALLOW'}});owner.submit();await flush();expect(api.resolveGitDiffScopeApproval).toHaveBeenCalledWith('task','request',{expectedTaskVersion:7,decisions:[{path:'src/Main.java',action:'ALLOW',patchSha256:'patch-sha'}]})})
it('new patch request preserves draft but fails closed until explicit discard',async()=>{const owner=await mount(createScopeController('task'));owner.edit({decisions:{'src/Main.java':'ALLOW'}});vi.mocked(api.getGitDiffScopeApproval).mockResolvedValue({...approval,requestId:'changed',taskVersion:9});await owner.load();expect(owner.getSnapshot().stale).toBe(true);owner.submit();expect(api.resolveGitDiffScopeApproval).not.toHaveBeenCalled();owner.discard();expect(owner.getSnapshot().dirty).toBe(false)})
it('scope ignores a retired preview failure',async()=>{const owner=await mount(createScopeController('task'));const old=deferred<Awaited<ReturnType<typeof api.getGitDiffScopeApprovalPreview>>>();vi.mocked(api.getGitDiffScopeApprovalPreview).mockReturnValueOnce(old.promise);const pending=owner.preview('src/Main.java');owner.retire(true);const before=owner.getSnapshot();old.reject(new Error('旧差异失败'));await pending;expect(owner.getSnapshot()).toBe(before)})
it('rolling design approval and start remain separate capabilities and CAS endpoints',async()=>{const owner=await mount(createRollingController('task'));await owner.act('start');expect(api.startRollingPackage).not.toHaveBeenCalled();await owner.act('approve');expect(api.approveRollingPackageDesign).toHaveBeenCalledWith('task','reviewing',{expectedTaskVersion:8,expectedPackageVersion:3,expectedDiscussionRevision:5,expectedDesignRevision:6});vi.mocked(api.getRollingPackageWorkbench).mockResolvedValue({...workbench,packageCapabilities:{...workbench.packageCapabilities,canApproveDesign:false,canStartPackage:true}});await owner.load();await owner.act('start');expect(api.startRollingPackage).toHaveBeenCalledTimes(1)})
it('rolling latest workbench controls replan availability and resume despite stale parent task',async()=>{vi.mocked(api.getRollingPackageWorkbench).mockResolvedValue({...workbench,taskVersion:9,packageCapabilities:{...workbench.packageCapabilities,canReplanRemaining:false,canResumeDesign:true}});const owner=await mount(createRollingController('task'));await owner.propose('ai');expect(api.suggestRollingPlan).not.toHaveBeenCalled();await owner.act('resume');expect(api.resumeRollingPackageDesign).toHaveBeenCalledWith('task','reviewing',{expectedTaskVersion:9,expectedPackageVersion:3,expectedDiscussionRevision:5,expectedDesignRevision:6})})
it('rolling checkpoint retry and fact selection preserve three fact layers',async()=>{vi.mocked(api.getRollingPackageWorkbench).mockResolvedValue({...workbench,packages:[frozen,{...reviewing,waitingReasonCode:'PACKAGE_CHECKPOINT_BLOCKED'}],packageCapabilities:{...workbench.packageCapabilities,canRetryPackage:true}});const owner=await mount(createRollingController('task'));await owner.act('checkpoint');expect(api.retryRollingPackageCheckpoint).toHaveBeenCalledWith('task','reviewing',expect.objectContaining({expectedDiscussionRevision:5,expectedDesignRevision:6}));await owner.load('frozen');expect(owner.getSnapshot().detail?.fact?.provenJson).toBe('{"tree":"abc"}');expect(owner.getSnapshot().detail?.fact?.acceptedContractJson).toBe('{"designRevision":2}');expect(owner.getSnapshot().detail?.fact?.navigationSummary).toBe('仅用于定位')})
it('AI suggestion polls original durable proposal and requires explicit impact confirmation',async()=>{const owner=await mount(createRollingController('task'));await owner.propose('ai');expect(api.suggestRollingPlan).toHaveBeenCalledWith('task',{expectedTaskVersion:8,expectedPackageRunId:'reviewing',expectedPackageVersion:3,expectedDiscussionRevision:5,expectedDesignRevision:6});expect(api.getRollingPlanRevisions).toHaveBeenCalledWith('task');expect(api.confirmRollingPlan).not.toHaveBeenCalled();owner.confirmPlan();await owner.acceptConfirmation();expect(api.confirmRollingPlan).toHaveBeenCalledWith('task','proposal',expect.objectContaining({expectedProposalVersion:2}));expect(owner.getSnapshot().proposal).toBeUndefined()})
it('manual plan move/split/merge/add/delete retain source IDs dependencies and refs',async()=>{const owner=await mount(createRollingController('task'));owner.openReplan();expect(owner.getSnapshot().planDraft).toHaveLength(1);owner.editPlan(0,{requirementRefs:['REQ-1'],objective:'原目标'});owner.transformPlan('split',0);owner.transformPlan('merge',1);expect(owner.getSnapshot().planDraft[0]?.sourcePackageRunIds).toEqual(['reviewing']);expect(owner.getSnapshot().planDraft[0]?.requirementRefs).toEqual(['REQ-1']);owner.transformPlan('add');owner.transformPlan('up',1);owner.transformPlan('down',0);owner.transformPlan('delete',1);await owner.propose('manual');expect(api.proposeRollingPlan).toHaveBeenCalledWith('task',expect.objectContaining({expectedPackageRunId:'reviewing',packages:owner.getSnapshot().planDraft}));expect(api.confirmRollingPlan).not.toHaveBeenCalled()})
it('correction targets the selected frozen package and remains a preview before confirmation',async()=>{const owner=await mount(createRollingController('task'));await owner.load('frozen');owner.edit({correctionTitle:'修正',correctionObjective:'修正已冻结行为'});await owner.propose('correction');expect(api.addRollingCorrection).toHaveBeenCalledWith('task',expect.objectContaining({correctionOfPackageRunId:'frozen',expectedPackageVersion:4,expectedDiscussionRevision:1,expectedDesignRevision:2,title:'修正',objective:'修正已冻结行为'}));expect(api.confirmRollingPlan).not.toHaveBeenCalled()})
it('keyless rolling unknown only reads, retains original versions and cannot propose again',async()=>{vi.mocked(api.suggestRollingPlan).mockRejectedValue(new Error('UNKNOWN'));const owner=await mount(createRollingController('task'));await owner.propose('ai');const original=owner.operationIdentity();await owner.recover();await owner.propose('ai');expect(api.suggestRollingPlan).toHaveBeenCalledTimes(1);expect(api.confirmRollingPlan).not.toHaveBeenCalled();expect(owner.operationIdentity()).toBe(original);expect(owner.canLeave().kind).toBe('BLOCK')})
it('AI poll resources release immediately on root loss with no follow-up reads or automatic confirmation',async()=>{vi.useFakeTimers();vi.mocked(api.getRollingPlanRevisions).mockResolvedValue([proposal('GENERATING')]);const owner=await mount(createRollingController('task'));const creating=owner.propose('ai');await flush();expect(vi.getTimerCount()).toBe(1);expect(owner.getSnapshot().command.accepted).toBe(true);owner.retire(true);expect(vi.getTimerCount()).toBe(0);await creating;await vi.advanceTimersByTimeAsync(10000);expect(api.getRollingPlanRevisions).toHaveBeenCalledTimes(1);expect(api.confirmRollingPlan).not.toHaveBeenCalled()})
it('a sibling dirty guard blocks writes but the caller own dirty draft can submit',async()=>{const parent=parentPort(),first=await mount(createDirtyController('task')),second=await mount(createJudgeController('task'));parent.registerChild(first);parent.registerChild(second);first.bindParent(parent);second.bindParent(parent);first.edit({actions:{'README.md':'STASH','notes.txt':'STASH'}});second.approve();expect(second.getSnapshot().confirmation).toBeUndefined();first.resolve();await flush();expect(api.resolveDirtyWorkspace).toHaveBeenCalledTimes(1)})
it('forced-retired generic child cannot start a late explicit mutation',async()=>{const owner=createPanelOwner('probe','task',panelState());await mount(owner);owner.retire(true);const write=vi.fn(async()=>task());expect(await owner.execute({label:'probe',input:{endpoint:'/legal',method:'POST',body:{}},write,read:async()=>{}})).toBe(false);expect(write).not.toHaveBeenCalled()})
it('definite rejected input can be corrected while a 409 without original proof stays blocked',async()=>{const owner=await mount(createJudgeController('task'));vi.mocked(api.approveJudges).mockRejectedValueOnce(new ApiError('明确拒绝',400));owner.approve();await owner.acceptConfirmation();expect(owner.canLeave().kind).toBe('ALLOW');owner.approve();vi.mocked(api.approveJudges).mockRejectedValueOnce(new ApiError('原结果冲突未知',409));await owner.acceptConfirmation();expect(owner.canLeave().kind).toBe('BLOCK');expect(api.approveJudges).toHaveBeenCalledTimes(2)})
it('a rolling CAS conflict refreshes real state without unlocking or reposting the unknown original intent',async()=>{
  const owner=await mount(createRollingController('task')),parent=parentPort();owner.bindParent(parent);vi.spyOn(parent,'refresh').mockResolvedValue(undefined)
  vi.mocked(api.approveRollingPackageDesign).mockRejectedValueOnce(new ApiError('版本已变化',409))
  const before=vi.mocked(api.getRollingPackageWorkbench).mock.calls.length;await owner.act('approve')
  expect(api.getRollingPackageWorkbench).toHaveBeenCalledTimes(before+1);expect(parent.refresh).toHaveBeenCalledTimes(1);expect(owner.canLeave().kind).toBe('BLOCK');expect(owner.getSnapshot().error).toContain('工作包状态已刷新')
  await owner.act('approve');expect(api.approveRollingPackageDesign).toHaveBeenCalledTimes(1)
})
it('a retired rolling first read cannot query detail after its awaited workbench resolves',async()=>{
  const pending=deferred<typeof workbench>();vi.mocked(api.getRollingPackageWorkbench).mockReturnValue(pending.promise);const owner=await mount(createRollingController('task'));expect(api.getRollingPackageDetail).not.toHaveBeenCalled();owner.retire(true);const before=owner.getSnapshot();pending.resolve(workbench);await flush();expect(api.getRollingPackageDetail).not.toHaveBeenCalled();expect(owner.getSnapshot()).toBe(before)
})
it('a retired dirty UNKNOWN lookup cannot query Task after its awaited workspace resolves',async()=>{
  vi.mocked(api.resolveDirtyWorkspace).mockRejectedValue(new Error('unknown'));const owner=await mount(createDirtyController('task'));owner.edit({actions:{'README.md':'STASH','notes.txt':'STASH'}});owner.resolve();await flush();expect(owner.getSnapshot().command.phase).toBe('UNKNOWN');expect(api.getTask).not.toHaveBeenCalled()
  const pending=deferred<typeof dirty>();vi.mocked(api.getDirtyWorkspace).mockReturnValueOnce(pending.promise);const recovering=owner.recover();await flush();owner.retire(true);const before=owner.getSnapshot();pending.resolve(dirty);await recovering;expect(api.getTask).not.toHaveBeenCalled();expect(api.resolveDirtyWorkspace).toHaveBeenCalledTimes(1);expect(owner.getSnapshot()).toBe(before)
})
