import { StrictMode } from 'react'
import { act,cleanup,fireEvent,render,screen,within } from '@testing-library/react'
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { api } from '@/api/client'
import { semanticName } from '@/foundation/semanticRegistry'
import { FoundationProvider } from '@/foundation/provider'
import { skins } from '@/themes/registry'
import { TaskJudgeApprovalPanel,TaskDecisionPanel,DirtyWorkspaceDialog,GitDiffScopeApprovalDialog,RollingPackageWorkbench } from './index'
import { panelProps,task,judge,decision,dirty,approval,patch,workbench,reviewing,frozen,proposal,foundationDOM,flush,deferred } from './test-support'
import type { TaskPanelProps } from '../shared/types'
import type { ComponentType } from 'react'
let retire:(()=>void)[]=[]
async function settle(){await act(async()=>{await flush()})}
async function frame(Component:ComponentType<TaskPanelProps>,props=panelProps({...task(),status:Component===TaskJudgeApprovalPanel?'JUDGING':Component===GitDiffScopeApprovalDialog?'WAITING_INPUT':'AWAITING_DECISION'}),strict=false){const owners=new Map<object,()=>void>();props.page.lifecycle.retain=(owner,dispose)=>{if(!owners.has(owner))owners.set(owner,dispose)};const content=<FoundationProvider skin={props.page.skin} reducedMotion><Component {...props}/></FoundationProvider>;const view=render(strict?<StrictMode>{content}</StrictMode>:content);retire.push(()=>owners.forEach(dispose=>dispose()));await settle();return view}
const click=async(name:string,host:HTMLElement=document.body)=>{await act(async()=>{fireEvent.click(within(host).getByRole('button',{name}));await flush()})}
beforeEach(()=>{foundationDOM();vi.spyOn(api,'getJudgeApproval').mockResolvedValue(judge);vi.spyOn(api,'approveJudges').mockResolvedValue({...judge,approved:true,available:false});vi.spyOn(api,'getTaskDecision').mockResolvedValue(decision());vi.spyOn(api,'continueTaskDecision').mockResolvedValue(decision());vi.spyOn(api,'cancelTaskDecision').mockResolvedValue({...decision(),taskState:'STOPPING'});vi.spyOn(api,'getDirtyWorkspace').mockResolvedValue(dirty);vi.spyOn(api,'getTask').mockResolvedValue({...task(),status:'READY'});vi.spyOn(api,'resolveDirtyWorkspace').mockResolvedValue({task:{...task(),status:'READY'},workspace:{...dirty,clean:true,files:[]}});vi.spyOn(api,'cancelDirtyWorkspace').mockResolvedValue({...task(),status:'CANCELLED'});vi.spyOn(api,'getGitDiffScopeApproval').mockResolvedValue(approval);vi.spyOn(api,'getGitDiffScopeApprovalPreview').mockResolvedValue({path:'src/Main.java',changeType:'MODIFIED',patch,truncated:false});vi.spyOn(api,'resolveGitDiffScopeApproval').mockResolvedValue(task());vi.spyOn(api,'getRollingPackageWorkbench').mockResolvedValue(workbench);vi.spyOn(api,'getRollingPackageDetail').mockImplementation(async(_id,runId)=>({packageRun:runId===frozen.id?frozen:reviewing,objective:'接入真实接口',deliverablesJson:'[]',acceptanceIntentJson:'[]',designMarkdown:'# 当前设计',fact:runId===frozen.id?{id:'fact',packageRunId:frozen.id,checkpointId:'checkpoint',successfulAttemptId:'attempt',provenJson:'{"tree":"abc"}',acceptedContractJson:'{"designRevision":2}',navigationSummary:'仅用于定位',createdAt:'now'}:undefined}));vi.spyOn(api,'approveRollingPackageDesign').mockResolvedValue(undefined);vi.spyOn(api,'startRollingPackage').mockResolvedValue(undefined);vi.spyOn(api,'proposeRollingPlan').mockResolvedValue(proposal());vi.spyOn(api,'suggestRollingPlan').mockResolvedValue(proposal('GENERATING'));vi.spyOn(api,'getRollingPlanRevisions').mockResolvedValue([proposal()]);vi.spyOn(api,'confirmRollingPlan').mockResolvedValue(proposal('ACTIVE'))})
afterEach(()=>{cleanup();retire.forEach(dispose=>dispose());retire=[];vi.restoreAllMocks()})
it('actual judge panel confirms once, sends displayed generation and preserves accepted human label',async()=>{await frame(TaskJudgeApprovalPanel);expect(api.approveJudges).not.toHaveBeenCalled();await click(semanticName('judge.approve'));expect(api.approveJudges).not.toHaveBeenCalled();vi.mocked(api.getJudgeApproval).mockResolvedValue({...judge,approved:true,available:false});await click(semanticName('judge.approve'),screen.getByRole('dialog'));expect(api.approveJudges).toHaveBeenCalledWith('task',{expectedTaskVersion:7,cycleId:'cycle',expectedCycleVersion:3,reviewBatchId:'batch'});expect(screen.getByText(/已由人工认定通过/)).toBeTruthy()})
it('actual judge canceled confirmation never submits',async()=>{await frame(TaskJudgeApprovalPanel);await click(semanticName('judge.approve'));await click(semanticName('ui.stay'),screen.getByRole('dialog'));expect(api.approveJudges).not.toHaveBeenCalled()})
it('actual failure disposition exposes all safe available actions and submits original versions',async()=>{await frame(TaskDecisionPanel);expect(screen.getByText('第 2 轮 · 执行失败')).toBeTruthy();for(const key of ['decision.inherit','decision.rework','decision.audit','decision.accept','task.cancel'] as const)expect(screen.getByRole('button',{name:semanticName(key)})).toBeTruthy();await click(semanticName('decision.continue'));await click(semanticName('decision.continue'),screen.getByRole('dialog'));expect(api.continueTaskDecision).toHaveBeenCalledWith('task',{expectedTaskVersion:7,expectedCycleVersion:3,stageId:undefined,supplementalRequirement:undefined})})
it('actual successful continuation keeps supplement required and unknown file count truthful',async()=>{vi.mocked(api.getTaskDecision).mockResolvedValue({...decision(),cycle:{...decision().cycle!,result:'SUCCEEDED'},checkpoint:{...decision().checkpoint!,changedFileCount:-1},availableActions:['CONTINUE_CURRENT_TASK','CANCEL']});await frame(TaskDecisionPanel);expect(screen.getByText('冻结点已验证 · 变更数量未确认')).toBeTruthy();expect(screen.queryByRole('button',{name:semanticName('decision.accept')})).toBeNull();await click(semanticName('decision.continue'));expect(screen.getByRole('alert').textContent).toContain('填写补充要求');fireEvent.change(screen.getByLabelText('补充要求'),{target:{value:'优化公开接口'}});await click(semanticName('decision.continue'));await click(semanticName('decision.continue'),screen.getByRole('dialog'));expect(api.continueTaskDecision).toHaveBeenCalledWith('task',{expectedTaskVersion:7,expectedCycleVersion:3,stageId:'stage',supplementalRequirement:'优化公开接口'})})
it('actual cancellation uses dedicated frozen result endpoint and shows STOPPING proof boundary',async()=>{await frame(TaskDecisionPanel);await click(semanticName('task.cancel'));await click(semanticName('task.cancel'),screen.getByRole('dialog'));expect(api.cancelTaskDecision).toHaveBeenCalledWith('task',{expectedTaskVersion:7,expectedCycleVersion:3});expect(screen.getByRole('alert').textContent).toContain('等待远端写入者停止确认')})
it('actual workspace lists every file, requires per-file choice and never silently closes on Escape',async()=>{await frame(DirtyWorkspaceDialog,panelProps({...task(),status:'WAITING_INPUT',waitingReasonCode:'SOURCE_BRANCH_WORKSPACE_DIRTY'}));const dialog=screen.getByRole('dialog');expect(dialog.textContent).toContain('README.md');expect(dialog.textContent).toContain('notes.txt');fireEvent.keyDown(dialog,{key:'Escape'});await settle();expect(screen.getByRole('dialog')).toBeTruthy();fireEvent.change(screen.getByLabelText('处理方式 README.md'),{target:{value:'COMMIT'}});fireEvent.change(screen.getByLabelText('处理方式 notes.txt'),{target:{value:'STASH'}});await click(semanticName('workspace.resolve'),dialog);expect(api.resolveDirtyWorkspace).toHaveBeenCalledWith('task',{snapshotId:'snapshot',resolutions:[{path:'README.md',action:'COMMIT'},{path:'notes.txt',action:'STASH'}],commitMessage:'chore: 保存任务开始前的本地改动'})})
it('actual workspace list read failure still allows confirmed cancellation without resolving files',async()=>{vi.mocked(api.getDirtyWorkspace).mockRejectedValue(new Error('列表不可达'));vi.mocked(api.getTask).mockResolvedValue({...task(),status:'CANCELLED'});await frame(DirtyWorkspaceDialog,panelProps({...task(),status:'WAITING_INPUT',waitingReasonCode:'SOURCE_BRANCH_WORKSPACE_DIRTY'}));await click(semanticName('task.cancel'));expect(api.cancelDirtyWorkspace).not.toHaveBeenCalled();const dialogs=screen.getAllByRole('dialog');await click(semanticName('task.cancel'),dialogs[dialogs.length-1]!);expect(api.cancelDirtyWorkspace).toHaveBeenCalledWith('task');expect(api.resolveDirtyWorkspace).not.toHaveBeenCalled()})
it('actual scope review displays exact patch lines, counts and content-bound decision',async()=>{await frame(GitDiffScopeApprovalDialog);expect(screen.getByRole('complementary',{name:'审阅范围外修改'})).toBeTruthy();expect(document.querySelector('.diff-line.removed')?.textContent).toContain('10');expect(document.querySelector('.diff-line.removed')?.textContent).toContain('-old value');expect(document.querySelector('.diff-line.added')?.textContent).toContain('+new value');expect(document.querySelector('.diff-line.hunk')?.textContent).toContain('@@ -10,2 +10,2 @@');expect(screen.getByRole('button',{name:semanticName('scope.submit')}).hasAttribute('disabled')).toBe(true);await click(semanticName('scope.allow'));expect(screen.getByText('已接受 1 · 已拒绝 0 · 待决定 0')).toBeTruthy();await click(semanticName('scope.submit'));expect(api.resolveGitDiffScopeApproval).toHaveBeenCalledWith('task','request',{expectedTaskVersion:7,decisions:[{path:'src/Main.java',action:'ALLOW',patchSha256:'patch-sha'}]})})
it('actual scope close preserves reopen card and does not cancel task or lose decisions',async()=>{await frame(GitDiffScopeApprovalDialog);await click(semanticName('scope.allow'));await click(semanticName('ui.close','审阅范围外修改'));expect(screen.getByText('任务没有失败。请检查实际差异后决定是否接受。')).toBeTruthy();await click(semanticName('scope.review'));expect(screen.getByText('已接受 1 · 已拒绝 0 · 待决定 0')).toBeTruthy();expect(api.resolveGitDiffScopeApproval).not.toHaveBeenCalled();expect(api.cancelTaskDecision).not.toHaveBeenCalled()})
it('actual rolling workbench separates manual design/start and three persisted fact layers',async()=>{await frame(RollingPackageWorkbench,panelProps({...task(),executionMode:'ROLLING_PACKAGES',version:8,currentPackage:reviewing}),true);expect(screen.getByText('已冻结 1/2 包')).toBeTruthy();expect(screen.getByRole('button',{name:semanticName('rolling.approve')})).toBeTruthy();expect(screen.queryByRole('button',{name:semanticName('rolling.start')})).toBeNull();await click(semanticName('rolling.approve'));expect(api.approveRollingPackageDesign).toHaveBeenCalledTimes(1);await click('第 1 包 · 基础能力 · '+(screen.getByRole('button',{name:/第 1 包/}).textContent!.split(' · ')[2]||''));expect(screen.getByText('已证明')).toBeTruthy();expect(screen.getByText('已接受合同')).toBeTruthy();expect(screen.getByText('AI 导航摘要 · 非证据')).toBeTruthy();expect(screen.getByText('仅用于定位')).toBeTruthy()})
it('actual AI plan has no activation until its explicit server impact confirmation',async()=>{await frame(RollingPackageWorkbench,panelProps({...task(),executionMode:'ROLLING_PACKAGES',version:8,currentPackage:reviewing}));await click(semanticName('rolling.aiReplan'));expect(api.confirmRollingPlan).not.toHaveBeenCalled();expect(screen.getByRole('region',{name:'服务端计划影响'})).toBeTruthy();await click(semanticName('rolling.confirmPlan'));await click(semanticName('rolling.confirmPlan'),screen.getByRole('dialog'));expect(api.confirmRollingPlan).toHaveBeenCalledWith('task','proposal',expect.objectContaining({expectedProposalVersion:2}))})
it('actual manual editor exposes add/move/split/merge/delete and dirty close confirmation',async()=>{await frame(RollingPackageWorkbench,panelProps({...task(),executionMode:'ROLLING_PACKAGES',version:8,currentPackage:reviewing}));await click(semanticName('rolling.manualReplan'));expect(screen.getByLabelText('工作包编号 1')).toBeTruthy();expect(screen.getByLabelText('依赖工作包 1')).toBeTruthy();await click(semanticName('rolling.split','业务接入'));expect(screen.getByLabelText('工作包编号 2')).toBeTruthy();await click(semanticName('ui.close','调整未执行工作包'));expect(screen.getByRole('dialog')).toBeTruthy();expect(api.proposeRollingPlan).not.toHaveBeenCalled()})
it('actual pending/unknown confirmation cannot start twice or unlock after a skin projection',async()=>{const pending=deferred<ReturnType<typeof judgeResult>>();function judgeResult(){return {...judge,approved:true}}vi.mocked(api.approveJudges).mockReturnValueOnce(pending.promise);const props=panelProps({...task(),status:'JUDGING'}),view=await frame(TaskJudgeApprovalPanel,props);await click(semanticName('judge.approve'));await click(semanticName('judge.approve'),screen.getByRole('dialog'));expect(api.approveJudges).toHaveBeenCalledTimes(1);for(const skin of skins){view.rerender(<FoundationProvider skin={skin} reducedMotion><TaskJudgeApprovalPanel {...props} page={{...props.page,skin}}/></FoundationProvider>);await settle();expect(screen.getByRole('button',{name:semanticName('judge.approve')}).hasAttribute('disabled')).toBe(true)}pending.reject(new Error('原回执未知'));await settle();expect(screen.getByRole('alert').textContent).toContain('结果尚未确认');expect(api.approveJudges).toHaveBeenCalledTimes(1)})
it('permanently mounted child owners do not read or display unrelated RUNNING endpoints',async()=>{
  const All=(props:TaskPanelProps)=><><TaskJudgeApprovalPanel {...props}/><TaskDecisionPanel {...props}/><DirtyWorkspaceDialog {...props}/><GitDiffScopeApprovalDialog {...props}/><RollingPackageWorkbench {...props}/></>
  const props=panelProps({...task(),status:'RUNNING'}),view=await frame(All,props,true)
  for(const read of [api.getJudgeApproval,api.getTaskDecision,api.getDirtyWorkspace,api.getGitDiffScopeApproval,api.getRollingPackageWorkbench])expect(read).not.toHaveBeenCalled()
  expect(screen.queryByText('执行结束，等待你的确认')).toBeNull();expect(screen.queryByRole('dialog')).toBeNull()
  view.rerender(<FoundationProvider skin={props.page.skin} reducedMotion><All {...props} task={{...props.task,status:'WAITING_INPUT',waitingReasonCode:'SOURCE_BRANCH_WORKSPACE_DIRTY'}}/></FoundationProvider>);await settle()
  expect(api.getJudgeApproval).toHaveBeenCalled();expect(api.getDirtyWorkspace).toHaveBeenCalled();expect(api.getGitDiffScopeApproval).toHaveBeenCalled();expect(api.getTaskDecision).not.toHaveBeenCalled();expect(api.getRollingPackageWorkbench).not.toHaveBeenCalled()
})
it('a judge UNKNOWN owner remains visible with its identity when eligibility disappears',async()=>{
  vi.mocked(api.approveJudges).mockRejectedValue(new Error('unknown approval'))
  const props=panelProps({...task(),status:'JUDGING'}),view=await frame(TaskJudgeApprovalPanel,props)
  await click(semanticName('judge.approve'));await click(semanticName('judge.approve'),screen.getByRole('dialog'))
  const reads=vi.mocked(api.getJudgeApproval).mock.calls.length
  view.rerender(<FoundationProvider skin={props.page.skin} reducedMotion><TaskJudgeApprovalPanel {...props} task={{...props.task,status:'RUNNING',version:8}}/></FoundationProvider>);await settle()
  expect(screen.getByRole('region',{name:'人工认定'})).toBeTruthy();expect(screen.getByRole('button',{name:semanticName('judge.approve')}).hasAttribute('disabled')).toBe(true)
  expect(api.getJudgeApproval).toHaveBeenCalledTimes(reads);expect(api.approveJudges).toHaveBeenCalledTimes(1)
  expect(screen.getAllByRole('alert').some(item=>item.textContent?.includes('结果尚未确认'))).toBe(true)
})
