import { rollingPanelEligible } from './eligibility'
import { useLayoutEffect,useMemo } from 'react'
import { Input,Select } from 'antd'
import { UiActionButton,UiContextPanel } from '@/foundation/components'
import { RichDocument } from '@/pages/w3/shared/RichDocument'
import { ReadOnlyCode } from '@/pages/w3/shared/ReadOnlyCode'
import { displayLabel } from '@/utils/displayLabels'
import type { UiActionKey } from '@/foundation/semanticRegistry'
import type { TaskPanelProps } from '../shared/types'
import { useW4Owner,useProtectedOwner,closePolicy } from '../shared/parts'
import { createRollingController,pretty,type PackageAction } from './rollingController'
import { PanelNotice,ReadOriginal } from './parts'

const actionKeys:Record<PackageAction,UiActionKey>={approve:'rolling.approve',start:'rolling.start',redesign:'rolling.redesign',resume:'rolling.resume',checkpoint:'rolling.checkpoint',discuss:'rolling.discuss'}
export function RollingPackageWorkbench(props:TaskPanelProps){
  const candidate=useMemo(()=>createRollingController(props.task.id),[props.task.id]),owner=useProtectedOwner(candidate);const eligible=rollingPanelEligible(props.task);owner.setEnabled(eligible);owner.bindParent(props.parent);const state=useW4Owner(props.page,owner,props.parent),wb=state.workbench,run=owner.selected(),current=owner.current(),cap=current?wb?.packageCapabilities:undefined
  useLayoutEffect(()=>{void owner.load()},[owner,eligible,props.task.updatedAt]);if(!eligible&&!owner.locked()&&!state.dirty&&!state.error)return null
  const button=(action:PackageAction,allowed?:boolean)=>allowed&&<UiActionButton key={action} actionKey={actionKeys[action]} availability={owner.actionBlocked()?{kind:'disabled',reason:'原工作包操作尚未结清。'}:{kind:'enabled'}} onAction={()=>void owner.act(action)}/>
  return <section aria-label="逐包闭环" className="w4-rolling"><h2>已冻结 {wb?.frozenPackageCount||0}/{wb?.plannedPackageCount||0} 包</h2><p>计划 R{wb?.planRevision||1}</p><p>{wb?.workspacePolicy==='PINNED_DIRECT'?'Direct 模式：从首次执行开始到任务完成或取消，登记目录会持续由本任务占用；包间会复核目录是否漂移。':'Git 模式：每包事实冻结后释放登记目录租约；下一包执行时从已验证 Checkpoint 精确恢复。'}</p>
    {wb&&props.task.version!==undefined&&(props.task.version!==wb.taskVersion||props.task.currentPackage?.id!==wb.currentPackageRunId)&&<p role="status">工作包状态已更新，操作已按最新服务端状态刷新。</p>}
    <div className="w4-rolling-grid"><nav aria-label="工作包导航">{wb?.packages.map((pack,i)=><button key={pack.id} type="button" aria-current={pack.id===state.selectedId?'true':undefined} onClick={()=>void owner.load(pack.id)}>第 {i+1} 包 · {pack.title} · {displayLabel(pack.state)}</button>)}</nav><article>{run&&state.detail&&<><h3>{run.title}</h3><p>{displayLabel(run.state)}</p><p>{state.detail.objective}</p><p>设计 → 执行 → 事实冻结</p>{state.detail.designMarkdown?<RichDocument content={state.detail.designMarkdown} skin={props.page.skin} collapsible/>:<p>详细设计尚未生成{cap?.canResumeDesign?'，可检查并继续当前包设计。':'。'}</p>}
      {button('approve',cap?.canApproveDesign)}{button('start',cap?.canStartPackage)}{button('redesign',cap?.canRedesignPackage)}{button('resume',cap?.canResumeDesign)}{button('checkpoint',cap?.canRetryPackage&&run.waitingReasonCode==='PACKAGE_CHECKPOINT_BLOCKED')}
      {current&&run.waitingReasonCode==='PACKAGE_EXECUTION_FAILED'&&<><UiActionButton actionKey="rolling.failureContinue" availability={owner.actionBlocked()?{kind:'disabled',reason:'原操作尚未结清。'}:{kind:'enabled'}} onAction={()=>owner.failure('CONTINUE_CANDIDATE')}/><UiActionButton actionKey="rolling.failureRedesign" availability={owner.actionBlocked()?{kind:'disabled',reason:'原操作尚未结清。'}:{kind:'enabled'}} onAction={()=>owner.failure('REDESIGN_FROM_PREVIOUS')}/><UiActionButton actionKey="task.cancel" availability={owner.actionBlocked()||props.task.cancellationAvailable===false?{kind:'disabled',reason:'原操作尚未结清或服务端不允许取消。'}:{kind:'enabled'}} onAction={()=>owner.failure('ABANDON_TASK')}/></>}
      {cap?.canReplanRemaining&&<><UiActionButton actionKey="rolling.aiReplan" availability={owner.actionBlocked()?{kind:'disabled',reason:'请先恢复原计划。'}:{kind:'enabled'}} onAction={()=>void owner.propose('ai')}/><UiActionButton actionKey="rolling.manualReplan" availability={owner.actionBlocked()?{kind:'disabled',reason:'请先恢复原计划。'}:{kind:'enabled'}} onAction={owner.openReplan}/></>}
      {cap?.canDiscuss&&<><Input.TextArea aria-label="包级反馈" maxLength={12000} disabled={owner.actionBlocked()} value={state.feedback} onChange={event=>owner.edit({feedback:event.target.value})}/>{button('discuss',!!state.feedback.trim())}</>}{current&&!cap&&<p role="alert">服务端未返回完整能力字段，工作包操作已安全关闭。</p>}
    </>}</article>{state.detail&&<aside aria-label="工作包事实"><h3>已证明</h3><ReadOnlyCode content={pretty(state.detail.fact?.provenJson)} language="json"/><h3>已接受合同</h3><ReadOnlyCode content={pretty(state.detail.fact?.acceptedContractJson)} language="json"/><h3>AI 导航摘要 · 非证据</h3><p>{state.detail.fact?.navigationSummary||state.detail.handoffSummary||'尚未形成'}</p>{run?.state==='FACT_FROZEN'&&wb?.packageCapabilities?.canAddCorrectionPackage&&<UiActionButton actionKey="rolling.correction" availability={owner.actionBlocked()?{kind:'disabled',reason:'原操作尚未结清。'}:{kind:'enabled'}} onAction={()=>owner.patch({correctionOpen:true})}/>}</aside>}</div>
    <UiContextPanel title="调整未执行工作包" open={state.replanOpen} closePolicy={closePolicy(owner)} onClose={()=>owner.patch({replanOpen:false})} onConfirmClose={()=>{if(!owner.locked())owner.patch({replanOpen:false,dirty:false,planDraft:[],proposal:undefined})}}>
      <p>已冻结包不会被修改。下面只编辑剩余后缀；确认前先生成服务端影响预览。</p>{state.planDraft.map((pack,i)=><article key={i}><Input aria-label={`工作包编号 ${i+1}`} disabled={owner.actionBlocked()} value={pack.packageKey} onChange={event=>owner.editPlan(i,{packageKey:event.target.value})}/><Input aria-label={`工作包标题 ${i+1}`} disabled={owner.actionBlocked()} value={pack.title} onChange={event=>owner.editPlan(i,{title:event.target.value})}/><Input.TextArea aria-label={`工作包目标 ${i+1}`} disabled={owner.actionBlocked()} value={pack.objective} onChange={event=>owner.editPlan(i,{objective:event.target.value})}/><Select mode="tags" aria-label={`依赖工作包 ${i+1}`} disabled={owner.actionBlocked()} value={pack.dependencies} options={state.planDraft.filter(other=>other.packageKey!==pack.packageKey).map(other=>({value:other.packageKey,label:other.packageKey}))} onChange={dependencies=>owner.editPlan(i,{dependencies})}/>{(['up','down','split','merge','delete'] as const).map(action=><UiActionButton key={action} actionKey={action==='up'?'rolling.moveUp':action==='down'?'rolling.moveDown':action==='split'?'rolling.split':action==='merge'?'rolling.merge':'ui.delete'} target={pack.title} availability={owner.actionBlocked()||(action==='up'||action==='merge')&&i===0||action==='down'&&i===state.planDraft.length-1||action==='split'&&state.planDraft.length>=6?{kind:'disabled',reason:'当前工作包无法执行此操作。'}:{kind:'enabled'}} onAction={()=>owner.transformPlan(action,i)}/>)}</article>)}<UiActionButton actionKey="rolling.add" availability={owner.actionBlocked()?{kind:'disabled',reason:'请先恢复原计划。'}:{kind:'enabled'}} onAction={()=>owner.transformPlan('add')}/><UiActionButton actionKey="rolling.propose" availability={owner.actionBlocked()||!state.planDraft.length?{kind:'disabled',reason:'先保留有效后缀并核对原操作。'}:{kind:'enabled'}} onAction={()=>void owner.propose('manual')}/>
    </UiContextPanel>
    <UiContextPanel title="新增修正包" open={state.correctionOpen} closePolicy={closePolicy(owner)} onClose={()=>owner.patch({correctionOpen:false})} onConfirmClose={()=>{if(!owner.locked())owner.patch({correctionOpen:false,correctionTitle:'',correctionObjective:'',dirty:false})}}><p>修正包会追加，不会改写已冻结包。</p><Input aria-label="修正包标题" disabled={owner.actionBlocked()} value={state.correctionTitle} onChange={event=>owner.edit({correctionTitle:event.target.value})}/><Input.TextArea aria-label="修正目标" disabled={owner.actionBlocked()} value={state.correctionObjective} onChange={event=>owner.edit({correctionObjective:event.target.value})}/><UiActionButton actionKey="rolling.propose" availability={owner.actionBlocked()?{kind:'disabled',reason:'请先恢复原修正包。'}:{kind:'enabled'}} onAction={()=>void owner.propose('correction')}/></UiContextPanel>
    {state.proposal&&<section aria-label="服务端计划影响"><h3>服务端影响预览 · R{state.proposal.revision}</h3><ReadOnlyCode content={pretty(state.proposal.impactJson)} language="json"/><UiActionButton actionKey="rolling.confirmPlan" availability={owner.actionBlocked()||state.draftRevision!==state.proposalDraftRevision?{kind:'disabled',reason:'原预览已过期或操作尚未结清，请重新核对。'}:{kind:'enabled'}} onAction={owner.confirmPlan}/></section>}
    <ReadOriginal load={owner.load}/><PanelNotice state={state} owner={owner}/>
  </section>
}
