import { scopePanelEligible } from './eligibility'
import { useLayoutEffect,useMemo } from 'react'
import { api } from '@/api/client'
import type { GitDiffScopeApproval,GitDiffScopeDecisionAction,TaskDiffPreview } from '@/types/domain'
import { UiActionButton,UiContextPanel } from '@/foundation/components'
import type { TaskPanelProps } from '../shared/types'
import { useW4Owner,useProtectedOwner } from '../shared/parts'
import { createPanelOwner,panelState } from './owner'
import { PanelNotice } from './parts'

export function parsePatch(patch:string){let oldLine:number|undefined,newLine:number|undefined;return patch.split('\n').map(content=>{const hunk=content.match(/^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);if(hunk){oldLine=Number(hunk[1]);newLine=Number(hunk[2]);return {content,kind:'hunk'}}if(/^(diff |index |---|\+\+\+)/.test(content))return {content,kind:'header'};if(content.startsWith('-'))return {content,kind:'removed',oldLine:oldLine===undefined?undefined:oldLine++};if(content.startsWith('+'))return {content,kind:'added',newLine:newLine===undefined?undefined:newLine++};if(content.startsWith('\\ No newline'))return {content,kind:'context'};return {content,kind:'context',oldLine:oldLine===undefined?undefined:oldLine++,newLine:newLine===undefined?undefined:newLine++}})}
export function createScopeController(taskId:string){
  const owner=createPanelOwner('task-diff-scope',taskId,{...panelState(),approval:undefined as GitDiffScopeApproval|undefined,open:false,selectedPath:'',preview:undefined as TaskDiffPreview|undefined,previewLoading:false,previewError:'',decisions:{} as Record<string,GitDiffScopeDecisionAction>,stale:false})
  let autoOpened=''
  async function preview(path:string){const current=owner.getSnapshot().approval;if(!current?.files.some(file=>file.path===path)||!owner.active()||!owner.readsAllowed())return;const ticket=owner.ticket('preview');owner.patch({selectedPath:path,preview:undefined,previewLoading:true,previewError:''});try{const result=await api.getGitDiffScopeApprovalPreview(taskId,current.requestId,path);if(result.path!==path)throw new Error('差异回执与原文件路径不一致。');if(ticket.current()&&owner.getSnapshot().approval?.requestId===current.requestId)owner.patch({preview:result})}catch(cause){if(ticket.current())owner.patch({previewError:String(cause instanceof Error?cause.message:'无法加载本次文件差异')})}finally{if(ticket.current())owner.patch({previewLoading:false})}}
  async function load(){if(!owner.active()||!owner.readsAllowed())return;const ticket=owner.ticket('approval');owner.patch({loading:true});try{const approval=await api.getGitDiffScopeApproval(taskId);if(approval&&approval.taskId!==taskId)throw new Error('范围审批不属于当前任务。');if(!ticket.current())return;const state=owner.getSnapshot(),changed=state.approval?.requestId!==approval?.requestId;owner.patch({approval,open:approval&&autoOpened!==approval.requestId?true:state.open,stale:changed&&state.dirty,decisions:changed&&!state.dirty?{}:state.decisions});if(approval){autoOpened=approval.requestId;await preview(approval.files.some(file=>file.path===state.selectedPath)?state.selectedPath:approval.files[0]?.path||'')}}catch(cause){if(ticket.current())owner.error(cause)}finally{if(ticket.current())owner.patch({loading:false})}}
  function submit(){const state=owner.getSnapshot(),current=state.approval;if(!current||state.stale||!current.files.length||!current.files.every(file=>state.decisions[file.path]))return
    const body={expectedTaskVersion:current.taskVersion,decisions:current.files.map(file=>({path:file.path,action:state.decisions[file.path]!,patchSha256:file.patchSha256}))}
    void owner.execute({label:'范围审批',input:{endpoint:`/tasks/${taskId}/git-diff-scope-approval/${current.requestId}/resolve`,method:'POST',body},write:input=>api.resolveGitDiffScopeApproval(taskId,current.requestId,input),lookup:async()=>{await api.getGitDiffScopeApproval(taskId);return {kind:'UNCONFIRMED'}},read:async(result,context)=>{if(result.id!==taskId)throw new Error('审批回执不属于原任务。');const approval=await api.getGitDiffScopeApproval(taskId);if(approval&&approval.taskId!==taskId)throw new Error('审批读取不属于原任务。');await owner.refreshParent();context.apply(()=>owner.patch({approval,dirty:false,decisions:{},open:!!approval}))},clearDraft:true})
  }
  owner.setStart(()=>void load());return Object.assign(owner,{load,preview,submit,discard:()=>{if(!owner.locked())owner.patch({dirty:false,stale:false,decisions:{},draftRevision:owner.getSnapshot().draftRevision+1})}})
}
export function GitDiffScopeApprovalDialog(props:TaskPanelProps){
  const candidate=useMemo(()=>createScopeController(props.task.id),[props.task.id]),owner=useProtectedOwner(candidate);const eligible=scopePanelEligible(props.task);owner.setEnabled(eligible);owner.bindParent(props.parent);const state=useW4Owner(props.page,owner,props.parent)
  useLayoutEffect(()=>{void owner.load()},[owner,eligible,props.task.updatedAt]);if(!eligible&&!owner.locked()&&!state.dirty&&!state.error)return null
  const approval=state.approval,count=approval?.files.filter(file=>state.decisions[file.path]).length||0,allowed=approval?.files.filter(file=>state.decisions[file.path]==='ALLOW').length||0
  if(!approval&&!owner.locked()&&!state.dirty)return <PanelNotice state={state} owner={owner}/>
  return <section aria-label="范围外修改审批"><h2>{approval?.files.length||0} 个既有文件需要确认</h2><p>任务没有失败。请检查实际差异后决定是否接受。</p><UiActionButton actionKey="scope.review" onAction={()=>owner.patch({open:true})}/>
    <UiContextPanel open={state.open} title="审阅范围外修改" closePolicy={owner.locked()?{kind:'block',reason:'原审批结果未确认，请先恢复原读取。'}:{kind:'allow'}} onClose={()=>owner.patch({open:false})}>
      <p>决定只对当前差异内容有效；文件再次变化会重新请求确认。</p>{state.stale&&<><p role="alert">原请求已变化，请保留并核对草稿后重新决定。</p><UiActionButton actionKey="ui.discardChanges" onAction={owner.discard}/></>}
      <nav aria-label="待决定文件">{approval?.files.map(file=><button type="button" key={file.path} aria-label={`查看差异 ${file.path}`} aria-current={state.selectedPath===file.path?'true':undefined} onClick={()=>void owner.preview(file.path)}>{({MODIFIED:'修改',DELETED:'删除',RENAMED_FROM:'重命名前',RENAMED_TO:'重命名后'} as const)[file.changeType]} · {file.path} · {state.decisions[file.path]==='ALLOW'?'已接受':state.decisions[file.path]==='REJECT'?'已拒绝':'待决定'}</button>)}</nav>
      <p>范围外新增文件已自动接受，并会保留在审计记录中。</p><h3>{state.selectedPath}</h3><UiActionButton actionKey="scope.allow" availability={owner.actionBlocked()||state.stale?{kind:'disabled',reason:'请先核对原请求。'}:{kind:'enabled'}} onAction={()=>owner.edit({decisions:{...state.decisions,[state.selectedPath]:'ALLOW'}})}/><UiActionButton actionKey="scope.reject" availability={owner.actionBlocked()||state.stale?{kind:'disabled',reason:'请先核对原请求。'}:{kind:'enabled'}} onAction={()=>owner.edit({decisions:{...state.decisions,[state.selectedPath]:'REJECT'}})}/>
      {state.previewError&&<p role="alert">{state.previewError}</p>}{state.previewLoading?<p>正在读取差异…</p>:<div aria-label="文件修改前后差异" role="textbox" aria-readonly="true">{parsePatch(state.preview?.patch||'').map((line,i)=><pre key={i} className={`diff-line ${line.kind}`}><span>{line.oldLine??''}</span> <span>{line.newLine??''}</span> <code>{line.content}</code></pre>)}</div>}{state.preview?.truncated&&<p>差异内容已截断，请核对完整文件。</p>}
      <p>已接受 {allowed} · 已拒绝 {count-allowed} · 待决定 {(approval?.files.length||0)-count}</p><UiActionButton actionKey="scope.submit" availability={owner.actionBlocked()||state.stale||!count||count!==approval?.files.length?{kind:'disabled',reason:'请为全部文件决定，并先核对原请求。'}:{kind:'enabled'}} onAction={owner.submit}/>
    </UiContextPanel><PanelNotice state={state} owner={owner}/>
  </section>
}
