import type { Task,TaskDecision,JudgeApproval,DirtyWorkspaceState,GitDiffScopeApproval,RollingPackageRun,RollingPackageWorkbench,RollingPlanProposal } from '@/types/domain'
import type { TaskParentPort,TaskPanelProps,TaskChildOwner } from '../shared/types'
import { pageProps } from '@/pages/w2/workflow/page.test-support'
export { deferred,flush,foundationDOM,pageFrame } from '@/pages/w2/workflow/page.test-support'
export const task=(id='task'):Task=>({id,projectId:'p',projectName:'项目',title:'任务',goal:'保留冻结合同',branch:'',worktreePath:'',status:'AWAITING_DECISION',version:7,attemptCount:1,maxAttempts:6,createdAt:'start',updatedAt:'now',cancellationAvailable:true})
export const decision=(id='task'):TaskDecision=>({taskId:id,taskState:'AWAITING_DECISION',taskVersion:7,cycle:{id:'cycle',ordinal:2,kind:'CONTINUE_FAILED',result:'FAILED',version:3,authorizedAt:'now',startedAt:'now',endedAt:'now'},checkpoint:{id:'checkpoint',state:'READY',changedFileCount:4,updatedAt:'now',version:2},stages:[{id:'stage',ordinal:0,objective:'修复接口',state:'FAILED'}],availableActions:['CONTINUE_CURRENT_TASK','DERIVE_INHERIT_CHANGES','DERIVE_REWORK_ALL','READ_ONLY_AUDIT','ACCEPT_RESULT','CANCEL']})
export const judge:JudgeApproval={available:true,approved:false,taskVersion:7,cycleId:'cycle',cycleVersion:3,reviewBatchId:'batch'}
export const dirty:DirtyWorkspaceState={branch:'main',head:'head',snapshotId:'snapshot',clean:false,files:[{path:'README.md',indexStatus:' ',workTreeStatus:'M',untracked:false},{path:'notes.txt',indexStatus:'?',workTreeStatus:'?',untracked:true}]}
export const approval:GitDiffScopeApproval={requestId:'request',taskId:'task',stageId:'stage',attemptId:'attempt',taskVersion:7,files:[{path:'src/Main.java',changeType:'MODIFIED',patchSha256:'patch-sha'}]}
export const patch='diff --git a/src/Main.java b/src/Main.java\n--- a/src/Main.java\n+++ b/src/Main.java\n@@ -10,2 +10,2 @@\n-old value\n+new value\n context'
export const frozen:RollingPackageRun={id:'frozen',packageKey:'WP-1',ordinal:0,title:'基础能力',state:'FACT_FROZEN',version:4,discussionRevision:1,designRevision:2,dependencies:[]}
export const reviewing:RollingPackageRun={id:'reviewing',packageKey:'WP-2',ordinal:1,title:'业务接入',state:'DESIGN_REVIEW',version:3,discussionRevision:5,designRevision:6,dependencies:['WP-1']}
export const workbench:RollingPackageWorkbench={taskId:'task',title:'三包任务',taskState:'PACKAGE_DESIGNING',taskVersion:8,executionMode:'ROLLING_PACKAGES',workspacePolicy:'RELEASE_BETWEEN_PACKAGES',planRevisionId:'plan',planRevision:2,plannedPackageCount:2,frozenPackageCount:1,currentPackageRunId:'reviewing',packageCapabilities:{canDiscuss:true,canApproveDesign:true,canStartPackage:false,canRetryPackage:false,canRedesignPackage:false,canResumeDesign:false,canReplanRemaining:true,canAddCorrectionPackage:true},packages:[frozen,reviewing]}
export const proposal=(state:RollingPlanProposal['state']='PROPOSED'):RollingPlanProposal=>({id:'proposal',revision:3,state,version:2,planJson:'[]',impactJson:'{"added":[]}',origin:'AI',createdAt:'now',updatedAt:'now'})
export function parentPort():TaskParentPort{const children=new Set<TaskChildOwner>();return {registerChild(owner){children.add(owner);return ()=>{children.delete(owner)}},canStartWrite(caller){return [...children].every(child=>{const decision=child.canLeave();return decision.kind==='ALLOW'||child===caller&&decision.kind==='CONFIRM_DISCARD'})},refresh:async()=>undefined}}
export function panelProps(input=task()):TaskPanelProps{return {task:input,page:pageProps(`/tasks/${input.id}`),parent:parentPort()}}
