import { describe,expect,it,vi,afterEach,beforeEach } from 'vitest'
import { PptCanvasView } from '@/react/ppt/PptCanvasView'
import { PptSlideNavigatorView } from '@/react/ppt/PptSlideNavigatorView'
import { slidePreviews } from '@/react/ppt/previews'
import { mount } from '@/pages/w6-tests/knowledge-ppt-template/react-test-root'
import { pptDeck } from './pptTestFixtures'
import type { PptJob } from '@/types/domain'
beforeEach(()=>vi.stubGlobal('ResizeObserver',undefined))
afterEach(()=>vi.unstubAllGlobals())
describe('PPT Vue to React bridge',()=>{
 it('mounts the React canvas and forwards events and changed props through the existing Vue contract',async()=>{const deck=pptDeck(),view=mount(PptCanvasView,{props:{deck,slide:deck.slides[0]!,selected:'text-1',revision:3}});expect(view.get('[data-canvas-kind="ppt"]').attributes('data-canvas-runtime')).toBe('react');await view.get('.ppt-canvas-object').trigger('keydown',{key:'ArrowRight',shiftKey:true});expect(view.emitted('patch')?.[0]).toEqual(['text-1',{x:90,y:70},3]);await view.get('.ppt-canvas-object').trigger('click');expect(view.emitted('select')?.at(-1)).toEqual(['text-1']);await view.setProps({revision:4,preview:'/new-preview.png',previewRevision:4});expect(view.get('.ppt-preview-image').attributes('src')).toBe('/new-preview.png');await view.get('.ppt-canvas-object').trigger('keydown',{key:'ArrowRight',altKey:true});expect(view.emitted('patch')?.at(-1)).toEqual(['text-1',{width:401,height:90},4]);await view.get('.ppt-canvas-object').trigger('keydown',{key:'Delete'});expect(view.emitted('remove')?.at(-1)).toEqual(['text-1']);await view.setProps({revision:5});expect(view.get('[data-canvas-kind="ppt"]').attributes('data-canvas-runtime')).toBe('react')})
 it('keeps a Vue fallback with the same event contract',async()=>{const deck=pptDeck(),view=mount(PptCanvasView,{props:{deck,slide:deck.slides[0]!,selected:'text-1',revision:3}});expect(view.get('[data-canvas-kind="ppt"]').attributes('data-canvas-runtime')).toBe('react');await view.get('.ppt-canvas-object').trigger('keydown',{key:'ArrowRight',shiftKey:true});expect(view.emitted('patch')?.[0]).toEqual(['text-1',{x:90,y:70},3]);await view.get('.ppt-canvas-object').trigger('keydown',{key:'Escape'});expect(view.emitted('select')?.at(-1)).toEqual([''])})
 it('reflects an in-place Vue object update through a plain React DTO snapshot',async()=>{const deck=pptDeck(),view=mount(PptCanvasView,{props:{deck,slide:deck.slides[0]!,selected:'text-1',revision:3}});deck.slides[0]!.elements[0]!.text='修改后的标题';deck.slides[0]!.elements[0]!.x=240;const dto=structuredClone(deck);await view.setProps({deck:dto,slide:dto.slides[0]!});const object=view.get('.ppt-canvas-object');expect(object.text()).toBe('修改后的标题');expect(object.attributes('aria-label')).toBe('文本框：修改后的标题');expect((object.element as HTMLElement).style.left).toBe('25%');deck.slides[0]!.elements[0]!.locked=true;const locked=structuredClone(deck);await view.setProps({deck:locked,slide:locked.slides[0]!});expect(view.find('.ppt-resize-handle').exists()).toBe(false)})
 it('bridges revision-matched thumbnail previews and selection without creating a new request path',async()=>{const deck=pptDeck(),jobs:PptJob[]=[{id:'preview',documentId:'doc',kind:'PREVIEW',revision:3,state:'COMPLETED',completed:1,total:1,detail:'',createdAt:'2026-10-03T00:00:00Z',artifacts:[{id:'current',slideId:'slide-1',name:'current.png',mediaType:'image/png',url:''}]}];const previews=slidePreviews(jobs,3,id=>`/api/ppt/documents/doc/artifacts/${id}`);const view=mount(PptSlideNavigatorView,{props:{deck,previews,selected:'slide-1',manual:true}});expect(view.get('[data-canvas-kind="ppt-navigator"]').attributes('data-canvas-runtime')).toBe('react');expect(view.get('img').attributes('src')).toBe('/api/ppt/documents/doc/artifacts/current');await view.get('[aria-label="第 2 页：下一步计划"]').trigger('click');expect(view.emitted('select')?.at(-1)).toEqual(['slide-2']);await view.get('.ppt-add-page').trigger('click');expect(view.emitted('add')).toHaveLength(1);await view.setProps({previews:slidePreviews(jobs,4,id=>`/api/ppt/documents/doc/artifacts/${id}`)});expect(view.find('img').exists()).toBe(false)})
 it('uses the Vue thumbnail fallback when the route selects Vue',async()=>{const view=mount(PptSlideNavigatorView,{props:{deck:pptDeck(),previews:new Map(),selected:'slide-1'}});expect(view.get('[data-canvas-kind="ppt-navigator"]').attributes('data-canvas-runtime')).toBe('react');await view.get('[aria-label="第 2 页：下一步计划"]').trigger('click');expect(view.emitted('select')?.at(-1)).toEqual(['slide-2'])})
})
