import { createElement, useSyncExternalStore } from 'react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { pptApi } from '@/api/ppt'
import { PptChat } from '@/pages/w3/ppt/Chat'
import { createPptStudioController } from '@/pages/w3/ppt/controller'
import { studioFixture, message as fixtureMessage } from '@/pages/w3/ppt/testFixture'
import { flushPromises, mount } from '@/pages/w6-tests/knowledge-ppt-template/react-test-root'
import { skins } from '@/themes/registry'
import { pptAgent, pptGeneration } from './pptTestFixtures'
import type { PptAgentStatus, PptMessage } from '@/types/ppt'
const message=(id:string,answer='已完成调整'):PptMessage=>({...fixtureMessage(id,'做一份季度汇报'),id,answer})
let owner:ReturnType<typeof createPptStudioController>, rows:PptMessage[], agent:PptAgentStatus
async function update(messages=rows,nextAgent=agent){rows=messages;agent=nextAgent;vi.mocked(pptApi.messages).mockResolvedValue({items:rows,facets:{}});vi.mocked(pptApi.agent).mockResolvedValue(agent);await owner.refresh();await flushPromises()}
function Chat({ready=true}:{ready?:boolean}){const state=useSyncExternalStore(owner.subscribe,owner.getSnapshot);return createElement(PptChat,{owner,state,scope:{kind:'DOCUMENT'},scopeLabel:'整份演示文稿',ready,disabled:false,skin:skins[0]!,onDocumentScope:()=>{}})}
const render=(ready=true)=>mount(Chat,{props:{ready}})
beforeEach(async()=>{sessionStorage.clear();studioFixture();rows=[];agent=pptAgent();owner=createPptStudioController('doc');await owner.start()})
afterEach(()=>{owner.retire(true);vi.restoreAllMocks()})
describe('PPT concise conversation',()=>{
 it('does not show the generic completion detail beside a completed discussion reply',async()=>{const detail='本轮模型已完成；制作结果以作品检查和作业状态为准';await update([{...message('discussion-complete','面向开发者，重点介绍架构和 API。'),detail}],{...agent,state:'COMPLETED',detail});const w=render(false);expect(w.text()).toContain('面向开发者，重点介绍架构和 API。');expect(w.text()).not.toContain(detail);expect(w.findAll('.ppt-notice')).toHaveLength(0)})
 it('keeps a specific completion check failure visible',async()=>{const detail='模型已停止；制作完成检查未通过，请检查页面问题后继续修改或重试完成制作';await update([{...message('discussion-check-failed','已整理出初稿。'),detail}],{...agent,state:'COMPLETED',detail});const w=render(false);expect(w.text()).toContain(detail);expect(w.findAll('.ppt-notice')).toHaveLength(1)})
 it('keeps the composer open for freeform discussion and confirms the persisted transcript on demand',async()=>{const generate=vi.spyOn(pptApi,'generate'),confirm=vi.spyOn(pptApi,'confirmGeneration').mockResolvedValue(pptGeneration('PLANNING'));const w=render(false);await w.get('.ppt-composer textarea').setValue('补充：面向开发者，强调架构和 API');await w.get('.ppt-composer').trigger('submit');expect(pptApi.send).toHaveBeenCalledWith('doc',expect.objectContaining({text:'补充：面向开发者，强调架构和 API',scope:{kind:'DOCUMENT'},expectedRevision:3,idempotencyKey:expect.any(String)}));expect(generate).not.toHaveBeenCalled();await update([message('discussion-complete')]);expect(w.find('.ppt-composer').exists()).toBe(true);expect(w.text()).toContain('确认需求并执行');await w.get('.ppt-composer textarea').setValue('还有新的要求');expect(w.findAll('button').some(b=>b.text().includes('确认需求并执行'))).toBe(false);await w.get('.ppt-composer textarea').setValue('');await w.get('[data-semantic="ppt.confirm"]').trigger('click');expect(confirm).toHaveBeenCalledOnce()})
 it('requires an explicit confirmation card before starting design and keeps clarification replies separate',async()=>{const q={id:'brief',kind:'CLARIFICATION' as const,prompt:'本次重点讲什么？',options:['业务成果'],state:'PENDING' as const,answer:null,version:1};await update([],{...agent,state:'WAITING_INPUT',requirementsState:'CLARIFYING',questions:[q]});const w=render();expect(w.text()).not.toContain('确认需求并执行');await w.get('textarea').setValue('突出业务成果');await w.get('.ppt-question').trigger('submit');expect(pptApi.reply).toHaveBeenLastCalledWith('doc','brief',expect.objectContaining({answer:'突出业务成果',version:1}));expect(vi.mocked(pptApi.reply).mock.calls.at(-1)![2].confirmed).toBeUndefined();const c={...q,id:'confirm',kind:'REQUIREMENTS_CONFIRMATION' as const,prompt:'## 汇报需求\n面向管理层，10 页，商务风格。'};await update([],{...agent,state:'WAITING_INPUT',requirementsState:'AWAITING_CONFIRMATION',questions:[c]});expect(w.get('.ppt-requirements-confirmation .markdown-document').text()).toContain('10 页');await w.get('textarea').setValue('改成 8 页');expect(w.get('[data-semantic="ppt.confirm"]').attributes('disabled')).toBeDefined();await w.get('.ppt-question').trigger('submit');expect(pptApi.reply).toHaveBeenLastCalledWith('doc','confirm',expect.objectContaining({answer:'改成 8 页',confirmed:false,version:1}));expect(w.get('[data-semantic="ppt.confirm"]').attributes('disabled')).toBeUndefined();await w.get('[data-semantic="ppt.confirm"]').trigger('click');expect(pptApi.reply).toHaveBeenLastCalledWith('doc','confirm',expect.objectContaining({answer:'确认以上需求，请开始设计',confirmed:true,version:1}))})
 it('restores a pending requirements confirmation after remount without automatically accepting it',async()=>{await update([],{...agent,state:'WAITING_INPUT',requirementsState:'AWAITING_CONFIRMATION',questions:[{id:'confirm',kind:'REQUIREMENTS_CONFIRMATION',prompt:'季度成果，面向管理层',options:[],state:'PENDING',answer:null,version:3}]});let w=render();await w.get('textarea').setValue('增加风险说明');w.unmount();w=render();expect((w.get('textarea').element as HTMLTextAreaElement).value).toBe('增加风险说明');expect(w.find('[data-semantic="ppt.confirm"]').exists()).toBe(true);expect(pptApi.reply).not.toHaveBeenCalled()})
 it('shares knowledge waiting, thinking and tool disclosure behavior across streaming updates and stop',async()=>{await update([{...message('stream',''),state:'RUNNING'}]);const w=render();expect(w.get('.knowledge-waiting').text()).toContain('正在思考');await update([{...message('stream',''),state:'RUNNING',thinking:'检查第一版\n\n正在检查页面',calls:[{id:'call',tool:'ppt_check_layout',state:'RUNNING',detail:''}]}]);expect(w.find('.knowledge-waiting').exists()).toBe(false);expect(w.get('[aria-label="思考"] button').attributes('aria-expanded')).toBe('false');expect(w.get('[aria-label="工具调用"] button').text()).toContain('检查页面布局');await w.get('[aria-label="思考"] button').trigger('click');await update([{...rows[0]!,thinking:'新的思考内容'}]);expect(w.get('[aria-label="思考"] button').attributes('aria-expanded')).toBe('true');await update([{...rows[0]!,state:'STOPPED'}]);expect(w.find('.knowledge-spinner').exists()).toBe(false);expect(w.text()).toContain('新的思考内容')})
 it('separates embedded thinking from answer and suppresses waiting while a question is pending',async()=>{await update([{...message('stream','<think>检查资料</think>完成设计'),state:'RUNNING'}]);const w=render();expect(w.get('[aria-label="思考"]').text()).toContain('检查资料');expect(w.get('.ppt-agent-message').text()).toBe('完成设计');await update([{...message('stream',''),state:'WAITING_INPUT'}]);expect(w.find('.knowledge-waiting').exists()).toBe(false)})
 it('collapses long replies while keeping failures and pending questions visible',async()=>{const answer='这是一段详细制作过程。'.repeat(70)+'\n\n演示文稿已经完成，可继续提出修改意见。';await update([message('one',answer),{...message('two',answer),state:'FAILED',detail:'图片无法读取，请更换图片后重试'}],{...agent,state:'WAITING_INPUT',questions:[{id:'question',prompt:'请确认报告的目标受众',options:['管理层'],state:'PENDING',answer:null,version:1}]});const w=render();expect(w.findAll('.ppt-long-reply')).toHaveLength(1);expect(w.get('.ppt-long-reply').attributes('open')).toBeUndefined();expect(w.get('.ppt-question').text()).toContain('请确认报告的目标受众');expect(w.text()).toContain('图片无法读取，请更换图片后重试');expect(w.find('.ppt-composer').exists()).toBe(false);expect(w.findAll('.ppt-user-message')).toHaveLength(1)})
 it('follows new replies at the bottom but preserves an intentional history scroll',async()=>{await update([message('one')]);const w=render();const timeline=w.get('.ppt-chat-timeline').element;Object.defineProperty(timeline,'scrollHeight',{configurable:true,get:()=>1200});Object.defineProperty(timeline,'clientHeight',{configurable:true,get:()=>200});timeline.scrollTop=1000;await w.get('.ppt-chat-timeline').trigger('scroll');await update([message('one','已完成页面制作')]);expect(timeline.scrollTop).toBe(1200);timeline.scrollTop=100;await w.get('.ppt-chat-timeline').trigger('scroll');await update([message('one','新的结果已经准备好')]);expect(timeline.scrollTop).toBe(100);expect(w.get('[data-semantic="ui.next"]').attributes('aria-label')).toContain('回到最新回复');await w.get('[data-semantic="ui.next"]').trigger('click');expect(timeline.scrollTop).toBe(1200);expect(w.find('[data-semantic="ui.next"]').exists()).toBe(false)})
 it('explicitly adjusts a stopped authorization without sending a manual request',async()=>{vi.mocked(pptApi.generation).mockResolvedValue(pptGeneration('FAILED'));await update([],{...agent,state:'FAILED'});const adjusted=vi.spyOn(pptApi,'resume').mockResolvedValue(pptGeneration('PLANNING'));const w=render(false);await w.get('.ppt-composer textarea').setValue('先完成八页，去掉示例截图');expect(w.get('[data-semantic="ppt.resume"]').exists()).toBe(true);await w.get('.ppt-composer').trigger('submit');expect(adjusted).toHaveBeenCalledWith('doc',3,expect.any(String),'先完成八页，去掉示例截图');expect(pptApi.send).not.toHaveBeenCalled();expect((w.get('textarea').element as HTMLTextAreaElement).value).toBe('')})
})
