<script setup lang="ts">
import type { PptEditablePlan, PptCapabilities, PptSource } from '@/types/domain'
const plan = defineModel<PptEditablePlan>({ required: true })
defineProps<{ tab: 'visual' | 'assets' | 'notes' | 'delivery'; capabilities: PptCapabilities | null; sources: PptSource[] }>()
</script>
<template>
  <div v-if="tab === 'visual'" class="ppt-plan-module"><h2>视觉规范</h2><label>整体风格<textarea v-model="plan.visualRules.style" rows="3" /></label><label>演示主题<select v-model="plan.theme"><option v-for="theme in capabilities?.themes || []" :key="theme.id" :value="theme.id">{{ theme.name }}</option></select></label><label>字体<select v-model="plan.visualRules.fontFamily"><option v-for="font in capabilities?.fonts || []" :key="font" :value="font">{{ font }}</option></select></label><div class="ppt-form-grid"><label>强调色<input v-model="plan.visualRules.accentColor" pattern="#?[a-fA-F0-9]{6}" /></label><label>文字密度<select v-model="plan.visualRules.density"><option>精简</option><option>适中</option><option>详细</option></select></label></div><label>页面比例<input value="16:9" readonly /></label><small>当前使用 16:9 宽屏。其余视觉要求指导助手制作，实际对象样式可在页面制作中调整。</small></div>
  <div v-else-if="tab === 'assets'" class="ppt-plan-module"><h2>图表与素材</h2><label>素材使用要求<textarea v-model="plan.assets.requirements" rows="3" /></label><label>图表表达要求<textarea v-model="plan.assets.chartGuidance" rows="4" /></label><label>配图要求<textarea v-model="plan.assets.imageGuidance" rows="4" /></label><p v-if="!sources.length" class="ppt-muted">从左侧资料栏上传文件后，可为每页选择依据。</p><article v-for="(slide, index) in plan.slides" :key="slide.id" class="ppt-direction"><strong>第 {{ index + 1 }} 页 · {{ slide.title }}</strong><label v-for="source in sources" :key="source.id" class="ppt-check"><input v-model="slide.sourceIds" type="checkbox" :value="source.id" :disabled="source.state !== 'READY'" />{{ source.name }}</label></article></div>
  <div v-else-if="tab === 'notes'" class="ppt-plan-module"><h2>演讲辅助</h2><p v-if="!plan.slides.length" class="ppt-muted">先增加页面设计，再完善每页讲稿与过渡。</p><article v-for="(slide, index) in plan.slides" :key="slide.id" class="ppt-plan-slide"><strong>第 {{ index + 1 }} 页 · {{ slide.title }}</strong><label>讲稿、时长与过渡<textarea v-model="slide.notes" rows="7" /></label></article></div>
  <div v-else class="ppt-plan-module"><h2>交付设置</h2><label>文件名称<input v-model="plan.delivery.fileName" placeholder="演示文稿.pptx" /></label><label>目标办公软件<input v-model="plan.delivery.targetSoftware" placeholder="WPS / PowerPoint" /></label><label class="ppt-check"><input v-model="plan.delivery.includeNotes" type="checkbox" />包含演讲备注</label><p class="ppt-muted">正式导出为可编辑 PPTX，页面预览为 PNG。</p></div>
</template>
