import { useEffect } from 'react'
import type { UiActionKey } from '@/foundation/semanticRegistry'
import { UiActionButton } from '@/foundation/components'
import { pptApi } from '@/api/ppt'
import { pptJobLabel, knowledgeStateLabel } from '@/utils/displayLabels'
import type { W2PageProps } from '@/pages/w2/shared'
import { RichDocument } from '../shared/RichDocument'
import { ArtifactDownload } from './Download'
import { studioActive, studioEditable, type PptStudioController, type StudioSnapshot } from './controller'

export function PptSources({ owner, state: s, skin, insert }: { owner: PptStudioController; state: Readonly<StudioSnapshot>; skin: W2PageProps['skin']; insert(assetId: string): void }) {
  useEffect(() => { if (s.document?.projectId) void owner.readKnowledge() }, [owner, s.document?.projectId])
  const disabled = !studioEditable(s)
  const choose = async (files: readonly File[], kind: 'sources' | 'assets') => { for (const file of files) if (!await owner.upload(file, kind)) break }
  return <section className="ppt-sources" aria-label="资料与素材" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); if (!disabled) { const files = Array.from(event.dataTransfer.files); void (async () => { for (const file of files) if (!await owner.upload(file, /^image\//.test(file.type) ? 'assets' : 'sources')) break })() } }}>
    {s.document?.projectId && <section aria-label="关联项目来源"><h3>{s.knowledge?.project?.name ?? '项目知识库'}</h3><UiActionButton actionKey="ui.refresh" target="关联项目来源" onAction={() => void owner.readKnowledge()} />{s.knowledge && <><p>{s.knowledge.detail || '助手可按需检索以下来源，为这份演示取材。'}</p><ul>{s.knowledge.sources.map(source => <li key={source.id}>{source.name} · {knowledgeStateLabel(source.state)}{source.detail && <p role={source.state === 'FAILED' ? 'alert' : undefined}>{source.detail}</p>}</li>)}</ul>{!s.knowledge.sources.length && <p>此作品没有可用的项目来源，你仍可上传资料并继续沟通。</p>}</>}</section>}
    <p>添加文字资料与图片，也可以拖入文件。资料最多 10 份，每份 20 MiB，总计 50 MiB。</p>
    <div className="w3-ppt-actions"><label>添加资料<input type="file" accept=".md,.docx,.xlsx,.pptx,.pdf" multiple disabled={disabled} onChange={event => { const files = Array.from(event.target.files ?? []); event.target.value = ''; void choose(files, 'sources') }} /></label><label>添加图片<input type="file" accept="image/png,image/jpeg" multiple disabled={disabled} onChange={event => { const files = Array.from(event.target.files ?? []); event.target.value = ''; void choose(files, 'assets') }} /></label></div>
    {s.pending?.kind === 'upload' && <label>重新选择原文件（必须核对相同字节）<input type="file" disabled={s.busy} onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void owner.reselectFile(file) }} /></label>}
    <h3>资料</h3>{!s.sources.length && <p>暂无资料</p>}{s.sources.map(source => <article key={source.id} className="ppt-resource"><UiActionButton actionKey="ui.open" target={source.name} onAction={() => void owner.readSource(source.id)} /><strong>{source.name}</strong><small>{(source.bytes / 1024).toFixed(0)} KiB · {source.sections} 个片段</small>{source.detail && <p>{source.detail}</p>}{source.limitations.map((text, index) => <p key={index}>{text}</p>)}</article>)}
    <h3>图片素材</h3>{!s.assets.length && <p>暂无图片</p>}{s.assets.map(asset => <article key={asset.id} className="ppt-resource"><img src={pptApi.assetUrl(owner.identity.id, asset.id)} alt={asset.name} loading="lazy" /><strong>{asset.name}</strong><UiActionButton actionKey="ppt.addObject" target="插入当前页图片" availability={disabled || !s.deck?.slides.length ? { kind: 'disabled', reason: '请先核对原操作并选择可编辑页面。' } : { kind: 'enabled' }} onAction={() => insert(asset.id)} /></article>)}
    {s.sourceContent && <section aria-label="资料正文"><h3>{s.sourceContent.name}</h3><UiActionButton actionKey="ui.close" target="正文" onAction={owner.closeSource} />{s.sourceContent.sections.map(section => <details key={section.id}><summary>{section.title || '资料片段'}</summary><RichDocument content={section.markdown} skin={skin} /></details>)}{s.sourceContent.limitations.map((text, index) => <p key={index}>{text}</p>)}</section>}
  </section>
}
export function PptHistory({ owner, state: s, confirm, view }: { owner: PptStudioController; state: Readonly<StudioSnapshot>; confirm(title: string, action: () => void, actionKey?: UiActionKey): void; view(revision: number): void }) {
  return <section className="ppt-history" aria-label="版本与导出"><h2>制作与导出</h2>{!s.jobs.length && <p>暂无制作记录</p>}{s.jobs.map(job => <article key={job.id} className="ppt-history-item"><h3>{job.kind === 'EXPORT' ? 'PPTX 导出' : '页面预览'} · {pptJobLabel(job.state)}</h3><p>版本 {job.revision}{job.revision !== s.document?.revision && ' · 当前草稿已有更新'}</p><p>已生成 {job.completed} / {job.total} 页</p>{job.total > 0 && ['PENDING', 'PREPARED', 'QUEUED', 'RUNNING'].includes(job.state) && <progress value={job.completed} max={job.total} />}{job.detail && <p>{job.detail}</p>}<div className="ppt-downloads">{job.artifacts.map(artifact => <ArtifactDownload key={artifact.id} documentId={owner.identity.id} artifact={artifact} label={artifact.slideId ? `${s.deck?.slides.find(slide => slide.id === artifact.slideId)?.title || '页面'}预览.png` : undefined} />)}</div>{job.state === 'FAILED' && <UiActionButton actionKey="ui.retry" target="继续生成未完成页面" availability={s.busy || !!s.pending ? { kind: 'disabled', reason: '请先核对原操作。' } : { kind: 'enabled' }} onAction={() => void owner.retryJob(job.id)} />}</article>)}
    <h2>历史版本</h2>{s.revisions.map(revision => <article key={revision.revision} className="ppt-history-item"><h3>版本 {revision.revision}</h3><p>{revision.reason || '保存修改'} · {new Date(revision.createdAt).toLocaleString('zh-CN')}</p><div className="w3-ppt-actions"><UiActionButton actionKey="ui.open" target={`版本 ${revision.revision}`} onAction={() => view(revision.revision)} /><UiActionButton actionKey="ppt.restoreRevision" target={`版本 ${revision.revision}`} availability={s.busy || !!s.pending || studioActive(s) || s.document?.archived || revision.revision === s.document?.revision ? { kind: 'disabled', reason: '当前版本或原操作尚不能恢复。' } : { kind: 'enabled' }} onAction={() => confirm('恢复为一个新的当前版本？现有版本会保留。', () => { void owner.action('restore', { targetRevision: revision.revision }).then(accepted => { if (accepted) owner.returnCurrent() }) }, 'ppt.restoreRevision')} /></div></article>)}{s.revisionCursor && <UiActionButton actionKey="ui.loadMore" target="历史版本" onAction={() => void owner.more('revisions')} />}
  </section>
}
