import { useEffect, useLayoutEffect, useRef, useState, type PointerEvent } from 'react'
import { UiActionButton, UiConfirmDialog, UiContextPanel } from '@/foundation/components'
import type { UiActionKey } from '@/foundation/semanticRegistry'
import { PageChrome, PageLink, SkinControl, useLeaveGuard, useOwnerSnapshot, useRetainedOwner, type W2PageProps } from '@/pages/w2/shared'
import { pptApi } from '@/api/ppt'
import { newPptElement, type PptElement, type PptScope, type PptSlide } from '@/types/ppt'
import { pptElementLabel, pptGenerationLabel, pptGenerationStepLabel, pptJobLabel, pptLayoutLabel, pptPhaseLabel, pptRunLabel } from '@/utils/displayLabels'
import { PptCanvasView } from '@/react/ppt/PptCanvasView'
import { PptSlideNavigatorView } from '@/react/ppt/PptSlideNavigatorView'
import { slidePreviews } from '@/react/ppt/previews'
import { createPptStudioController, studioActive, studioDirty, studioEditable, studioJobsActive, studioReady } from './controller'
import { PptChat } from './Chat'
import { PptProperties } from './Properties'
import { PptPlanEditor } from './Plan'
import { PptHistory, PptSources } from './Details'
import { useArtifactDownload } from './Download'
import '@/components/ppt/ppt.css'
import './studio.css'

export function PptStudioPage(props: W2PageProps) {
  const documentId = String(props.route.params.id ?? '')
  return <StudioBody key={documentId} {...props} documentId={documentId} />
}
function StudioBody(props: W2PageProps & { documentId: string }) {
  const [owner] = useState(() => createPptStudioController(props.documentId)), s = useOwnerSnapshot(owner)
  useRetainedOwner(props, owner, () => owner.retire(true)); useLeaveGuard(props, () => owner.canLeave())
  useEffect(() => { const detach = owner.attachView(); void owner.start(); return detach }, [owner])
  const [slideId, setSlideId] = useState(() => { try { return sessionStorage.getItem(`loopper.ppt.slide.${props.documentId}`) || '' } catch { return '' } })
  const [elementId, setElementId] = useState(''), [manual, setManual] = useState(false), [assistant, setAssistant] = useState(false)
  const [tab, setTab] = useState<'chat' | 'properties'>('chat'), [scopeKind, setScopeKind] = useState<PptScope['kind']>('DOCUMENT')
  const [details, setDetails] = useState<'sources' | 'history' | 'plan' | null>(null), [menu, setMenu] = useState(false), [tools, setTools] = useState<'insert' | 'page' | null>(null), [layout, setLayout] = useState('title_content')
  const [localError, setLocalError] = useState(''), [expanded, setExpanded] = useState(false)
  const [confirmation, setConfirmation] = useState<{ title: string; action: () => void; actionKey: UiActionKey } | null>(null)
  const assistantTrigger = useRef<HTMLButtonElement | HTMLAnchorElement | null>(null), detailsTrigger = useRef<HTMLElement | null>(null), root = useRef<HTMLDivElement | null>(null)
  const [panelWidth, setPanelWidth] = useState(() => { try { return Math.max(280, Math.min(520, Number(JSON.parse(localStorage.getItem('loopper.ppt.panels') || '{}').right) || 340)) } catch { return 340 } })
  const resize = useRef<{ target: HTMLElement; pointer: number; x: number; width: number } | null>(null)
  const saveWidth = (width: number) => { try { const old = JSON.parse(localStorage.getItem('loopper.ppt.panels') || '{}'); localStorage.setItem('loopper.ppt.panels', JSON.stringify({ ...old, right: width })) } catch { /* Optional view preference. */ } }
  const cancelResize = () => { const gesture = resize.current; resize.current = null; if (gesture?.target.hasPointerCapture?.(gesture.pointer)) gesture.target.releasePointerCapture(gesture.pointer) }
  useEffect(() => { const ownerWindow = root.current?.ownerDocument.defaultView ?? window; const blur = (event: FocusEvent) => { if (event.target === ownerWindow || (event.target as Window | null)?.document === ownerWindow.document) cancelResize() }; ownerWindow.addEventListener('blur', blur); return () => { ownerWindow.removeEventListener('blur', blur); cancelResize() } }, [])
  useEffect(() => { if (!menu && !tools) return; const outside = (event: globalThis.PointerEvent) => { const target = event.target; if (!(target instanceof Element) || !target.closest('.w3-ppt-menus') || !root.current?.contains(target)) { setMenu(false); setTools(null) } }; document.addEventListener('pointerdown', outside); return () => document.removeEventListener('pointerdown', outside) }, [menu, tools])
  const scene = s.historical?.deck ?? s.deck, revision = s.historical?.revision ?? s.document?.revision ?? 0
  const slide = scene?.slides.find(item => item.id === slideId) ?? scene?.slides[0], element = slide?.elements.find(item => item.id === elementId)
  const ready = studioReady(s), active = studioActive(s), editable = studioEditable(s)
  const propertyDirty = Object.values(s.drafts).some(draft => draft.dirty && draft.kind !== 'plan')
  const scope: PptScope = scopeKind === 'ELEMENT' && element && slide ? { kind: 'ELEMENT', slideId: slide.id, elementId: element.id } : scopeKind === 'SLIDE' && slide ? { kind: 'SLIDE', slideId: slide.id } : { kind: 'DOCUMENT' }
  const scopeLabel = scope.kind === 'ELEMENT' ? `${slide?.title} · ${pptElementLabel(element?.type ?? '')}` : scope.kind === 'SLIDE' ? slide?.title ?? '当前页面' : '整份演示文稿'
  const previews = slidePreviews(s.jobs, revision, id => pptApi.artifactUrl(props.documentId, id))
  const previewJob = slide && s.jobs.find(job => job.kind === 'PREVIEW' && job.revision <= revision && (!s.historical || job.revision === revision) && job.artifacts.some(artifact => artifact.slideId === slide.id && artifact.mediaType === 'image/png'))
  const previewArtifact = previewJob?.artifacts.find(artifact => artifact.slideId === slide?.id && artifact.mediaType === 'image/png')
  const exportArtifact = s.jobs.find(job => job.kind === 'EXPORT' && job.state === 'COMPLETED' && job.revision === s.document?.revision)?.artifacts.find(artifact => artifact.mediaType !== 'image/png')
  const download = useArtifactDownload(props.documentId), requestedExport = useRef<number | null>(null)
  useEffect(() => { if (exportArtifact && requestedExport.current === s.document?.revision) { requestedExport.current = null; void download.download(exportArtifact) } else if (requestedExport.current !== s.document?.revision || s.jobs.some(job => job.kind === 'EXPORT' && job.revision === requestedExport.current && job.state === 'FAILED')) requestedExport.current = null }, [exportArtifact?.id, s.document?.revision, s.jobs])
  useLayoutEffect(() => { if (elementId && !element) { setElementId(''); setScopeKind('SLIDE') } }, [elementId, element])
  useEffect(() => { if (ready && s.agent?.questions.some(question => question.state === 'PENDING')) { setAssistant(true); setTab('chat') } }, [ready, s.agent?.questions])
  const protect = () => { if (!propertyDirty) return true; setLocalError('对象或页面输入尚未保存，请先核对属性；草稿仍保留。'); setAssistant(true); setTab('properties'); return false }
  const selectSlide = (id: string) => { if (!protect()) return; setSlideId(id); setElementId(''); setScopeKind('SLIDE'); setTools(null); try { sessionStorage.setItem(`loopper.ppt.slide.${props.documentId}`, id) } catch { /* Optional preference. */ } }
  const selectElement = (id: string) => { if (!protect()) return; setElementId(id); setScopeKind(id ? 'ELEMENT' : 'SLIDE'); if (id && manual) { setAssistant(true); setTab('properties') } }
  const confirm = (title: string, action: () => void, actionKey: UiActionKey = 'ui.delete') => setConfirmation({ title, action, actionKey })
  const available = (enabled: boolean, reason = '请先核对原操作、草稿与当前权限。') => enabled ? { kind: 'enabled' as const } : { kind: 'disabled' as const, reason }
  const button = (key: UiActionKey, onAction: () => void, enabled = true, target?: string) => <UiActionButton actionKey={key} target={target} availability={available(enabled)} onAction={onAction} />
  async function patchElement(id: string, patch: Partial<PptElement>, base: number) { if (!slide || !editable) return; if (await owner.operations([{ op: 'update_element', slideId: slide.id, elementId: id, patch }], base)) await owner.createJob('PREVIEW', slide.id) }
  async function addElement(type: string, assetId?: string) { if (!slide || !editable || slide.locked || !protect()) return; const next = newPptElement(type); if (assetId) next.assetId = assetId; if (await owner.operations([{ op: 'add_element', slideId: slide.id, element: next }])) { setElementId(next.id); setScopeKind('ELEMENT'); setAssistant(true); setTab('properties'); setTools(null); await owner.createJob('PREVIEW', slide.id) } }
  const deleteElement = (targetId = elementId) => { const selected = slide?.elements.find(item => item.id === targetId); if (!selected || !slide || !editable || slide.locked || selected.locked || !protect()) return; const id = selected.id, currentSlide = slide.id; confirm('删除这个对象？历史版本仍会保留。', () => { void owner.operations([{ op: 'delete_element', slideId: currentSlide, elementId: id }]).then(async accepted => { if (accepted) { setElementId(''); await owner.createJob('PREVIEW', currentSlide) } }) }, 'ppt.removeObject') }
  const slideAction = (action: string, index?: number) => { if (!slide || !protect()) return; const apply = () => { void owner.operations([{ op: action, slideId: slide.id, ...(index === undefined ? {} : { index }) }]).then(async accepted => { if (accepted) { setElementId(''); await owner.createJob('PREVIEW') } }) }; action === 'delete_slide' ? confirm('删除这页？历史版本仍会保留。', apply, 'ppt.deleteSlide') : apply() }
  const addSlide = () => { if (!editable || !protect()) return; const next: PptSlide = { id: crypto.randomUUID(), title: `第 ${(s.deck?.slides.length ?? 0) + 1} 页`, section: '', notes: '', locked: false, elements: [] }; void owner.operations([{ op: 'create_slide', slide: next }]).then(accepted => { if (accepted) { setSlideId(next.id); setElementId('') } }) }
  const openDetails = (value: NonNullable<typeof details>) => { if (protect()) { detailsTrigger.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setDetails(value); setMenu(false) } }
  const openAssistant = () => { if (protect()) { setAssistant(true); setTab(manual ? 'properties' : 'chat') } }
  function resizeStart(event: PointerEvent<HTMLElement>) { if (event.button !== 0) return; event.preventDefault(); resize.current = { target: event.currentTarget, pointer: event.pointerId, x: event.clientX, width: panelWidth }; event.currentTarget.setPointerCapture?.(event.pointerId) }
  const clarification = ['CLARIFYING', 'AWAITING_CONFIRMATION'].includes(s.agent?.requirementsState ?? '') && !['STOPPED', 'FAILED', 'STOPPING'].includes(s.generation?.state ?? '')
  const heading = s.generation?.recovery?.retryAt ? '等待自动恢复' : clarification ? s.agent?.requirementsState === 'AWAITING_CONFIRMATION' ? '请确认制作需求' : '先聊清你的想法' : s.generation ? pptGenerationLabel(s.generation.state) : active ? pptRunLabel(s.agent?.state ?? 'IDLE') : s.document?.phase === 'BRIEFING' ? '需求讨论中' : '让我们继续完成这份演示'
  const critical = <>{(s.error || localError || download.error) && <p role="alert">{s.error || localError || download.error}</p>}{s.pending && <div className="w3-ppt-critical" data-operation-phase={s.pending.phase}><strong>{s.pending.phase === 'ACCEPTED_READBACK' ? '原写入已接受，等待读取结果' : s.busy ? '原操作正在提交' : '原操作结果待核对'}</strong><p>身份与正文已冻结；不会自动换 key 或重复提交。文件仅保留在当前内存中，不承诺跨刷新恢复。</p>{button(s.pending.phase === 'ACCEPTED_READBACK' || ['message', 'upload', 'stop', 'retry-job'].includes(s.pending.kind) ? 'receipt.readOriginal' : 'receipt.retryOriginal', () => void owner.recover(), !s.busy)}{s.pending.phase === 'UNKNOWN' && ['message', 'upload'].includes(s.pending.kind) && button('receipt.retryOriginal', () => void owner.retryOriginal(), !s.busy)}{s.pending.kind === 'upload' && <label>核对原上传文件<input type="file" disabled={s.busy} onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void owner.reselectFile(file) }} /></label>}</div>}{s.disconnected && <p role="status">连接暂时中断，正在核对作品。制作状态以服务器为准。</p>}{s.capabilities && !s.capabilities.renderingAvailable && <p role="alert">{s.capabilities.renderingMessage || '页面预览与导出服务暂时不可用；现有作品和草稿仍保留。'}</p>}{(s.error || localError) && button('ui.refresh', () => { setLocalError(''); void owner.refresh() }, !s.busy, '核对作品')}</>
  return <div ref={root as React.Ref<HTMLDivElement>} className="w3-ppt-studio" style={{ '--w3-ppt-panel-width': `${panelWidth}px` } as React.CSSProperties} data-ppt-document={props.documentId}>
    <PageChrome title={s.document?.title ?? 'PPT 工作室'} objectKey="nav.ppt" status={critical} actions={<><PageLink to="/ppt" navigation={props.navigation}>返回作品列表</PageLink><SkinControl skin={props.skin} setSkin={props.setSkin} />{ready && button(manual ? 'ui.cancelEditing' : 'ppt.editObject', () => { if (protect()) { setManual(!manual); setTools(null); setAssistant(!manual); setTab('properties') } }, !active && !s.document?.archived && !s.historical && !s.pending && !s.busy, manual ? '结束手动编辑' : '手动编辑')}{ready && !s.historical && <UiActionButton actionKey="ppt.download" variant="primary" busy={download.busy} availability={available(!!exportArtifact || !active && !s.busy && !s.pending && !s.document?.archived && !!s.capabilities?.renderingAvailable && ['REVIEW', 'EXPORTED'].includes(s.document?.phase ?? ''))} onAction={() => { if (exportArtifact) void download.download(exportArtifact); else { requestedExport.current = s.document?.revision ?? null; void owner.createJob('EXPORT').then(accepted => { if (!accepted) requestedExport.current = null }) } }} />}<div className="w3-ppt-menus">{button('ui.open', () => setMenu(!menu), !!s.document, '作品菜单')}{menu && <div className="w3-ppt-popup" onKeyDown={event => { if (event.key === 'Escape') { event.stopPropagation(); setMenu(false) } }}>{ready && <>{button('ppt.openSources', () => openDetails('sources'))}{button('ppt.openHistory', () => openDetails('history'))}{button('ppt.openPlan', () => openDetails('plan'))}</>}{button(s.document?.archived ? 'ppt.restoreArchive' : 'ppt.archive', () => confirm(s.document?.archived ? '恢复这份作品？' : '归档这份作品？作品与历史版本仍保留。', () => { void owner.action('archive', { archived: !s.document?.archived }).then(accepted => { if (accepted) setMenu(false) }) }, s.document?.archived ? 'ppt.restoreArchive' : 'ppt.archive'), !active && !s.busy && !s.pending)}</div>}</div></>} context={ready ? <UiContextPanel open={assistant} title={tab === 'chat' ? 'PPT 助手' : element ? '对象属性' : '页面属性'} returnFocus={assistantTrigger} expanded={expanded} onExpandedChange={setExpanded} onClose={() => { if (protect()) { setAssistant(false); setElementId(''); setScopeKind('DOCUMENT') } }} closePolicy={propertyDirty ? { kind: 'block', reason: '输入尚未保存，请核对属性；草稿仍保留。' } : { kind: 'allow' }}>
      <nav className="ppt-tabs" aria-label="助手与属性"><button role="tab" aria-selected={tab === 'chat'} onClick={() => { if (protect()) setTab('chat') }}>讨论</button><button role="tab" aria-selected={tab === 'properties'} disabled={!manual || !slide} onClick={() => setTab('properties')}>属性</button></nav>
      {tab === 'chat' ? <PptChat owner={owner} state={s} scope={scope} scopeLabel={scopeLabel} ready disabled={!!s.document?.archived || !!s.historical || propertyDirty} skin={props.skin} onDocumentScope={() => setScopeKind('DOCUMENT')} /> : slide && <><PptProperties owner={owner} state={s} slide={slide} element={element} />{element && button('ppt.removeObject', () => deleteElement(), editable && !slide.locked && !element.locked)}</>}
    </UiContextPanel> : undefined}>
      {s.loading && <p role="status">正在读取作品…</p>}
      {s.document && <p className="w3-ppt-meta">{pptPhaseLabel(s.document.phase)} · 版本 {s.document.revision} · 模型 {s.document.model}{s.document.archived && ' · 已归档'}</p>}
      {!ready && !s.loading && <section className="w3-ppt-generation"><h2>{heading}</h2><p>{s.generation?.detail || (clarification ? '确认下面的需求后，助手才会开始第一轮设计。' : '随时补充你的要求；确认需求并执行后才开始制作。')}</p>{s.generation && !clarification && <ol className="ppt-generation-steps">{(['PLANNING', 'PRODUCING', 'PREVIEW', 'EXPORT'] as const).map(step => <li key={step} aria-current={s.generation?.step === step ? 'step' : undefined}>{pptGenerationStepLabel(step)}</li>)}</ol>}{s.generation?.recovery && s.generation.recovery.revision === s.document?.revision && <p>已通过 {s.generation.recovery.completedPages} 页检查，待补充 {s.generation.recovery.missingPages} 页，待检查问题 {s.generation.recovery.issues} 项</p>}{s.generation?.canResume && button('ppt.resume', () => void owner.resume(), !s.busy && !s.pending, '按当前要求继续')}<PptChat owner={owner} state={s} scope={{ kind: 'DOCUMENT' }} scopeLabel="整份演示文稿" ready={false} disabled={!!s.document?.archived} skin={props.skin} onDocumentScope={() => setScopeKind('DOCUMENT')} /></section>}
      {ready && scene && <>
        {s.historical && <p role="status">正在查看历史版本 {s.historical.revision}，此版本只读。{button('ui.open', () => { owner.returnCurrent(); setManual(false) }, true, '回到当前草稿')}</p>}
        {active && <div className="w3-ppt-critical"><strong>{s.generation ? pptGenerationLabel(s.generation.state) : '助手正在处理'}</strong><p>{s.generation?.detail || s.agent?.detail}</p>{button('ppt.stop', () => void owner.stop(), !s.busy && !s.pending && s.agent?.state !== 'STOPPING' && s.generation?.state !== 'STOPPING')}</div>}
        {!active && s.generation?.canResume && button('ppt.resume', () => void owner.resume(), !s.busy && !s.pending, '按当前要求继续')}
        <section aria-label="制作进度">{s.jobs.filter(job => ['PREPARED', 'PENDING', 'QUEUED', 'RUNNING'].includes(job.state) || job.state === 'FAILED' && job.revision === s.document?.revision).slice(0, 3).map(job => <article key={job.id} className="ppt-progress"><strong>{job.kind === 'EXPORT' ? '导出 PPTX' : '生成页面预览'} · {pptJobLabel(job.state)}</strong><p>{job.completed}/{job.total} · 版本 {job.revision}{job.revision !== s.document?.revision && '（草稿已有更新）'}</p>{job.total > 0 && job.state !== 'FAILED' && <progress value={job.completed} max={job.total} />}{job.detail && <p>{job.detail}</p>}{job.state === 'FAILED' && button('ui.retry', () => void owner.retryJob(job.id), !s.busy && !s.pending, '继续未完成页面')}{button('ppt.openHistory', () => openDetails('history'))}</article>)}</section>
        {slide ? <div className="w3-ppt-scene"><header className="w3-ppt-scene-heading"><h2>{slide.title || `第 ${scene.slides.indexOf(slide) + 1} 页`}</h2><div className="w3-ppt-actions">{button('ui.previous', () => selectSlide(scene.slides[scene.slides.indexOf(slide) - 1]!.id), scene.slides.indexOf(slide) > 0, '页面')}{button('ui.next', () => selectSlide(scene.slides[scene.slides.indexOf(slide) + 1]!.id), scene.slides.indexOf(slide) < scene.slides.length - 1, '页面')}<UiActionButton actionKey="ui.open" target="PPT 助手" buttonRef={assistantTrigger} onAction={openAssistant} /></div></header>
          {manual && <div className="w3-ppt-menus"><div className="w3-ppt-actions">{button('ppt.addObject', () => setTools(tools === 'insert' ? null : 'insert'), editable && !slide.locked && !propertyDirty)}{button('ui.open', () => setTools(tools === 'page' ? null : 'page'), true, '页面设置')}</div>{tools === 'insert' && <div className="w3-ppt-popup">{['text', 'shape', 'line', 'table', 'chart'].map(type => <div key={type}>{button('ppt.addObject', () => void addElement(type), editable && !slide.locked, pptElementLabel(type))}</div>)}{button('ppt.uploadImage', () => openDetails('sources'), editable && !slide.locked)}</div>}{tools === 'page' && <div className="w3-ppt-popup"><div className="w3-ppt-actions">{button(slide.locked ? 'ppt.unlockSlide' : 'ppt.lockSlide', () => void owner.operations([{ op: 'update_slide', slideId: slide.id, patch: { locked: !slide.locked } }]), editable && !propertyDirty)}{button('ppt.duplicateSlide', () => slideAction('duplicate_slide'), editable && !propertyDirty)}{button('ppt.deleteSlide', () => slideAction('delete_slide'), editable && !slide.locked && !propertyDirty)}{button('ppt.moveSlideUp', () => slideAction('move_slide', scene.slides.indexOf(slide) - 1), editable && scene.slides.indexOf(slide) > 0 && !propertyDirty)}{button('ppt.moveSlideDown', () => slideAction('move_slide', scene.slides.indexOf(slide) + 1), editable && scene.slides.indexOf(slide) < scene.slides.length - 1 && !propertyDirty)}</div><label>页面版式<select value={layout} disabled={!editable || slide.locked || propertyDirty} onChange={event => setLayout(event.target.value)}>{s.capabilities?.layouts.map(layout => <option key={layout} value={layout}>{pptLayoutLabel(layout)}</option>)}</select></label>{button('ppt.applyLayout', () => void owner.operations([{ op: 'apply_layout', slideId: slide.id, layout }]), editable && !slide.locked && !propertyDirty)}<label>演示主题<select value={scene.theme} disabled={!editable || propertyDirty} onChange={event => { void owner.operations([{ op: 'apply_theme', theme: event.target.value }]).then(async accepted => { if (accepted) await owner.createJob('PREVIEW') }) }}>{s.capabilities?.themes.map(theme => <option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label>{element && <div className="w3-ppt-actions">{button('ppt.bringToFront', () => void owner.operations([{ op: 'move_element', slideId: slide.id, elementId: element.id, index: slide.elements.length - 1 }]), editable && !slide.locked && !element.locked && !propertyDirty)}{button('ppt.sendToBack', () => void owner.operations([{ op: 'move_element', slideId: slide.id, elementId: element.id, index: 0 }]), editable && !slide.locked && !element.locked && !propertyDirty)}</div>}</div>}</div>}
          {element && <div className="w3-ppt-selection"><strong>{pptElementLabel(element.type)}</strong>{button('ppt.editObject', () => { setAssistant(true); setTab('properties') }, manual, '对象属性')}{button('ui.open', () => { if (protect()) { setAssistant(true); setTab('chat') } }, true, '讨论此对象')}{button('ui.close', () => selectElement(''), !propertyDirty, '取消对象选择')}</div>}
          {previewArtifact || manual ? <div className="ppt-page"><PptCanvasView deck={scene} slide={slide} selected={elementId} preview={previewArtifact ? pptApi.artifactUrl(props.documentId, previewArtifact.id) : undefined} previewRevision={previewJob?.revision} revision={revision} editing={manual} disabled={!manual || !editable || propertyDirty} onSelect={selectElement} onPatch={(id, patch, base) => void patchElement(id, patch, base)} onRemove={id => deleteElement(id)} /></div> : <div className="ppt-empty">页面预览暂时不可用。{button('ppt.preview', () => void owner.createJob('PREVIEW', slide.id), editable && !studioJobsActive(s) && !!s.capabilities?.renderingAvailable)}</div>}
          {manual && <footer className="w3-ppt-actions"><span>修改自动保存</span>{button('ppt.check', () => void owner.check(), !s.busy, '检查页面')}{button('ppt.preview', () => void owner.createJob('PREVIEW', slide.id), editable && !propertyDirty && !!s.capabilities?.renderingAvailable, '更新页面预览')}</footer>}
          {!!s.issues.length && s.checkedRevision === s.document?.revision && <ul aria-label="页面检查问题">{s.issues.map((issue, index) => <li key={index}><button onClick={() => { if (protect()) { setSlideId(issue.slideId); setElementId(issue.elementId); setAssistant(true); setTab('properties') } }}>{issue.severity} · {issue.message}</button></li>)}</ul>}
          {assistant && <div role="separator" aria-orientation="vertical" aria-label="调整助手宽度" aria-valuemin={280} aria-valuemax={520} aria-valuenow={panelWidth} tabIndex={0} className="w3-ppt-resize" onPointerDown={resizeStart} onPointerMove={event => { const gesture = resize.current; if (gesture && gesture.pointer === event.pointerId) setPanelWidth(Math.max(280, Math.min(520, gesture.width - (event.clientX - gesture.x)))) }} onPointerUp={() => { cancelResize(); saveWidth(panelWidth) }} onPointerCancel={cancelResize} onLostPointerCapture={cancelResize} onKeyDown={event => { if (['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) { event.preventDefault(); const width = Math.max(280, Math.min(520, event.key === 'Home' ? 280 : event.key === 'End' ? 520 : panelWidth + (event.key === 'ArrowLeft' ? 20 : -20))); setPanelWidth(width); saveWidth(width) } }} />}
        </div> : <div className="ppt-empty">当前作品没有页面。{button('ppt.addSlide', addSlide, editable)}</div>}
        <div className="ppt-page"><PptSlideNavigatorView deck={scene} selected={slide?.id ?? ''} previews={previews} manual={manual} disabled={!editable || propertyDirty} onSelect={selectSlide} onAdd={addSlide} /></div>
      </>}
    <div style={{ '--w3-ppt-panel-width': `${panelWidth}px` } as React.CSSProperties} className="w3-ppt-detail-host"><UiContextPanel open={!!details} title={details === 'sources' ? '资料与素材' : details === 'history' ? '版本与导出' : '制作方案'} returnFocus={detailsTrigger} expanded onClose={() => setDetails(null)}>{details === 'sources' ? <PptSources owner={owner} state={s} skin={props.skin} insert={id => { if (protect()) { setDetails(null); setManual(true); void addElement('image', id) } }} /> : details === 'history' ? <PptHistory owner={owner} state={s} confirm={confirm} view={revision => { if (protect()) { void owner.inspectRevision(revision).then(accepted => { if (accepted) { setManual(false); setElementId(''); setDetails(null) } }) } }} /> : details === 'plan' ? <><p>助手使用这份方案组织内容和页面。</p>{!['BRIEFING', 'DIRECTION', 'DESIGN'].includes(s.document?.phase ?? '') ? button('ppt.reopenPlan', () => confirm('修改制作方案？现有页面和导出会保留。', () => void owner.action('reopen'), 'ppt.reopenPlan'), editable) : button('ppt.generate', () => { void owner.generate('请按照当前已保存的制作方案和资料，重新完成演示文稿制作。').then(accepted => { if (accepted) setDetails(null) }) }, editable && !Object.values(s.drafts).some(draft => draft.kind === 'plan' && draft.dirty))}<PptPlanEditor owner={owner} state={s} confirm={confirm} /></> : null}</UiContextPanel></div>
    <UiConfirmDialog open={!!confirmation} title={confirmation?.title ?? '确认操作'} confirmActionKey={confirmation?.actionKey ?? 'ui.delete'} onCancel={() => setConfirmation(null)} policy={s.pending || s.busy ? { kind: 'block', reason: '原操作尚未确认，请先核对。' } : { kind: 'allow' }} onConfirm={() => { const current = confirmation; setConfirmation(null); if (!s.pending && !s.busy) current?.action() }}>{confirmation?.title}</UiConfirmDialog>
    {studioDirty(s) && <span className="w3-ppt-draft-marker" data-ppt-dirty="true">草稿仍保留</span>}
    </PageChrome>
  </div>
}
