import { act, cleanup, fireEvent, render, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { readFileSync } from 'node:fs'
import { api } from '@/api/client'
import { newNode, emptyGraph } from '@/components/workflow/graph'
import { commandPreset, verificationPreset } from '@/components/workflow/workflowTestFixtures'
import { pageFrame, foundationDOM, deferred, flush } from '@/pages/w2/workflow/page.test-support'
import { semanticName } from '@/foundation/semanticRegistry'
import type { RoleDetail, RoleRevision, WorkflowNode, WorkflowPreset } from '@/types/domain'
import { WorkflowNodeEditor } from './WorkflowNodeEditor'
import { WorkflowPublicInputs } from './WorkflowPublicInputs'
import { WorkflowRolePicker } from './WorkflowRolePicker'
import { WorkflowCommandEditor, WorkflowDocumentReviewEditor, WorkflowSourceDesignEditor, WorkflowVerificationEditor } from './NodeSpecialists'
const presets = (JSON.parse(readFileSync('../src/main/resources/workflows/node-presets.json', 'utf8')) as { presets: WorkflowPreset[] }).presets
const preset = (module: string) => presets.find(p => p.node.moduleId === module)!.node
const role: RoleDetail = { roleId: 'designer', displayName: '设计师', description: '', origin: 'BUILTIN', latestRevisionId: 'published', latestRevisionNumber: 2, activeSlots: [] }
const revision = (id = 'published', number = 2, slots = ['WORKFLOW_READ_ONLY']): RoleRevision => ({ roleId: role.roleId, revisionId: id, revisionNumber: number, contentSha256: 'hash', promptFragments: {}, manifest: { allowedSlots: slots, workInstructions: '分析授权资料' } })
beforeEach(() => { foundationDOM(); vi.spyOn(api, 'getRoles').mockResolvedValue({ items: [role] }); vi.spyOn(api, 'getRole').mockResolvedValue(role); vi.spyOn(api, 'getRoleRevision').mockResolvedValue(revision()); vi.spyOn(api, 'getRoleRevisions').mockResolvedValue({ items: [{ revisionId: 'published', revisionNumber: 2, contentSha256: 'hash' }] }) })
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
const settle = () => act(async () => { await flush() })
function nodeEditor(node: WorkflowNode, disabled = false) { const change = vi.fn(), graph = { ...emptyGraph(), nodes: [node] }; const view = render(pageFrame(<WorkflowNodeEditor node={node} graph={graph} disabled={disabled} onChange={change} onRemove={() => {}} />)); return { view, change } }
it('command edits keep argv boundaries, exact whitespace and unrelated params; locked controls remain disabled', async () => {
  const node = { ...commandPreset().node, parameters: { ...commandPreset().node.parameters, untouched: 'keep', commandVerification: JSON.stringify({ version: 1, inputName: 'code', argv: ['npm', 'arg with space'], timeoutSeconds: 300, purpose: 'TEST', outputContains: null }) } }, change = vi.fn(), view = render(pageFrame(<WorkflowCommandEditor node={node} onChange={change} />))
  fireEvent.change(view.getByRole('textbox', { name: '参数 1' }), { target: { value: 'two words' } }); expect(JSON.parse(change.mock.calls[0]![0].parameters.commandVerification).argv).toEqual(['npm', 'two words'])
  fireEvent.change(view.getByRole('textbox', { name: '输出须包含（可选）' }), { target: { value: '  exact\nline  ' } }); const changed = change.mock.calls[1]![0]; expect(JSON.parse(changed.parameters.commandVerification).outputContains).toBe('  exact\nline  '); expect(changed.parameters.untouched).toBe('keep'); expect(node.parameters.untouched).toBe('keep')
  view.rerender(pageFrame(<WorkflowCommandEditor node={node} disabled onChange={change} />)); expect(view.getByRole('textbox', { name: '执行程序' }).matches(':disabled')).toBe(true)
})
it('unreadable command configuration requires actual confirmation and never rewrites malformed bytes on mount', async () => {
  const node = { ...commandPreset().node, parameters: { commandVerification: 'original invalid bytes' } }, change = vi.fn(), view = render(pageFrame(<WorkflowCommandEditor node={node} onChange={change} />)); expect(change).not.toHaveBeenCalled(); expect(view.getByRole('alert').textContent).toContain('无法读取')
  fireEvent.click(view.getByRole('button', { name: semanticName('workflow.editConfiguration', '检查命令') })); await settle(); expect(change).not.toHaveBeenCalled(); fireEvent.click(within(view.getByRole('dialog')).getByRole('button', { name: semanticName('workflow.editConfiguration') })); await settle(); expect(JSON.parse(change.mock.calls[0]![0].parameters.commandVerification)).toMatchObject({ argv: [], timeoutSeconds: 300 })
})
it('file verification preserves exact criterion and confirms removing a check; invalid config is retained', async () => {
  const base = verificationPreset().node, node = { ...base, parameters: { ...base.parameters, retained: 'yes', verification: JSON.stringify({ version: 1, inputName: 'code', checks: [{ title: '内容', type: 'FILE_CONTENT', path: 'a', expected: '', matchMode: 'EXACT' }] }) } }, change = vi.fn(), view = render(pageFrame(<WorkflowVerificationEditor node={node} onChange={change} />))
  fireEvent.change(view.getByRole('textbox', { name: '期望文本' }), { target: { value: '  exact\nline ' } }); expect(JSON.parse(change.mock.calls[0]![0].parameters.verification).checks[0].expected).toBe('  exact\nline '); expect(change.mock.calls[0]![0].parameters.retained).toBe('yes')
  fireEvent.click(view.getByRole('button', { name: semanticName('ui.delete', '内容') })); await settle(); expect(change).toHaveBeenCalledTimes(1); fireEvent.click(within(view.getByRole('dialog')).getByRole('button', { name: semanticName('ui.delete') })); await settle(); expect(JSON.parse(change.mock.calls[1]![0].parameters.verification).checks).toEqual([])
})
it('source target paths preserve whitespace and other parameters, with malformed selection guarded until explicit reset', async () => {
  const node = { ...preset('source.design'), parameters: { kept: 'yes', targetPaths: JSON.stringify([' src/Main.java ']) } }, change = vi.fn(), view = render(pageFrame(<WorkflowSourceDesignEditor node={node} onChange={change} />)); fireEvent.change(view.getByRole('textbox', { name: '本批源码文件' }), { target: { value: ' src/Main.java \nsrc/Other.java' } }); expect(JSON.parse(change.mock.calls[0]![0].parameters.targetPaths)).toEqual([' src/Main.java ', 'src/Other.java']); expect(change.mock.calls[0]![0].parameters.kept).toBe('yes')
  view.rerender(pageFrame(<WorkflowSourceDesignEditor node={{ ...node, parameters: { targetPaths: 'broken' } }} onChange={change} />)); expect(view.getByRole('alert').textContent).toContain('原配置已保留'); expect(change).toHaveBeenCalledTimes(1)
})
it('document selected sections use readable ordinals, retain unrelated settings and keep expert outputs/completion', async () => {
  const node = { ...preset('document.direct-review'), parameters: { kept: 'yes', documentSections: JSON.stringify([{ fileId: 'DOC-1', section: 1 }]), documentBatchOrdinal: '0' } }, change = vi.fn(), view = render(pageFrame(<WorkflowDocumentReviewEditor node={node} onChange={change} />))
  fireEvent.change(view.getByRole('spinbutton', { name: '原文 1 文档序号' }), { target: { value: '2' } }); expect(JSON.parse(change.mock.calls[0]![0].parameters.documentSections)).toEqual([{ fileId: 'DOC-2', section: 1 }]); fireEvent.change(view.getByRole('spinbutton', { name: '评审批次序号' }), { target: { value: '3' } }); expect(change.mock.calls[1]![0].parameters).toMatchObject({ kept: 'yes', documentBatchOrdinal: '2' }); expect(change.mock.calls[1]![0].outputs).toEqual(node.outputs)
})
it.each([
  ['system.git.history', '采集时限（秒）', 'historyTimeoutSeconds', '300'], ['system.repository.snapshot', '采集时限（秒）', 'repositoryTimeoutSeconds', '120'], ['system.source.test-run', '执行时限（秒）', 'testTimeoutSeconds', '30'], ['history.review', '历史审查批次', 'historyBatchOrdinal', '2'], ['snapshot.analyze', '版本分析批次', 'snapshotBatchOrdinal', '2'],
] as const)('specialist numeric %s remains structured and retains unrelated parameters', (module, label, key, value) => { const node = { ...preset(module), parameters: { ...preset(module).parameters, retained: 'yes' } }, { view, change } = nodeEditor(node); fireEvent.change(view.getByRole('spinbutton', { name: label }), { target: { value } }); const changed: WorkflowNode = change.mock.calls[0]![0]; expect(changed.parameters.retained).toBe('yes'); expect(changed.parameters[key]).toBe(key.endsWith('Ordinal') ? String(Number(value) - 1) : value); expect(changed.outputs).toEqual(node.outputs); expect(changed.completion).toEqual(node.completion) })
it.each([
  ['system.source.test-summary', '单测独立复核策略', 'reviewPolicy', 'NONE'], ['system.snapshot.report', '版本报告复核策略', 'reviewPolicy', 'NONE'], ['system.history.report', '历史报告类型', 'historyReportKind', 'CONTRIBUTION_REPORT'], ['snapshot.analyze', '历史分析复用', 'snapshotReuse', 'BYPASS'], ['system.source.snapshot', '采集用途', 'sourcePurpose', 'UNIT_TEST'],
] as const)('specialist selection %s uses domain choices, not generic JSON', (module, label, key, value) => { const node = { ...preset(module), parameters: { ...preset(module).parameters, retained: 'yes' } }, { view, change } = nodeEditor(node); fireEvent.change(view.getByRole('combobox', { name: label }), { target: { value } }); expect(change.mock.calls[0]![0].parameters).toEqual({ ...node.parameters, [key]: value }); expect(change.mock.calls[0]![0].outputs).toEqual(node.outputs) })
it('review mode adjusts only date bindings, with downstream public date synchronization left to graph owner', () => { const node = preset('system.review.snapshot'), { view, change } = nodeEditor(node); fireEvent.change(view.getByRole('combobox', { name: '版本审查范围' }), { target: { value: 'FULL' } }); const changed: WorkflowNode = change.mock.calls[0]![0]; expect(changed.inputs.some(i => ['startDate', 'endDate'].includes(i.name))).toBe(false); expect(changed.inputs.filter(i => !['startDate', 'endDate'].includes(i.name))).toEqual(node.inputs.filter(i => !['startDate', 'endDate'].includes(i.name))); expect(changed.parameters).toEqual({ ...node.parameters, reviewMode: 'FULL' }) })
it.each(['source.design', 'source.test-design', 'source.test-write', 'source.test-review', 'document.direct-review', 'history.review', 'snapshot.analyze'])('professional %s fixed deliverables/outcomes cannot be deleted or replaced by unsupported success kind', module => { const node = preset(module), { view } = nodeEditor(node, true); expect(view.getByRole('region', { name: '专业交付物' })).toBeTruthy(); expect(view.queryByRole('button', { name: semanticName('workflow.addOutput') })).toBeNull(); expect(view.queryByRole('button', { name: semanticName('workflow.addOutcome') })).toBeNull(); expect(view.getByRole('textbox', { name: '名称' }).matches(':disabled')).toBe(true) })
it('outcomes referenced by an edge or expected completion cannot be removed', () => { const node = { ...newNode('human'), outcomes: ['pass'], completion: { ...newNode('human').completion, expectedOutcome: 'pass' } }, change = vi.fn(), view = render(pageFrame(<WorkflowNodeEditor node={node} graph={{ ...emptyGraph(), nodes: [node] }} onChange={change} onRemove={() => {}} />)); fireEvent.click(view.getByRole('button', { name: semanticName('ui.delete', '通过') })); expect(view.getByRole('alert').textContent).toContain('仍被完成规则'); expect(change).not.toHaveBeenCalled() })
it.each(['free.write', 'source.test-write'])('role revisions enforce explicit allowed slot for %s and do not silently substitute latest', async module => { const change = vi.fn(), label = vi.fn(), node = { ...newNode('free.write'), moduleId: module }, view = render(pageFrame(<WorkflowRolePicker node={node} onChange={change} onLabel={label} />)); await settle(); fireEvent.change(view.getByRole('combobox', { name: '选择执行角色' }), { target: { value: role.roleId } }); await settle(); expect(change).not.toHaveBeenCalled(); expect(view.getByRole('alert').textContent).toContain('不支持当前工作类型'); vi.mocked(api.getRoleRevision).mockResolvedValue(revision('published', 2, ['WORKFLOW_WRITE'])); fireEvent.change(view.getByRole('combobox', { name: '选择执行角色' }), { target: { value: role.roleId } }); await settle(); expect(change).toHaveBeenCalledWith(role.roleId, 'published'); expect(label).toHaveBeenCalledWith(role.roleId, role.displayName) })
it('late role label/choice cannot apply to a changed revision or a locked node', async () => {
  const pending = deferred<RoleRevision>(); vi.mocked(api.getRoleRevision).mockImplementation((_id, rev) => rev === 'old' ? pending.promise : Promise.resolve(revision()))
  const node = { ...newNode('free.readonly'), roleId: role.roleId, roleRevisionId: 'old' }, change = vi.fn(), label = vi.fn(), view = render(pageFrame(<WorkflowRolePicker node={node} onChange={change} onLabel={label} />)); await settle(); view.rerender(pageFrame(<WorkflowRolePicker node={{ ...node, roleRevisionId: 'published' }} onChange={change} onLabel={label} />)); await settle(); pending.resolve(revision('old', 1)); await settle(); expect(view.getByText('设计师 · v2')).toBeTruthy(); expect(view.queryByText('设计师 · v1')).toBeNull(); expect(change).not.toHaveBeenCalled()
})
it('confirmation opened for malformed original command cannot reset a later node/config projection', async () => {
  const node = { ...commandPreset().node, parameters: { commandVerification: 'original-invalid' } }, change = vi.fn(), view = render(pageFrame(<WorkflowCommandEditor node={node} onChange={change} />))
  fireEvent.click(view.getByRole('button', { name: semanticName('workflow.editConfiguration', '检查命令') })); await settle()
  const next = { ...node, id: 'new-selected', parameters: { commandVerification: 'later-invalid' } }; view.rerender(pageFrame(<WorkflowCommandEditor node={next} onChange={change} />)); await settle()
  const confirm = within(view.getByRole('dialog')).getByRole('button', { name: semanticName('workflow.editConfiguration') }); expect(confirm.matches(':disabled')).toBe(true); fireEvent.click(confirm); expect(change).not.toHaveBeenCalled(); expect(next.parameters.commandVerification).toBe('later-invalid')
})
it('free node bindings, deliverable kind, outcome labels, retry and pause remain individual controlled fields', () => {
  const node = { ...newNode('free.write'), inputs: [{ name: 'material', source: 'NODE' as const, sourceId: '', output: '', kind: 'TEXT' as const, required: true }], outcomes: ['pass'] }, change = vi.fn(), graph = { ...emptyGraph(), nodes: [node], inputs: [{ name: 'documents', title: '需求原文', kind: 'DOCUMENT' as const, required: true }] }, view = render(pageFrame(<WorkflowNodeEditor node={node} graph={graph} onChange={change} onRemove={() => {}} />))
  fireEvent.change(view.getByRole('combobox', { name: '使用交付物' }), { target: { value: 'REQUIREMENT|documents|documents' } }); expect(change.mock.calls[0]![0].inputs[0]).toMatchObject({ source: 'REQUIREMENT', sourceId: 'documents', output: null, kind: 'DOCUMENT' })
  fireEvent.change(within(view.getByRole('group', { name: '预期交付物' })).getAllByRole('combobox', { name: '内容类型' })[0]!, { target: { value: 'CODE' } }); expect(change.mock.calls[1]![0].outputs[0].kind).toBe('CODE')
  fireEvent.change(view.getByRole('textbox', { name: '业务结果名称' }), { target: { value: '中文继续' } }); expect(JSON.parse(change.mock.calls[2]![0].parameters.outcomeTitles)).toEqual({ pass: '中文继续' }); expect(change.mock.calls[2]![0].outcomes).toEqual(['pass'])
  fireEvent.change(view.getByRole('spinbutton', { name: '失败自动重试次数' }), { target: { value: '5' } }); expect(change.mock.calls[3]![0].maxRetries).toBe(5)
  fireEvent.click(view.getByRole('checkbox', { name: '执行后暂停检查' })); expect(change.mock.calls[4]![0].pauseAfter).toBe(true); expect(change.mock.calls[4]![0].inputs).toEqual(node.inputs)
})
it('foreign role revision DTO cannot relabel or bind the selected node', async () => {
  vi.mocked(api.getRoleRevision).mockResolvedValue({ ...revision(), roleId: 'other-role' }); const change = vi.fn(), label = vi.fn(), view = render(pageFrame(<WorkflowRolePicker node={newNode('free.readonly')} onChange={change} onLabel={label} />)); await settle(); fireEvent.change(view.getByRole('combobox', { name: '选择执行角色' }), { target: { value: role.roleId } }); await settle(); expect(view.getByRole('alert').textContent).toContain('所选身份不一致'); expect(change).not.toHaveBeenCalled(); expect(label).not.toHaveBeenCalled()
})

it('pending removal confirmation cannot discard a changed public input declaration', async () => {
  const graph = { ...emptyGraph(), inputs: [{ name: 'source', title: '资料', kind: 'TEXT' as const, required: false }] }, change = vi.fn(), view = render(pageFrame(<WorkflowPublicInputs graph={graph} onChange={change} />))
  fireEvent.click(view.getByRole('button', { name: semanticName('ui.delete', '公共资料 资料') })); await settle()
  const next = { ...graph, inputs: [{ ...graph.inputs[0]!, title: '新的资料', required: true }] }; view.rerender(pageFrame(<WorkflowPublicInputs graph={next} onChange={change} />)); await settle()
  const confirm = within(view.getByRole('dialog')).getByRole('button', { name: semanticName('ui.delete', '资料') }); expect(confirm.matches(':disabled')).toBe(true); fireEvent.click(confirm); expect(change).not.toHaveBeenCalled(); expect(next.inputs).toHaveLength(1)
})
