import { useState } from 'react'
import type { WorkflowInput, WorkflowNode } from '@/types/domain'
import { UiActionButton, UiConfirmDialog } from '@/foundation/components'

export interface NodeFieldsProps { node: WorkflowNode; disabled?: boolean; onChange(node: WorkflowNode): void }
export function jsonParameter<T>(raw: string | undefined, valid: (value: unknown) => value is T): T | null {
  try { const value: unknown = JSON.parse(raw || '{}'); return valid(value) ? value : null } catch { return null }
}
export const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value)
const configurationIdentity = (node: WorkflowNode, key: string) => JSON.stringify([node.id, node.parameters[key]])
const keys = (value: Record<string, unknown>, permitted: string[]) => Object.keys(value).every(key => permitted.includes(key))
type CommandSpec = { version: number; inputName: string; argv: string[]; timeoutSeconds: number; purpose: 'TEST' | 'CHECK'; outputContains: string | null }
type Check = { title: string; type: string; path: string; expected: string | null; matchMode: string | null }
type FileSpec = { version: number; inputName: string; checks: Check[] }
export function WorkflowCommandEditor({ node, disabled, onChange }: NodeFieldsProps) {
  const [reset, setReset] = useState<string | null>(null)
  const spec = jsonParameter(node.parameters.commandVerification, (v): v is CommandSpec => object(v) && v.version === 1 && typeof v.inputName === 'string' && Array.isArray(v.argv) && v.argv.every(arg => typeof arg === 'string') && Number.isInteger(v.timeoutSeconds) && ['TEST', 'CHECK'].includes(String(v.purpose)) && (v.outputContains == null || typeof v.outputContains === 'string') && keys(v, ['version', 'inputName', 'argv', 'timeoutSeconds', 'purpose', 'outputContains']))
  const sources = node.inputs.filter(input => input.kind === 'CODE' && input.source === 'NODE' && input.required)
  const change = (value: CommandSpec) => { if (!disabled) onChange({ ...node, parameters: { ...node.parameters, commandVerification: JSON.stringify(value) } }) }
  const patch = (value: Partial<CommandSpec>) => { if (spec) change({ ...spec, ...value }) }
  const argument = (index: number, value: string) => { if (spec) { const argv = [...spec.argv]; argv[index] = value; patch({ argv }) } }
  return <fieldset className="workflow-fields" disabled={disabled}><legend>检查命令</legend>{spec ? <>
    <label>检查哪份代码<select value={spec.inputName} onChange={e => patch({ inputName: e.target.value })}>{!sources.some(input => input.name === spec.inputName) && <option value={spec.inputName} disabled>请选择有效的上游代码输入</option>}{sources.map(input => <option key={input.name} value={input.name}>{input.name}</option>)}</select></label>
    <label>检查用途<select value={spec.purpose} onChange={e => patch({ purpose: e.target.value as CommandSpec['purpose'] })}><option value="TEST">运行测试</option><option value="CHECK">运行其他检查</option></select></label>
    <label>执行程序<input value={spec.argv[0] || ''} maxLength={4096} placeholder="例如 mvn、npm 或 ./check" onChange={e => argument(0, e.target.value)} /></label><p>每项填写一个参数；参数中包含空格时无需额外加引号。</p>
    {spec.argv.slice(1).map((arg, index) => <div className="workflow-binding" key={index}><label>参数 {index + 1}<input value={arg} maxLength={4096} onChange={e => argument(index + 1, e.target.value)} /></label><UiActionButton actionKey="ui.delete" target={`参数 ${index + 1}`} onAction={() => patch({ argv: spec.argv.filter((_, i) => i !== index + 1) })} /></div>)}
    <UiActionButton actionKey="workflow.addParameter" target="命令参数" availability={!spec.argv[0]?.trim() || spec.argv.length >= 128 ? { kind: 'disabled', reason: '先填写执行程序，命令最多包含 128 项。' } : { kind: 'enabled' }} onAction={() => patch({ argv: [...spec.argv, ''] })} />
    <label>最长执行秒数<input type="number" min={1} max={3600} value={spec.timeoutSeconds} onChange={e => patch({ timeoutSeconds: Number(e.target.value) })} /></label><label>输出须包含（可选）<textarea value={spec.outputContains || ''} maxLength={4000} rows={3} onChange={e => patch({ outputContains: e.target.value || null })} /></label>
  </> : <><p role="alert">当前命令配置无法读取，可以重新配置。</p><UiActionButton actionKey="workflow.editConfiguration" target="检查命令" onAction={() => setReset(configurationIdentity(node, 'commandVerification'))} /></>}
    <UiConfirmDialog open={reset !== null} title="重新配置检查命令" confirmActionKey="workflow.editConfiguration" onCancel={() => setReset(null)} policy={disabled || reset !== configurationIdentity(node, 'commandVerification') ? { kind: 'block', reason: disabled ? '当前节点只读。' : '节点或配置已经变化，请关闭后重新确认。' } : { kind: 'allow' }} onConfirm={() => { if (disabled || reset !== configurationIdentity(node, 'commandVerification')) return; change({ version: 1, inputName: sources[0]?.name || 'code', argv: [], timeoutSeconds: 300, purpose: 'TEST', outputContains: null }); setReset(null) }}>原命令配置将被替换。</UiConfirmDialog>
  </fieldset>
}
export function WorkflowVerificationEditor({ node, disabled, onChange }: NodeFieldsProps) {
  const [confirm, setConfirm] = useState<{ selection: 'reset' | number; original: string } | null>(null)
  const spec = jsonParameter(node.parameters.verification, (v): v is FileSpec => object(v) && v.version === 1 && typeof v.inputName === 'string' && Array.isArray(v.checks) && keys(v, ['version', 'inputName', 'checks']) && v.checks.every(check => object(check) && typeof check.title === 'string' && typeof check.path === 'string' && ['FILE_CONTENT', 'FILE_HASH', 'FILE_NOT_EXISTS'].includes(String(check.type)) && (check.expected == null || typeof check.expected === 'string') && (check.matchMode == null || typeof check.matchMode === 'string') && keys(check, ['title', 'type', 'path', 'expected', 'matchMode'])))
  const change = (value: FileSpec) => { if (!disabled) onChange({ ...node, parameters: { ...node.parameters, verification: JSON.stringify(value) } }) }
  const patch = (index: number, value: Partial<Check>) => { if (spec) change({ ...spec, checks: spec.checks.map((check, i) => i === index ? { ...check, ...value } : check) }) }
  return <fieldset className="workflow-fields" disabled={disabled}><legend>交付物检查</legend>{spec ? <>
    <label>检查哪份输入<select value={spec.inputName} onChange={e => change({ ...spec, inputName: e.target.value })}>{node.inputs.filter(v => v.kind === 'CODE' && v.source === 'NODE' && v.required).map(v => <option key={v.name} value={v.name}>{v.name}</option>)}</select></label>
    {!spec.checks.length && <p>添加需要程序检查的文件和期望结果。</p>}{spec.checks.map((check, i) => <div className="workflow-binding" key={i}>
      <label>检查名称<input value={check.title} maxLength={120} onChange={e => patch(i, { title: e.target.value })} /></label><label>检查类型<select value={check.type} onChange={e => patch(i, { type: e.target.value, expected: '', matchMode: 'CONTAINS' })}><option value="FILE_CONTENT">文件内容</option><option value="FILE_HASH">文件 SHA-256</option><option value="FILE_NOT_EXISTS">文件已移除</option></select></label>
      <label>项目内文件路径<input value={check.path} maxLength={1024} placeholder="例如 src/config.json" onChange={e => patch(i, { path: e.target.value })} /></label>{check.type === 'FILE_CONTENT' && <label>匹配方式<select value={check.matchMode || ''} onChange={e => patch(i, { matchMode: e.target.value })}><option value="CONTAINS">包含期望文本</option><option value="EXACT">与期望文本完全相同</option></select></label>}
      {check.type !== 'FILE_NOT_EXISTS' && <label>{check.type === 'FILE_HASH' ? '期望 SHA-256' : '期望文本'}<textarea value={check.expected || ''} maxLength={check.type === 'FILE_HASH' ? 64 : 4000} rows={3} onChange={e => patch(i, { expected: e.target.value })} /></label>}
      <UiActionButton actionKey="ui.delete" target={check.title} onAction={() => setConfirm({ selection: i, original: configurationIdentity(node, 'verification') })} />
    </div>)}<UiActionButton actionKey="workflow.addCheck" target="检查项目" availability={spec.checks.length >= 16 ? { kind: 'disabled', reason: '最多 16 项检查。' } : { kind: 'enabled' }} onAction={() => change({ ...spec, checks: [...spec.checks, { title: '文件内容检查', type: 'FILE_CONTENT', path: '', expected: '', matchMode: 'CONTAINS' }] })} />
  </> : <><p role="alert">当前检查配置无法读取，可以重新配置。</p><UiActionButton actionKey="workflow.editConfiguration" target="交付物检查" onAction={() => setConfirm({ selection: 'reset', original: configurationIdentity(node, 'verification') })} /></>}
    <UiConfirmDialog open={confirm !== null} title={confirm?.selection === 'reset' ? '重新配置检查项目' : '移除交付物检查'} confirmActionKey={confirm?.selection === 'reset' ? 'workflow.editConfiguration' : 'ui.delete'} onCancel={() => setConfirm(null)} policy={disabled || confirm?.original !== configurationIdentity(node, 'verification') ? { kind: 'block', reason: disabled ? '当前节点只读。' : '节点或配置已经变化，请关闭后重新确认。' } : { kind: 'allow' }} onConfirm={() => { if (disabled || confirm?.original !== configurationIdentity(node, 'verification')) return; if (confirm?.selection === 'reset') change({ version: 1, inputName: 'code', checks: [] }); else if (spec) change({ ...spec, checks: spec.checks.filter((_, i) => i !== confirm?.selection) }); setConfirm(null) }}>确认调整此节点的检查配置？</UiConfirmDialog>
  </fieldset>
}
export function WorkflowReviewSourceEditor({ node, disabled, onChange }: NodeFieldsProps) {
  const mode = (value: string) => { if (disabled || !['FULL', 'DATE_INCREMENTAL'].includes(value)) return; const inputs = node.inputs.filter(input => !['startDate', 'endDate'].includes(input.name)); if (value === 'DATE_INCREMENTAL') for (const name of ['startDate', 'endDate']) inputs.push(node.inputs.find(input => input.name === name) ?? { name, source: 'REQUIREMENT', sourceId: name, output: null, kind: 'TEXT', required: true } satisfies WorkflowInput); onChange({ ...node, inputs, parameters: { ...node.parameters, reviewMode: value } }) }
  return <fieldset disabled={disabled} className="workflow-fields" aria-label="版本审查采集设置"><legend>版本审查采集</legend><label>审查范围<select aria-label="版本审查范围" value={node.parameters.reviewMode || 'DATE_INCREMENTAL'} onChange={e => mode(e.target.value)}><option value="DATE_INCREMENTAL">日期增量</option><option value="FULL">全面审查</option></select></label><label>采集时限（秒）<input aria-label="版本审查采集时限" type="number" min={10} max={600} value={node.parameters.reviewTimeoutSeconds || '600'} onChange={e => { if (!disabled) onChange({ ...node, parameters: { ...node.parameters, reviewTimeoutSeconds: e.target.value } }) }} /></label><p>{node.parameters.reviewMode === 'FULL' ? '固定所选分支的当前提交，采集项目范围内的代码。' : '绑定开始、结束日期，按北京时间选择两个边界版本并比较最终代码。切换范围后请核对输入来源。'}</p><p>重试沿用原提交和范围。采集只固定资料，审查结论由后续节点交付。</p></fieldset>
}
export function WorkflowSourceDesignEditor({ node, disabled, onChange }: NodeFieldsProps) {
  const [reset, setReset] = useState<string | null>(null)
  const paths = !node.parameters.targetPaths ? [] : jsonParameter(node.parameters.targetPaths, (v): v is string[] => Array.isArray(v) && v.every(p => typeof p === 'string' && !/[\r\n]/.test(p)))
  const change = (value: string) => { if (disabled) return; const parameters = { ...node.parameters }, selected = value.split(/\r?\n/).filter(Boolean); if (selected.length) parameters.targetPaths = JSON.stringify(selected); else delete parameters.targetPaths; onChange({ ...node, parameters }) }
  return <fieldset className="workflow-fields" disabled={disabled}><legend>本批源码范围</legend>{paths ? <label>本批源码文件<textarea value={paths.join('\n')} rows={4} placeholder="每行一个项目内路径；留空使用全部适用目标" onChange={e => change(e.target.value)} /></label> : <><p role="alert">现有路径配置无法按列表编辑，原配置已保留。</p><UiActionButton actionKey="workflow.editConfiguration" target="源码范围" onAction={() => setReset(configurationIdentity(node, 'targetPaths'))} /></>}<p>每批最多 12 个文件、160000 字节；单个大文件独立一批。路径必须属于上游冻结资料的目标范围。</p>{node.moduleId === 'source.design-review' && <p>复核目标须与本批设计稿一致；其他模块需绑定相关设计稿。</p>}<UiConfirmDialog open={reset !== null} title="重新设置为全部适用目标" confirmActionKey="workflow.editConfiguration" onCancel={() => setReset(null)} policy={disabled || reset !== configurationIdentity(node, 'targetPaths') ? { kind: 'block', reason: disabled ? '当前节点只读。' : '节点或配置已经变化，请关闭后重新确认。' } : { kind: 'allow' }} onConfirm={() => { if (disabled || reset !== configurationIdentity(node, 'targetPaths')) return; change(''); setReset(null) }}>原路径配置将被替换。</UiConfirmDialog></fieldset>
}
type Section = { fileId: string; section: number }
export function WorkflowDocumentReviewEditor({ node, disabled, onChange }: NodeFieldsProps) {
  const [reset, setReset] = useState<string | null>(null)
  const selection = !node.parameters.documentSections ? [] : jsonParameter(node.parameters.documentSections, (v): v is Section[] => Array.isArray(v) && v.every(item => object(item) && typeof item.fileId === 'string' && /^DOC-[1-9][0-9]?$/.test(item.fileId) && Number.isSafeInteger(item.section) && Number(item.section) > 0))
  const patch = (value: Record<string, string>) => { if (!disabled) onChange({ ...node, parameters: { ...node.parameters, ...value } }) }
  const choose = (mode: string) => patch({ documentSections: mode === 'ALL' ? '' : JSON.stringify([{ fileId: 'DOC-1', section: 1 }]) })
  const change = (index: number, field: 'fileId' | 'section', value: string) => { const n = Number(value); if (!selection || !Number.isSafeInteger(n) || n < 1 || field === 'fileId' && n > 99) return; patch({ documentSections: JSON.stringify(selection.map((item, i) => i === index ? { ...item, [field]: field === 'fileId' ? `DOC-${n}` : n } : item)) }) }
  return <fieldset className="workflow-fields" disabled={disabled}><legend>本批原文范围</legend><label>批次序号<input aria-label="评审批次序号" type="number" min={1} max={512} value={Number(node.parameters.documentBatchOrdinal || 0) + 1} onChange={e => { const n = Number(e.target.value); if (Number.isSafeInteger(n) && n >= 1 && n <= 512) patch({ documentBatchOrdinal: String(n - 1) }) }} /></label>
    {selection ? <><label>原文章节<select aria-label="评审原文章节" value={node.parameters.documentSections ? 'SELECTED' : 'ALL'} onChange={e => choose(e.target.value)}><option value="ALL">全部原文</option><option value="SELECTED">指定章节</option></select></label>{node.parameters.documentSections && <>{selection.map((item, i) => <div className="workflow-binding" key={i}><label>文档序号<input aria-label={`原文 ${i + 1} 文档序号`} type="number" min={1} max={99} value={item.fileId.slice(4)} onChange={e => change(i, 'fileId', e.target.value)} /></label><label>章节序号<input aria-label={`原文 ${i + 1} 章节序号`} type="number" min={1} value={item.section} onChange={e => change(i, 'section', e.target.value)} /></label><UiActionButton actionKey="ui.delete" target={`章节 ${i + 1}`} onAction={() => patch({ documentSections: JSON.stringify(selection.filter((_, j) => j !== i)) })} /></div>)}{!selection.length && <p role="alert">请至少选择一个章节，或改为全部原文。</p>}<UiActionButton actionKey="workflow.addSection" target="章节" availability={selection.length >= 256 ? { kind: 'disabled', reason: '最多 256 章。' } : { kind: 'enabled' }} onAction={() => patch({ documentSections: JSON.stringify([...selection, { fileId: 'DOC-1', section: 1 }]) })} /></>}</> : <><p role="alert">现有章节配置无法编辑，原配置已保留。</p><UiActionButton actionKey="workflow.editConfiguration" target="原文章节" onAction={() => setReset(configurationIdentity(node, 'documentSections'))} /></>}
    <p>文档序号按上传顺序，章节按解析目录从 1 开始。每批最多 256 章、48000 字符；单个超长章节独立成批。</p>{node.moduleId === 'document.direct-review-check' && <p>批次与章节须和本批评审稿一致。复核独立读取原文、代码及全部绑定稿件，保留真实通过或返修意见。</p>}<UiConfirmDialog open={reset !== null} title="重新设置为全部原文" confirmActionKey="workflow.editConfiguration" onCancel={() => setReset(null)} policy={disabled || reset !== configurationIdentity(node, 'documentSections') ? { kind: 'block', reason: disabled ? '当前节点只读。' : '节点或配置已经变化，请关闭后重新确认。' } : { kind: 'allow' }} onConfirm={() => { if (disabled || reset !== configurationIdentity(node, 'documentSections')) return; choose('ALL'); setReset(null) }}>原章节配置将被替换。</UiConfirmDialog>
  </fieldset>
}
