import type { ComponentType } from 'react'
import { act, cleanup, fireEvent, render } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { semanticName } from '@/foundation/semanticRegistry'
import { pageFrame, foundationDOM, flush } from '@/pages/w2/workflow/page.test-support'
import { skins } from '@/themes/registry'
import type { WorkflowCommandEvidence as Evidence, WorkflowCommandResult } from '@/types/domain'
import { snapshotAnalysis, snapshotReview } from '@/components/workflow/snapshotTestFixtures'
import * as reports from './reports'
import type { ReportProps } from './reports'
const settle = () => act(async () => { await flush() })
beforeEach(() => foundationDOM())
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
const references = [{ path: 'src/Main.java', sha256: 'private-hash', startLine: 1, endLine: 2, quote: '<img src=x onerror=alert(1)>' }]
const design = { title: '订单模块设计', summary: '冻结源码职责', sections: [{ key: 'main', title: '核心流程', markdown: '**事务边界**\n\n<img src=x onerror=alert(1)>\n\n![外部图片](https://invalid.example/image)', paths: ['src/Main.java'], references }], limitations: ['外部依赖行为待确认'] }
const review = { verdict: 'PASS', reason: '设计与源码一致', checkedPaths: ['src/Main.java'], references, issues: [] }
const nativeResult = { version: 1, type: 'SOURCE_TEST_RUN', valid: true, passed: true, moduleRoot: '.', framework: 'junit', counts: { total: 3, passed: 2, failed: 0, skipped: 1 }, exitCode: 0, command: ['mvn', 'test'], files: [{ path: 'target/surefire-reports/TEST-Calculator.xml', sha256: 'private-hash' }], fileCount: 1, message: '已读取原生报告', scenarioCoverageVerified: false, producerAttempt: 'private-attempt' }
const finalCode = { ...nativeResult, version: 2, inputUnchanged: true, writerLineage: ['private-attempt', 'private-first'], batches: [{ inputName: 'design', designAttempt: 'private-design1', designSha256: 'a'.repeat(64), writerAttempt: 'private-first', scenarioCount: 1 }, { inputName: 'design_second', designAttempt: 'private-design2', designSha256: 'b'.repeat(64), writerAttempt: 'private-attempt', scenarioCount: 1 }] }
const summary = { version: 1, type: 'SOURCE_TEST_SUMMARY', complete: true, passed: true, testPassed: true, reviewSatisfied: true, sourceCount: 2, coveredSourceCount: 2, moduleCount: 1, batchCount: 1, reviewedBatchCount: 1, reviewPolicy: 'DUAL', writerAttempt: 'private-writer-id', modules: [{ root: '.', passed: true, counts: { total: 3, passed: 2, failed: 0, skipped: 1 } }], batches: [{ moduleRoot: '.', scenarioCount: 2, reviewSatisfied: true, reviews: [{ attempt: 'private-review-1' }, { attempt: 'private-review-2' }] }] }
const evidence: Evidence = { attemptId: 'private-attempt', requestSha256: null, resultSha256: null, request: null, registration: null, result: null, nativeReport: { files: [{ path: 'report.xml', content: '<testsuite><failure>expected 3</failure></testsuite>' }] } }
const process: WorkflowCommandResult = { requestSha256: 'private-sha', worker: { pid: 42, startedAt: '2026-01-01T00:00:00Z' }, exitCode: 7, launched: true, timedOut: false, cancelled: false, outputTruncated: false, stopConfirmed: true, output: '安装缺少依赖', error: '', children: [] }
const prepared: Evidence = { ...evidence, request: { id: 'private-attempt', directory: '/private', argv: ['npm', 'test'], timeoutSeconds: 60, preparations: [{ name: 'NPM_INSTALL', directory: '/private', argv: ['npm', 'ci'] }, { name: 'CHECK_ENV', directory: '/private', argv: ['node', '--version'] }] }, result: { ...process, exitCode: null, launched: false, output: '', error: 'COMMAND_PREPARATION_FAILED', preparations: [process] } }

it('source design keeps structured chapters/citations, sanitizes markdown and hides internal hashes', async () => {
  const view = render(<reports.WorkflowOutputReport moduleId="source.design" name="design" value={{ kind: 'JSON', content: design }} />); await settle()
  expect(view.getByRole('heading', { name: '订单模块设计' })).toBeTruthy(); expect(view.getByText('外部依赖行为待确认')).toBeTruthy(); expect(view.container.querySelector('strong')!.textContent).toContain('事务边界'); expect(view.container.querySelector('img, script, [onerror]')).toBeNull(); expect(view.container.textContent).not.toContain('private-hash'); expect(view.getByRole('textbox', { name: 'src/Main.java 引用片段' }).textContent).toContain(references[0]!.quote); expect([...view.container.querySelectorAll('details')].every(d => !d.open)).toBe(true)
})
it.each([null, {}, { ...review, issues: [{ sectionKey: 'main', detail: '问题', recommendation: '修订' }] }, { ...review, verdict: 'REVISE' }, { ...review, references: [] }, { ...review, checkedPaths: [] }])('contradictory source review never renders a passing verdict (%j)', content => {
  const view = render(<reports.WorkflowSourceDesignReport content={content} review />); expect(view.getByRole('alert').textContent).toContain('无法读取'); expect(view.queryByText('复核通过')).toBeNull()
})
it('real source REVISE and independent PASS remain separate, unsafe issue text stays plain', () => {
  const view = render(<reports.WorkflowSourceDesignReport content={{ ...review, verdict: 'REVISE', reason: '遗漏异常路径', issues: [{ sectionKey: 'main', detail: '<script>alert(1)</script>', recommendation: '补充异常回滚说明' }] }} review />); expect(view.getByText('需要返修')).toBeTruthy(); expect(view.getByText('修订建议：补充异常回滚说明')).toBeTruthy(); expect(view.container.querySelector('script')).toBeNull(); view.rerender(<reports.WorkflowSourceDesignReport content={review} review />); expect(view.getByText('复核通过')).toBeTruthy(); expect(view.getByText('已复核 1 个源码文件')).toBeTruthy()
})
it('snapshot analysis/review preserves coverage, actual independent findings and historical reuse provenance', () => {
  const view = render(<reports.WorkflowSnapshotReport content={snapshotAnalysis} />); expect(view.container.textContent).toContain('第 2 / 3 批版本分析'); expect(view.container.textContent).toContain('空输入未被处理'); expect(view.container.textContent).toContain('第 24–25 行'); expect(view.container.textContent).toContain('未运行的测试不能视为通过'); expect(view.container.textContent).not.toContain('private-'); view.rerender(<reports.WorkflowSnapshotReport content={snapshotReview} />); expect(view.container.textContent).toContain('证据支持'); expect(view.container.textContent).toContain('独立读取');
  const reuse = { sourceRequirementId: 'private-source', sourceAttemptId: 'private-attempt', sourceTitle: '上周固定版本审查', sourceNodeTitle: '第一批分析', sourceDeliverySha256: 'a'.repeat(64) }
  view.rerender(<reports.WorkflowSnapshotReport content={{ ...snapshotAnalysis, reuse, claims: { ...snapshotAnalysis.claims, findings: [], limitations: [], coverage: snapshotAnalysis.claims.coverage.map(c => ({ ...c, evidence: [], limitations: [] })) } }} />); expect(view.getByRole('link').getAttribute('href')).toBe('/requirements/private-source'); expect(view.container.textContent).toContain('本次没有创建模型会话'); expect(view.container.textContent).not.toContain('private-')
})
it.each([null, { ...snapshotAnalysis, version: 9 }, { ...snapshotAnalysis, batchOrdinal: 3 }, { ...snapshotAnalysis, locations: [] }, { ...snapshotAnalysis, claims: { ...snapshotAnalysis.claims, coverage: [] } }, { ...snapshotReview, claims: { ...snapshotReview.claims, decisions: [] } }])('invalid snapshot report does not synthesize a successful judgment (%j)', content => {
  const view = render(<reports.WorkflowSnapshotReport content={content} />); expect(view.getByRole('alert').textContent).toContain('无法读取'); expect(view.container.textContent).not.toContain('证据支持')
})
it('native test counts skip explicitly and verifies multi-batch final-code lineage without exposing identity', () => {
  const view = render(<reports.WorkflowNativeTestReport content={finalCode} />); expect(view.container.textContent).toContain('同一份固定代码上回归 2 批场景'); expect(view.getByText('原生测试通过')).toBeTruthy(); expect(view.container.textContent).toContain('实际执行 2 项：通过 2，失败 0，另有 1 项跳过'); expect(view.container.textContent).not.toContain('private-'); view.rerender(<reports.WorkflowNativeTestReport content={{ ...nativeResult, counts: { total: 0, passed: 0, failed: 0, skipped: 0 } }} />); expect(view.getByText('测试证据不完整')).toBeTruthy(); expect(view.queryByText('原生测试通过')).toBeNull(); view.rerender(<reports.WorkflowNativeTestReport content={{ ...nativeResult, inputUnchanged: false }} />); expect(view.queryByText('原生测试通过')).toBeNull()
})
it.each([{ ...finalCode, batches: [] }, { ...finalCode, batches: [finalCode.batches[0], finalCode.batches[0]] }, { ...finalCode, writerLineage: ['private-first'] }, { ...nativeResult, scenarioCoverageVerified: true }, { ...nativeResult, counts: { total: 4, passed: 2, failed: 0, skipped: 1 } }])('native report corruption/lineage cannot be displayed as passing (%j)', content => {
  const view = render(<reports.WorkflowNativeTestReport content={content} />); expect(view.getByRole('alert').textContent).toContain('无法读取')
})
it('test summary preserves explicit dual review, exact coverage and an intentional NONE policy', () => {
  const view = render(<reports.WorkflowTestSummaryReport content={summary} />); expect(view.container.textContent).toContain('源码覆盖 2 / 2'); expect(view.container.textContent).toContain('每批两位独立角色'); expect(view.container.textContent).not.toContain('private-'); view.rerender(<reports.WorkflowTestSummaryReport content={{ ...summary, reviewPolicy: 'NONE', reviewedBatchCount: 0, batches: [{ ...summary.batches[0], reviews: [] }] }} />); expect(view.container.textContent).toContain('按自定义策略不要求复核'); expect(view.container.textContent).toContain('0 份意见'); expect(view.container.textContent).not.toContain('复核通过')
})
it.each([null, {}, { ...summary, coveredSourceCount: 3 }, { ...summary, batchCount: 2 }, { ...summary, modules: [] }, { ...summary, testPassed: false }, { ...summary, reviewPolicy: 'unknown' }])('inconsistent test summary refuses a successful result (%j)', content => {
  const view = render(<reports.WorkflowTestSummaryReport content={content} />); expect(view.getByRole('alert').textContent).toContain('无法读取'); expect(view.queryByText('单测汇总通过')).toBeNull()
})
it('command evidence distinguishes preparation failure/not-executed/unconfirmed-stop and preserves safe lazy raw/native output', async () => {
  const view = render(pageFrame(<reports.WorkflowCommandEvidence evidence={prepared} terminal />)); expect(view.container.textContent).toContain('进程退出码：7'); expect(view.container.textContent).toContain('本步骤未执行'); expect(view.container.textContent).toContain('检查命令没有启动'); expect(view.container.textContent).toContain('依赖准备未完成'); expect(view.container.textContent).not.toContain('private-'); expect(view.container.textContent).not.toContain('NPM_INSTALL')
  view.rerender(pageFrame(<reports.WorkflowCommandEvidence evidence={{ ...prepared, result: { ...prepared.result!, preparations: [{ ...process, cancelled: true, timedOut: true, outputTruncated: true, stopConfirmed: false }] } }} terminal />)); const preparation = view.getByRole('region', { name: '依赖准备结果' }); expect(preparation.textContent).toContain('准备已取消'); expect(preparation.textContent).toContain('准备超过执行时限'); expect(preparation.textContent).toContain('停止尚未确认'); expect(preparation.textContent).toContain('保存的输出不完整')
  view.rerender(pageFrame(<reports.WorkflowCommandEvidence evidence={evidence} terminal />)); expect(view.container.querySelector('[data-readonly-code]')).toBeNull(); fireEvent.click(view.getByRole('button', { name: semanticName('ui.open', 'report.xml') })); await settle(); expect(view.container.textContent).toContain('<testsuite>'); expect(view.container.querySelector('testsuite')).toBeNull(); fireEvent.click(view.getByRole('button', { name: semanticName('ui.open', 'report.xml') })); expect(view.container.textContent).not.toContain('<testsuite>')
})
it('repository command details are only disclosed explicitly and active preparation is not marked unexecuted', () => {
  const value: Evidence = { ...evidence, nativeReport: undefined, request: { id: 'private-attempt', directory: '/private', argv: ['java', '-jar', '/private/helper.jar'], timeoutSeconds: 180 }, result: process }
  const view = render(<reports.WorkflowCommandEvidence evidence={value} terminal={false} repository />); expect(view.container.textContent).toContain('分支代码采集'); expect(view.container.textContent).toContain('代码采集命令已启动'); expect(view.container.textContent).not.toContain('/private/helper.jar'); const details = view.getByText('查看采集命令').closest('details')!; details.open = true; fireEvent(details, new Event('toggle')); expect(view.container.textContent).toContain('/private/helper.jar'); view.rerender(<reports.WorkflowCommandEvidence evidence={{ ...prepared, result: null }} terminal={false} />); expect(view.container.textContent).toContain('尚未取得执行结果'); expect(view.container.textContent).not.toContain('本步骤未执行')
})
it('relative report navigation preserves scope containment and routes Markdown links through the reader callback', async () => {
  expect(reports.resolveWorkflowDocumentLink('docs/report/main.md', '../appendix.md#part')).toBe('#workflow-document=docs%2Fappendix.md'); for (const href of ['../../../outside.md', '/root.md', 'https://invalid.example/x.md', '%2e%2e/%2e%2e/%2e%2e/evil.md', 'notes.md?query=1', 'image.png', 'bad%00.md']) expect(reports.resolveWorkflowDocumentLink('docs/report/main.md', href)).toBeNull()
  const onNavigate = vi.fn(), onLoad = vi.fn(), view = render(pageFrame(<reports.WorkflowDocumentPreview path="docs/report/main.md" body={{ text: '[附录](../appendix.md)\n<img src=x>', sha256: 'private-hash', nextOffset: 20 }} skin={skins[0]!} onLoad={onLoad} onNavigate={onNavigate} onClose={vi.fn()} />)); await settle(); fireEvent.click(view.getByRole('link', { name: '附录' })); expect(onNavigate).toHaveBeenCalledWith('docs/appendix.md'); expect(view.container.querySelector('img')).toBeNull(); fireEvent.click(view.getByRole('button', { name: semanticName('ui.loadMore', '报告正文') })); expect(onLoad).toHaveBeenCalledWith(true); expect(view.container.textContent).not.toContain('private-hash')
})
const strictReports: [string, ComponentType<ReportProps>][] = Object.entries(reports).filter(([name]) => /^Workflow.*(?:Report|Summary)$/.test(name) && !['WorkflowOutputReport', 'WorkflowKnowledgeReport', 'WorkflowSnapshotPartialReport'].includes(name)) as [string, ComponentType<ReportProps>][]
it.each(strictReports)('%s invalid DTO is an explicit unavailable report, never an invented successful result', (_name, Component) => { const view = render(<Component content={null} />); expect(view.getByRole('alert').textContent).toContain('无法读取'); expect(view.container.querySelector('[data-report-status="PASS"]')).toBeNull() })
