import { useState } from 'react'
import type { WorkflowGraph, WorkflowInput, WorkflowNode, WorkflowOutput } from '@/types/domain'
import { outcomeTitle, outcomeTitles } from '@/components/workflow/graph'
import { UiActionButton } from '@/foundation/components'
import { WorkflowRolePicker } from './WorkflowRolePicker'
import { WorkflowCommandEditor, WorkflowDocumentReviewEditor, WorkflowReviewSourceEditor, WorkflowSourceDesignEditor, WorkflowVerificationEditor } from './NodeSpecialists'

export const workflowKinds = { TEXT: '文本', JSON: '结构化数据', DOCUMENT: '文档', CODE: '代码', DECISION: '业务判断', PLAN: '候选计划', CONTROL: '控制记录' }
export interface WorkflowNodeEditorProps { node: WorkflowNode; graph: WorkflowGraph; disabled?: boolean; removeDisabled?: boolean; readonlyReason?: string; onChange(node: WorkflowNode): void; onRemove(): void; onRoleLabel?(id: string, label: string): void }
const sourceDesigns = ['source.design', 'source.design-review', 'source.test-design'], documentReviews = ['document.direct-review', 'document.direct-review-check'], snapshotWorks = ['snapshot.analyze', 'snapshot.review'], histories = ['history.review', 'history.contribution']
const completionMessages: Record<string, string> = {
  'system.review.snapshot': '版本、范围及完整证据保存且采集进程停止后完成；审查结论由后续节点交付。', 'system.git.history': '完整历史证据保存且采集进程停止后完成；空范围保存无提交说明。', 'system.repository.snapshot': '固定提交与完整文件清单保存成功，且采集进程停止后完成。', 'system.source.snapshot': '全部适用目标均已完整采集并冻结后完成。',
  'system.source.design-plan': '完整生成候选计划后完成；应用计划与开始执行由你确认。', 'system.source.test-plan': '完整生成候选计划后完成；应用计划与开始执行由你确认。', 'system.document.review-plan': '完整生成候选计划后完成；应用计划与开始执行由你确认。', 'system.history.plan': '完整生成候选计划后完成；应用计划与开始执行由你确认。', 'system.snapshot.plan': '完整生成候选计划后完成；应用计划与开始执行由你确认。',
  'system.source.test-profile': '全部目标源码的测试配置识别完成；实际测试由后续节点执行。', 'system.source.design-document': '生成完整文档后完成，复核是否必需由上方策略决定。', 'system.document.review-report': '生成完整文档后完成，复核是否必需由上方策略决定。', 'system.snapshot.report': '全部可审查片段分析完成，适用复核符合所选策略，完整报告保存后完成。', 'system.history.report': '全部适用分析完整覆盖，且固定报告保存成功后完成。',
}
const planningMessages: Record<string, [string, string]> = {
  'system.snapshot.plan': ['版本审查分批', '连接分析、可选的条件复核和报告配置。程序完整划分固定代码，继承角色、任务、重试和检查点；候选先由你确认。'],
  'system.history.plan': ['历史分批', '连接一份审查、可选的一份个人评价和一份报告配置。程序按完整历史生成候选，继承角色、重试和检查点；确认后执行。'],
  'system.document.review-plan': ['原文分批', '连接一份评审、可选的一份复核和一份报告汇总配置。程序完整划分原文章节并继承配置；候选先由你确认。'],
  'system.source.design-plan': ['分批规划', '连接一份编写、可选的一份复核和一份文档汇总配置。程序按全部冻结源码细化批次，保留角色版本、任务、重试和检查点；候选先由你确认。'],
  'system.source.test-plan': ['单测分批规划', '按全部冻结源码与测试模块生成批次，保留后续角色、任务和检查点。代码逐批继承，全部编写后测试最终代码；候选先由你确认。'],
  'source.test-review': ['场景覆盖复核', '绑定同一次原生测试的源码、配置、场景、代码与报告，逐场景核对真实测试和固定断言。可选择复核通过后继续，或保留返修意见继续其他分支。'],
  'source.test-write': ['单测编写范围', '使用所绑定场景设计的源码范围，仅补充原生测试与夹具。已有测试须保留；代码和范围检查由程序在停止后保存。'],
}
export function WorkflowNodeEditor({ node, graph, disabled, removeDisabled, readonlyReason, onChange, onRemove, onRoleLabel }: WorkflowNodeEditorProps) {
  const [error, setError] = useState(''), module = node.moduleId || '', fixed = node.kind === 'SYSTEM' || [...sourceDesigns, ...documentReviews, ...snapshotWorks, ...histories, 'source.test-write', 'source.test-review'].includes(module)
  const patch = (value: Partial<WorkflowNode>) => { if (!disabled) onChange({ ...node, ...value }) }
  const parameter = (key: string, value: string) => patch({ parameters: { ...node.parameters, [key]: value } })
  const output = (index: number, value: Partial<WorkflowOutput>) => patch({ outputs: node.outputs.map((o, i) => i === index ? { ...o, ...value } : o) })
  const input = (index: number, value: Partial<WorkflowInput>) => patch({ inputs: node.inputs.map((o, i) => i === index ? { ...o, ...value } : o) })
  const availableKinds = Object.entries(workflowKinds).filter(([kind]) => kind !== 'DOCUMENT' && (kind !== 'PLAN' || node.kind === 'WORK' && module === 'free.readonly') && (kind !== 'CODE' || ['free.write', 'source.test-write'].includes(module)))
  const fields = { node, disabled, onChange: (value: WorkflowNode) => { if (!disabled) onChange(value) } }
  const numericParameter = (key: string, label: string, fallback: string, min: number, max: number, ordinal = false) => <label>{label}<input aria-label={label} type="number" min={min} max={max} value={ordinal ? Number(node.parameters[key] || fallback) + 1 : node.parameters[key] || fallback} onChange={e => parameter(key, ordinal ? String(Number(e.target.value) - 1) : e.target.value)} /></label>
  const policy = (label: string, options = [['REQUIRED', '每份稿件均须复核通过'], ['NONE', '不要求复核，保留实际复核情况']], fallback = 'REQUIRED') => <label>{label}<select aria-label={label} value={node.parameters.reviewPolicy || fallback} onChange={e => parameter('reviewPolicy', e.target.value)}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>
  return <section className="workflow-inspector" aria-label="节点设置" data-workflow-node-editor={node.id}><header className="w2-actions"><h2>节点设置</h2><UiActionButton actionKey="workflow.deleteSelection" target={node.title} variant="danger" availability={(removeDisabled ?? disabled) ? { kind: 'disabled', reason: readonlyReason || '当前节点不能删除。' } : { kind: 'enabled' }} onAction={onRemove} /></header>{readonlyReason && <p>{readonlyReason}</p>}{error && <p role="alert">{error}</p>}
    <fieldset className="workflow-fields" disabled={disabled}><label>名称<input value={node.title} maxLength={120} onChange={e => patch({ title: e.target.value })} /></label><label>任务说明<textarea value={node.task} rows={3} placeholder="描述这个节点要完成的具体工作" onChange={e => patch({ task: e.target.value })} /></label></fieldset>
    {node.kind === 'WORK' && <WorkflowRolePicker node={node} disabled={disabled} onChange={(roleId, roleRevisionId) => patch({ roleId, roleRevisionId })} onLabel={onRoleLabel} />}
    <details className="workflow-node-advanced"><summary>更多节点设置 · 输入、交付物与完成规则</summary><fieldset disabled={disabled} className="workflow-fields"><legend>输入来源</legend>{node.inputs.map((item, index) => <div key={index} className="workflow-binding">
      <label>输入名称<input value={item.name} onChange={e => input(index, { name: e.target.value })} /></label><label>使用交付物<select value={`${item.source}|${item.sourceId}|${item.output || item.sourceId}`} onChange={e => { const [source, id, name] = e.target.value.split('|'); if (!id || !name) return; const out = source === 'NODE' ? graph.nodes.find(n => n.id === id)?.outputs.find(o => o.name === name) : graph.inputs.find(o => o.name === name); if (out) input(index, { source: source === 'NODE' ? 'NODE' : 'REQUIREMENT', sourceId: id, output: source === 'NODE' ? name : null, kind: out.kind }) }}><option value="">选择前置交付物</option>{graph.nodes.filter(n => n.id !== node.id).map(source => <optgroup key={source.id} label={source.title}>{source.outputs.map(out => <option key={out.name} value={`NODE|${source.id}|${out.name}`}>{out.title || out.name}</option>)}</optgroup>)}{!!graph.inputs.length && <optgroup label="任务公共资料">{graph.inputs.map(out => <option key={out.name} value={`REQUIREMENT|${out.name}|${out.name}`}>{out.title}</option>)}</optgroup>}</select></label>
      <label><input type="checkbox" checked={item.required} onChange={e => input(index, { required: e.target.checked })} />必需</label><UiActionButton actionKey="ui.delete" target={`输入 ${item.name}`} onAction={() => patch({ inputs: node.inputs.filter((_, i) => i !== index) })} />
    </div>)}<UiActionButton actionKey="workflow.addInput" onAction={() => patch({ inputs: [...node.inputs, { name: `input${node.inputs.length + 1}`, source: 'NODE', sourceId: '', output: '', kind: 'TEXT', required: true }] })} /></fieldset>
    {module === 'system.verify.command' && <WorkflowCommandEditor {...fields} />}{module === 'system.verify.files' && <WorkflowVerificationEditor {...fields} />}{module === 'system.review.snapshot' && <WorkflowReviewSourceEditor {...fields} />}
    {['system.git.history', 'system.repository.snapshot'].includes(module) && <fieldset disabled={disabled} className="workflow-fields"><legend>{module === 'system.git.history' ? 'Git 历史采集' : '分支代码采集'}</legend>{numericParameter(module === 'system.git.history' ? 'historyTimeoutSeconds' : 'repositoryTimeoutSeconds', '采集时限（秒）', module === 'system.git.history' ? '600' : '180', 10, 600)}<p>{module === 'system.git.history' ? '分支和日期来自所选输入，日期按北京时间计算并包含结束日。重试保留原提交和范围；分析新的历史时新增采集节点。' : '采集开始时固定所选分支提交，重试沿用该提交；需要新版本时新增采集节点。'}</p></fieldset>}
    {module === 'system.source.snapshot' && <fieldset disabled={disabled} className="workflow-fields"><legend>源码采集</legend><label>采集用途<select value={node.parameters.sourcePurpose || 'DESIGN'} onChange={e => parameter('sourcePurpose', e.target.value)}><option value="DESIGN">设计与分析</option><option value="UNIT_TEST">单元测试（已有测试作为上下文）</option></select></label><p>项目内路径来自输入，支持单文件或目录。重试沿用冻结版本；新代码需新增采集节点。</p></fieldset>}
    {planningMessages[module] && <section><h3>{planningMessages[module]![0]}</h3><p>{planningMessages[module]![1]}</p></section>}
    {['system.source.design-document', 'system.document.review-report', 'system.snapshot.report'].includes(module) && <fieldset disabled={disabled} className="workflow-fields"><legend>文档与报告汇总</legend>{policy(module === 'system.snapshot.report' ? '版本报告复核策略' : '独立复核策略')}<p>{module === 'system.document.review-report' ? '须覆盖全部固定原文章节。复核读取全部关联稿件，真实保留未复核和修正情况。' : module === 'system.snapshot.report' ? '绑定全部分析及适用复核，无问题分支跳过复核；未复核的问题仅作为候选保留。' : '须覆盖全部适用目标，多批设计需绑定全部设计稿及对应复核。'}</p></fieldset>}
    {module === 'system.history.report' && <fieldset disabled={disabled} className="workflow-fields"><legend>历史报告</legend><label>报告类型<select aria-label="历史报告类型" value={node.parameters.historyReportKind || 'CODE_REVIEW'} onChange={e => parameter('historyReportKind', e.target.value)}><option value="CODE_REVIEW">历史提交审查</option><option value="CONTRIBUTION_REPORT">项目贡献周报</option></select></label><p>绑定全部已完成审查；贡献周报覆盖适用人员评价，格式与计分由程序持有。</p></fieldset>}
    {module === 'system.source.test-summary' && <fieldset disabled={disabled} className="workflow-fields"><legend>单测汇总</legend>{policy('单测独立复核策略', [['DUAL', '每批两位独立角色复核通过'], ['SINGLE', '每批一份独立复核通过'], ['NONE', '不要求复核']], 'DUAL')}<p>汇总完整源码范围。全部模块测试绑定同一份最终代码；移除复核节点时同步选择完成策略。</p></fieldset>}
    {module === 'system.source.test-profile' && <fieldset disabled={disabled} className="workflow-fields"><legend>测试配置识别</legend><label>测试输出目录（可选）<input value={node.parameters.testOutputPath || ''} maxLength={2048} placeholder="留空使用项目原生测试目录" onChange={e => parameter('testOutputPath', e.target.value)} /></label><p>绑定单元测试用途的冻结源码，指定目录只能缩小已识别范围；多模块各自使用原生目录。</p></fieldset>}
    {module === 'system.source.test-run' && <fieldset disabled={disabled} className="workflow-fields" aria-label="原生单测设置"><legend>原生单测设置</legend><label>测试模块路径<input aria-label="测试模块路径" value={node.parameters.testModuleRoot || '.'} maxLength={2048} onChange={e => parameter('testModuleRoot', e.target.value)} /></label>{numericParameter('testTimeoutSeconds', '执行时限（秒）', '600', 1, 3600)}<p>命令从固定配置生成，根模块填写“.”。{node.moduleVersion === 2 ? '各批场景须属于最终代码的继承链，可追加其他场景输入。' : '源码、配置和场景须与代码来自同一次单测编写。'}</p></fieldset>}
    {histories.includes(module) && <fieldset disabled={disabled} className="workflow-fields"><legend>历史分析范围</legend>{module === 'history.review' ? numericParameter('historyBatchOrdinal', '历史审查批次', '0', 1, 100001, true) : <label>贡献者邮箱<input aria-label="贡献者邮箱" value={node.parameters.historyContributorEmail || ''} maxLength={2000} placeholder="固定历史中经 mailmap 归一化的邮箱" onChange={e => parameter('historyContributorEmail', e.target.value)} /></label>}<p>贡献评价需绑定覆盖本人全部变更的审查结果，可追加其他审查批次。</p></fieldset>}
    {snapshotWorks.includes(module) && <fieldset disabled={disabled} className="workflow-fields"><legend>版本代码审查</legend>{module === 'snapshot.analyze' ? <>{numericParameter('snapshotBatchOrdinal', '版本分析批次', '0', 1, 100001, true)}<p>按固定资料批次分析，交付存在或没有候选问题；前者可连接独立复核。</p><label>历史分析复用<select aria-label="历史分析复用" value={node.parameters.snapshotReuse || 'ALLOW'} onChange={e => parameter('snapshotReuse', e.target.value)}><option value="ALLOW">条件完全一致时复用</option><option value="BYPASS">每次重新分析（返修或资格验收）</option></select></label><p>仅复用固定资料及角色配置一致的无问题分析；有可变知识来源授权时重新执行。</p></> : <p>绑定同一份固定资料和已完成分析，仅复核其中候选问题；无需复核时可删除本节点。</p>}</fieldset>}
    {documentReviews.includes(module) && <WorkflowDocumentReviewEditor {...fields} />}{sourceDesigns.includes(module) && <WorkflowSourceDesignEditor {...fields} />}
    {fixed ? <section className="workflow-fixed-outputs" aria-label={node.kind === 'SYSTEM' ? '程序交付物' : '专业交付物'}><h3>{node.kind === 'SYSTEM' ? '程序交付物' : '专业交付物'}</h3>{node.outputs.map(item => <p key={item.name}>{item.title} · {workflowKinds[item.kind]}</p>)}</section> : <fieldset disabled={disabled} className="workflow-fields"><legend>预期交付物</legend>{node.outputs.map((item, index) => <div key={index} className="workflow-binding"><label>交付名称<input value={item.title} onChange={e => output(index, { title: e.target.value })} /></label><label>引用名称<input value={item.name} onChange={e => output(index, { name: e.target.value })} /></label><label>内容类型<select value={item.kind} onChange={e => output(index, { kind: e.target.value as WorkflowOutput['kind'] })}>{!availableKinds.some(([kind]) => kind === item.kind) && <option value={item.kind} disabled>{workflowKinds[item.kind]}（需对应工作模块）</option>}{availableKinds.map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select></label><label><input type="checkbox" checked={item.required} onChange={e => output(index, { required: e.target.checked })} />必需</label><UiActionButton actionKey="ui.delete" target={`交付物 ${item.title}`} onAction={() => patch({ outputs: node.outputs.filter((_, i) => i !== index) })} /></div>)}<UiActionButton actionKey="workflow.addOutput" onAction={() => patch({ outputs: [...node.outputs, { name: `output${node.outputs.length + 1}`, title: '新交付物', kind: 'TEXT', required: true }] })} /></fieldset>}
    <fieldset disabled={disabled} className="workflow-fields"><legend>完成规则</legend>{completionMessages[module] ? <p>{completionMessages[module]}</p> : <label>完成方式<select value={node.completion.kind} onChange={e => patch({ completion: { ...node.completion, kind: e.target.value as WorkflowNode['completion']['kind'] } })}><option value="DELIVERABLES">{node.kind === 'SYSTEM' ? '完成检查后继续（允许检查未通过）' : '提交有效交付物'}</option>{node.kind === 'SYSTEM' && <option value="VERIFIED">全部程序检查通过</option>}{!['source.design', 'source.test-design', 'source.test-write', 'document.direct-review', ...histories, ...snapshotWorks].includes(module) && <option value="OUTCOME">取得指定业务结果</option>}{node.kind === 'HUMAN' && <option value="HUMAN">人工确认</option>}</select></label>}
      <label>完成标准<textarea value={node.completion.criterion} rows={2} onChange={e => patch({ completion: { ...node.completion, criterion: e.target.value } })} /></label>{node.outcomes.map(outcome => <div className="workflow-binding" key={outcome}><label>业务结果名称<input value={outcomeTitle(node, outcome)} maxLength={120} onChange={e => parameter('outcomeTitles', JSON.stringify({ ...outcomeTitles(node), [outcome]: e.target.value }))} /></label>{!fixed && <UiActionButton actionKey="ui.delete" target={outcomeTitle(node, outcome)} onAction={() => { if (graph.edges.some(edge => edge.from === node.id && edge.outcome === outcome) || node.completion.expectedOutcome === outcome) { setError('这个结果仍被完成规则或后续连接使用，请先调整。'); return }; const titles = outcomeTitles(node); delete titles[outcome]; setError(''); patch({ outcomes: node.outcomes.filter(value => value !== outcome), parameters: { ...node.parameters, outcomeTitles: JSON.stringify(titles) } }) }} />}</div>)}{!fixed && <UiActionButton actionKey="workflow.addOutcome" availability={node.outcomes.length >= 32 ? { kind: 'disabled', reason: '最多 32 个业务结果。' } : { kind: 'enabled' }} onAction={() => { const key = `result_${crypto.randomUUID().slice(0, 8)}`; patch({ outcomes: [...node.outcomes, key], parameters: { ...node.parameters, outcomeTitles: JSON.stringify({ ...outcomeTitles(node), [key]: '新业务结果' }) } }) }} />}
      {node.completion.kind === 'OUTCOME' && <label>成功结果<select value={node.completion.expectedOutcome || ''} onChange={e => patch({ completion: { ...node.completion, expectedOutcome: e.target.value } })}><option value="">选择结果</option>{node.outcomes.map(outcome => <option key={outcome} value={outcome}>{outcomeTitle(node, outcome)}</option>)}</select></label>}<label>失败自动重试次数<input type="number" min={0} max={10} value={node.maxRetries} onChange={e => patch({ maxRetries: Number(e.target.value) })} /></label><label><input type="checkbox" checked={node.pauseAfter} onChange={e => patch({ pauseAfter: e.target.checked })} />执行后暂停检查</label>
    </fieldset></details>
  </section>
}
