import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import {webcrypto} from 'node:crypto'
import {api,ApiError} from '@/api/client'
import {deferred} from '@/pages/w2/core/coreTestHelpers'
import {createTemplateCatalogController} from './controller'
import {createTemplateCreationController} from './creation'
import {catalogFixture,documentInput} from './fixtures'
const owners:ReturnType<typeof createTemplateCatalogController>[]=[]
function owner(){const o=createTemplateCatalogController('p');owners.push(o);return o}
beforeEach(()=>{sessionStorage.clear();vi.stubGlobal('crypto',webcrypto);vi.spyOn(api,'templateCatalog').mockResolvedValue(catalogFixture);vi.spyOn(api,'templateProjects').mockResolvedValue({items:[],facets:{}});vi.spyOn(api,'templateProject').mockResolvedValue({id:'p',name:'项目',createdAt:'now',documentPath:'/docs'});vi.spyOn(api,'templateBranches').mockResolvedValue({page:{items:[{id:'local:main',label:'main',ref:'refs/heads/main',remote:null}],nextCursor:null},defaultBranch:{id:'local:main',label:'main',ref:'refs/heads/main',remote:null},defaultBranchId:'local:main',remoteAvailable:false,remoteProblems:['remote offline']});vi.spyOn(api,'documentTemplateRequest').mockRejectedValue(new ApiError('未确认',404))})
afterEach(()=>{owners.splice(0).forEach(o=>o.retire(true));vi.restoreAllMocks();vi.unstubAllGlobals();sessionStorage.clear()})
it('inherits project/output and default local branch with dates and exact scoring catalogue',async()=>{const o=owner();await o.initialize();expect(o.getSnapshot().documentPath).toBe('/docs');expect(o.getSnapshot().branchId).toBe('local:main');expect(o.getSnapshot().startDate).toBe('2026-09-01');expect(o.getSnapshot().remoteProblems).toEqual(['remote offline']);expect(o.getSnapshot().catalog!.dimensions).toEqual(catalogFixture.dimensions);o.change('endDate','2026-08-01');expect(o.dateError()).toBe('结束日期不能早于开始日期');expect(o.valid()).toBe(false);o.change('reviewMode','FULL');expect(o.needsDates()).toBe(false);expect(o.valid()).toBe(true)})
it('stale folder picker cannot replace changed path/template and cannot write after retirement',async()=>{const picked=deferred<{selected:boolean;path:string}>();vi.spyOn(api,'pickProjectDirectory').mockReturnValue(picked.promise);const o=owner();await o.initialize();const read=o.pick('documentPath');o.change('documentPath','/new');picked.resolve({selected:true,path:'/old'});await read;expect(o.getSnapshot().documentPath).toBe('/new');expect(o.getSnapshot().picking).toBe('')})
it('scope preview is invalidated by source/output/requirements changes and emits supported fields only',async()=>{const delayed=deferred<any>();vi.spyOn(api,'sourcePreview').mockReturnValue(delayed.promise);const o=owner();await o.initialize();await o.select('UNIT_TEST_DEVELOPMENT');o.change('sourcePath',' src/main ');o.change('testPath',' src/test ');o.change('documentPath','/unsupported');o.change('requirements',' 保持接口 ');const read=o.preview();expect(api.sourcePreview).toHaveBeenCalledWith(expect.objectContaining({sourcePath:'src/main',testOutputPath:'src/test',requirements:'保持接口'}));expect(vi.mocked(api.sourcePreview).mock.calls[0]![0]).not.toHaveProperty('documentPath');o.change('requirements','changed');delayed.resolve({sourcePath:'src/main',manifestSha256:'sha',targetCount:1,excludedCount:0,moduleCount:1,truncated:false,files:[],testProfile:null,configurationProblem:null});await read;expect(o.getSnapshot().preview).toBeUndefined();expect(o.valid()).toBe(false)})
it('empty file chooser cancellation preserves native files/order; invalid files block creation',async()=>{const o=owner();await o.initialize();await o.select('REQUIREMENT_CODE_REVIEW');const files=[new File(['one'],'one.md'),new File(['two'],'two.pdf')];o.chooseFiles(files);o.chooseFiles([]);expect(o.originalFiles()).toEqual(files);expect(o.originalFiles()[0]).toBe(files[0]);o.chooseFiles([new File(['bad'],'unsupported.doc')]);expect(o.fileError()).toContain('转换旧 DOC');expect(o.valid()).toBe(false);expect(o.canLeave().kind).toBe('CONFIRM_DISCARD')})
it('default report plus restored document UNKNOWN selects the original existing template without POST',async()=>{const original=createTemplateCreationController('document');const f=new File(['original'],'a.md');Object.defineProperty(f,'arrayBuffer',{value:async()=>new TextEncoder().encode('original').buffer});const write=vi.spyOn(api,'createDocumentTemplate').mockRejectedValue(new Error('lost'));await original.start(documentInput,[f]);original.retire(true);const o=owner();await o.initialize();expect(o.getSnapshot().selected).toBe('REQUIREMENT_CODE_REVIEW');expect(o.blocked()).toBe(true);expect(o.creations.document.getSnapshot().needsFiles).toBe(true);expect(o.creations.report.getSnapshot().phase).toBe('IDLE');expect(write).toHaveBeenCalledTimes(1);expect(o.canLeave().kind).toBe('BLOCK')})
it('history metadata for an absent template stays blocked and reachable through its own original operation',async()=>{sessionStorage.setItem('loopper.source-template-request.v1',JSON.stringify({fingerprint:'frozen',request:{requestKey:'original-key-000000',templateId:'retired-template',templateVersion:'original',projectId:'p',sourcePath:'src'}}));const o=owner();await o.initialize();expect(o.getSnapshot().selected).toBe('SNAPSHOT_CODE_REVIEW');expect(o.blocked()).toBe(true);expect(o.creations.source.getSnapshot().canRetry).toBe(true);expect((o.creations.source.originalIdentity() as any).templateId).toBe('retired-template');expect(o.canLeave().kind).toBe('BLOCK')})
