import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest'
import { webcrypto } from 'node:crypto'
import { api,ApiError } from '@/api/client'
import { deferred } from '@/pages/w2/core/coreTestHelpers'
import { createTemplateCreationController,identifyFiles } from './creation'
import { documentInput,sourceInput,reportInput,documentRun,sourceRun,task } from './fixtures'
const owners:ReturnType<typeof createTemplateCreationController>[]=[]
function owner(kind:'report'|'source'|'document'){const value=createTemplateCreationController(kind);owners.push(value);return value}
function file(text='原文',name='需求.md'){const f=new File([text],name);Object.defineProperty(f,'arrayBuffer',{value:async()=>new TextEncoder().encode(text).buffer,configurable:true});return f}
beforeEach(() => {sessionStorage.clear();vi.stubGlobal('crypto',webcrypto);vi.spyOn(api,'getTask').mockImplementation(async id=>task(id));vi.spyOn(api,'sourceTemplate').mockImplementation(async id=>sourceRun(id));vi.spyOn(api,'documentTemplate').mockImplementation(async id=>documentRun(id));vi.spyOn(api,'documentTemplateRequest').mockRejectedValue(new ApiError('尚未确认',404));vi.spyOn(api,'startTemplateTask').mockImplementation(async id=>({id,state:'QUEUED'}))})
afterEach(() => {owners.splice(0).forEach(o=>o.retire(true));vi.restoreAllMocks();vi.unstubAllGlobals();sessionStorage.clear()})
describe('production creation identity and route guard',()=>{
  it('active native FileReader fallback is aborted and releases handlers at forced root disposal',async()=>{const Native=FileReader,readers:FileReader[]=[];vi.stubGlobal('FileReader',class extends Native{constructor(){super();readers.push(this)}});const f=new File(['original '.repeat(10000)],'a.md');Object.defineProperty(f,'arrayBuffer',{value:undefined});const write=vi.spyOn(api,'createDocumentTemplate'),o=owner('document'),run=o.start(documentInput,[f]);expect(readers).toHaveLength(1);expect(readers[0]!.readyState).toBe(1);const abort=vi.spyOn(readers[0]!,'abort');o.retire(true);expect.soft(abort).toHaveBeenCalledTimes(1);expect.soft(readers[0]!.readyState).toBe(2);expect.soft(readers[0]!.onload).toBeNull();expect.soft(readers[0]!.onerror).toBeNull();await run;expect(write).not.toHaveBeenCalled()})
  for(const kind of ['report','source','document'] as const){
    const input=kind==='report'?reportInput:kind==='source'?sourceInput:documentInput
    const method=kind==='report'?'createTemplateTask':kind==='source'?'createSourceTemplate':'createDocumentTemplate'
    it(`${kind} blocks real in-flight writes and refuses writes after retirement`,async()=>{const pending=deferred<any>(),write=vi.spyOn(api,method).mockReturnValue(pending.promise),o=owner(kind),run=o.start(input,[file()]);await vi.waitFor(()=>expect(write).toHaveBeenCalledTimes(1));expect(o.canLeave().kind).toBe('BLOCK');const identity=o.originalIdentity();o.retire(true);pending.resolve({id:kind});await run;expect(o.getSnapshot().knownId).toBe('');expect(o.originalIdentity()).toEqual(identity);await o.start(input,[file()]);expect(write).toHaveBeenCalledTimes(1)})
    it(`${kind} retries exact unknown request and File identity without permitting changed intent`,async()=>{const write=vi.spyOn(api,method).mockRejectedValue(new Error('lost')),o=owner(kind),files=[file()];await o.start(input,files);const identity=write.mock.calls[0]![0];expect(o.getSnapshot().phase).toBe('UNKNOWN');expect(o.canLeave().kind).toBe('BLOCK');await o.retryOriginal();expect(write.mock.calls[1]![0]).toEqual(identity);if(kind==='document')expect((write.mock.calls[1] as unknown as [unknown,File[]])[1][0]).toBe(files[0]);await o.start({...input,projectId:'changed'},files);if(kind==='document')expect(write).toHaveBeenCalledTimes(2);else expect(write.mock.calls[2]![0]).toEqual(identity)})
    it(`${kind} preserves accepted receipt when read fails and only retries reads`,async()=>{const write=vi.spyOn(api,method).mockResolvedValue({id:kind} as never),read=vi.mocked(kind==='report'?api.getTask:kind==='source'?api.sourceTemplate:api.documentTemplate);read.mockRejectedValueOnce(new Error('read failed'));const o=owner(kind);await o.start(input,[file()]);expect(o.getSnapshot().phase).toBe('ACCEPTED_READBACK');expect(o.canLeave().kind).toBe('BLOCK');await o.recover();expect(write).toHaveBeenCalledTimes(1);expect(o.getSnapshot().destination).toBe(kind==='report'?'/tasks/report':`/template-tasks/${kind}-runs/${kind}`)})
    it(`${kind} known rejection permits ordinary draft confirmation, while unknown stays blocked`,async()=>{const write=vi.spyOn(api,method).mockRejectedValueOnce(new ApiError('输入不合法',422)).mockRejectedValueOnce(new Error('lost')),o=owner(kind);await o.start(input,[file()]);expect(o.getSnapshot().phase).toBe('IDLE');expect(o.getSnapshot().error).toContain('输入不合法');expect(o.canLeave().kind).toBe('ALLOW');await o.start(input,[file()]);expect(write).toHaveBeenCalledTimes(2);expect(write.mock.calls[1]![0].requestKey).not.toBe(write.mock.calls[0]![0].requestKey);expect(o.canLeave().kind).toBe('BLOCK')})
  }
  it('hash preparation blocks navigation before POST and cannot write after a forced exit',async()=>{const bytes=deferred<ArrayBuffer>(),f=file();Object.defineProperty(f,'arrayBuffer',{value:()=>bytes.promise});const write=vi.spyOn(api,'createDocumentTemplate'),o=owner('document'),run=o.start(documentInput,[f]);expect(o.getSnapshot().hashing).toBe(true);expect(o.canLeave().kind).toBe('BLOCK');expect(write).not.toHaveBeenCalled();o.retire(true);bytes.resolve(new TextEncoder().encode('原文').buffer);await run;expect(write).not.toHaveBeenCalled()})
  it('restored UNKNOWN document compares actual bytes and order before original-key POST',async()=>{const write=vi.spyOn(api,'createDocumentTemplate').mockRejectedValue(new Error('lost')),first=owner('document'),files=[file('a','a.md'),file('b','b.md')];await first.start(documentInput,files);const key=write.mock.calls[0]![0].requestKey;first.retire(true);const restored=owner('document');await restored.restore();expect(restored.getSnapshot().needsFiles).toBe(true);await restored.start(documentInput,[file('changed','a.md'),file('b','b.md')]);await restored.start(documentInput,[file('b','b.md'),file('a','a.md')]);expect(write).toHaveBeenCalledTimes(1);const selected=[file('a','a.md'),file('b','b.md')];await restored.start(documentInput,selected);expect(write).toHaveBeenCalledTimes(2);expect(write.mock.calls[1]![0].requestKey).toBe(key);expect(write.mock.calls[1]![1]).toEqual(selected);expect(await identifyFiles(write.mock.calls[1]![1])).toEqual(await identifyFiles(files))})
  for(const kind of ['source','document'] as const)it(`${kind} restored known run reads exact id and permits only its destination`,async()=>{const method=kind==='source'?'createSourceTemplate':'createDocumentTemplate';const write=vi.spyOn(api,method).mockResolvedValue({id:kind} as never),first=owner(kind);await first.start(kind==='source'?sourceInput:documentInput,[file()]);first.retire(true);const restored=owner(kind);expect(restored.canLeave().kind).toBe('BLOCK');await restored.restore();const target=`/template-tasks/${kind}-runs/${kind}`;expect(restored.getSnapshot().destination).toBe(target);expect(restored.canLeave({destination:'/exit'}).kind).toBe('BLOCK');expect(restored.canLeave({destination:target}).kind).toBe('ALLOW');expect(restored.prepareHandoff()).toBeUndefined();expect(write).toHaveBeenCalledTimes(1)})
  it('keyless Start UNKNOWN reads original task before a second explicit same-id Start',async()=>{const create=vi.spyOn(api,'createTemplateTask').mockResolvedValue({id:'known',state:'PENDING_START'}),start=vi.mocked(api.startTemplateTask).mockRejectedValueOnce(new Error('lost')),o=owner('report');await o.start(reportInput);expect(o.getSnapshot().startUnknown).toBe(true);await o.recover();expect(start).toHaveBeenCalledTimes(1);expect(o.getSnapshot().startAllowed).toBe(true);await o.start({...reportInput,documentPath:'/changed'});expect(start.mock.calls).toEqual([['known'],['known']]);expect(create).toHaveBeenCalledTimes(1);expect(api.getTask).toHaveBeenCalledWith('known');expect(await o.startOriginal()).toBe('known');expect(start).toHaveBeenCalledTimes(2)})
})
