import type { DocumentTemplateOverview, SourceTemplateOverview, TemplateTaskCatalog, Task } from '@/types/domain'
export const reportInput={templateId:'SNAPSHOT_CODE_REVIEW',templateVersion:'1',projectId:'p',branchId:'local:main',reviewMode:'FULL' as const,documentPath:'/docs'}
export const sourceInput={templateId:'UNIT_TEST_DEVELOPMENT',templateVersion:'1',projectId:'p',sourcePath:'src/main',requirements:'保持公开接口',testOutputPath:'src/test'}
export const documentInput={templateId:'REQUIREMENT_CODE_REVIEW',templateVersion:'1',projectId:'p',branchId:'local:main'}
export const task=(id='task'):Task => ({id,projectId:'p',projectName:'项目',title:'评审任务',goal:'评审',branch:'main',worktreePath:'/project',status:'PENDING_START',attemptCount:0,maxAttempts:3,createdAt:'now',updatedAt:'now'})
export const sourceRun=(id='source'):SourceTemplateOverview => ({id,projectId:'p',templateId:'UNIT_TEST_DEVELOPMENT',templateVersion:'1',title:'源码任务',state:'PENDING_START',version:3,createdAt:'now',updatedAt:'now',archived:false,sourcePath:'src/main',testOutputPath:null,documentPath:null,requirements:'',snapshot:null,designerId:null,taskId:null,taskState:null,waitingReasonCode:null,waitingMessage:null,coverage:[],progress:[],canResume:false,canArchive:false,testProfile:null})
export const documentRun=(id='document'):DocumentTemplateOverview => ({id,projectId:'p',templateId:'REQUIREMENT_CODE_REVIEW',templateVersion:'1',title:'文档任务',state:'ASSESSING',waitingReasonCode:null,waitingMessage:null,designerId:null,taskId:null,requirementRevision:1,version:3,createdAt:'now',updatedAt:'now',canCancel:true,canResume:true,archived:false,uploadReady:true,snapshotSha:'frozen',files:[],progress:{attempts:0,validated:0,active:0,stopped:0,requirements:0,reports:0,revision:1}})
export const catalogFixture:TemplateTaskCatalog={timezone:'Asia/Shanghai',defaultStartDate:'2026-09-01',defaultEndDate:'2026-09-14',scoringVersion:'1',scoreFormula:'评分 = 各维度加权',dimensions:[{title:'质量',weight:1,levels:['完整','待改进']}],templates:[
  {id:'SNAPSHOT_CODE_REVIEW',workflow:'SNAPSHOT_CODE_REVIEW',version:'1',title:'快照代码评审',description:'按合同评审代码',category:'评审',contentRepairLimit:2,stages:['准备','评审'],scoringVersion:'1',inputs:{documents:false,branch:true,dates:true,extensions:[],maxFiles:0,maxFileMiB:0,maxTotalMiB:0}},
  {id:'UNIT_TEST_DEVELOPMENT',workflow:'SOURCE',version:'1',title:'单元测试开发',description:'冻结源码范围',category:'开发',contentRepairLimit:2,stages:['准备','开发'],scoringVersion:null,inputs:{documents:false,branch:false,dates:false,sourcePath:true,testOutputPath:true,documentOutputPath:false,extensions:[],maxFiles:0,maxFileMiB:0,maxTotalMiB:0}},
  {id:'REQUIREMENT_CODE_REVIEW',workflow:'DOCUMENT',version:'1',title:'需求代码评审',description:'原始需求文档',category:'评审',contentRepairLimit:2,stages:['分析','评审'],scoringVersion:null,inputs:{documents:true,branch:true,dates:false,extensions:['md','pdf','docx'],maxFiles:10,maxFileMiB:20,maxTotalMiB:50}},
]}

export const historicalRule={id:'rule',name:'隔离 Git 检查',projectId:'p',templateVersionId:'v',triggerType:'GIT_HEAD_CHANGED',triggerConfig:{},state:'ENABLED',approvalMode:'REVIEW_REQUIRED',version:3,updatedAt:'now',health:{status:'FAILED',lastCheckedAt:'now',consecutiveFailures:2,errorMessage:'Git 检查超时，请检查项目目录后刷新。'}}
export const historicalTemplate={id:'template',name:'旧模板',description:'冻结合同',state:'ARCHIVED',updatedAt:'now',version:3,versions:[{id:'v',templateId:'template',versionNumber:2,spec:{contractVersion:1,title:'原始合同',stages:[]},specSha256:'original-sha',immutable:true,autoStartApproved:false,createdAt:'now'}]}
export const historicalRun={id:'run',ruleId:'rule',triggerType:'MANUAL',state:'REVIEW_REQUIRED',draftId:'draft',taskId:null,evidence:{original:'frozen'},detectedAt:'now',startedAt:null,endedAt:null}
export const historicalWorkspace={templates:[historicalTemplate],rules:[historicalRule],runs:[historicalRun],serverTime:'now'}
