import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {deferred} from '@/pages/w2/core/coreTestHelpers'
import {api} from '@/api/client'
import {archiveReads,createTemplateHistoryArchiveController,decodeHistoricalRun,decodeHistoricalRule,decodeHistoricalTemplate,decodeHistoricalWorkspace,validateHistoricalExport} from './history'
import {historicalRule,historicalTemplate,historicalRun,historicalWorkspace} from './fixtures'
const owners:ReturnType<typeof createTemplateHistoryArchiveController>[]=[]
const owner=(reads=archiveReads)=>{const o=createTemplateHistoryArchiveController(reads);owners.push(o);return o}
beforeEach(()=>{vi.stubGlobal('fetch',vi.fn(async (input:RequestInfo|URL)=>{const path=String(input);const body=path.endsWith('/workspace')?historicalWorkspace:path.endsWith('/templates/template')?historicalTemplate:path.endsWith('/versions')?historicalTemplate.versions:path.endsWith('/rule/runs')?[historicalRun]:path.endsWith('/rules')?[historicalRule]:path.endsWith('/runs')?{runs:[historicalRun],serverTime:'now'}:[historicalTemplate];return new Response(JSON.stringify(body))}))})
afterEach(()=>{owners.splice(0).forEach(o=>o.retire(true));vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('current explicit historical consumer, never a retired writer',()=>{
  it('constructor/default catalogue makes zero historical requests, open issues exactly one workspace GET',async()=>{const o=owner();expect(fetch).not.toHaveBeenCalled();await o.open();expect(fetch).toHaveBeenCalledTimes(1);expect(fetch).toHaveBeenCalledWith('/api/automations/workspace',expect.objectContaining({headers:expect.objectContaining({Accept:'application/json'})}));expect(o.getSnapshot().workspace!.rules[0]!.health!.consecutiveFailures).toBe(2)})
  it('all nine original endpoints keep method GET and exact route identity',async()=>{await archiveReads.workspace();await archiveReads.templates();await archiveReads.template('template');await archiveReads.versions('template');await archiveReads.rules();await archiveReads.ruleRuns('rule');await archiveReads.runs();vi.mocked(fetch).mockResolvedValueOnce(new Response('{"contractVersion":1}'));await archiveReads.latestExport('template');vi.mocked(fetch).mockResolvedValueOnce(new Response('{"formatVersion":1,"templates":[],"rules":[]}'));await archiveReads.workspaceExport();expect(vi.mocked(fetch).mock.calls.map(c=>String(c[0]))).toEqual(['/api/automations/workspace','/api/automations/templates','/api/automations/templates/template','/api/automations/templates/template/versions','/api/automations/rules','/api/automations/rules/rule/runs','/api/automations/runs','/api/automations/templates/template/export','/api/automations/templates/export']);expect(vi.mocked(fetch).mock.calls.every(c=>!c[1]?.method || c[1].method==='GET')).toBe(true)})
  it('frozen contract spec/version/hash/approval survives decoding without compilation or normalization',()=>{const t=decodeHistoricalTemplate(historicalTemplate);expect(t.versions[0]).toEqual(historicalTemplate.versions[0]);expect(Object.isFrozen(t.versions[0]!.spec)).toBe(true);expect(()=>decodeHistoricalTemplate({...historicalTemplate,versions:[{...historicalTemplate.versions[0],templateId:'foreign'}]})).toThrow('归属')})
  it.each(['MANUAL','CRON','GIT_HEAD_CHANGED','WEBHOOK'])('preserves trigger %s and all original approval flags without secret recovery',trigger=>{const config=trigger==='CRON'?{expression:'0 0 * * *',timezone:'Asia/Shanghai'}:{branch:'main',webhookToken:'do-not-return',lastObservedHead:'private'};const r=decodeHistoricalRule({...historicalRule,triggerType:trigger,triggerConfig:config,approvalMode:'AUTO_START',webhookToken:'private'});expect(r.triggerType).toBe(trigger);expect(r.approvalMode).toBe('AUTO_START');expect(JSON.stringify(r)).not.toContain('do-not-return');expect(JSON.stringify(r)).not.toContain('lastObservedHead')})
  it.each(['DETECTED','REVIEW_REQUIRED','QUEUED','RUNNING','SUCCEEDED','FAILED','SKIPPED'])('keeps historical %s records with null task binding and original evidence',state=>{const r=decodeHistoricalRun({...historicalRun,state});expect(r.state).toBe(state);expect(r.taskId).toBeUndefined();expect(r.draftId).toBe('draft');expect(r.evidence).toEqual({original:'frozen'});expect(()=>decodeHistoricalRun(historicalRun,'foreign')).toThrow('归属')})
  it('failed health disappears only after a current server CHECKED read',async()=>{const o=owner();await o.open();expect(o.getSnapshot().workspace!.rules[0]!.health!.errorMessage).toContain('Git 检查超时');vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({...historicalWorkspace,rules:[{...historicalRule,health:{status:'CHECKED',lastCheckedAt:'next',consecutiveFailures:0,errorMessage:null}}]})));await o.refresh();expect(o.getSnapshot().workspace!.rules[0]!.health!.status).toBe('CHECKED');expect(JSON.stringify(o.getSnapshot())).not.toContain('Git 检查超时')})
  it('close and retirement invalidate late tab/id reads without hiding original records',async()=>{const pending=deferred<ReturnType<typeof decodeHistoricalWorkspace>>();const reads={...archiveReads,workspace:vi.fn(()=>pending.promise)},o=owner(reads),read=o.open();o.close();pending.resolve(decodeHistoricalWorkspace(historicalWorkspace));await read;expect(o.getSnapshot().workspace).toBeUndefined();expect(o.getSnapshot().open).toBe(false)})
  it('unreadable linked task leaves frozen run/evidence intact and issues no lifecycle writes',async()=>{vi.spyOn(api,'getTask').mockRejectedValue(new Error('removed'));const o=owner();await o.open();o.selectRun({...decodeHistoricalRun(historicalRun),taskId:'missing'});await o.verifyTask();expect(api.getTask).toHaveBeenCalledWith('missing');expect(o.getSnapshot().selectedRun!.evidence).toEqual({original:'frozen'});expect(o.getSnapshot().taskVerified).toBeUndefined();expect(o.getSnapshot().taskError).not.toBe('')})
  it('export preserves exact server bytes and rejects secrets, runs and unsupported rule fields',()=>{const text=' { "formatVersion": 1, "templates": [], "rules": [] }\n';expect(validateHistoricalExport(text,'workspace')).toBe(text);expect(()=>validateHistoricalExport('{"secret":"bad"}','latest')).toThrow('密钥');expect(()=>validateHistoricalExport('{"formatVersion":1,"templates":[],"rules":[],"runs":[]}','workspace')).toThrow('运行');expect(()=>validateHistoricalExport('{"formatVersion":1,"templates":[],"rules":[{"health":{}}]}','workspace')).toThrow('字段')})
})
