import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react'
import {StrictMode} from 'react'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {webcrypto} from 'node:crypto'
import {api,ApiError} from '@/api/client'
import {semanticName} from '@/foundation/semanticRegistry'
import {coreFixture,coreFrame,setupCoreDom} from '@/pages/w2/core/coreTestHelpers'
import {TemplateTasksPage} from './TemplateTasksPage'
import {ArchiveTabs} from './HistoryDrawer'
import {catalogFixture,task} from './fixtures'
import {historicalWorkspace,historicalRule} from './fixtures'
import type {TemplateCatalogController} from './controller'
const fixtures:ReturnType<typeof coreFixture>[]=[]
function page(){const f=coreFixture();f.props.route={path:'/template-tasks',fullPath:'/template-tasks?projectId=p',query:{projectId:'p'},params:{}};fixtures.push(f);return {f,view:render(coreFrame(<TemplateTasksPage {...f.props}/>))}}
const button=(key:Parameters<typeof semanticName>[0],target?:string)=>screen.getByRole('button',{name:semanticName(key,target)})
beforeEach(()=>{setupCoreDom();sessionStorage.clear();vi.stubGlobal('crypto',webcrypto);vi.spyOn(api,'templateCatalog').mockResolvedValue(catalogFixture);vi.spyOn(api,'templateProjects').mockResolvedValue({items:[],facets:{}});vi.spyOn(api,'templateProject').mockResolvedValue({id:'p',name:'项目',createdAt:'now',documentPath:'/docs'});vi.spyOn(api,'templateBranches').mockResolvedValue({page:{items:[{id:'main',label:'main',ref:'main',remote:null}],nextCursor:null},defaultBranch:{id:'main',label:'main',ref:'main',remote:null},defaultBranchId:'main',remoteAvailable:true});vi.spyOn(api,'getTask').mockImplementation(async id=>task(id));vi.spyOn(api,'startTemplateTask').mockImplementation(async id=>({id,state:'QUEUED'}));vi.spyOn(api,'documentTemplateRequest').mockRejectedValue(new ApiError('未确认',404));vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify(historicalWorkspace))))})
afterEach(()=>{cleanup();fixtures.splice(0).forEach(f=>f.dispose());vi.restoreAllMocks();vi.unstubAllGlobals();sessionStorage.clear()})
it('archive keyboard focus is local manual activation; busy tabs issue no selection or reads',()=>{const change=vi.fn(),items=[{key:'overview' as const,label:'归档概览',children:'概览'},{key:'templates' as const,label:'历史模板',children:'模板'},{key:'rules' as const,label:'旧规则与检测记录',children:'规则'},{key:'runs' as const,label:'运行记录',children:'运行'},{key:'export' as const,label:'导出说明',children:'导出'}];const view=render(coreFrame(<ArchiveTabs activeKey="overview" busy={false} onChange={change} items={items}/>));const tabs=screen.getAllByRole('tab');act(()=>tabs[0]!.focus());fireEvent.keyDown(tabs[0]!,{key:'ArrowRight'});expect(document.activeElement).toBe(tabs[1]);expect(change).not.toHaveBeenCalled();fireEvent.keyDown(tabs[1]!,{key:'End'});expect(document.activeElement).toBe(tabs[4]);fireEvent.keyDown(tabs[4]!,{key:'Enter'});expect(change).toHaveBeenCalledExactlyOnceWith('export');view.rerender(coreFrame(<ArchiveTabs activeKey="export" busy={true} onChange={change} items={items}/>));expect(screen.getByRole('tabpanel').textContent).toBe('导出');fireEvent.keyDown(screen.getAllByRole('tab')[4]!,{key:' '});expect(change).toHaveBeenCalledTimes(1);expect(screen.getAllByRole('tab').every(tab=>(tab as HTMLButtonElement).disabled)).toBe(true);expect(fetch).not.toHaveBeenCalled()})
it('catalogue shows dynamic template search/categories and exact inherited branch/path/date contract with zero history GET',async()=>{page();await screen.findByRole('heading',{name:'快照代码评审'});await waitFor(()=>expect((screen.getByLabelText('分支') as HTMLSelectElement).value).toBe('main'));expect((screen.getByLabelText('文档生成路径') as HTMLInputElement).value).toBe('/docs');expect(screen.getByText('包含结束日期当天 24:00 之前的提交。')).toBeTruthy();expect(fetch).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('搜索模板'),{target:{value:'单元'}});expect(screen.getByRole('button',{name:'单元测试开发'})).toBeTruthy();expect(screen.queryByRole('button',{name:'需求代码评审'})).toBeNull();fireEvent.change(screen.getByLabelText('搜索模板'),{target:{value:''}});expect(screen.getByRole('link',{name:'新建需求开发'}).getAttribute('href')).toContain('/requirements/new?template=builtin.workflow.development&projectId=p')})
it('actual report submit preserves FULL mode/body and navigates only accepted known task',async()=>{const create=vi.spyOn(api,'createTemplateTask').mockResolvedValue({id:'known',state:'PENDING_START'}),{f}=page();await waitFor(()=>expect((screen.getByLabelText('分支') as HTMLSelectElement).value).toBe('main'));fireEvent.change(screen.getByLabelText('评审模式'),{target:{value:'FULL'}});expect(screen.queryByLabelText('开始日期')).toBeNull();fireEvent.click(button('template.startReview'));await waitFor(()=>expect(f.props.navigation.go).toHaveBeenCalled());expect(create).toHaveBeenCalledWith(expect.objectContaining({templateId:'SNAPSHOT_CODE_REVIEW',templateVersion:'1',projectId:'p',branchId:'main',reviewMode:'FULL',documentPath:'/docs'}));expect(create.mock.calls[0]![0]).not.toHaveProperty('startDate');expect(api.startTemplateTask).toHaveBeenCalledWith('known');expect(f.props.navigation.go).toHaveBeenCalledWith('/tasks/known',false,expect.any(Object))})
it('actual UNKNOWN locks business inputs, keeps recovery visible and registered leave guard BLOCK',async()=>{vi.spyOn(api,'createTemplateTask').mockRejectedValue(new Error('lost'));const {f}=page();await waitFor(()=>expect((screen.getByLabelText('分支') as HTMLSelectElement).value).toBe('main'));fireEvent.click(button('template.startReview'));await screen.findByText('评审模板创建：原操作结果尚未确认');expect((screen.getByLabelText('文档生成路径') as HTMLInputElement).disabled).toBe(true);expect(button('receipt.retryOriginal','评审模板创建')).toBeTruthy();expect([...f.guards][0]!().kind).toBe('BLOCK');expect(api.createTemplateTask).toHaveBeenCalledTimes(1)})
it('source template field capabilities and scope preview must complete before create',async()=>{const preview=vi.spyOn(api,'sourcePreview').mockResolvedValue({sourcePath:'src/main',testOutputPath:'src/test',documentPath:null,manifestSha256:'sha',targetCount:2,excludedCount:1,moduleCount:1,truncated:false,files:[],testProfile:null,configurationProblem:null});page();await screen.findByRole('heading',{name:'快照代码评审'});fireEvent.click(screen.getByRole('button',{name:'单元测试开发'}));await screen.findByLabelText('源码路径');expect(screen.queryByLabelText('分支')).toBeNull();expect(screen.queryByLabelText('文档生成路径')).toBeNull();fireEvent.change(screen.getByLabelText('源码路径'),{target:{value:' src/main '}});fireEvent.change(screen.getByLabelText('测试输出路径'),{target:{value:' src/test '}});fireEvent.change(screen.getByLabelText('补充要求'),{target:{value:' 保持接口 '}});expect((button('template.create') as HTMLButtonElement).disabled).toBe(true);fireEvent.click(button('template.checkScope'));await screen.findByText('目标 2 · 排除 1 · 模块 1');expect(preview).toHaveBeenCalledWith(expect.objectContaining({sourcePath:'src/main',testOutputPath:'src/test',requirements:'保持接口'}));expect((button('template.create') as HTMLButtonElement).disabled).toBe(false)})
it('document native files, chooser cancellation, ordered list and validation stay visible',async()=>{page();await screen.findByRole('heading',{name:'快照代码评审'});fireEvent.click(screen.getByRole('button',{name:'需求代码评审'}));await screen.findByLabelText('需求文档');const files=[new File(['1'],'a.md'),new File(['2'],'b.pdf')];fireEvent.change(screen.getByLabelText('需求文档'),{target:{files}});expect(screen.getByText(/1\. a.md/)).toBeTruthy();expect(screen.getByText(/2\. b.pdf/)).toBeTruthy();fireEvent.change(screen.getByLabelText('需求文档'),{target:{files:[]}});expect(screen.getByText(/1\. a.md/)).toBeTruthy();fireEvent.change(screen.getByLabelText('需求文档'),{target:{files:[new File(['bad'],'old.doc')]}});expect(screen.getByRole('alert').textContent).toContain('转换旧 DOC');expect((button('template.create') as HTMLButtonElement).disabled).toBe(true)})
it('switch confirmation cannot discard a newer public-owner draft and Stay preserves input',async()=>{const {f}=page();await screen.findByRole('heading',{name:'快照代码评审'});fireEvent.change(screen.getByLabelText('文档生成路径'),{target:{value:'/draft'}});fireEvent.click(screen.getByRole('button',{name:'单元测试开发'}));const dialog=await screen.findByRole('dialog');const retained=[...f.retained.keys()].find(value=>(value as TemplateCatalogController).identity?.domain==='template-catalog') as TemplateCatalogController;act(()=>retained.change('documentPath','/newer'));expect((within(dialog).getByRole('button',{name:semanticName('ui.discardChanges')}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByLabelText('文档生成路径') as HTMLInputElement).value).toBe('/newer')})
it('archive is an explicit readonly consumer and CHECKED refresh clears old failure text',async()=>{page();await screen.findByRole('heading',{name:'快照代码评审'});expect(fetch).not.toHaveBeenCalled();fireEvent.click(button('automation.readArchive'));const health=await screen.findByLabelText('自动化检测状态');expect(health.textContent).toContain('检测失败 · 连续 2 次');expect(screen.getByText('Git 检查超时，请检查项目目录后刷新。')).toBeTruthy();vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({...historicalWorkspace,rules:[{...historicalRule,health:{status:'CHECKED',lastCheckedAt:'later',consecutiveFailures:0,errorMessage:null}}]})));fireEvent.click(button('ui.refresh','历史模板与自动化记录'));await waitFor(()=>expect(screen.getByLabelText('自动化检测状态').textContent).toContain('检测正常'));expect(screen.queryByText('Git 检查超时，请检查项目目录后刷新。')).toBeNull();expect(vi.mocked(fetch).mock.calls.every(call=>!call[1]?.method)).toBe(true);expect(screen.queryByRole('button',{name:'创建旧规则'})).toBeNull()})
it('StrictMode mounting never creates commands or downloads history; pending APIs remain one owner',async()=>{const f=coreFixture();f.props.route={path:'/template-tasks',fullPath:'/template-tasks',query:{},params:{}};fixtures.push(f);const create=vi.spyOn(api,'createTemplateTask'),view=render(coreFrame(<StrictMode><TemplateTasksPage {...f.props}/></StrictMode>));await screen.findByRole('heading',{name:'快照代码评审'});expect(api.templateCatalog).toHaveBeenCalledTimes(1);expect(create).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();view.unmount();f.dispose()})
