import { beforeEach,afterEach,describe,expect,it,vi } from 'vitest'
import { webcrypto } from 'node:crypto'
import { api as appApi } from '@/api/client'
import { knowledgeApi as api } from '@/api/knowledge'
import { createKnowledgeController } from '@/pages/w3/knowledge/controller'
import { conversationFixture,messageFixture,sourceFixture } from '@/pages/w3/knowledge/fixtures'
import { defaultSettings } from '@/pages/w2/core/settingsController'
import type { KnowledgeConversation,KnowledgeMessage } from '@/types/domain'
const conversation={...conversationFixture(),projectId:'project',model:'local/model',version:0}
const message=(ordinal:number,answer=''):KnowledgeMessage=>({...messageFixture(ordinal,answer),id:`message-${ordinal}`})
const owners:ReturnType<typeof createKnowledgeController>[]=[]
function owner(id='conversation'){const value=createKnowledgeController({conversationId:id});owners.push(value);return value}
async function loaded(id='conversation'){const value=owner(id);await value.load(id);return value}
async function createSend(text='问题'){const value=owner('');await value.initialize();value.editText(text);await value.send();return value}
beforeEach(()=>{sessionStorage.clear();vi.stubGlobal('crypto',webcrypto);vi.spyOn(appApi,'getProjects').mockResolvedValue([{id:'project',name:'项目',rootPath:'/project',status:'READY',updatedAt:'now',taskCount:0,openDesignerSessionCount:0}]);vi.spyOn(appApi,'getSettings').mockResolvedValue({...defaultSettings(),openCode:{...defaultSettings().openCode,mode:'managed',provider:'local',model:'model'}});vi.spyOn(appApi,'getSettingsModels').mockResolvedValue([]);vi.spyOn(api,'sources').mockResolvedValue({items:[sourceFixture],facets:{}});vi.spyOn(api,'get').mockImplementation(async id=>({...conversation,id}));vi.spyOn(api,'messages').mockResolvedValue({items:[],facets:{}});vi.spyOn(api,'updates').mockResolvedValue({items:[],facets:{}});vi.spyOn(api,'receipt').mockResolvedValue({accepted:false});vi.spyOn(api,'create').mockImplementation(async input=>({...conversation,id:input.id}));vi.spyOn(api,'send').mockResolvedValue(message(1));vi.spyOn(api,'events').mockImplementation(()=>({close:vi.fn(),onmessage:null,onerror:null,onopen:null}) as unknown as EventSource)})
afterEach(()=>{owners.splice(0).forEach(value=>value.retire(true));vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('knowledge authoritative chat',()=>{
 it('keeps exact message identity across a lost response and page reload',async()=>{vi.mocked(api.send).mockRejectedValueOnce(new Error('lost'));const first=await createSend(),id=first.getSnapshot().conversation!.id,key=vi.mocked(api.send).mock.calls[0]![1];expect(first.getSnapshot().mutation.phase).toBe('UNKNOWN');first.retire(true);const restored=await loaded(id);await restored.retryOriginal();expect(vi.mocked(api.send).mock.calls[1]![1]).toBe(key);expect(api.create).toHaveBeenCalledTimes(1);expect(restored.getSnapshot().mutation.phase).toBe('SETTLED')})
 it('clears an acknowledged lost response on reload so the next question can be sent',async()=>{vi.mocked(api.send).mockRejectedValueOnce(new Error('lost'));const first=await createSend(),id=first.getSnapshot().conversation!.id,oldKey=vi.mocked(api.send).mock.calls[0]![1];first.retire(true);vi.mocked(api.receipt).mockResolvedValue({accepted:true,messageId:'stored'});const restored=await loaded(id);await restored.loadSettings();restored.editText('新的问题');expect(await restored.send()).toBe(true);expect(vi.mocked(api.send).mock.calls[1]![1]).not.toBe(oldKey);expect(restored.getSnapshot().text).toBe('')})
 it('restores an unacknowledged draft after reload without automatically dispatching it',async()=>{vi.mocked(api.send).mockRejectedValueOnce(new Error('lost'));const first=await createSend(),id=first.getSnapshot().conversation!.id;first.retire(true);const restored=await loaded(id);expect(restored.getSnapshot().text).toBe('问题');expect(api.send).toHaveBeenCalledTimes(1)})
 it('rejects a changed question while the previous delivery is unknown',async()=>{vi.mocked(api.send).mockRejectedValue(new Error('lost'));const value=await createSend();expect(value.editText('different')).toBe(false);expect(await value.send()).toBe(false);expect(api.send).toHaveBeenCalledTimes(1);expect(value.canLeave().kind).toBe('BLOCK');expect(value.getSnapshot().text).toBe('问题')})
 it('never lets late reads overwrite a different conversation',async()=>{let resolve!:(value:KnowledgeConversation)=>void;vi.mocked(api.get).mockReturnValueOnce(new Promise(done=>{resolve=done}));const value=owner(),first=value.load('old');await value.load('new');resolve({...conversation,id:'old'});await first;expect(value.getSnapshot().conversation?.id).toBe('new')})
 it('keeps stop pending until REST reports an idle conversation',async()=>{vi.mocked(api.get).mockResolvedValue({...conversation,state:'RUNNING'});vi.spyOn(api,'stop').mockResolvedValue({...conversation,state:'STOPPING'});const value=await loaded();vi.mocked(api.get).mockResolvedValue({...conversation,state:'STOPPING'});await value.stop();expect(value.active()).toBe(true);vi.mocked(api.get).mockResolvedValue(conversation);await value.refresh();expect(value.active()).toBe(false)})
 it('does not restore an old conversation when its stop response arrives after navigation',async()=>{let resolve!:(value:KnowledgeConversation)=>void;vi.mocked(api.get).mockImplementation(async id=>({...conversation,id,state:'RUNNING'}));vi.spyOn(api,'stop').mockReturnValueOnce(new Promise(done=>{resolve=done}));const first=await loaded(),pending=first.stop();first.retire(true);const next=await loaded('new');const reads=vi.mocked(api.get).mock.calls.length;resolve(conversation);await pending;expect(next.getSnapshot().conversation?.id).toBe('new');expect(api.get).toHaveBeenCalledTimes(reads)})
 it('does not turn an SSE disconnect into a model failure',async()=>{const value=await loaded();const detach=value.attachView();await value.initialize();const stream=vi.mocked(api.events).mock.results.at(-1)!.value;stream.onerror?.(new Event('error'));expect(value.getSnapshot().disconnected).toBe(true);expect(value.getSnapshot().conversation?.state).toBe('IDLE');expect(value.getSnapshot().error).toBe('');detach()})
 it('does not download loaded historical pages on a live refresh',async()=>{vi.mocked(api.messages).mockResolvedValueOnce({items:[],facets:{},nextCursor:'older-1'}).mockResolvedValueOnce({items:[],facets:{},nextCursor:'older-2'}).mockResolvedValueOnce({items:[],facets:{}});const value=await loaded();await value.more();await value.more();vi.mocked(api.messages).mockClear();await value.refresh();expect(api.messages).toHaveBeenCalledTimes(0);expect(api.updates).toHaveBeenCalledTimes(1)})
 it('updates the last turn, catches up missing pages, and preserves older messages and token totals',async()=>{vi.mocked(api.get).mockResolvedValue({...conversation,usage:{inputTokens:100,outputTokens:80}});vi.mocked(api.messages).mockResolvedValue({items:[message(3,'草稿')],facets:{},nextCursor:'older'});const value=await loaded();vi.mocked(api.messages).mockResolvedValue({items:[message(1,'历史')],facets:{}});await value.more();vi.mocked(api.get).mockResolvedValue({...conversation,usage:{inputTokens:90,outputTokens:null}});vi.mocked(api.updates).mockResolvedValueOnce({items:[message(3,'完成'),message(4)],facets:{},nextCursor:'catch-up'}).mockResolvedValueOnce({items:[message(5)],facets:{}});await value.refresh();await vi.waitFor(()=>expect(value.getSnapshot().messages).toHaveLength(4));expect(api.updates).toHaveBeenNthCalledWith(1,'conversation',2,'');expect(api.updates).toHaveBeenNthCalledWith(2,'conversation',2,'catch-up');expect(value.getSnapshot().messages.map(row=>row.answer)).toEqual(['历史','完成','','']);expect(value.getSnapshot().conversation?.usage).toEqual({inputTokens:100,outputTokens:80})})
 it('coalesces event bursts and discards a pending timer when leaving the conversation',async()=>{vi.useFakeTimers();const value=await loaded(),detach=value.attachView();await value.initialize();const stream=vi.mocked(api.events).mock.results.at(-1)!.value;for(let i=0;i<10;i++)stream.onmessage?.(new MessageEvent('message'));await vi.advanceTimersByTimeAsync(180);expect(api.updates).toHaveBeenCalledTimes(1);stream.onmessage?.(new MessageEvent('message'));detach();value.retire(true);await vi.advanceTimersByTimeAsync(180);expect(api.updates).toHaveBeenCalledTimes(1)})
 it('ignores late incremental pages after a conversation switch',async()=>{let resolve!:(value:Awaited<ReturnType<typeof api.updates>>)=>void;vi.mocked(api.updates).mockReturnValueOnce(new Promise(done=>{resolve=done}));const value=await loaded(),pending=value.refresh();await value.load('new');resolve({items:[message(9,'旧会话')],facets:{},nextCursor:'old'});await pending;expect(value.getSnapshot().conversation?.id).toBe('new');expect(value.getSnapshot().messages).toEqual([]);await value.refresh();expect(api.updates).toHaveBeenLastCalledWith('new',0,'')})
})
