import { displayLabel } from '@/utils/displayLabels'
const record=(value:unknown):Record<string,unknown>=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}
const rows=(value:unknown)=>Array.isArray(value)?value.map(record):[]
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback
function verifierLabel(v:Record<string,unknown>) { const type=text(v.type).toUpperCase();if(type==='PROCESS'){const command=Array.isArray(v.command)?v.command.filter((x):x is string=>typeof x==='string').join(' '):'缺少命令';return command+(v.outputContains?' → 包含“'+text(v.outputContains)+'”':'')}if(type==='FILE_EXISTS')return '仅记录：'+text(v.path,'缺少路径');if(type==='FILE_NOT_EXISTS')return '文件不存在：'+text(v.path,'缺少路径');if(type==='GIT_DIFF')return 'Git 改动范围与删除策略';return displayLabel(type||'UNKNOWN') }
export function ExecutionAcceptancePanel({source}:{source:string}) {
 let stages:Record<string,unknown>[]=[];try{stages=rows(record(JSON.parse(source)).stages)}catch{}
 return <section className="w4-card acceptance-panel" aria-label="验收计划"><h2>验收计划</h2>{stages.length?stages.map((stage,index)=>{const verifiers=rows(stage.verifiers),criteria=rows(stage.acceptanceCriteria).filter(c=>c.verificationMode==='JUDGE'||c.verificationMode==='BOTH');return <article key={index}><h3>阶段 {index+1} · {text(stage.objective,`阶段 ${index+1}`)}</h3><h4>机器执行验收</h4>{verifiers.map((v,i)=><p key={i}><strong>{({PROCESS:'命令验证',FILE_EXISTS:'兼容检查（不阻断）',FILE_NOT_EXISTS:'文件不存在',GIT_DIFF:'Git 差异检查'} as Record<string,string>)[text(v.type).toUpperCase()]||displayLabel(text(v.type))}</strong> · {verifierLabel(v)}</p>)}{!!criteria.length&&<><h4>最终 AI 评审</h4>{criteria.map((c,i)=><p key={i}>{c.verificationMode==='BOTH'?'机器 + AI':'AI 评审'} · {text(c.judgeRubric,'尚未填写 AI 评审准则')}{c.verificationMode==='JUDGE'&&` · 仅 AI 原因：${text(c.judgeOnlyReason,'尚未填写')}`}</p>)}</>}{!verifiers.some(v=>text(v.type).toUpperCase()!=='GIT_DIFF')&&<p role="status">缺少功能验收，暂时无法确认。</p>}</article>}):<p>执行规范有误或尚未定义阶段。</p>}</section>
}
