import {useMemo} from 'react'
import {UiActionButton,UiConfirmDialog} from '@/foundation/components'
import type {TaskPanelProps} from '../shared/types'
import {CommandNotice,ReadNotice,useProtectedOwner,useW4Owner} from '../shared/parts'
import {createSessionLifecycleController,type SessionLifecycleAction,type SessionLifecycleController} from './sessionLifecycleController'
import {displayLabel} from '@/utils/displayLabels'
import type {UiActionKey} from '@/foundation/semanticRegistry'
const keys:Record<SessionLifecycleAction,UiActionKey>={refresh:'session.syncTodos',checkpoint:'session.createCheckpoint',fork:'session.forkTranscript',revert:'session.revertWorktree',summarize:'session.requestSummary'}
export function SessionLifecyclePanel({task,page,parent,sessionId,controller}:TaskPanelProps&{sessionId:string;controller?:SessionLifecycleController}){
 const candidate=useMemo(()=>controller??createSessionLifecycleController(task,sessionId),[controller,task.id,sessionId]),owner=useProtectedOwner(candidate);owner.updateTask(task);owner.setWriteGate(()=>parent.canStartWrite(owner));const s=useW4Owner(page,owner,parent)
 return <section className="w4-card" aria-label="会话生命周期"><header><h3>会话快照</h3><UiActionButton actionKey="session.refreshSnapshot" busy={s.loading} onAction={()=>void owner.load()}/></header><ReadNotice error={s.error} retry={()=>void owner.load()}/><CommandNotice command={s.command} recover={()=>void owner.recover()}/>{s.notice&&<p role="status">{s.notice}</p>}<div className="w4-actions">{(Object.keys(keys)as SessionLifecycleAction[]).map(action=><UiActionButton key={action} actionKey={keys[action]} busy={s.command.busy} availability={owner.allowed(action)?{kind:'enabled'}:{kind:'disabled',reason:'请先结清原操作；Fork、回退还需要暂停任务和原消息引用。'}} onAction={()=>owner.request(action)}/>)}</div>{task.branch==='DIRECT'?<p>直接执行目录不支持原地回退；请创建派生 Recovery 任务。</p>:task.status!=='PAUSED'&&<p>Fork 与回退前必须先暂停任务，并由服务端确认旧 writer 已终止。</p>}<label>OpenCode message id<input aria-label="OpenCode message id" value={s.messageId} disabled={owner.locked()} onChange={e=>owner.change('messageId',e.target.value)}/></label><label>OpenCode part id<input aria-label="OpenCode part id" value={s.partId} disabled={owner.locked()} onChange={e=>owner.change('partId',e.target.value)}/></label><h4>服务端 todo</h4>{s.todos.length?<ol>{s.todos.map(row=><li key={row.id}>{row.content} · {displayLabel(row.status)}</li>)}</ol>:<p>尚无持久化 todo；可点击“同步真实 todo”。</p>}<h4>Checkpoint</h4>{s.checkpoints.length?<ol>{s.checkpoints.map(row=><li key={row.id}><details><summary>{row.externalMessageId?'消息快照':'完整 transcript'}</summary><code>{row.contentSha256}</code></details></li>)}</ol>:<p>尚未固化 transcript、todo 和 diff 引用。</p>}<UiConfirmDialog open={!!s.confirming} title="会话回退操作" confirmActionKey={s.confirming?keys[s.confirming.action]:'session.revertWorktree'} policy={owner.confirmationCurrent()?{kind:'allow'}:{kind:'block',reason:'原会话、任务许可或输入已变化，请重新核对。'}} busy={s.command.busy} onConfirm={()=>owner.confirm()} onCancel={owner.cancelConfirmation}>仅操作原会话。关闭详情不会停止服务端执行。</UiConfirmDialog></section>
}
