ALTER TABLE ppt_agent_question ADD COLUMN kind TEXT NOT NULL DEFAULT 'CLARIFICATION'
 CHECK(kind IN ('CLARIFICATION','REQUIREMENTS_CONFIRMATION'));
ALTER TABLE ppt_agent_question ADD COLUMN confirmed INTEGER
 CHECK(confirmed IS NULL OR (confirmed IN (0,1) AND kind='REQUIREMENTS_CONFIRMATION' AND state='ANSWERED'));
