import { expect, test, type Page } from '@playwright/test'
import { canvasReviewFixture } from './fixtures/canvasReview'

const evidence = process.env.CANVAS_EVIDENCE_DIR ?? 'test-results/canvas-focus'
const skins = ['spdb', 'tech-blue', 'github-white'] as const

async function clearSelection(page: Page) {
  const canvas = page.getByRole('region', { name: '流程画布', exact: true })
  const box = await canvas.boundingBox()
  if (!box) throw new Error('画布未显示')
  await canvas.click({ position: { x: 26, y: box.height - 120 } })
}

for (const skin of skins) {
  test(`${skin} 流程画布默认留白，选择、切换、连线和取消形成完整循环`, async ({ page }) => {
    const data = await canvasReviewFixture(page)
    await page.setViewportSize({ width: 1600, height: 1000 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.addInitScript(value => localStorage.setItem('loopper.skin', value), skin)
    await page.goto('/workflows/new')
    await expect(page.locator('[data-canvas-runtime="react"][data-canvas-kind="workflow"] .react-flow')).toBeVisible()
    await expect(page.locator('.workflow-canvas-empty')).toBeVisible()
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await expect(page.getByLabel('流程名称', { exact: true })).toHaveCount(0)
    const canvas = page.locator('.workflow-canvas')
    const box = await canvas.boundingBox()
    expect(box!.width).toBeGreaterThan(1200)
    expect(box!.height).toBeGreaterThan(750)
    await page.screenshot({ path: `${evidence}/${skin}-empty.png`, fullPage: true })

    await page.goto('/workflows/canvas-review')
    await expect(page.locator('[data-canvas-runtime="react"][data-canvas-kind="workflow"] .react-flow')).toBeVisible()
    await expect(page.locator('.workflow-node')).toHaveCount(3)
    await expect(page.locator('.workflow-port')).toHaveCount(0)
    await page.screenshot({ path: `${evidence}/${skin}-editor.png`, fullPage: true })
    const first = page.locator('.workflow-node').filter({ hasText: '确认需求' })
    const second = page.locator('.workflow-node').filter({ hasText: '分析与设计' })
    await first.click()
    await expect(page.getByLabel('名称', { exact: true })).toHaveValue('确认需求')
    await first.click()
    await expect(page.locator('.workflow-context-panel')).toHaveCount(1)
    await expect(page.locator('.workflow-port')).toHaveCount(1)
    await page.screenshot({ path: `${evidence}/${skin}-selected.png`, fullPage: true })
    await second.click()
    await expect(page.getByLabel('名称', { exact: true })).toHaveValue('分析与设计')
    await expect(page.locator('.workflow-node.selected')).toHaveCount(1)
    await page.locator('.workflow-wire-hit').first().focus()
    await page.keyboard.press('Space')
    await expect(page.getByRole('complementary', { name: '连接设置', exact: true })).toBeVisible()
    await expect(page.locator('.workflow-node.selected')).toHaveCount(0)
    await page.keyboard.press('Escape')
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await first.focus(); await page.keyboard.press('Enter')
    await expect(page.getByLabel('名称', { exact: true })).toHaveValue('确认需求')
    await page.getByRole('button', { name: '关闭节点详情', exact: true }).click()
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await first.click(); await clearSelection(page)
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await expect(page.locator('.workflow-node.selected')).toHaveCount(0)
    await page.screenshot({ path: `${evidence}/${skin}-deselected.png`, fullPage: true })
    expect(data.mutations).toEqual([])
    expect(data.errors).toEqual([])
  })

  test(`${skin} 需求规划与执行均按选择展示详情，资料与辅助操作仍可达`, async ({ page }) => {
    const data = await canvasReviewFixture(page)
    await page.setViewportSize({ width: 1600, height: 1000 })
    await page.addInitScript(value => localStorage.setItem('loopper.skin', value), skin)
    await page.goto('/requirements/req')
    await expect(page.locator('[data-canvas-runtime="react"][data-canvas-kind="workflow"] .react-flow')).toBeVisible()
    await expect(page.locator('.workflow-node')).toHaveCount(3)
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await page.screenshot({ path: `${evidence}/${skin}-planning.png`, fullPage: true })
    await page.locator('.workflow-node').first().click()
    await expect(page.getByLabel('名称', { exact: true })).toHaveValue('确认需求')
    await page.screenshot({ path: `${evidence}/${skin}-planning-selected.png`, fullPage: true })
    await page.keyboard.press('Escape')
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await page.getByRole('button', { name: '需求与资料', exact: true }).click()
    await expect(page.getByRole('complementary', { name: '需求与资料', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    data.req.state = 'PAUSED'; data.snapshot.execution.state = 'PAUSED'
    await page.reload()
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await expect(page.getByRole('button', { name: '执行所选节点', exact: true })).toHaveCount(0)
    await page.locator('.workflow-node').first().click()
    await expect(page.getByRole('complementary', { name: '节点执行详情' })).toBeVisible()
    await expect(page.getByRole('button', { name: '执行所选节点', exact: true })).toBeEnabled()
    await page.screenshot({ path: `${evidence}/${skin}-execution-selected.png`, fullPage: true })
    await clearSelection(page)
    await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
    await page.screenshot({ path: `${evidence}/${skin}-execution.png`, fullPage: true })
    expect(data.mutations).toEqual([])
    expect(data.errors).toEqual([])
  })
}

for (const skin of skins) {
  test(`${skin} 流程库、需求列表和新建需求的入口与视觉一致`, async ({ page }) => {
    const data = await canvasReviewFixture(page)
    await page.setViewportSize({ width: 1600, height: 1000 })
    await page.addInitScript(value => localStorage.setItem('loopper.skin', value), skin)
    await page.goto('/workflows')
    await expect(page.getByRole('link', { name: data.flow.title, exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: '复制', exact: true })).toHaveCount(0)
    await page.screenshot({ path: `${evidence}/${skin}-library.png`, fullPage: true })
    await page.getByRole('button', { name: `更多操作：${data.flow.title}`, exact: true }).click()
    await expect(page.getByRole('button', { name: '复制', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: '复制', exact: true })).toHaveCount(0)
    await page.goto('/requirements')
    await expect(page.getByRole('link', { name: data.req.title, exact: true })).toBeVisible()
    await page.screenshot({ path: `${evidence}/${skin}-requirements.png`, fullPage: true })
    await page.getByRole('link', { name: '打开画布', exact: true }).click()
    await expect(page.locator('.workflow-node')).toHaveCount(3)
    await page.goto('/requirements/new?template=canvas-review&projectId=project')
    await page.getByLabel('需求名称', { exact: true }).fill('新需求 · 模拟数据')
    await page.getByLabel('需求说明', { exact: true }).fill('明确工作范围，形成方案，并人工核对交付结果。')
    await expect(page.getByRole('button', { name: '进入规划画布', exact: true })).toBeEnabled()
    await page.screenshot({ path: `${evidence}/${skin}-new-requirement.png`, fullPage: true })
    expect(data.mutations).toEqual([])
    expect(data.errors).toEqual([])
  })
}

test('跨标签换肤不丢失选中草稿，刷新恢复皮肤，窄屏面板可以关闭', async ({ page, context }) => {
  await canvasReviewFixture(page)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/workflows/canvas-review')
    await expect(page.locator('[data-canvas-runtime="react"][data-canvas-kind="workflow"] .react-flow')).toBeVisible()
  await page.locator('.workflow-node').first().click()
  await page.getByLabel('任务说明', { exact: true }).fill('换肤过程中保留的任务草稿')
  const home = await context.newPage(); await canvasReviewFixture(home); await home.goto('/')
  for (const skin of skins) {
    await home.getByRole('combobox', { name: '选择皮肤' }).selectOption(skin)
    await expect(page.locator('html')).toHaveAttribute('data-skin', skin)
    await expect(page.getByLabel('任务说明', { exact: true })).toHaveValue('换肤过程中保留的任务草稿')
    await expect(page.locator('.workflow-node.selected')).toHaveCount(1)
  }
  await home.close()
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-skin', 'github-white')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '适应画布', exact: true }).click()
  await page.locator('.workflow-node').first().click()
  await expect(page.getByLabel('名称', { exact: true })).toBeVisible()
  expect(await page.locator('body').evaluate(el => el.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: `${evidence}/github-white-mobile-selected.png`, fullPage: true })
  await page.getByRole('button', { name: '关闭节点详情', exact: true }).click()
  await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
  await page.screenshot({ path: `${evidence}/github-white-mobile-canvas.png`, fullPage: true })
})


test('导航键盘闭环、搜索画布外节点与高级设置保持可达且不造成布局修改', async ({ page }) => {
  const data = await canvasReviewFixture(page)
  data.flow.layout.positions.review = { x: 8000, y: 6000 }
  await page.goto('/workflows/canvas-review')
    await expect(page.locator('[data-canvas-runtime="react"][data-canvas-kind="workflow"] .react-flow')).toBeVisible()
  const navigation = page.getByRole('button', { name: '展开导航', exact: true })
  await navigation.focus(); await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '应用导航' })
  await expect(dialog.getByRole('link', { name: 'OpenCode Loopper 首页' })).toBeFocused()
  await expect(page.locator('.app-main')).toHaveAttribute('inert', '')
  const last = dialog.getByRole('link').last()
  await last.focus(); await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: '收起导航' })).toBeFocused()
  await page.keyboard.press('Shift+Tab'); await expect(last).toBeFocused()
  await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0)
  await expect(navigation).toBeFocused()
  await page.getByRole('button', { name: '更多工具', exact: true }).click()
  await page.getByRole('button', { name: '节点列表', exact: true }).click()
  await page.getByLabel('搜索节点', { exact: true }).fill('检查交付')
  await page.getByRole('region', { name: '节点列表', exact: true }).getByRole('button', { name: '检查交付', exact: true }).click()
  const node = page.locator('.workflow-node.selected')
  await expect(node).toBeInViewport()
  await expect(node).toBeFocused()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('检查交付')
  await expect(page.locator('.workflow-save-state')).not.toHaveText('未保存')
  await page.locator('.workflow-node-advanced summary').click()
  await expect(page.getByLabel('执行后暂停检查', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
  expect(data.mutations).toEqual([])
  expect(data.errors).toEqual([])
})


test('不展开需求与资料也会使用配置的默认模型，且不预读模型目录', async ({ page }) => {
  const data = await canvasReviewFixture(page)
  data.req.state = 'PENDING_START'; data.snapshot.execution.state = 'PENDING_START'
  const starts: Array<{ model: unknown }> = [], catalogReads: string[] = []
  page.on('request', request => { if (new URL(request.url()).pathname === '/api/settings/models') catalogReads.push(request.url()) })
  await page.route('**/api/workflows/requirements/req/control/start', async route => {
    const body = route.request().postDataJSON(); starts.push(body)
    data.snapshot.control = { ...data.snapshot.control, configured: true, model: body.model }
    await route.fulfill({ json: data.snapshot.control })
  })
  await page.goto('/requirements/req')
    await expect(page.locator('[data-canvas-runtime="react"][data-canvas-kind="workflow"] .react-flow')).toBeVisible()
  await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
  await page.getByRole('button', { name: '连续执行', exact: true }).click()
  await expect.poll(() => starts.length).toBe(1)
  expect(starts[0]!.model).toEqual({ providerId: 'preview-provider', modelId: 'simulated-model', thinking: null })
  await expect(page.locator('.workflow-context-panel')).toHaveCount(0)
  expect(catalogReads).toEqual([])
  expect(data.errors).toEqual([])
})
