import { expect, test, type Page } from '@playwright/test'
import { canvasReviewFixture } from './fixtures/canvasReview'

const canvasSelector = '[data-canvas-runtime="react"][data-canvas-kind="workflow"]'
async function pair(page: Page, from: string, to: string, reverse = false) {
  const canvas = page.locator(canvasSelector)
  await canvas.locator(`[data-node-id="${from}"]`).click()
  const source = canvas.locator(`.react-flow__handle.${reverse ? 'target' : 'source'}[data-nodeid="${from}"]`)
  const target = canvas.locator(`.react-flow__handle.${reverse ? 'source' : 'target'}[data-nodeid="${to}"]`)
  const start = (await source.boundingBox())!, end = (await target.boundingBox())!
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await expect(canvas).toHaveAttribute('data-pointer-gesture', 'connect')
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 5 })
  await page.mouse.up()
  await expect(canvas).not.toHaveAttribute('data-pointer-gesture', 'connect')
}

test('应用指针连线继续由原业务所有者拒绝重复、循环与自身连接（模拟数据）', async ({ page }) => {
  const fixture = await canvasReviewFixture(page)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/workflows/canvas-review')
  const canvas = page.locator(canvasSelector)
  await pair(page, 'scope', 'design')
  await expect(page.getByRole('alert')).toContainText('已经连接')
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  await pair(page, 'review', 'scope')
  await expect(page.getByRole('alert')).toContainText('循环')
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  await pair(page, 'scope', 'scope')
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  // The unchanged editor renders history controls only after an accepted edit.
  await expect(page.getByRole('button', { name: '撤销修改', exact: true })).toHaveCount(0)
  expect(fixture.mutations).toEqual([])
  expect(fixture.errors).toEqual([])
})

test('反向端口指针连接只生成一次原方向意图与撤销记录，键盘连接继续可达（模拟数据）', async ({ page }) => {
  const fixture = await canvasReviewFixture(page)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/workflows/canvas-review')
  const canvas = page.locator(canvasSelector)
  // Pull from the receiving handle toward the source; the DTO remains source → target.
  await pair(page, 'review', 'scope', true)
  await expect(canvas.locator('.workflow-wire')).toHaveCount(3)
  await page.getByRole('button', { name: '撤销修改', exact: true }).click()
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '撤销修改', exact: true })).toBeDisabled()
  await canvas.locator('[data-node-id="scope"]').focus()
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: '从确认需求连接后续节点', exact: true }).focus()
  await page.keyboard.press('Enter')
  await canvas.locator('[data-node-id="review"]').focus()
  await page.keyboard.press('Enter')
  await expect(canvas.locator('.workflow-wire')).toHaveCount(3)
  await page.getByRole('button', { name: '撤销修改', exact: true }).click()
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '撤销修改', exact: true })).toBeDisabled()
  expect(fixture.mutations).toEqual([])
  expect(fixture.errors).toEqual([])
})

test('执行需求允许显示位置拖动但不能通过端口或键盘编辑业务图（模拟数据）', async ({ page }) => {
  const fixture = await canvasReviewFixture(page, true)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/requirements/req')
  const canvas = page.locator(canvasSelector), node = canvas.locator('[data-node-id="scope"]')
  await expect(node).toBeVisible()
  const before = (await node.boundingBox())!
  await page.mouse.move(before.x + 40, before.y + 25); await page.mouse.down()
  await expect(canvas).toHaveAttribute('data-pointer-gesture', 'drag')
  await page.mouse.move(before.x + 145, before.y + 45); await page.mouse.up()
  await expect.poll(async () => (await node.boundingBox())!.x - before.x).toBeCloseTo(105, 0)
  await expect.poll(async () => (await node.boundingBox())!.y - before.y).toBeCloseTo(20, 0)
  await node.focus(); await page.keyboard.press('Delete')
  await expect(canvas.locator('.workflow-port')).toHaveCount(0)
  await expect(canvas.locator('.workflow-node')).toHaveCount(3)
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  expect(fixture.mutations).toEqual([])
  expect(fixture.errors).toEqual([])
})

for (const reverse of [false, true]) {
  test(`${reverse ? '反向' : '正向'}端口两次真实点按保持原方向且只提交一次意图（模拟数据）`, async ({ page }) => {
    const fixture = await canvasReviewFixture(page)
    await page.setViewportSize({ width: 1600, height: 1000 })
    await page.goto('/workflows/canvas-review')
    const canvas = page.locator(canvasSelector)
    await canvas.locator(`[data-node-id="${reverse ? 'review' : 'scope'}"]`).click()
    await canvas.locator(`.react-flow__handle.${reverse ? 'target' : 'source'}[data-nodeid="${reverse ? 'review' : 'scope'}"]`).click()
    await expect(canvas).toHaveClass(/workflow-connection-dragging/)
    await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
    await canvas.locator(`.react-flow__handle.${reverse ? 'source' : 'target'}[data-nodeid="${reverse ? 'scope' : 'review'}"]`).click()
    await expect(canvas.locator('.workflow-wire')).toHaveCount(3)
    await expect(canvas).not.toHaveClass(/workflow-connection-dragging/)
    await page.getByRole('button', { name: '撤销修改', exact: true }).click()
    await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
    await expect(page.getByRole('button', { name: '撤销修改', exact: true })).toBeDisabled()
    expect(fixture.mutations).toEqual([])
    expect(fixture.errors).toEqual([])
  })
}

test('端口点按与原加号连接模式互斥，不保留第二个连接意图（模拟数据）', async ({ page }) => {
  const fixture = await canvasReviewFixture(page)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/workflows/canvas-review')
  const canvas = page.locator(canvasSelector)
  await canvas.locator('[data-node-id="review"]').click()
  await canvas.locator('.react-flow__handle.target[data-nodeid="review"]').click()
  await canvas.locator('[data-node-id="scope"]').click()
  await page.getByRole('button', { name: '从确认需求连接后续节点', exact: true }).click()
  await canvas.locator('.react-flow__handle.target[data-nodeid="review"]').click()
  await expect(canvas.locator('.workflow-wire')).toHaveCount(3)
  await page.getByRole('button', { name: '撤销修改', exact: true }).click()
  await expect(canvas.locator('.workflow-wire')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '撤销修改', exact: true })).toBeDisabled()
  expect(fixture.mutations).toEqual([])
  expect(fixture.errors).toEqual([])
})
