import {describe,expect,it,vi} from 'vitest'
import {api} from '@/api/client'
import {archiveFixture} from '@/pages/w6-tests/ordinary/archive'
import {action,body,flushPromises,fireEvent,act,screen} from '@/pages/w6-tests/ordinary/actions'
import {decodeHistoricalWorkspace,validateHistoricalExport} from '@/pages/w3/templates/catalog/history'
import {historicalWorkspace,historicalRule} from '@/pages/w3/templates/catalog/fixtures'
// W0 approved compatibility destination: historical GET/read/export only. The ten old writes remain retired.
describe('AutomationsView expected public API contract',()=>{
 it('renders loading before the server responds',async()=>{const f=archiveFixture();f.reads.workspace.mockReturnValue(new Promise(()=>{}));expect(f.reads.workspace).not.toHaveBeenCalled();void f.owner.open();await flushPromises();expect(f.view.text()).toContain('历史模板与自动化记录');expect(f.owner.getSnapshot().loading).toBe(true);expect(f.reads.workspace).toHaveBeenCalledOnce()})
 it('reads the create mutation wrapper and only offers manual triggering for MANUAL rules',async()=>{const create=vi.spyOn(api,'createAutomationRule'),trigger=vi.spyOn(api,'triggerAutomationRule'),f=archiveFixture();f.current.workspace=decodeHistoricalWorkspace({...historicalWorkspace,rules:[{...historicalRule,id:'r-manual',name:'手工检查',triggerType:'MANUAL',state:'DISABLED',approvalMode:'REVIEW_REQUIRED',triggerConfig:{},webhookToken:'once-secret'}, {...historicalRule,id:'r-cron',name:'定时检查',triggerType:'CRON',triggerConfig:{expression:'0 2 * * *',timezone:'Asia/Shanghai'}}]});await f.open();expect(f.view.text()).toContain('手动');expect(f.view.text()).toContain('定时');expect(f.view.text()).toContain('需要审批');expect(f.view.text()).not.toContain('once-secret');expect(f.view.findAll('button').filter(b=>/立即触发|创建规则/.test(b.text()))).toHaveLength(0);expect(create).not.toHaveBeenCalled();expect(trigger).not.toHaveBeenCalled();expect(f.current.workspace.rules[0]!.triggerType).toBe('MANUAL')})
 it('explicitly updates rules, gates AUTO_START by version approval, and confirms review runs',async()=>{const update=vi.spyOn(api,'updateAutomationRule'),confirm=vi.spyOn(api,'confirmAutomationRun'),f=archiveFixture();f.current.workspace=decodeHistoricalWorkspace({...historicalWorkspace,rules:[{...historicalRule,approvalMode:'AUTO_START',state:'ENABLED'},{...historicalRule,id:'manual',approvalMode:'REVIEW_REQUIRED'}]});await f.open();expect(f.view.text()).toContain('自动开始');expect(f.view.text()).toContain('需要审批');act(()=>fireEvent.click(screen.getByRole('tab',{name:'历史模板'})));await flushPromises();await action('ui.open');expect(f.view.get('[aria-label="冻结模板版本"]').text()).toContain('原自动开始未批准');act(()=>fireEvent.click(screen.getByRole('tab',{name:'运行记录'})));await flushPromises();expect(f.view.text()).toContain('等待审批');expect(f.view.text()).not.toContain('REVIEW_REQUIRED');expect(update).not.toHaveBeenCalled();expect(confirm).not.toHaveBeenCalled()})
 it('previews before import, reveals imported webhook tokens once, and exports persisted configuration',async()=>{const preview=vi.spyOn(api,'previewLoopSpecTemplateImport'),confirm=vi.spyOn(api,'confirmLoopSpecTemplateImport'),f=archiveFixture();vi.stubGlobal('URL',class extends URL{static createObjectURL=vi.fn(()=>'blob:archive');static revokeObjectURL=vi.fn()});const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});await f.open();expect(f.view.text()).toContain('原写入接口已退役');expect(f.view.find('textarea[aria-label="导入配置"]').exists()).toBe(false);expect(f.view.text()).not.toContain('imported-once-secret');expect(preview).not.toHaveBeenCalled();expect(confirm).not.toHaveBeenCalled();act(()=>fireEvent.click(screen.getByRole('tab',{name:'导出说明'})));await flushPromises();await action('automation.exportWorkspace');expect(f.reads.workspaceExport).toHaveBeenCalledOnce();expect(click).toHaveBeenCalledOnce();expect(validateHistoricalExport('{"formatVersion":1,"templates":[],"rules":[]}', 'workspace')).toBe('{"formatVersion":1,"templates":[],"rules":[]}');expect(()=>validateHistoricalExport('{"formatVersion":1,"templates":[],"rules":[{"secret":"imported-once-secret"}]}','workspace')).toThrow('密钥');f.owner.close();await flushPromises();expect(body().find('.ui-context-panel').isVisible()).toBe(false)})
})
