import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {flushPromises} from '@/pages/w6-tests/knowledge-ppt-template/react-test-root'
import {designerPage} from '@/pages/w6-tests/knowledge-ppt-template/designer-page'
import {project,session,settings,draftFrom,completedRouterRun} from '@/pages/w6-tests/knowledge-ppt-template/designer-fixtures'
import {api,ApiError} from '@/api/client'
import {mockDesigner,deferred} from '@/pages/w5/designer/test-support'
import {createDesignerController} from '@/pages/w5/designer/controller'
import {blankSpec,messageKey,promptKey,workspaceKey,timeline} from '@/pages/w5/designer/model'
import {pageProps} from '@/pages/w3/ppt/testFixture'
import type {DesignerSession,DesignerMessage,LoopSpec,Task,DesignWorkPackageStatus,DesignerActivity,DesignerStreamEvent,DesignerAcceptancePlanningStatus} from '@/types/domain'
vi.mock('@/api/client',async original=>({...await original<typeof import('@/api/client')>(),subscribeDesignerEvents:vi.fn()}))
function spec(goal='原版本'):LoopSpec{return {...blankSpec(project.id,goal,settings),stages:[{workPackageId:'WP-1',objective:'实现功能',implementationKind:'JAVA_PRODUCTION',allowedPaths:['src/**'],forbiddenPaths:['data/**'],deliverables:['实现'],acceptanceCriteria:[{id:'WP-1-AC-1',description:'业务行为通过聚焦测试验证'}],verifiers:[{type:'PROCESS',command:['mvn','test','-Dtest=FeatureTest'],processPurpose:'TEST',testTargets:['FeatureTest'],criterionIds:['WP-1-AC-1']}]}]}}
function value(overrides:Partial<DesignerSession>={}):DesignerSession{return {...session,state:'REVIEWING',workflowPhase:'DISCUSSING_REQUIREMENT',discussionScope:'REQUIREMENT',finalConfirmationEligible:false,draft:draftFrom(spec()),availableProfileOverrides:['SOFTWARE_CHANGE','DOCUMENT_AUTHORING','READ_ONLY_REVIEW'],availableArtifactOverrides:['SOURCE_CODE','PYTHON_SCRIPT','DOCX','MARKDOWN'],taskProfile:{...session.taskProfile,state:'PROVISIONAL',decisionState:'CONFIRMED',confirmationReady:true,largeTaskMode:false,version:3},...overrides}}
function pkg(overrides:Partial<DesignWorkPackageStatus>={}):DesignWorkPackageStatus{return {id:'WP-1',ordinal:0,title:'默认单包设计',objective:'完整需求',dependencies:[],state:'APPROVED',redesignCount:0,compilerRepairCount:0,compilerPlanningRepairCount:0,designRevision:2,approvedDesignRevision:2,discussionRoundCount:0,...overrides}}
function message(id:string,actor:DesignerMessage['actor'],content:string,extra:Partial<DesignerMessage>={}):DesignerMessage{return {id,role:actor==='USER'?'USER':actor==='SYSTEM'||actor==='VALIDATOR'?'SYSTEM':'ASSISTANT',actor,content,deliveryState:'PERSISTED',createdAt:'2026-08-19T08:00:00Z',...extra}}
const streamEvent=(partial:Partial<DesignerStreamEvent>):DesignerStreamEvent=>({sequence:1,sessionId:session.id,type:'STATUS',state:'RUNNING',workflowPhase:'DESIGNING',activeActor:'DESIGNER',runtimeConnected:false,content:'',detail:'',at:'now',modelCallsUsed:0,maxModelCalls:32,...partial})
const planning=(overrides:Partial<DesignerAcceptancePlanningStatus>={}):DesignerAcceptancePlanningStatus=>({state:'COMPILED',bindingSource:'SERVER_STAGE_HINTS',routingReasons:[],factCount:0,scenarioCount:0,automatedCount:0,bothCount:0,judgeCount:0,unresolvedCount:0,mutationObligationCount:0,resolvedMutationObligationCount:0,unresolvedMutationObligationCount:0,pathConservation:'CONSERVED',mutationBindingReasons:[],scenarios:[],issues:[],...overrides})
const activity:DesignerActivity={actor:'DESIGNER',connected:true,remoteState:'RUNNING',observedAt:'now',detail:'处理中',parts:[{id:'thought',type:'THINKING',label:'思考',content:'正在分析项目'}],usage:{totalTokens:15,unknownUsageCount:0,observedAt:'now'}}
function question(id='question',scope='REQUIREMENT',revision=1,designMessageId?:string){return {id,scope,discussionRevision:revision,designMessageId,answeredAt:'2026-08-19T08:00:00Z',questions:[{question:'选择缓存刷新范围',header:'范围',multiple:false,custom:false,options:[{label:'完整刷新',description:'覆盖全部缓存条目'}],answers:['完整刷新']}]}}
async function show(next=value()) {const streams=mockDesigner(next);vi.mocked(api.getSettings).mockResolvedValue(settings);vi.mocked(api.getProjects).mockResolvedValue([project]);vi.spyOn(api,'getDesignerActivity').mockResolvedValue(activity);vi.mocked(api.getDraft).mockResolvedValue(next.draft!);const c=await designerPage(next);return {...c,...streams}}
async function initial(next=value()){const streams=mockDesigner(next);vi.mocked(api.getProjects).mockResolvedValue([project]);vi.mocked(api.getSettings).mockResolvedValue(settings);let draft=next.draft!;vi.mocked(api.createDraft).mockImplementation(async source=>{draft=draftFrom(source);return draft});vi.mocked(api.createDesignerSession).mockImplementation(async()=>({...next,draft}));vi.mocked(api.createDesignerContextTurn).mockImplementation(async()=>({...next,draft}));const c=await designerPage(undefined,false);return {...c,...streams}}
async function goal(c:Awaited<ReturnType<typeof initial>>,text='创建可靠的执行计划'){await c.view.get('textarea[aria-label="草案设计目标"]').setValue(text);await c.button('designer.start');return c}
async function openSpec(c:Awaited<ReturnType<typeof show>>){await c.button('ui.open','最终执行规范')}
async function confirmed(c:Awaited<ReturnType<typeof show>>){await c.button('designer.confirm');await c.confirm('designer.confirm')}
const finalSession=(overrides:Partial<DesignerSession>={})=>value({workflowPhase:'FINAL_REVIEW',discussionScope:'FINAL',finalConfirmationEligible:true,...overrides})
const failedTask=(id='task-1',status:Task['status']='FAILED'):Task=>({id,projectId:project.id,projectName:project.name,title:'交接到任务控制台',goal:'交接到任务控制台',branch:'',worktreePath:'',status,attemptCount:0,maxAttempts:12,createdAt:'now',updatedAt:'now',errors:[{id:'error-1',layer:'TASK',code:'GIT_HEAD_UNAVAILABLE',message:"Cannot resolve the project's Git HEAD",retryable:false,occurredAt:'now'}]})
function taskTransport(c:Awaited<ReturnType<typeof show>>,task=failedTask()){vi.spyOn(api,'confirmDraft').mockResolvedValue({taskId:task.id});vi.mocked(api.getDraft).mockResolvedValue({...c.owner.getSnapshot().draft!,status:'CONFIRMED'});vi.spyOn(api,'getTaskOverview').mockResolvedValue(task);vi.spyOn(api,'getTaskAudit').mockResolvedValue({errors:task.errors??[],judges:[],artifacts:[],attempts:[]});return task}
beforeEach(()=>{vi.restoreAllMocks();sessionStorage.clear()})
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();sessionStorage.clear()})
describe('Designer draft composer',()=>{
  it("shows a reopened design generation while preserving its stage after refresh",async()=>{
    const next=value({workflowPhase:'REVIEWING_PACKAGE',designConversations:[{id:'c1',scopeKey:'wp-row',generation:1,state:'RETIRED',reason:'PACKAGE_APPROVED',externalSessionId:'remote-1'},{id:'c2',scopeKey:'wp-row',generation:2,state:'OPEN',reason:null,externalSessionId:'remote-2'}]});const c=await show(next);expect(c.view.text()).toContain('第 2 代');expect(c.view.text()).toContain('工作包待确认');c.close();const refreshed=await show(next);expect(refreshed.view.text()).toContain('第 2 代');expect(refreshed.owner.getSnapshot().session?.workflowPhase).toBe('REVIEWING_PACKAGE')
  })
  it("refreshes accounting failures while idle and warns once across replay and remount",async()=>{
    vi.useFakeTimers();const idle=value({storyBinding:{enabled:true,systemCode:'SYS-001',storyCode:'000123'}});const c=await show(idle);const notice=message('story-failed-once','SYSTEM','AI 工作量统计失败：请求超时（30 秒），任务继续执行。',{deliveryState:'STORY_BINDING_FAILED'});vi.mocked(api.getDesignerSession).mockResolvedValue({...idle,messages:[notice]});c.streams[0]!.event(streamEvent({sequence:1,sessionId:idle.id,type:'STORY_BINDING_FAILED',state:'RUNNING',workflowPhase:'DESIGNING',activeActor:'SYSTEM',runtimeConnected:false,at:'later'}));await flushPromises();expect(api.getDesignerSession).toHaveBeenCalledTimes(2);expect(c.view.text()).toContain('SYS-001 / 000123');expect(c.view.findAll('p').filter(p=>p.text().includes('AI 工作量统计失败'))).toHaveLength(1);c.streams[0]!.event(streamEvent({sequence:1,sessionId:idle.id,type:'STORY_BINDING_FAILED',at:'later'}));await flushPromises();expect(c.owner.getSnapshot().session?.messages.filter(m=>m.id===notice.id)).toHaveLength(1);c.close();const replay=await show({...idle,messages:[notice]});expect(replay.view.findAll('p').filter(p=>p.text().includes('AI 工作量统计失败'))).toHaveLength(1)
  })
  it("keeps polling a reviewing session until profile rerouting finishes and then enables single-package design",async()=>{
    vi.useFakeTimers();const routing=value({taskProfile:{...value().taskProfile,decisionState:'ROUTING',confirmationReady:false,resolutionSource:'ROUTER'},routerRun:{...completedRouterRun(),state:'RUNNING'}});const c=await show(routing);expect(c.owner.getSnapshot().routerOpen).toBe(true);expect(c.body().get('[role="dialog"] button[data-semantic="designer.confirmProfile"]').element.matches(':disabled')).toBe(true);vi.mocked(api.getDesignerSession).mockResolvedValue({...routing,taskProfile:{...routing.taskProfile,decisionState:'CONFIRMED',confirmationReady:true,workflowTemplate:'DIRECT_SOFTWARE_DESIGN',resolutionSource:'USER_CONFIRMED_CARRIED_FORWARD'}});await vi.advanceTimersByTimeAsync(1200);await flushPromises();expect(api.getDesignerSession).toHaveBeenCalledTimes(2);expect(c.owner.getSnapshot().session?.taskProfile.confirmationReady).toBe(true);expect(c.view.get('button[data-semantic="designer.confirmRequirement"]').element.matches(':disabled')).toBe(false)
  })
  it("invalidates an in-flight poll when the Designer view unmounts",async()=>{
    vi.useFakeTimers();const c=await show(value({state:'RUNNING',workflowPhase:'DESIGNING'}));const pending=deferred<DesignerSession>();vi.mocked(api.getDesignerSession).mockReturnValueOnce(pending.promise);await vi.advanceTimersByTimeAsync(1200);expect(api.getDesignerSession).toHaveBeenCalledTimes(2);c.close();pending.reject(new Error('view already unmounted'));await flushPromises();await vi.advanceTimersByTimeAsync(12000);expect(api.getDesignerSession).toHaveBeenCalledTimes(2);expect(c.owner.base.capture().isCurrent()).toBe(false);expect(c.streams[0]!.close).toHaveBeenCalledTimes(1)
  })
  it("cancels the active Router through the server and refreshes into manual selection",async()=>{
    const routing=value({state:'PENDING_HANDOFF',workflowPhase:'ROUTING',taskProfile:{...value().taskProfile,decisionState:'ROUTING',confirmationReady:false},routerRun:{...completedRouterRun(),state:'RUNNING'}});const c=await show(routing);const cancelled={...routing,routerRun:{...routing.routerRun!,state:'SUPERSEDED' as const,errorCode:'ROUTER_USER_CANCELLED'},taskProfile:{...routing.taskProfile,decisionState:'NEEDS_CONFIRMATION' as const,resolutionSource:'USER_SELECTION_PENDING'}};vi.spyOn(api,'cancelDesignerTaskProfileRouting').mockResolvedValue(cancelled.taskProfile);vi.mocked(api.getDesignerSession).mockResolvedValue(cancelled);await c.button('designer.cancelRouter');expect(api.cancelDesignerTaskProfileRouting).toHaveBeenCalledWith(routing.id,routing.routerRun!.id);expect(c.body().text()).toContain('已取消 AI 识别，请手动选择任务设置');await c.body().get('[role="dialog"] button[data-semantic="designer.editSettings"]').trigger('click');expect(c.body().get('select[aria-label="任务类型"]').element.matches(':disabled')).toBe(false);expect(c.owner.getSnapshot().command.phase).toBe('SETTLED')
  })
  it("shows changed profile choices and confirms the new recommendation explicitly",async()=>{
    const next=value({taskProfile:{...value().taskProfile,decisionState:'NEEDS_CONFIRMATION',confirmationReady:false,intent:'DOCUMENT_AUTHORING',artifactKinds:['MARKDOWN'],workflowTemplate:'DIRECT_ARTIFACT',version:7,previousConfirmedChoice:{intent:'SOFTWARE_CHANGE',primaryArtifactKind:'SOURCE_CODE',workflowTemplate:'DIRECT_SOFTWARE_DESIGN',mutationMode:'WRITE_CODE',largeTaskMode:false,resolutionSource:'USER_CONFIRMED'}},routerRun:completedRouterRun()});const c=await show(next);expect(c.body().text()).toContain('原设置：软件变更');expect(c.body().text()).toContain('本次识别结果：文档编写');const confirm=vi.spyOn(api,'confirmDesignerTaskProfile').mockResolvedValue(next.taskProfile),preview=vi.spyOn(api,'previewDesignerTaskProfileUpdate');await c.confirm('designer.confirmProfile');expect(confirm).toHaveBeenCalledWith(next.id,7);expect(preview).not.toHaveBeenCalled()
  })
  it("refreshes an authoritative profile conflict without showing a red error",async()=>{
    const c=await show();c.owner.editProfile();vi.spyOn(api,'previewDesignerTaskProfileUpdate').mockResolvedValue({selectionChanged:true,updateRequired:true,sessionRestartRequired:true,targetWorkflowTemplate:'DIRECT_SOFTWARE_DESIGN'});vi.spyOn(api,'updateDesignerTaskProfile').mockRejectedValue(new ApiError('任务设置已变化',409,{code:'TASK_PROFILE_VERSION_CONFLICT'}));const proposal=await c.owner.previewProfile();expect(proposal).toBeDefined();await c.owner.applyProfile(proposal!);await flushPromises();expect(api.getDesignerSession).toHaveBeenCalledTimes(2);expect(c.owner.getSnapshot().notice).toContain('已刷新最新结果');expect(c.owner.getSnapshot().error).toBe('');expect(c.owner.getSnapshot().command.phase).toBe('SETTLED')
  })
  it("shows task profile summaries and override options in Chinese while preserving enum values",async()=>{
    const next=value({taskProfile:{...value().taskProfile,decisionState:'NEEDS_CONFIRMATION',confirmationReady:false,confidence:90,confidenceAvailable:true,resolutionSource:'AI_ROUTER'},routerRun:completedRouterRun()});const c=await show(next);expect(c.body().text()).toContain('90%');expect(c.body().text()).toContain('技术栈java');expect(c.body().text()).not.toContain('SOFTWARE_CHANGE');await c.body().get('[role="dialog"] button[data-semantic="designer.editSettings"]').trigger('click');expect(c.body().get('select[aria-label="任务类型"]').findAll('option').map(o=>o.attributes('value'))).toEqual(next.availableProfileOverrides);expect(c.body().get('select[aria-label="交付物类型"]').text()).toContain('Python')
  })
  it("asks for a component only when a multi-stack software task is ambiguous",async()=>{
    const next=value({taskProfile:{...value().taskProfile,componentSelectionRequired:true,componentKeys:[],candidateComponents:[{key:'backend',relativeRoot:'.',technologyFamilies:['java'],technologies:['java'],buildTools:['maven'],testFrameworks:['junit'],manifestSources:['pom.xml']},{key:'frontend',relativeRoot:'frontend',technologyFamilies:['node'],technologies:['node'],buildTools:['npm'],testFrameworks:['vitest'],manifestSources:['frontend/package.json']}]}});const c=await show(next);await c.button('designer.editSettings');await c.body().get('[data-foundation-component="context"] button[data-semantic="designer.editSettings"]').trigger('click');const option=c.body().findAll('label').find(label=>label.text().includes('frontend · node'))!;await option.get('input').setValue(true);vi.spyOn(api,'previewDesignerTaskProfileUpdate').mockResolvedValue({selectionChanged:true,updateRequired:true,sessionRestartRequired:false,targetWorkflowTemplate:'DIRECT_SOFTWARE_DESIGN'});vi.spyOn(api,'updateDesignerTaskProfile').mockResolvedValue(next.taskProfile);await c.button('designer.save');expect(api.updateDesignerTaskProfile).toHaveBeenCalledWith(next.id,'SOFTWARE_CHANGE','SOURCE_CODE',3,false,['frontend'])
  })
  it("defaults software design to one package and only enables decomposition through the explicit switch",async()=>{
    const next=value({taskProfile:{...value().taskProfile,workflowTemplate:'DIRECT_SOFTWARE_DESIGN',largeTaskMode:false,version:4}});const c=await show(next);expect(c.view.find('input[aria-label="大型任务模式"]').exists()).toBe(false);await c.button('designer.editSettings');await c.body().get('[data-foundation-component="context"] button[data-semantic="designer.editSettings"]').trigger('click');expect((c.body().get<HTMLInputElement>('[aria-label="大型任务模式"]').element).checked).toBe(false);await c.body().get('[aria-label="大型任务模式"]').setValue(true);vi.spyOn(api,'previewDesignerTaskProfileUpdate').mockResolvedValue({selectionChanged:true,updateRequired:true,sessionRestartRequired:true,targetWorkflowTemplate:'FULL_PACKAGE_DESIGN'});vi.spyOn(api,'updateDesignerTaskProfile').mockResolvedValue({...next.taskProfile,largeTaskMode:true});await c.button('designer.save');expect(api.updateDesignerTaskProfile).not.toHaveBeenCalled();expect(c.body().get('[role="dialog"]').text()).toContain('重建');await c.confirm('designer.save');expect(api.updateDesignerTaskProfile).toHaveBeenCalledWith(next.id,'SOFTWARE_CHANGE','SOURCE_CODE',4,true,[])
  })
  it("renders the authoritative requirement snapshot separately and excludes its audit message from system history",async()=>{
    const markdown='# 需求快照\n\n原始需求保持原样';const c=await show(value({requirementSnapshot:{discussionRevision:2,source:'SERVER_ASSEMBLED',markdown,updatedAt:'now'},messages:[message('snapshot-source','SYSTEM',markdown,{deliveryState:'SERVER_REQUIREMENT_SNAPSHOT'}),message('normal-system','SYSTEM','画像重算完成')]}));expect(c.view.get('[aria-label="整体需求"]').text()).toContain('R2');expect(c.view.get('[aria-label="整体需求"]').text()).toContain('服务端整理');expect(c.view.get('[aria-label="整体需求"]').text()).toContain('原始需求保持原样');const system=timeline(c.owner.getSnapshot().session!).find(entry=>entry.kind==='system');expect(system&&system.kind==='system'&&system.messages.map(m=>m.id)).toEqual(['normal-system']);expect(c.view.findAll('details').find(d=>d.get('summary').text().includes('系统记录'))!.text()).not.toContain('原始需求保持原样')
  })
  it("labels a historical AI requirement snapshot without presenting it as a server assembly",async()=>{
    const c=await show(value({requirementSnapshot:{discussionRevision:1,source:'AI_ASSEMBLED',markdown:'# 历史需求稿',updatedAt:'now'}}));expect(c.view.get('[aria-label="整体需求"]').text()).toContain('历史 AI 整理');expect(c.view.get('[aria-label="整体需求"]').text()).not.toContain('服务端整理')
  })
  it("hides the package approval rail in direct mode and exposes only the explicit large-task recovery",async()=>{
    const next=value({state:'WAITING_INPUT',workflowPhase:'FAILED',discussionScope:'WP-1',discussionRevision:3,taskProfile:{...value().taskProfile,workflowTemplate:'DIRECT_SOFTWARE_DESIGN',version:2},workPackages:[pkg({state:'WAITING_INPUT',lastErrorCode:'LARGE_TASK_MODE_REQUIRED'})],messages:[message('overflow','VALIDATOR','LARGE_TASK_MODE_REQUIRED：无法容纳在 1–6 个 Stage 中',{deliveryState:'TERMINAL_ERROR'})]});const c=await show(next);expect(c.view.find('[aria-label="工作包设计轨道"]').exists()).toBe(false);expect(c.view.text()).toContain('大型任务');vi.spyOn(api,'enableDesignerLargeTaskMode').mockResolvedValue({...next.taskProfile,largeTaskMode:true});await c.button('designer.largeTask');await c.confirm('designer.largeTask');expect(api.enableDesignerLargeTaskMode).toHaveBeenCalledWith(next.id,3,2)
  })
  it("shows server-owned MCP candidate facts without restoring the package rail in direct mode",async()=>{
    const c=await show(finalSession({taskProfile:{...value().taskProfile,workflowTemplate:'DIRECT_SOFTWARE_DESIGN'},workPackages:[pkg({candidateRunState:'ACCEPTED',candidateSessions:1,candidateSubmissions:2,compilationSource:'MCP_ACCEPTED',serverCompiled:true})]}));expect(c.view.find('[aria-label="工作包设计轨道"]').exists()).toBe(false);const facts=c.view.get('[aria-label="单工作包候选状态"]');expect(facts.text()).toContain('候选状态：已接受');expect(facts.text()).toContain('MCP 候选已接受');expect(facts.text()).toContain('服务端已编译');expect(facts.text()).toContain('候选会话 1');expect(facts.text()).toContain('候选提交 2')
  })
  it("shows the persisted Markdown fallback reason in the direct-mode candidate summary",async()=>{
    const c=await show(value({taskProfile:{...value().taskProfile,workflowTemplate:'DIRECT_SOFTWARE_DESIGN'},workPackages:[pkg({candidateRunState:'CLOSED',candidateSessions:1,candidateSubmissions:0,compilationSource:'MARKDOWN_FALLBACK',fallbackReason:'MODEL_COMPLETED_WITHOUT_SUBMISSION',serverCompiled:false})]}));const facts=c.view.get('[aria-label="单工作包候选状态"]');expect(facts.text()).toContain('候选状态：已关闭');expect(facts.text()).toContain('Markdown 兜底');expect(facts.text()).toContain('模型结束但未提交候选');expect(facts.text()).toContain('候选会话 1');expect(facts.text()).not.toContain('候选提交')
  })
  it("keeps the new-design page focused and restores a history session from an explicit route",async()=>{
    const c=await show(value({id:'designer-recover',state:'WAITING_INPUT',workflowPhase:'FAILED',draft:draftFrom(spec('恢复重启前的设计'))}));expect(sessionStorage.getItem(workspaceKey)).toContain('designer-recover');expect(c.view.find('[aria-label="待继续设计"]').exists()).toBe(false);expect(c.view.get('textarea[aria-label="设计消息"]').exists()).toBe(true);expect(c.p.props.route.query.sessionId).toBe('designer-recover')
  })
  it("keeps the recovery pointer when the backend is temporarily unavailable after restart",async()=>{
    sessionStorage.setItem(workspaceKey,JSON.stringify({sessionId:'designer-recover',draftId:'draft-1'}));mockDesigner(value({id:'designer-recover'}));vi.mocked(api.getDesignerSession).mockRejectedValue(new Error('服务正在重启'));const p=pageProps(),owner=createDesignerController({sessionId:'designer-recover',historyOnly:true,navigation:p.props.navigation});const release=owner.attachView();await flushPromises();expect(owner.getSnapshot().error).toContain('服务正在重启');expect(sessionStorage.getItem(workspaceKey)).toContain('designer-recover');expect(owner.getSnapshot().session).toBeUndefined();release();owner.retire(true)
  })
  it("does not auto-open an archived design from a stale browser recovery pointer",async()=>{
    sessionStorage.setItem(workspaceKey,JSON.stringify({sessionId:'designer-archived',draftId:'draft-1'}));mockDesigner(value({id:'designer-archived',archived:true}));const p=pageProps(),owner=createDesignerController({historyOnly:true,navigation:p.props.navigation});const release=owner.attachView();await flushPromises();expect(api.getDesignerSession).not.toHaveBeenCalled();expect(owner.getSnapshot().session).toBeUndefined();expect(sessionStorage.getItem(workspaceKey)).toContain('designer-archived');release();owner.retire(true)
  })
  it("starts a structured brief from a quick template and persists it locally",async()=>{
    const c=await initial();const repair='当前现象：\n\n预期行为：\n\n验收方式：';c.owner.setPrompt(repair);await flushPromises();expect(c.view.get<HTMLTextAreaElement>('textarea[aria-label="草案设计目标"]').element.value).toContain('当前现象：');expect(c.owner.getSnapshot().prompt).toContain('验收方式：');expect(sessionStorage.getItem(promptKey)).toBe(repair);c.close();const historical=await designerPage(undefined,true);expect(historical.view.find('textarea[aria-label="草案设计目标"]').exists()).toBe(false);expect(historical.view.find('[data-semantic="designer.start"]').exists()).toBe(false)
  })
  it("asks before a quick template overwrites the current draft",async()=>{
    const c=await initial();await c.view.get('textarea[aria-label="草案设计目标"]').setValue('保留这段现有草稿');const policy=c.owner.canLeave();expect(policy.kind).toBe('CONFIRM_DISCARD');expect(policy.kind==='CONFIRM_DISCARD'&&policy.draftRevision).toBe(c.owner.getSnapshot().revision);const before=c.owner.getSnapshot().prompt;expect(before).toBe('保留这段现有草稿');expect(c.owner.getSnapshot().prompt).toBe(before);expect(sessionStorage.getItem(promptKey)).toBe(before);expect(api.createDesignerSession).not.toHaveBeenCalled()
  })
  it("restores the initial goal and submits it as both the session message and LoopSpec goal",async()=>{
    const text='Task 错误退出任务；Session 错误保留上下文并继续 loop。';let c=await initial();await c.view.get('textarea[aria-label="草案设计目标"]').setValue(text);expect(sessionStorage.getItem(promptKey)).toBe(text);c.close();c=await initial();expect(c.view.get<HTMLTextAreaElement>('textarea[aria-label="草案设计目标"]').element.value).toBe(text);await c.button('designer.start');expect(api.createDesignerSession).toHaveBeenCalledWith(project.id,'draft-1',text,false,{enabled:false});const request=vi.mocked(api.createDraft).mock.calls[0]![0];expect(request.goal).toBe(text);expect(request.schemaVersion).toBe('v2');expect(request.stages[0]).toMatchObject({allowedPaths:[],forbiddenPaths:[],verifiers:[]});expect(request.limits).toMatchObject({maxTaskAttempts:7,attemptTimeout:'PT45M'});expect(sessionStorage.getItem(promptKey)).toBeNull();expect(c.view.get('textarea[aria-label="设计消息"]').exists()).toBe(true)
  })
  it("replays an uncertain initial attachment submission with its original draft and retains later edits",async()=>{
    const c=await initial(),file=new File(['old bytes'],'original.txt');c.owner.stageFiles([file]);c.owner.setPrompt('旧目标');await flushPromises();vi.mocked(api.createDesignerContextTurn).mockRejectedValueOnce(new Error('connection lost'));await c.button('designer.start');expect(c.owner.getSnapshot().command.phase).toBe('UNKNOWN');const original=vi.mocked(api.createDesignerContextTurn).mock.calls[0]!;c.owner.setPrompt('后写目标');c.owner.stageFiles([new File(['later'],'later.txt')]);await flushPromises();const receipt=value({draft:c.owner.getSnapshot().draft});vi.mocked(api.createDesignerContextTurn).mockResolvedValue(receipt);await c.button('designer.start');const retry=vi.mocked(api.createDesignerContextTurn).mock.calls[1]!;expect(retry[0]).toEqual(original[0]);expect(retry[1][0]).toBe(file);expect(api.createDraft).toHaveBeenCalledTimes(1);expect(c.owner.getSnapshot().message).toBe('后写目标');expect(c.owner.getSnapshot().files.map(f=>f.name)).toEqual(['later.txt'])
  })
  it("allows correcting files rejected before the initial session was created",async()=>{
    const c=await initial();c.owner.setPrompt('目标');c.owner.stageFiles([new File(['bad'],'context.txt')]);await flushPromises();vi.mocked(api.createDesignerContextTurn).mockRejectedValueOnce(new ApiError('附件不受支持',400,{code:'ATTACHMENT_TYPE_UNSUPPORTED'}));await c.button('designer.start');expect(c.owner.getSnapshot().command.phase).toBe('SETTLED');const rejected=vi.mocked(api.createDesignerContextTurn).mock.calls[0]![0];const corrected=new File(['corrected'],'context.txt');c.owner.stageFiles([corrected]);await flushPromises();vi.mocked(api.createDesignerContextTurn).mockResolvedValue(value({draft:c.owner.getSnapshot().draft}));await c.button('designer.start');expect(vi.mocked(api.createDesignerContextTurn).mock.calls[1]![0].submissionId).not.toBe(rejected.submissionId);expect(vi.mocked(api.createDesignerContextTurn).mock.calls[1]![1]).toEqual([corrected]);expect(api.createDraft).toHaveBeenCalledTimes(1)
    c.close()
    for (const code of [undefined,'ATTACHMENT_SESSION_TOO_LARGE']) {
      const unsafe=await initial(), originalFile=new File(['original'],'原文件.txt');unsafe.owner.setPrompt('保留原目标');unsafe.owner.stageFiles([originalFile]);await flushPromises();vi.mocked(api.createDesignerContextTurn).mockRejectedValueOnce(new ApiError('不能证明原提交无副作用',400,{code}));await unsafe.button('designer.start');expect(unsafe.owner.getSnapshot().command.phase).toBe('UNKNOWN');expect(unsafe.owner.canLeave().kind).toBe('BLOCK');const originalRequest=vi.mocked(api.createDesignerContextTurn).mock.calls.at(-1)!;
      unsafe.owner.setPrompt('后来草稿');unsafe.owner.stageFiles([new File(['corrected'],'原文件.txt')]);await flushPromises();vi.mocked(api.createDesignerContextTurn).mockRejectedValueOnce(new Error('原交接仍未确认'));await unsafe.button('designer.start');const retry=vi.mocked(api.createDesignerContextTurn).mock.calls.at(-1)!;expect(retry[0]).toEqual(originalRequest[0]);expect(retry[1][0]).toBe(originalFile);expect(unsafe.owner.getSnapshot().command.phase).toBe('UNKNOWN');expect(unsafe.owner.getSnapshot().prompt).toBe('后来草稿');unsafe.close()
    }
  })
  it("shows staged files in a standalone context card and hides it after the last file is removed",async()=>{
    const c=await initial(),file=new File(['context'],'context.txt',{type:'text/plain'});await c.view.get('.designer-page').trigger('drop',{dataTransfer:{types:['Files'],files:[file]}});expect(c.view.get('[aria-label="待发送附件"]').text()).toContain('context.txt');expect(c.owner.getSnapshot().initialFiles[0]?.size).toBe(file.size);await c.button('ui.delete','context.txt');expect(c.view.find('[aria-label="待发送附件"]').exists()).toBe(false);expect(c.owner.getSnapshot().initialFiles).toEqual([])
  })
  it("requires risk confirmation before creating an auto-mode design",async()=>{
    const c=await initial();await c.view.get('input[aria-label="全自动创建"]').setValue(true);expect(c.owner.getSnapshot().autoMode).toBe(false);expect(c.body().get('[role="dialog"]').text()).toContain('人工');await c.confirm('designer.autoMode');expect(c.owner.getSnapshot().autoMode).toBe(true);await goal(c);expect(api.createDesignerSession).toHaveBeenCalledWith(project.id,'draft-1','创建可靠的执行计划',true,{enabled:false})
  })
  it("shows that auto mode will adopt a low-confidence task profile recommendation without manual override",async()=>{
    const next=value({taskProfile:{...value().taskProfile,decisionState:'NEEDS_CONFIRMATION',confirmationReady:false,confidence:0},autoMode:{enabled:true,state:'ACTIVE',version:1},routerRun:completedRouterRun()});const c=await show(next);expect(c.view.text()).toContain('全自动模式');expect(c.view.find('button[data-semantic="designer.confirmRequirement"]').exists()).toBe(false);expect(c.view.find('textarea[aria-label="设计消息"]').exists()).toBe(false);expect(c.owner.getSnapshot().session?.autoMode.enabled).toBe(true);expect(api.createDesignerSession).not.toHaveBeenCalled()
  })
  it("keeps auto mode off when the creation warning is cancelled",async()=>{
    const c=await initial();await c.view.get('input[aria-label="全自动创建"]').setValue(true);await c.confirm('ui.stay');expect(c.owner.getSnapshot().autoMode).toBe(false);await goal(c);expect(api.createDesignerSession).toHaveBeenCalledWith(project.id,'draft-1','创建可靠的执行计划',false,{enabled:false})
  })
  it("keeps an unsent follow-up after a request failure and clears it only after persistence succeeds",async()=>{
    const c=await show();await c.view.get('textarea[aria-label="设计消息"]').setValue('补充验收：前端测试和 Maven clean verify 必须通过。');vi.mocked(api.sendRequirementMessage).mockRejectedValueOnce(new ApiError('请求被拒绝，请重试',400));await c.button('designer.send');expect(c.owner.getSnapshot().message).toContain('Maven clean verify');expect(sessionStorage.getItem(messageKey)).toBe(c.owner.getSnapshot().message);vi.mocked(api.sendRequirementMessage).mockResolvedValueOnce({sessionId:session.id,state:'REVIEWING',persistedMessages:[],notice:'saved'});await c.button('designer.send');expect(c.owner.getSnapshot().message).toBe('');expect(sessionStorage.getItem(messageKey)).toBeNull();expect(api.sendRequirementMessage).toHaveBeenCalledTimes(2)
  })
  it("keeps follow-up text and staged files after an atomic context-turn failure",async()=>{
    const c=await show(),file=new File(['context'],'context.txt',{type:'text/plain'});await c.view.get('.designer-page').trigger('drop',{dataTransfer:{types:['Files'],files:[file]}});await c.view.get('textarea[aria-label="设计消息"]').setValue('请结合文件继续设计');vi.mocked(api.sendDesignerContextTurn).mockRejectedValue(new Error('parse failed'));await c.button('designer.send');expect(api.sendDesignerContextTurn).toHaveBeenCalledWith(session.id,expect.objectContaining({content:'请结合文件继续设计',scopeKey:'REQUIREMENT'}),[file]);expect(c.owner.getSnapshot().message).toBe('请结合文件继续设计');expect(c.view.get('[aria-label="待发送附件"]').text()).toContain('context.txt');expect(c.owner.getSnapshot().command.phase).toBe('UNKNOWN');expect(c.owner.canLeave().kind).toBe('BLOCK')
  })
  it("keeps the chat answer composer available in auto mode when native question is unsupported",async()=>{
    const next=value({state:'RUNNING',autoMode:{enabled:true,state:'ACTIVE',version:1},questionInteraction:{mode:'CHAT_FALLBACK',awaitingAnswer:true},messages:[message('chat-question','DESIGNER','1. 失败时保留旧值还是清空？',{deliveryState:'CHAT_QUESTION'})]});const c=await show(next);expect(c.view.text()).toContain('对话回答模式');expect(c.view.text()).toContain('失败时保留旧值还是清空');expect(c.view.find('[role="status"][aria-label$="正在处理"]').exists()).toBe(false);await c.view.get('textarea[aria-label="设计消息"]').setValue('保留旧值并记录错误');await c.button('designer.send');expect(api.sendRequirementMessage).toHaveBeenCalledWith(next.id,'保留旧值并记录错误',1)
  })
  it("keeps the reply composer immediately after the naturally growing message history",async()=>{
    const c=await show(value({messages:[message('assistant-1','DESIGNER','# 很长的设计回复\n\n正文')]}));const history=c.view.get('[aria-label="设计讨论记录"]').element,composer=c.view.get('[aria-label="设计消息输入"]').element;expect(history.parentElement).toBe(composer.parentElement);expect(history.compareDocumentPosition(composer)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(c.view.get('textarea[aria-label="设计消息"]').element.closest('[aria-label="设计消息输入"]')).toBe(composer);expect(c.view.get('textarea[aria-label="设计消息"]').attributes('rows')).toBe('10')
  })
  it("places the current role activity inside the message list only while work is running",async()=>{
    const c=await show(value({state:'RUNNING',workflowPhase:'DESIGNING'}));expect(c.view.findAll('[role="status"][aria-label$="正在处理"]')).toHaveLength(1);expect(c.view.get('[role="status"][aria-label$="正在处理"]').element.closest('[aria-label="设计讨论记录"]')).not.toBeNull();vi.mocked(api.getDesignerSession).mockResolvedValue(value());await c.owner.refresh();await flushPromises();expect(c.view.find('[role="status"][aria-label$="正在处理"]').exists()).toBe(false)
  })
  it("uses the inline current-role activity for every actor and never renders raw SSE role output",async()=>{
    const c=await show(value({state:'RUNNING',workflowPhase:'DESIGNING'}));for(const actor of ['DESIGNER','DECOMPOSER','COMPILER','VALIDATOR'] as const){vi.mocked(api.getDesignerSession).mockResolvedValue(value({state:'RUNNING',workflowPhase:'DESIGNING',activeActor:actor}));await c.owner.refresh();c.streams[0]!.event(streamEvent({sequence:2,sessionId:session.id,type:'PARTIAL',state:'RUNNING',workflowPhase:'DESIGNING',activeActor:actor,runtimeConnected:true,content:'STREAM_OUTPUT_SHOULD_NOT_RENDER',at:'now'}));await flushPromises();expect(c.view.findAll('[role="status"][aria-label$="正在处理"]')).toHaveLength(1);expect(c.view.text()).not.toContain('STREAM_OUTPUT_SHOULD_NOT_RENDER');expect(c.owner.getSnapshot().session?.messages).toEqual([])}
  })
  it("renders pending Designer questions and submits their answers before continuing",async()=>{
    const next=value({state:'RUNNING',pendingQuestions:[{id:'q',questions:[{question:'选择缓存刷新范围',header:'范围',multiple:false,custom:true,options:[{label:'完整刷新',description:'覆盖全部缓存条目'}]}]}]});const c=await show(next);expect(c.view.find('textarea[aria-label="设计消息"]').exists()).toBe(false);await c.view.get('[aria-label="设计师等待回答"] input[type="radio"]').setValue(true);vi.spyOn(api,'replyDesignerQuestion').mockResolvedValue(undefined);await c.button('designer.replyQuestion');expect(api.replyDesignerQuestion).toHaveBeenCalledWith(next.id,'q',[['完整刷新']]);expect(c.view.text()).toContain('选择缓存刷新范围')
  })
  it("places each discussion round immediately before its matching design snapshot",async()=>{
    const next=value({answeredQuestions:[question('q1','REQUIREMENT',1,'d1'),question('q2','WP-1',2,'d2')],messages:[message('u1','USER','整体需求'),message('d1','DESIGNER','第一版设计'),message('u2','USER','工作包反馈',{workPackageId:'WP-1'}),message('d2','DESIGNER','第二版设计',{workPackageId:'WP-1'})]});const c=await show(next),entries=timeline(next);expect(entries.map(e=>e.key)).toEqual(['u1',expect.any(String),'d1','u2',expect.any(String),'d2']);const history=c.view.get('[aria-label="设计讨论记录"]');const first=history.findAll('details').filter(d=>d.get('summary').text()==='需求讨论');expect(first).toHaveLength(2);expect(first.every(d=>d.attributes('open')===undefined)).toBe(true);expect(history.text().indexOf('完整刷新')).toBeLessThan(history.text().indexOf('第一版设计'))
  })
  it("keeps requirement discussion anchored before its hidden server snapshot as later messages arrive",async()=>{
    const next=value({answeredQuestions:[question('q','REQUIREMENT',1,'snapshot')],messages:[message('snapshot','SYSTEM','# 冻结快照',{deliveryState:'SERVER_REQUIREMENT_SNAPSHOT'}),message('later','DESIGNER','# 最新设计')]});const c=await show(next);const entries=timeline(next);expect(entries[0]?.kind).toBe('discussion');expect(entries.some(e=>e.kind==='message'&&e.message.id==='snapshot')).toBe(false);expect(c.view.text()).toContain('完整刷新');expect(c.view.text()).toContain('最新设计');expect(c.view.text()).not.toContain('冻结快照')
  })
  it("keeps package feedback scoped and requires explicit acceptance before continuing",async()=>{
    const next=value({workflowPhase:'REVIEWING_PACKAGE',discussionScope:'WP-1',discussionRevision:4,activeWorkPackageId:'WP-1',workPackages:[pkg({state:'REVIEWING',approvedDesignRevision:undefined})]});const c=await show(next);await c.view.get('textarea[aria-label="设计消息"]').setValue('请补充错误恢复');vi.spyOn(api,'sendWorkPackageMessage').mockResolvedValue({sessionId:next.id,state:'REVIEWING',persistedMessages:[],notice:'saved'});await c.button('designer.send');expect(api.sendWorkPackageMessage).toHaveBeenCalledWith(next.id,'WP-1','请补充错误恢复',4,2);vi.spyOn(api,'approveWorkPackage').mockResolvedValue(undefined);await c.button('designer.approvePackage');expect(api.approveWorkPackage).not.toHaveBeenCalled();await c.confirm('designer.approvePackage');expect(api.approveWorkPackage).toHaveBeenCalledWith(next.id,'WP-1',4,2)
  })
  it("shows acceptance intent coverage without exposing internal fact or capability ids",async()=>{
    const next=value({activeWorkPackageId:'WP-1',workPackages:[pkg({acceptancePlanning:planning({routingReasons:['历史路径消歧','历史路径消歧']})})]});const c=await show(next);expect(c.view.get('[aria-label="验收意图覆盖"]').text()).toContain('0 项待覆盖');expect(c.view.get('[aria-label="验收意图覆盖"]').find('[role="alert"]').exists()).toBe(false);expect(c.view.text()).not.toContain('ap');expect(c.view.findAll('details').find(d=>d.get('summary').text()==='历史消歧说明')!.findAll('p')).toHaveLength(1)
  })
  it("labels server direct compilation and does not mount remote activity polling",async()=>{
    const next=value({state:'RUNNING',workflowPhase:'COMPILING',compiler:{id:'compiler',state:'COMPLETED',repairCount:0,planningRepairCount:0,designRevision:1,workflowStep:'FINAL_JSON',serverCompiled:true},workPackages:[pkg({serverCompiled:true})]});const c=await show(next);expect(c.view.text()).toContain('服务端直接编译');expect(c.view.find('[role="status"][aria-label$="正在处理"]').exists()).toBe(false);expect(api.getDesignerActivity).not.toHaveBeenCalled();expect(c.view.text()).not.toContain('LOOPSPEC_COMPILATION_JSON')
  })
  it("replaces the right-side LoopSpec when the completed Designer session returns its bound draft",async()=>{
    vi.useFakeTimers();const c=await show(value({state:'RUNNING',workflowPhase:'DESIGNING'})),generated=spec('精确计算圆周率10万位');generated.stages[0]!.objective='实现并验证 100000 位圆周率计算';vi.mocked(api.getDesignerSession).mockResolvedValue(finalSession({draft:draftFrom(generated)}));await vi.advanceTimersByTimeAsync(1200);await flushPromises();await openSpec(c);expect(c.owner.getSnapshot().editor).toContain('实现并验证 100000 位圆周率计算');expect(c.body().get('textarea[aria-label="阶段 1 目标"]').text()).toContain('100000');expect(c.body().text()).toContain('1 个阶段')
  })
  it("hides informational handoff notices but keeps pending runtime errors visible",async()=>{
    const c=await show(value({messages:[message('created','SYSTEM','Designer session created in read-only mode.',{deliveryState:'PENDING_HANDOFF'}),message('waiting','SYSTEM','Message was handed to the read-only OpenCode Designer.',{deliveryState:'PENDING_HANDOFF'}),message('error','SYSTEM','SYSTEM_ERROR[SESSION]: Runtime is unavailable.',{deliveryState:'PENDING_HANDOFF'})]}));expect(c.view.text()).not.toContain('Designer session created in read-only mode.');expect(c.view.text()).not.toContain('Message was handed');expect(c.view.text()).not.toContain('SYSTEM_ERROR');const system=c.view.findAll('details').find(d=>d.get('summary').text().includes('系统记录'))!;expect(system.attributes('open')).toBeUndefined();expect(system.text()).toContain('会话出现错误')
  })
  it("collects consecutive system notices into one disclosure even when their scope metadata changes",async()=>{
    const next=value({messages:[message('user','USER','请设计事件系统'),message('s1','SYSTEM','全自动模式已授权',{requirementRevision:1}),message('s2','SYSTEM','任务画像已生成',{requirementRevision:1}),message('d','DESIGNER','# 完整需求稿'),message('s3','SYSTEM','正在重新计算任务画像',{requirementRevision:2}),message('s4','SYSTEM','整体需求已确认',{requirementRevision:3,workPackageId:'WP-1'})]});const c=await show(next);const grouped=timeline(next).filter(e=>e.kind==='system');expect(grouped.map(e=>e.kind==='system'&&e.messages.map(m=>m.id))).toEqual([['s1','s2'],['s3','s4']]);const histories=c.view.findAll('details').filter(d=>d.get('summary').text().includes('系统记录'));expect(histories).toHaveLength(2);expect(histories.every(d=>d.attributes('open')===undefined)).toBe(true);await histories[0]!.get('summary').trigger('click');expect(histories[0]!.attributes('open')).toBe('');expect(histories[0]!.text()).not.toContain('正在重新计算任务画像')
  })
  it("restores distinct role cards, hides compiler JSON, and exposes both recovery actions",async()=>{
    const next=value({state:'SESSION_ERROR',workflowPhase:'FAILED',compiler:{id:'compiler-1',state:'SESSION_ERROR',externalSessionState:'FAILED',repairCount:2,planningRepairCount:0,designRevision:1,workflowStep:'FINAL_JSON'},answeredQuestions:[question()],messages:[message('u','USER','请设计缓存刷新任务'),message('d','DESIGNER','# 完整设计稿'),message('c','COMPILER','已编译1个阶段'),message('raw','COMPILER','<!-- LOOPSPEC_COMPILATION_JSON_START -->{"loopSpec":"secret"}'),message('v1','VALIDATOR','字段校验失败，可修复',{deliveryState:'RETRYABLE_ERROR'}),message('v2','VALIDATOR','输出包装已自动规范化',{deliveryState:'NORMALIZED'}),message('v3','VALIDATOR','工作流已停止',{deliveryState:'TERMINAL_ERROR'}),message('s','SYSTEM','服务端状态通知')]});const c=await show(next);expect(c.view.text()).toContain('设计师');expect(c.view.text()).toContain('规范工程师');expect(c.view.text()).not.toContain('"loopSpec":"secret"');expect(c.view.findAll('details').filter(d=>d.get('summary').text().includes('验收记录'))).toHaveLength(1);expect(c.view.text()).toContain('字段校验失败');vi.spyOn(api,'retryDesignerCompiler').mockResolvedValue(undefined);vi.spyOn(api,'requestDesignerRedesign').mockResolvedValue(undefined);await c.button('designer.retryCompiler');await c.confirm('designer.retryCompiler');await c.button('designer.redesign');await c.confirm('designer.redesign');expect(api.retryDesignerCompiler).toHaveBeenCalledWith(next.id);expect(api.requestDesignerRedesign).toHaveBeenCalledWith(next.id)
  })
  it("does not expose compiler recovery actions when requirement questioning failed before compilation",async()=>{
    const c=await show(value({state:'WAITING_INPUT',workflowPhase:'FAILED',compiler:undefined,messages:[message('failure','VALIDATOR','DESIGN_QUESTION_REQUIRED: Designer completed without asking the required question',{deliveryState:'TERMINAL_ERROR'})]}));expect(c.view.text()).toContain('设计前需要先回答问题');expect(c.view.find('button[data-semantic="designer.retryCompiler"]').exists()).toBe(false);expect(c.view.find('button[data-semantic="designer.redesign"]').exists()).toBe(false);expect(c.view.get('button[data-semantic="designer.reset"]').exists()).toBe(true)
  })
  it("restores the Decomposer card, package rail, retry counters, and waiting-input boundary",async()=>{
    const next=value({state:'WAITING_INPUT',workflowPhase:'FAILED',activeWorkPackageId:'WP-2',discussionScope:'WP-2',requirementRevision:3,requirement:{revision:3,state:'WAITING_INPUT',modelCallsUsed:9,maxModelCalls:32,sourceDraftVersion:4},decomposition:{id:'decomposition-3',state:'COMPLETED',resultType:'DECOMPOSED',repairCount:1,planningRepairCount:1,transportRetryCount:0,workflowStep:'FINAL_JSON',candidateSessions:2,candidateSubmissions:5},compiler:{id:'compiler',state:'SESSION_ERROR',repairCount:2,planningRepairCount:2,designRevision:1,workPackageId:'WP-2',workflowStep:'FINAL_JSON'},workPackages:[pkg({compilationSource:'MARKDOWN_FALLBACK',fallbackReason:'FEATURE_DISABLED'}),pkg({id:'WP-2',ordinal:1,state:'WAITING_INPUT',dependencies:['WP-1'],candidateRunState:'ACCEPTED',candidateSessions:1,candidateSubmissions:2,compilationSource:'MCP_ACCEPTED',serverCompiled:true})],messages:[message('decomposer','DECOMPOSER','拆解校验通过：形成2个工作包。'),message('raw','COMPILER','<!-- LOOPSPEC_COMPILATION_JSON_START -->{"stages":["secret"]}') ]});const c=await show(next);vi.spyOn(api,'confirmDraft');expect(c.view.text()).toContain('任务规划师');expect(c.view.get('[aria-label="工作包设计轨道"]').text()).toContain('第 2 包');expect(c.view.text()).toContain('模型调用 9/32');expect(c.view.text()).not.toContain('模型调用 14/32');expect(c.view.text()).toContain('候选提交 5');expect(c.view.text()).toContain('Markdown 兜底');expect(c.view.text()).not.toContain('"stages":["secret"]');expect(c.view.find('button[data-semantic="designer.confirm"]:not(:disabled)').exists()).toBe(false);expect(api.confirmDraft).not.toHaveBeenCalled();vi.spyOn(api,'retryWorkPackageCompiler').mockResolvedValue(undefined);vi.spyOn(api,'redesignWorkPackage').mockResolvedValue(undefined);await c.button('designer.retryPackageCompiler');await c.confirm('designer.retryPackageCompiler');await c.button('designer.redesignPackage');await c.confirm('designer.redesignPackage');expect(api.retryWorkPackageCompiler).toHaveBeenCalledWith(next.id,'WP-2');expect(api.redesignWorkPackage).toHaveBeenCalledWith(next.id,'WP-2')
  })
  it("blocks unchanged recompilation and opens targeted package feedback for mutation ownership gaps",async()=>{
    const next=value({state:'WAITING_INPUT',workflowPhase:'FAILED',activeWorkPackageId:'WP-1',discussionScope:'WP-1',discussionRevision:4,workPackages:[pkg({state:'WAITING_INPUT',lastErrorCode:'REQUIRED_MUTATION_PATH_UNASSIGNED',acceptancePlanning:planning({state:'FAILED',unresolvedCount:1,unresolvedMutationObligationCount:1,pathConservation:'BLOCKED',mutationBindingReasons:['路径待归属'],issues:['REQUIRED_MUTATION_PATH_UNASSIGNED']})})]});const c=await show(next);expect(c.view.get('button[data-semantic="designer.retryPackageCompiler"]').element.matches(':disabled')).toBe(true);expect(c.view.get('button[data-semantic="designer.redesignPackage"]').element.matches(':disabled')).toBe(false);expect(c.view.text()).toContain('补充路径归属与改动计划');vi.spyOn(api,'retryWorkPackageCompiler');vi.spyOn(api,'redesignWorkPackage');vi.spyOn(api,'sendWorkPackageMessage').mockResolvedValue({sessionId:next.id,state:'RUNNING',persistedMessages:[],notice:''});await c.view.get('textarea[aria-label="设计消息"]').setValue('请将 ScheduleSceneEnum.java 明确归入任务定义阶段');await c.button('designer.send');expect(api.sendWorkPackageMessage).toHaveBeenCalledWith(next.id,'WP-1','请将 ScheduleSceneEnum.java 明确归入任务定义阶段',4,2);expect(api.retryWorkPackageCompiler).not.toHaveBeenCalled();expect(api.redesignWorkPackage).not.toHaveBeenCalled()
  })
  it("clears the restored workspace and local message drafts when starting over",async()=>{
    const c=await show();await c.view.get('textarea[aria-label="设计消息"]').setValue('未发送的旧补充');expect(sessionStorage.getItem(workspaceKey)).toContain(session.id);const stop=vi.spyOn(api,'stopDesignerSession').mockResolvedValue({stopStatus:'CANCELLED',archived:true,stoppedSessions:1,failedSessions:0,pendingFinalizations:0});await c.button('designer.reset');expect(stop).not.toHaveBeenCalled();await c.confirm('designer.reset');expect(stop).toHaveBeenCalledWith(session.id);expect(sessionStorage.getItem(workspaceKey)).toBeNull();expect(sessionStorage.getItem(promptKey)).toBeNull();expect(sessionStorage.getItem(messageKey)).toBeNull();expect(c.p.props.navigation.go).toHaveBeenCalledWith(`/requirements/new?projectId=${project.id}`)
  })
  it("loads the confirmed Task into the store and opens its detail even when worktree preparation failed",async()=>{
    const loop=spec('交接到任务控制台');loop.limits={...loop.limits,sessionErrorLimit:4,stagnationLimit:5,verifierTimeout:'420'};loop.model={providerId:'provider-1',modelId:'model-1',thinking:false};loop.sessionPolicy={reuseHealthySession:false,createFreshOnVerifierFailure:false};loop.nextAttemptPromptTemplate='人工继续时处理 ${failureSummary}';const c=await show(finalSession({draft:draftFrom(loop)})),task=taskTransport(c);await openSpec(c);await c.body().get('textarea[aria-label="任务目标"]').setValue('交接到任务控制台（修订）');vi.spyOn(api,'updateDraft').mockResolvedValue({...c.owner.getSnapshot().draft!,spec:{...loop,goal:'交接到任务控制台（修订）'}});vi.mocked(api.getDesignerSession).mockResolvedValue(finalSession({draft:{...draftFrom(loop),spec:{...loop,goal:'交接到任务控制台（修订）'}}}));await confirmed(c);expect(api.updateDraft).toHaveBeenCalledWith('draft-1',expect.objectContaining({stages:[expect.objectContaining({workPackageId:'WP-1'})],limits:expect.objectContaining({sessionErrorLimit:4,stagnationLimit:5,verifierTimeout:'420'}),model:loop.model,sessionPolicy:loop.sessionPolicy,nextAttemptPromptTemplate:loop.nextAttemptPromptTemplate}),0);expect(api.confirmDraft).toHaveBeenCalledWith('draft-1',0);expect(api.getTaskOverview).toHaveBeenCalledWith(task.id);expect(c.p.props.navigation.goAccepted).toHaveBeenCalledWith(`/tasks/${task.id}`,expect.any(Object));expect(sessionStorage.getItem(workspaceKey)).toBeNull();expect(c.owner.canLeave().kind).toBe('ALLOW')
  })
  it("renders the coverage matrix and blocks save when a v2 criterion is uncovered",async()=>{
    const c=await show(finalSession());await openSpec(c);vi.mocked(api.validateDraft).mockResolvedValue({valid:false,schemaVersion:'v2',legacy:false,errors:['验收条件缺少有效BEHAVIOR验证器'],stageAssessments:[{stageIndex:0,criteria:[{id:'WP-1-AC-1',description:'异常语义和消息文本',verificationMode:'MACHINE',covered:false,machineCovered:false,judgePlanned:false,overallPlanned:false,verifierIndexes:[]}],verifiers:[{index:0,type:'PROCESS',category:'BUILD',blocking:true,criterionIds:['WP-1-AC-1'],reason:'compile/build/static-quality command'}]}]});const update=vi.spyOn(api,'updateDraft');await c.button('designer.save');expect(update).not.toHaveBeenCalled();const matrix=c.body().get('[aria-label="双重验收计划矩阵"]');expect(matrix.text()).toContain('异常语义和消息文本');expect(matrix.text()).toContain('机器：不适用');expect(matrix.text()).toContain('AI：不适用');expect(matrix.text()).toContain('BUILD')
  })
  it("keeps the editing baseline across refreshed snapshots and preserves conflicts until explicit reload",async()=>{
    const original={...draftFrom(spec('原版本')),version:6},latest={...original,version:7,spec:spec('其他页面已保存')};const c=await show(finalSession({draft:original}));await openSpec(c);await c.body().get('textarea[aria-label="任务目标"]').setValue('本地尚未保存');vi.mocked(api.getDesignerSession).mockResolvedValue(finalSession({draft:latest}));await c.owner.refresh();const update=vi.spyOn(api,'updateDraft').mockRejectedValue(new ApiError('草稿已改变',409,{code:'DRAFT_VERSION_CONFLICT'}));await c.button('designer.save');expect(update).toHaveBeenCalledWith(original.id,expect.objectContaining({goal:'本地尚未保存'}),6);expect(c.owner.getSnapshot().editor).toContain('本地尚未保存');expect(c.owner.getSnapshot().conflict).toBe(true);expect(c.view.get('button[data-semantic="designer.confirm"]').element.matches(':disabled')).toBe(true);vi.mocked(api.getDraft).mockResolvedValue(latest);await c.button('designer.reloadDraft');await c.confirm('designer.reloadDraft');expect(c.owner.getSnapshot().editor).toContain('其他页面已保存');expect(c.owner.getSnapshot().conflict).toBe(false)
  })
  it("refreshes confirmation eligibility after save and displays the server blocker without creating a task",async()=>{
    const c=await show(finalSession());await openSpec(c);await c.body().get('textarea[aria-label="任务目标"]').setValue('撰写文档');vi.spyOn(api,'updateDraft').mockResolvedValue({...c.owner.getSnapshot().draft!,spec:spec('撰写文档')});vi.mocked(api.getDesignerSession).mockResolvedValue(finalSession({draft:draftFrom(spec('撰写文档')),finalConfirmationEligible:false,confirmationBlocker:'正文 AI 评审缺失，请修复后保存。'}));const confirm=vi.spyOn(api,'confirmDraft');await confirmed(c);expect(confirm).not.toHaveBeenCalled();expect(c.view.text()).toContain('正文 AI 评审缺失');expect(c.view.get('button[data-semantic="designer.confirm"]').element.matches(':disabled')).toBe(true)
  })
  it("shows a restored invalid design blocker and refreshes eligibility after a successful repair save",async()=>{
    const c=await show(finalSession({finalConfirmationEligible:false,confirmationBlocker:'正文 AI 评审缺失，请修复后保存。'}));expect(c.view.text()).toContain('正文 AI 评审缺失');await openSpec(c);vi.spyOn(api,'updateDraft').mockResolvedValue(c.owner.getSnapshot().draft!);vi.mocked(api.getDesignerSession).mockResolvedValue(finalSession());await c.button('designer.save');expect(c.view.text()).not.toContain('正文 AI 评审缺失');expect(c.view.get('button[data-semantic="designer.confirm"]').element.matches(':disabled')).toBe(false)
  })
  it("keeps creation blocked when the eligibility refresh fails after a persisted save",async()=>{
    const c=await show(finalSession());await openSpec(c);await c.body().get('textarea[aria-label="任务目标"]').setValue('已保存但待核对');vi.spyOn(api,'updateDraft').mockResolvedValue({...c.owner.getSnapshot().draft!,spec:spec('已保存但待核对')});vi.mocked(api.getDesignerSession).mockRejectedValue(new Error('连接失败'));const confirm=vi.spyOn(api,'confirmDraft');await confirmed(c);expect(api.updateDraft).toHaveBeenCalledTimes(1);expect(confirm).not.toHaveBeenCalled();expect(c.owner.getSnapshot().command.phase).toBe('ACCEPTED_READBACK');expect(c.owner.canLeave().kind).toBe('BLOCK');expect(c.view.get('button[data-semantic="designer.confirm"]').element.matches(':disabled')).toBe(true)
  })
  it("confirms a DIRECT_ARTIFACT document from FINAL_REVIEW using server eligibility without an artifact plan",async()=>{
    const document=spec('撰写详细设计文档');document.stages[0]={...document.stages[0]!,stageKind:'DOCUMENT_AUTHORING',executionStrategy:'OPEN_CODE_IMPLEMENTATION',implementationKind:'NON_JAVA',allowedPaths:['docs/design.md'],deliverables:['docs/design.md'],verifiers:[{type:'DOCUMENT_STRUCTURE',path:'docs/design.md',criterionIds:['AC-1'],documentAssertions:[{type:'TEXT_NON_EMPTY'}]}],acceptanceCriteria:[{id:'AC-1',description:'格式有效'},{id:'AC-2',description:'正文完整',verificationMode:'JUDGE',judgeRubric:'逐项核对来源',judgeOnlyReason:'需要内容评审'}]};const c=await show(finalSession({draft:draftFrom(document),taskProfile:{...value().taskProfile,workflowTemplate:'DIRECT_ARTIFACT',intent:'DOCUMENT_AUTHORING',testPolicy:'NOT_APPLICABLE',artifactKinds:['MARKDOWN']}}));const task=taskTransport(c,failedTask('document-task','PENDING_START'));expect(c.view.get('button[data-semantic="designer.confirm"]').element.matches(':disabled')).toBe(false);await confirmed(c);expect(api.confirmDraft).toHaveBeenCalledWith('draft-1',0);expect(api.getTaskOverview).toHaveBeenCalledWith(task.id);expect(c.owner.getSnapshot().draft?.spec.stages[0]).toMatchObject({stageKind:'DOCUMENT_AUTHORING',executionStrategy:'OPEN_CODE_IMPLEMENTATION'});expect(c.p.props.navigation.goAccepted).toHaveBeenCalledWith(`/tasks/${task.id}`,expect.any(Object))
  })
  it("confirms a PACKAGED_ARTIFACT document from FINAL_REVIEW using server eligibility without an artifact plan",async()=>{
    const document=spec('撰写详细设计文档');document.stages[0]={...document.stages[0]!,stageKind:'DOCUMENT_AUTHORING',executionStrategy:'OPEN_CODE_IMPLEMENTATION',implementationKind:'NON_JAVA',allowedPaths:['docs/design.md'],deliverables:['docs/design.md'],verifiers:[{type:'DOCUMENT_STRUCTURE',path:'docs/design.md',criterionIds:['AC-1'],documentAssertions:[{type:'TEXT_NON_EMPTY'}]}],acceptanceCriteria:[{id:'AC-1',description:'格式有效'},{id:'AC-2',description:'正文完整',verificationMode:'JUDGE',judgeRubric:'逐项核对来源',judgeOnlyReason:'需要内容评审'}]};const c=await show(finalSession({draft:draftFrom(document),taskProfile:{...value().taskProfile,workflowTemplate:'PACKAGED_ARTIFACT',intent:'DOCUMENT_AUTHORING',testPolicy:'NOT_APPLICABLE',artifactKinds:['MARKDOWN']}}));const task=taskTransport(c,failedTask('document-task','PENDING_START'));expect(c.view.get('button[data-semantic="designer.confirm"]').element.matches(':disabled')).toBe(false);await confirmed(c);expect(api.confirmDraft).toHaveBeenCalledWith('draft-1',0);expect(api.getTaskOverview).toHaveBeenCalledWith(task.id);expect(c.owner.getSnapshot().draft?.spec.stages[0]).toMatchObject({stageKind:'DOCUMENT_AUTHORING',executionStrategy:'OPEN_CODE_IMPLEMENTATION'});expect(c.p.props.navigation.goAccepted).toHaveBeenCalledWith(`/tasks/${task.id}`,expect.any(Object))
  })
  it("reopens an already confirmed draft idempotently without trying to modify the immutable LoopSpec",async()=>{
    const loop={...spec('重新打开已确认交接'),schemaVersion:'v1' as const},draft={...draftFrom(loop),status:'CONFIRMED' as const};const c=await show(finalSession({draft,taskId:'task-existing'}));const task=failedTask('task-existing','READY');vi.spyOn(api,'getTaskOverview').mockResolvedValue(task);vi.spyOn(api,'getTaskAudit').mockResolvedValue({errors:[],judges:[],artifacts:[],attempts:[]});const update=vi.spyOn(api,'updateDraft'),confirm=vi.spyOn(api,'confirmDraft');await c.owner.openTask();await flushPromises();expect(update).not.toHaveBeenCalled();expect(confirm).not.toHaveBeenCalled();expect(api.getTaskOverview).toHaveBeenCalledWith('task-existing');expect(c.p.props.navigation.go).toHaveBeenCalledWith('/tasks/task-existing');expect(c.owner.getSnapshot().acceptedTask).toBe('')
  })
})
