import {describe,expect,it,vi,afterEach} from 'vitest'
import {api} from '@/api/client'
import {projectPage} from '@/pages/w6-tests/ordinary/projects'
import {action,confirm,change,flushPromises} from '@/pages/w6-tests/ordinary/actions'
import {projectFixture} from '@/pages/w2/core/coreTestHelpers'
afterEach(()=>vi.useRealTimers())
describe('Projects folder picker',()=>{
 it('fills the absolute path and suggests a project name after directory selection',async()=>{vi.spyOn(api,'pickProjectDirectory').mockResolvedValue({selected:true,path:'/tmp/example-project',name:'example-project'});const p=projectPage([]);await action('project.register');await p.view.get('button[data-semantic="project.chooseDirectory"]').trigger('click');expect((p.view.get('input[aria-label="项目根路径"]').element as HTMLInputElement).value).toBe('/tmp/example-project');expect((p.view.get('input[aria-label="项目名称"]').element as HTMLInputElement).value).toBe('example-project')})
 it('keeps a manually entered path when the native selector is cancelled',async()=>{vi.spyOn(api,'pickProjectDirectory').mockResolvedValue({selected:false});const p=projectPage([]);await action('project.register');await change('项目根路径','/tmp/keep-this-path');await p.view.get('button[data-semantic="project.chooseDirectory"]').trigger('click');expect((p.view.get('input[aria-label="项目根路径"]').element as HTMLInputElement).value).toBe('/tmp/keep-this-path')})
})
const content='<!-- LOOPPER:START -->\n# Project rules\n<!-- LOOPPER:END -->\n'
describe('Projects AGENTS.md convention flow',()=>{
 it('shows an empty current convention before starting AI design and applies only after confirmation',async()=>{vi.spyOn(api,'getCurrentProjectConvention').mockResolvedValue({projectId:'project-1',exists:false,loopperManaged:false,content:''});vi.spyOn(api,'generateProjectConvention').mockResolvedValue({id:'draft-1',projectId:'project-1',state:'READY',operation:'CREATE',readOnlyGeneration:true,content,normalizationNotice:'AI 输出已自动规范化：WRAPPER_TOLERATED',updatedAt:'2026-08-05T00:00:01Z'});const apply=vi.spyOn(api,'applyProjectConvention').mockResolvedValue({id:'draft-1',projectId:'project-1',state:'APPLIED',operation:'CREATE',readOnlyGeneration:true,content,updatedAt:'now'});const p=projectPage();await p.select();await action('project.readConvention');expect(api.getCurrentProjectConvention).toHaveBeenCalledWith('project-1');expect(p.view.text()).toContain('暂无项目公约');expect(api.generateProjectConvention).not.toHaveBeenCalled();await action('project.generateConvention');expect(api.generateProjectConvention).toHaveBeenCalledWith('project-1');expect((p.view.get('textarea[aria-label="AGENTS.md 完整预览"]').element as HTMLTextAreaElement).value).toContain('# Project rules');expect(p.view.text()).toContain('AI 输出已自动规范化：已兼容常见外层格式');expect(p.view.text()).not.toContain('WRAPPER_TOLERATED');expect(apply).not.toHaveBeenCalled();await action('project.applyConvention');expect(apply).toHaveBeenCalledWith('project-1','draft-1')})
 it('shows the existing AGENTS.md without starting AI',async()=>{vi.spyOn(api,'getCurrentProjectConvention').mockResolvedValue({projectId:'project-1',exists:true,loopperManaged:true,content:'# Existing rules\n'});const generate=vi.spyOn(api,'generateProjectConvention'),p=projectPage();await p.select();await action('project.readConvention');expect((p.view.get('textarea[aria-label="当前 AGENTS.md 项目公约"]').element as HTMLTextAreaElement).value).toContain('# Existing rules');expect(p.view.find('[data-semantic="project.generateConvention"]').exists()).toBe(true);expect(generate).not.toHaveBeenCalled()})
 it('streams live AI activity and sends an explicit remote stop request',async()=>{vi.useFakeTimers();vi.spyOn(api,'getCurrentProjectConvention').mockResolvedValue({projectId:'project-1',exists:true,loopperManaged:true,content:'# Existing\n'});const draft={id:'draft-1',projectId:'project-1',state:'RUNNING' as const,operation:'UPDATE' as const,readOnlyGeneration:true,updatedAt:'now'};vi.spyOn(api,'generateProjectConvention').mockResolvedValue(draft);vi.spyOn(api,'getProjectConventionDraft').mockResolvedValue(draft);vi.spyOn(api,'getProjectConventionActivity').mockResolvedValue({actor:'PROJECT_CONVENTION',remoteState:'RUNNING',connected:true,observedAt:'later',parts:[{id:'part-1',type:'THINKING',label:'分析构建文件',content:'正在核对 Maven 模块',status:'RUNNING'}],usage:{totalTokens:321,unknownUsageCount:0,observedAt:'later'}});const cancel=vi.spyOn(api,'cancelProjectConvention').mockImplementation(async()=>{const stopped={...draft,state:'CANCELLED' as const,error:'用户取消了项目公约生成'};vi.mocked(api.getProjectConventionDraft).mockResolvedValue(stopped);return stopped});const p=projectPage();await p.select();await action('project.readConvention');await action('project.generateConvention');await vi.advanceTimersByTimeAsync(1000);await flushPromises();expect(p.view.text()).toContain('项目公约设计师正在处理');expect(p.view.text()).toContain('正在核对 Maven 模块');expect(p.view.text()).toContain('321');expect(p.view.text()).not.toContain('超时上限');await action('project.stopConvention');expect(cancel).not.toHaveBeenCalled();await confirm('project.stopConvention');expect(cancel).toHaveBeenCalledWith('project-1','draft-1')})
})
describe('Projects management',()=>{
 it('shows the persisted project stack summary without triggering a filesystem refresh',()=>{const read=vi.spyOn(api,'getProjectStackProfile'),p=projectPage([{...projectFixture,id:'project-1',name:'Example',stackTechnologyFamilies:['java'],stackComponentCount:2}]);expect(p.view.text()).toContain('Java');expect(p.view.text()).toContain('2 个组件');expect(read).not.toHaveBeenCalled()})
 it('keeps Task count separate and opens the persistent Designer recovery list',async()=>{const p=projectPage([{...projectFixture,id:'project-1',name:'Example',taskCount:0,openDesignerSessionCount:1}]);expect(p.view.text()).toContain('0 个任务 · 1 个待继续设计');await p.select();await action('designer.continue');expect(p.props.navigation.go).toHaveBeenCalledWith({path:'/designs',query:{projectId:'project-1'}})})
 it('shows the real Git task-branch or direct execution mode',async()=>{const p=projectPage([{...projectFixture,id:'git-project',name:'Git project',rootPath:'/tmp/git/module',repositoryRoot:'/tmp/git',description:'Isolated changes',executionMode:'WORKTREE',branch:'main'},{...projectFixture,id:'plain-project',name:'Plain project',rootPath:'/tmp/plain',status:'NEEDS_GIT',executionMode:'DIRECT'}]);expect(p.view.text()).toContain('Git 分支模式');expect(p.view.text()).toContain('/tmp/git/module');expect(p.view.text()).toContain('main');expect(p.view.text()).toContain('直接模式');expect(p.view.text()).toContain('原项目目录');await p.select();expect(p.view.text()).toContain('Git 仓库：/tmp/git');expect(p.view.text()).toContain('Isolated changes');expect(p.view.text()).not.toContain('no git head')})
 it('cancels management without deleting the project history from the UI contract',async()=>{const cancel=vi.spyOn(api,'cancelProjectManagement').mockResolvedValue(undefined),get=vi.spyOn(api,'getProjects').mockResolvedValue([]),p=projectPage([{...projectFixture,id:'project-1',name:'Example',taskCount:4}]);await p.select();await action('project.unmanage');expect(document.body.textContent).toContain('历史任务、设计对话、LoopSpec 与执行证据都不会删除');expect(cancel).not.toHaveBeenCalled();await confirm('project.unmanage');expect(cancel).toHaveBeenCalledWith('project-1');expect(get).not.toHaveBeenCalled();expect(p.port.getSnapshot().projects).toHaveLength(0)})
})
