<script setup lang="ts">
import { computed } from 'vue'
import { Icon } from '@iconify/vue'
import PageHeader from '@/components/PageHeader.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { useTaskStore } from '@/stores/taskStore'

const store = useTaskStore()
const runtime = computed(() => store.runtime)
</script>

<template>
  <PageHeader eyebrow="System / Runtime" title="OpenCode Runtime" subtitle="本机受管服务只监听 loopback；认证信息从不写入 SQLite、日志或设置页面。">
    <template #actions><el-button v-if="runtime?.managed" type="primary" :loading="runtime?.status === 'STARTING'" @click="store.restartRuntime"><Icon icon="lucide:rotate-cw" />重启 Runtime</el-button><el-button v-else type="primary" :loading="runtime?.status === 'STARTING'" @click="store.refreshRuntime"><Icon icon="lucide:rotate-cw" />重新检测</el-button></template>
  </PageHeader>
  <main id="main-content" class="content" tabindex="-1"><section v-if="store.error" class="error-panel error-panel-task" role="alert" aria-live="assertive" style="margin-bottom:16px"><Icon class="error-panel-icon" icon="lucide:circle-alert" /><div><h3>Runtime 操作未完成</h3><p>{{ store.error }}</p></div></section><section v-if="runtime" class="runtime-grid"><article class="card card-pad runtime-hero"><div class="runtime-orb"><Icon icon="lucide:cpu" width="34" /></div><p class="eyebrow">OPENCODE SERVICE</p><h2>{{ runtime.version ? `OpenCode ${runtime.version}` : '等待 Runtime' }}</h2><StatusBadge :status="runtime.status" /><div class="runtime-model"><span>ACTIVE MODEL</span><strong>{{ runtime.model ?? '未配置' }}</strong></div></article><article class="card card-pad"><div class="card-header"><div><p class="eyebrow">PROCESS BOUNDARY</p><h2 class="card-title">受管进程</h2></div><Icon icon="lucide:shield-check" color="var(--color-success)" width="20" /></div><dl class="definition-list"><div><dt>监听地址</dt><dd class="mono">{{ runtime.endpoint ?? '—' }}</dd></div><div><dt>进程 PID</dt><dd class="mono">{{ runtime.pid ?? '—' }}</dd></div><div><dt>所有权</dt><dd>{{ runtime.managed ? 'Loopper 受管，启动时严格核验' : '外部复用服务' }}</dd></div><div><dt>上次检查</dt><dd class="mono">{{ runtime.checkedAt }}</dd></div></dl></article></section><section v-else class="card empty-state"><div><Icon icon="lucide:server-off" width="30" /><strong>Runtime 尚未读取</strong><p>启动后可在此检查版本、监听地址和模型配置。</p></div></section><section class="card card-pad" style="margin-top: 16px"><div class="card-header"><div><p class="eyebrow">SAFETY GUARDRAILS</p><h2 class="card-title">执行授权边界</h2></div></div><div class="guardrail-grid"><div><Icon icon="lucide:folder-lock" /><strong>执行目录内读写</strong><span>按 Task 模式授权</span></div><div><Icon icon="lucide:circle-help" /><strong>权限请求</strong><span>按 Task 策略审计</span></div><div><Icon icon="lucide:ban" /><strong>外部路径 / push</strong><span>永不自动批准</span></div></div></section></main>
</template>

<style scoped>
.runtime-grid { display: grid; grid-template-columns: minmax(340px, .9fr) minmax(380px, 1.1fr); gap: 16px; }.runtime-hero { min-height: 275px; overflow: hidden; background: radial-gradient(circle at 65% 22%, rgb(34 211 238 / 16%), transparent 35%), linear-gradient(145deg, #121c30, #0d1424); }.runtime-orb { display: grid; place-items: center; width: 64px; height: 64px; margin-bottom: 22px; border: 1px solid rgb(34 211 238 / 42%); border-radius: 50%; color: var(--color-accent-cyan); box-shadow: var(--shadow-glow); }.runtime-hero h2 { margin: 0 0 13px; font-size: 22px; }.runtime-model { display: flex; flex-direction: column; gap: 5px; margin-top: 23px; }.runtime-model span { color: var(--color-text-muted); font-family: var(--font-code); font-size: 10px; }.runtime-model strong { font-family: var(--font-code); font-size: 12px; font-weight: 500; }.definition-list { margin: 8px 0 0; }.definition-list div { display: flex; justify-content: space-between; gap: 16px; padding: 14px 0; border-bottom: 1px solid var(--color-border-default); }.definition-list dt { color: var(--color-text-secondary); font-size: 12px; }.definition-list dd { margin: 0; color: var(--color-text-primary); font-size: 12px; text-align: right; }.guardrail-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }.guardrail-grid div { display: flex; flex-direction: column; gap: 7px; padding: 15px; border: 1px solid var(--color-border-default); border-radius: var(--radius-control); }.guardrail-grid svg { color: var(--color-accent-cyan); }.guardrail-grid strong { font-size: 12px; }.guardrail-grid span { color: var(--color-text-secondary); font-size: 11px; }
</style>
