import {afterEach,describe,expect,it,vi} from 'vitest'
import {api} from '@/api/client'
import {SettingsPage} from '@/pages/w2/core/SettingsPage'
import {coreFixture} from '@/pages/w2/core/coreTestHelpers'
import {createTaskApplicationOwner} from '@/stores/taskStore'
import {createW2TaskPort} from '@/migration/w2TaskPort'
import {mount,flushPromises} from '@/pages/w6-tests/ordinary/render'
import {action,change} from '@/pages/w6-tests/ordinary/actions'
import {demoRuntime} from '@/mock/demoData'
import type {AppSettings} from '@/types/domain'
const disposers:(()=>void)[]=[]
afterEach(()=>disposers.splice(0).forEach(f=>f()))
function page(realOwner=false){const f=coreFixture(),app=createTaskApplicationOwner();app.usingDemo=false;const adapter=createW2TaskPort(app);if(realOwner)f.props.legacy.task=adapter.port;const view=mount(SettingsPage,{props:f.props});disposers.push(()=>{f.dispose();adapter.dispose();app.dispose()});return{...f,app,view}}
async function section(p:ReturnType<typeof page>,key:string){await p.view.get(`[aria-controls="settings-${key}"]`).trigger('click')}
function defaults(){vi.spyOn(api,'getSettings').mockResolvedValue(currentSettings());vi.spyOn(api,'getSettingsModels').mockResolvedValue([{id:'opencode/model-a',provider:'opencode',model:'model-a',label:'model-a'}])}
function currentSettings(): AppSettings {
  return {
    runtime: { serverPort: 8080, openBrowser: true, allowedRoot: '', monitorDelaySeconds: 2, designerMonitorDelayMillis: 750, abortCleanupAttempts: 3 },
    openCode: { cliPath: 'opencode', mode: 'managed', baseUrl: 'http://127.0.0.1:4096', provider: 'opencode', model: 'model-a', connectTimeoutSeconds: 5, requestTimeoutSeconds: 30, startupTimeoutSeconds: 15 },
    limits: { maxStageAttempts: 3, maxTaskAttempts: 12, sessionErrorLimit: 3, maxDurationMinutes: 120, attemptTimeoutMinutes: 30, verifierTimeoutMinutes: 10, designerTimeoutMinutes: 30 },
    retryWait: { rateLimitBaseSeconds: 60, rateLimitMaxSeconds: 300, sessionBaseSeconds: 10, sessionMaxSeconds: 60, verificationBaseSeconds: 5, verificationMaxSeconds: 30 },
    publication: { httpWebHosts: ['gitlab.spdb.com'], gitlabHost: 'gitlab.spdb.com', gitlabApiBaseUrl: 'http://gitlab.spdb.com/api/v4', connectTimeoutSeconds: 3, requestTimeoutSeconds: 10 },
    startupConfigPath: '/tmp/startup-overrides.properties', appliedLiveFields: ['retryWait'], restartRequiredFields: ['runtime.serverPort'],
  }
}

describe('Settings model selection',()=>{
 it('opens role management from settings without including it in the save form',async()=>{defaults();const save=vi.spyOn(api,'updateSettings'),p=page();await flushPromises();expect(p.view.find('a[href="/settings/roles"]').exists()).toBe(false);expect(save).not.toHaveBeenCalled()})
 it('preserves edits across sections and reveals the field that blocks saving',async()=>{defaults();const update=vi.spyOn(api,'updateSettings'),p=page();await flushPromises();await section(p,'runtime');await change('允许项目根（立即生效）','relative/path');await section(p,'models');expect(p.view.get('#settings-runtime').isVisible()).toBe(false);expect(p.view.get('#settings-models').isVisible()).toBe(true);await action('settings.save');expect(p.view.get('#settings-runtime').isVisible()).toBe(true);expect(p.view.get('#settings-runtime').text()).toContain('允许项目根必须是绝对路径');expect((p.view.get('[aria-label="允许项目根（立即生效）"]').element as HTMLInputElement).value).toBe('relative/path');expect(update).not.toHaveBeenCalled();await change('允许项目根（立即生效）','/workspace');await section(p,'models');await change('命令行路径（下次会话生效）','');await action('settings.save');expect(p.view.get('#settings-models').isVisible()).toBe(true);expect(p.view.text()).toContain('OpenCode CLI 路径不能为空');expect(update).not.toHaveBeenCalled()},10000)
 it('keeps all execution limit controls in the bottom-aligned limits grid',async()=>{defaults();const p=page();await flushPromises();await section(p,'limits');expect(p.view.get('#settings-limits').text()).toContain('启用业务超时限制');expect(p.view.get('.limits-grid').text()).not.toContain('尝试超时（分钟）');await p.view.get('[role="switch"][aria-label="启用业务超时限制"]').trigger('click');expect(p.view.get('.limits-grid').findAll('.ant-form-item')).toHaveLength(8);for(const label of ['尝试超时（分钟）','验证超时（分钟）','设计超时（分钟）'])expect(p.view.get('.limits-grid').text()).toContain(label)},10000)
 it('loads CLI models into dropdowns and persists the selected model',async()=>{defaults();vi.mocked(api.getSettingsModels).mockResolvedValue([{id:'opencode/big-pickle',provider:'opencode',model:'big-pickle',label:'opencode / big-pickle'},{id:'opencode/model-a',provider:'opencode',model:'model-a',label:'opencode / model-a'},{id:'deepseek/deepseek-chat',provider:'deepseek',model:'deepseek-chat',label:'deepseek / deepseek-chat'}]);const update=vi.spyOn(api,'updateSettings').mockImplementation(async body=>({...currentSettings(),...body})),runtime=vi.spyOn(api,'getRuntime').mockResolvedValue({...demoRuntime,model:'opencode/big-pickle'}),p=page(true);await flushPromises();await section(p,'models');expect(p.view.get('#settings-models').findAll('select')).toHaveLength(3);expect(p.view.text()).toContain('model-a');p.app.runtime={...demoRuntime,model:'opencode/model-a'};await change('模型','big-pickle');await section(p,'limits');await change('模板分析并发数','7');await action('settings.save');expect(runtime).toHaveBeenCalledOnce();expect(p.app.runtime?.model).toBe('opencode/big-pickle');expect(update).toHaveBeenCalledWith(expect.objectContaining({openCode:expect.objectContaining({mode:'managed',provider:'opencode',model:'big-pickle'}),limits:expect.objectContaining({templateAnalysisConcurrency:7})}))},10000)
 it('toggles demo data off and reloads the real overview',async()=>{defaults();vi.spyOn(api,'getProjects').mockResolvedValue([]);vi.spyOn(api,'getTasks').mockResolvedValue([]);vi.spyOn(api,'getRuntime').mockResolvedValue({...demoRuntime,pid:9001,endpoint:'127.0.0.1:4096'});const p=page(true);await flushPromises();await section(p,'demo');await action('settings.toggleDemo');expect(p.app.usingDemo).toBe(true);expect(p.app.error).toBeUndefined();expect(p.view.get('.settings-demo button').attributes('aria-label')).toContain('退出演示数据');await action('settings.toggleDemo');expect(p.app.usingDemo).toBe(false);expect(p.app.runtime?.pid).toBe(9001);expect(p.view.get('.settings-demo button').attributes('aria-label')).toContain('启用演示数据')})
 it('keeps the form available and reports a settings save failure',async()=>{defaults();const write=vi.spyOn(api,'updateSettings').mockRejectedValue(new Error('配置文件写入失败')),p=page();await flushPromises();await section(p,'runtime');await change('允许项目根（立即生效）','/workspace');await action('settings.save');expect(p.view.text()).toContain('配置文件写入失败');expect(p.view.get('#settings-runtime').isVisible()).toBe(true);expect((p.view.get('[aria-label="允许项目根（立即生效）"]').element as HTMLInputElement).value).toBe('/workspace');expect((p.view.get('[data-semantic="settings.save"]').element as HTMLButtonElement).disabled).toBe(true);expect([...p.guards].some(read=>read().kind==='BLOCK')).toBe(true);expect(write).toHaveBeenCalledOnce()})
})
