import {beforeEach,describe,expect,it,vi} from 'vitest'
import {api,ApiError} from '@/api/client'
import {detailFixture,taskFixture,flushPromises} from '@/pages/w6-tests/ordinary/detail'
import {action,confirm,body,fireEvent,act} from '@/pages/w6-tests/ordinary/actions'
import type {Task,ErrorEvent} from '@/types/domain'
const reviewTask:Task=taskFixture('task-review',{projectId:'project-1',title:'待评审任务',goal:'验证显式评审入口',status:'WAITING_INPUT',branch:'DIRECT',worktreePath:'/tmp/project',attemptCount:1,stages:[{id:'stage-1',ordinal:1,objective:'完成实现',status:'SUCCEEDED',attempts:[]}],judges:[{id:'requirement-1',role:'REQUIREMENT',ordinal:1,status:'COMPLETED',verdict:'BLOCKED',reason:'证据不足',createdAt:'start'},{id:'risk-1',role:'RISK',ordinal:1,status:'COMPLETED',verdict:'PASS',reason:'风险可控',createdAt:'start'}]})
const failure=(id:string,code:string,message:string,time='2026-10-03T10:00:00Z',layer:ErrorEvent['layer']='TASK'):ErrorEvent=>({id,code,message,layer,retryable:true,occurredAt:time})
async function page(value:Task){const f=detailFixture(value),p=await f.mount();await flushPromises();return {...f,...p}}
async function select(title:string){const target=[...document.querySelectorAll<HTMLButtonElement>('[aria-label="任务内容"] button')].find(b=>b.textContent===title);if(!target)throw new Error(`Missing selection ${title}`);act(()=>fireEvent.click(target));await flushPromises()}
const visibleActions=()=>[...document.querySelectorAll<HTMLButtonElement>('button[data-semantic]')].filter(b=>!b.closest('[hidden]')).map(b=>b.dataset.semantic)
const templateProgress={dualReviewRequired:false,reportCount:29,reviewBatches:0,contributorBatches:0,completedReviews:0,completedContributors:0,activeBatches:0,failedBatches:0,repairRound:0,documentPath:null}
beforeEach(()=>vi.useFakeTimers())
describe('TaskDetailView judge action',()=>{
 it('counts the persisted task diff when a document verifier has no changedPaths',async()=>{const p=await page({...reviewTask,artifacts:[{id:'document-diff',kind:'DIFF',title:'task-diff.json',createdAt:'now',content:'',metadata:{changedPaths:['docs/detail-design.md']}}]});await select('结果摘要');expect(p.view.get('[aria-label="结果摘要"] dl').text()).toContain('文件变更1')})
 it('offers a confirmed cancel action while the task is waiting for input',async()=>{const p=await page(reviewTask);await action('task.cancel');expect(p.cancel).not.toHaveBeenCalled();expect(body().text()).toContain('只有停止得到确认后');await confirm('task.cancel','取消任务');expect(p.cancel).toHaveBeenCalledWith('task-review');expect(p.view.text()).toContain('已取消')})
 it.each([{label:'取消任务',key:'task.cancel',method:'cancel' as const,task:reviewTask},{label:'重新发起双评审',key:'task.retryJudges',method:'judges' as const,task:reviewTask},{label:'继续一轮',key:'task.retryLoop',method:'loop' as const,task:{...reviewTask,loopRetryAvailable:true,stages:[{id:'stage-1',ordinal:1,objective:'待继续',status:'FAILED' as const,attempts:[]}]}},{label:'新分支重做',key:'task.redo',method:'rework' as const,task:{...reviewTask,branch:'loopper/review'}}])('invalidates the $label confirmation after leaving and returning to its task',async({key,method,task})=>{const p=await page(task);p.tasks.set('task-other',{...task,id:'task-other'});await action(key);const old=body().get(`[role=dialog] button[data-semantic="${key}"]`).element!;await p.navigation.push('/tasks/task-other');await p.navigation.push('/tasks/task-review');act(()=>fireEvent.click(old));await flushPromises();expect(p[method]).not.toHaveBeenCalled();expect(p.navigation.currentRoute.value.path).toBe('/tasks/task-review')})
 it('does not cancel after the confirmation owner unmounts',async()=>{const p=await page(reviewTask);await action('task.cancel');const old=body().get('[role=dialog] button[data-semantic="task.cancel"]').element!;p.unmount();act(()=>fireEvent.click(old));await flushPromises();expect(p.cancel).not.toHaveBeenCalled()})
 it('cancels a queued task so it can become eligible for archive and deletion',async()=>{const p=await page({...reviewTask,id:'task-queued',title:'排队任务',status:'QUEUED',worktreePath:'',stages:[],judges:[]});await action('task.cancel');await confirm('task.cancel','取消任务');expect(p.cancel).toHaveBeenCalledWith('task-queued');expect(p.view.text()).toContain('已取消');expect(p.view.find('[data-semantic="task.start"]').exists()).toBe(false)})
 it('starts or cancels a confirmed task before any workspace resource is allocated',async()=>{const p=await page({...reviewTask,id:'task-pending',title:'待开始任务',status:'PENDING_START',branch:'',worktreePath:'',stages:[],judges:[]});expect(visibleActions()).toContain('task.start');expect(p.view.text()).toContain('尚未入队');expect(p.view.text()).toContain('尚未分配');expect(p.start).not.toHaveBeenCalled();await action('task.cancel');await confirm('task.cancel','取消任务');expect(p.cancel).toHaveBeenCalledWith('task-pending');expect(p.start).not.toHaveBeenCalled()})
 it('manually reconciles a terminal holder and refreshes task and queue state',async()=>{const p=await page({...reviewTask,id:'task-queued',status:'QUEUED',worktreePath:'',stages:[],judges:[]});const reconcile=vi.spyOn(api,'reconcileTaskQueue').mockImplementation(async()=>{p.queue.mockResolvedValue({taskId:'task-queued',state:'ADMITTED',leaseState:'HELD',holderTaskId:'task-queued',reconcileAvailable:false});return{taskId:'task-queued',state:'ADMITTED',leaseState:'HELD',holderTaskId:'task-queued',reconcileAvailable:false}});await action('task.reconcileQueue');expect(reconcile).toHaveBeenCalledWith('task-queued');expect(p.overview).toHaveBeenCalledWith('task-queued');expect(p.queue.mock.calls.length).toBeGreaterThan(1)})
 it('keeps the blocker visible when manual reconciliation returns a 409 reason',async()=>{const p=await page({...reviewTask,id:'task-queued',status:'QUEUED',worktreePath:'',stages:[],judges:[]});p.queue.mockResolvedValue({taskId:'task-queued',state:'QUEUED',leaseState:'RELEASE_PENDING',holderTaskId:'holder-1',holderTaskTitle:'已取消的旧任务',holderTaskState:'CANCELLED',holderArchived:true,releaseReason:'SESSION_WRITER_UNCONFIRMED',reconcileAvailable:true});await action('ui.refresh');const reconcile=vi.spyOn(api,'reconcileTaskQueue').mockRejectedValue(new ApiError('当前写入 Session 尚未确认停止',409));await action('task.terminateQueueWriter');expect(body().text()).toContain('停止');await confirm('task.reconcileQueue','终止遗留会话并释放队列');expect(reconcile).toHaveBeenCalledWith('task-queued');expect(p.view.text()).toContain('当前写入 Session 尚未确认停止');expect(p.view.text()).toContain('已取消的旧任务');expect(p.view.find('[data-operation-phase="UNKNOWN"]').exists()).toBe(true)})
 it('groups execution progress by work package and shows each independent attempt pool',async()=>{const p=await page({...reviewTask,id:'task-packages',status:'RUNNING',judges:[],workPackages:[{id:'WP-1',ordinal:1,status:'SUCCEEDED',stageCount:2,completedStages:2,attemptCount:2,attemptLimit:4},{id:'WP-2',ordinal:2,status:'RUNNING',stageCount:1,completedStages:0,attemptCount:1,attemptLimit:3}]});await select('执行进度');const progress=p.view.get('[aria-label="工作包进度"]');expect(progress.text()).toContain('工作包 1');expect(progress.text()).toContain('2/4');expect(progress.text()).toContain('工作包 2');expect(progress.text()).toContain('1/3');expect(progress.text()).not.toContain('WP-1');expect(p.view.text()).not.toContain('Requirement / Risk Judge')})
 it('offers an explicit fresh double review for a deterministically accepted waiting task',async()=>{const p=await page(reviewTask);await select('双评审');expect(p.view.findAll('.w4-judge')).toHaveLength(2);await action('task.retryJudges');expect(p.judges).not.toHaveBeenCalled();expect(body().text()).toContain('独立只读双评审');await confirm('task.retryJudges');expect(p.judges).toHaveBeenCalledWith('task-review')})
 it('hides a historical judge conflict after the latest double review passes',async()=>{const p=await page({...reviewTask,id:'task-approved',status:'SUCCEEDED',errors:[failure('old-conflict','JUDGE_CONFLICT','旧双评审冲突','2026-10-02','VERIFICATION'),failure('verification-note','PROCESS_FAILED','仍需展示的普通验证证据','2026-10-02','VERIFICATION')],judges:[...reviewTask.judges!,{id:'requirement-2',role:'REQUIREMENT',ordinal:2,status:'COMPLETED',verdict:'PASS',reason:'需求已满足',createdAt:'later'},{id:'risk-2',role:'RISK',ordinal:2,status:'COMPLETED',verdict:'PASS',reason:'风险可控',createdAt:'later'}]});expect(p.view.findAll('.w4-layered-error')).toHaveLength(1);expect(p.view.text()).toContain('仍需展示的普通验证证据');expect(p.view.text()).not.toContain('旧双评审冲突');await select('双评审');expect(p.view.findAll('.w4-judge')).toHaveLength(2);expect(p.view.get('[aria-label="双评审"]').text()).toContain('需求已满足');expect(p.view.get('[aria-label="双评审"]').text()).not.toContain('证据不足')})
 it('offers one explicit fresh retry when unchanged loop protection is waiting for input',async()=>{const p=await page({...reviewTask,id:'task-stagnant',title:'停滞任务',stages:[{id:'stage-1',ordinal:1,objective:'修复验证',status:'RUNNING',attempts:[]}],judges:[],waitingReasonCode:'LOOP_STAGNATION_DETECTED',loopRetryAvailable:true,errors:[failure('stagnation','LOOP_STAGNATION_DETECTED','连续两轮未变化','now','VERIFICATION')]});expect(visibleActions().filter(k=>k==='task.retryLoop')).toHaveLength(1);expect(p.view.text()).toContain('显式继续一轮');await action('task.retryLoop');await confirm('task.retryLoop');expect(p.loop).toHaveBeenCalledWith('task-stagnant')})
 it('does not offer loop retry when an old stagnation error is not the current waiting reason',async()=>{await page({...reviewTask,id:'task-budget-wait',stages:[{id:'stage-1',ordinal:1,objective:'继续实现',status:'RUNNING',attempts:[]}],judges:[],waitingReasonCode:'TASK_BUDGET_WAITING_INPUT',loopRetryAvailable:false,errors:[failure('budget','TASK_BUDGET_WAITING_INPUT','等待调整预算'),failure('old-stagnation','LOOP_STAGNATION_DETECTED','历史停滞','earlier','VERIFICATION')]});expect(visibleActions()).not.toContain('task.retryLoop')})
 it('hides the resolved dirty-workspace alert after execution preparation continues',async()=>{const p=await page({...reviewTask,id:'task-dirty-resolved',status:'RUNNING',branch:'loopper/task-dirty-resolved',waitingReasonCode:undefined,judges:[],errors:[failure('dirty-history','SOURCE_BRANCH_WORKSPACE_DIRTY','历史未提交文件提示')]});expect(p.view.findAll('.w4-layered-error')).toHaveLength(0);expect(p.view.text()).not.toContain('历史未提交文件提示')})
 it('hides a historical task failure after a new execution cycle starts',async()=>{const p=await page({...reviewTask,id:'task-failure-resumed',status:'RUNNING',branch:'loopper/task-failure-resumed',waitingReasonCode:'DIRECT_WORKSPACE_UNAVAILABLE',judges:[],errors:[failure('workspace-history','DIRECT_WORKSPACE_UNAVAILABLE','历史项目目录失败')]});expect(p.view.findAll('.w4-layered-error')).toHaveLength(0);expect(p.view.text()).not.toContain('历史项目目录失败')})
 it('keeps only the latest task failure visible while its cycle awaits a decision',async()=>{const p=await page({...reviewTask,id:'task-failure-current',status:'AWAITING_DECISION',executionResult:'FAILED',judges:[],errors:[failure('current','DIRECT_WORKSPACE_UNAVAILABLE','当前失败','2026-10-03'),failure('historical','PROCESS_FAILED','历史失败','2026-10-02')]});expect(p.view.findAll('.w4-layered-error')).toHaveLength(1);expect(p.view.findAll('.w4-layered-error')[0]!.text()).toContain('当前失败');expect(p.view.findAll('.w4-layered-error')[0]!.text()).not.toContain('历史失败')})
 it('keeps the dirty-workspace alert visible while that wait reason is current',async()=>{const p=await page({...reviewTask,id:'task-dirty-current',status:'WAITING_INPUT',branch:'',worktreePath:'',waitingReasonCode:'SOURCE_BRANCH_WORKSPACE_DIRTY',judges:[],errors:[failure('dirty-current','SOURCE_BRANCH_WORKSPACE_DIRTY','当前未提交文件提示')]});expect(p.view.findAll('.w4-layered-error')).toHaveLength(1);expect(p.view.findAll('.w4-layered-error')[0]!.text()).toContain('当前未提交文件提示');expect(body().find('[role=dialog]').exists()).toBe(true)})
 it('creates a new branch rework task and navigates to the child',async()=>{const p=await page({...reviewTask,id:'task-success',title:'已完成任务',status:'SUCCEEDED',branch:'loopper/task-success'});await action('task.redo');expect(p.rework).not.toHaveBeenCalled();await confirm('task.redo');expect(p.rework).toHaveBeenCalledWith('task-success','REWORK_ALL_STAGES');expect(p.start).toHaveBeenCalledWith('task-rework');expect(p.navigation.currentRoute.value.path).toBe('/tasks/task-rework')})
 it('keeps completed template reports outside design, publication and human approval actions',async()=>{const p=await page({...reviewTask,status:'COMPLETED',executionResult:'SUCCEEDED',executionMode:'TEMPLATE_REPORT',hasDesignHistory:true});expect(visibleActions()).not.toContain('publication.createMergeRequest');expect(visibleActions()).not.toContain('judge.approve');expect(p.view.text()).not.toContain('查看设计过程');expect(p.view.text()).toContain('重新发起模板任务')})
 it.each(['COMPLETED','WAITING_INPUT'] as const)('hides Judge actions and metrics for a new template in %s',async status=>{const p=await page({...reviewTask,status,executionMode:'TEMPLATE_REPORT',judges:[],templateProgress});expect(p.view.text()).not.toContain('双评审');expect(p.view.text()).not.toContain('评审通过');expect(p.view.findAll('.w4-judge')).toHaveLength(0);expect(p.view.text()).toContain('报告文件29');if(status==='COMPLETED')expect(p.view.text()).toContain('报告已通过程序校验并保存')})
 it('mounts publication actions after a successful result is confirmed completed',async()=>{const p=await page({...reviewTask,id:'task-completed',status:'COMPLETED',executionResult:'SUCCEEDED',branch:'loopper/task-completed'});expect(p.view.find('[data-semantic="publication.createMergeRequest"]').isVisible()).toBe(true)})
})
