package io.opencode.loopper.service;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;

/** Model Markdown describes facts; navigation and source links are generated by the server. */
final class SourceDesignMarkdown {
    private SourceDesignMarkdown() { }
    static void validate(String markdown) {
        Parser.builder().build().parse(markdown).accept(new AbstractVisitor() {
            @Override public void visit(HtmlBlock node) { reject(); }
            @Override public void visit(HtmlInline node) { reject(); }
            @Override public void visit(Image node) { reject(); }
            @Override public void visit(Link node) { reject(); }
            private void reject() {
                throw new BadRequestException("SOURCE_MARKDOWN_LINK_INVALID",
                        "正文不能包含 HTML、图片或自建链接；文档目录和源码引用由程序生成");
            }
        });
    }
    static String text(String value) {
        return value.replace("\r", " ").replace("\n", " ").replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("|", "\\|").replace("`", "&#96;").replace("[", "&#91;").replace("]", "&#93;");
    }
}
