package io.opencode.loopper.service;

import io.opencode.loopper.config.LoopperProperties;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.Map;
import java.util.Set;
import org.springframework.stereotype.Component;

/** Writes the non-secret, script-readable mirror of settings without evaluating shell content. */
@Component
public class StartupSettingsFile {
    private final Path target;

    public StartupSettingsFile(LoopperProperties properties) {
        this.target = properties.getDataDir().toAbsolutePath().normalize()
                .resolve("config/startup-overrides.properties");
    }

    public Path path() {
        return target;
    }

    public Prepared prepare(Map<String, String> values) {
        try {
            Files.createDirectories(target.getParent());
            byte[] previous = Files.exists(target) ? Files.readAllBytes(target) : null;
            Path temporary = Files.createTempFile(target.getParent(), "startup-overrides-", ".tmp");
            StringBuilder content = new StringBuilder("# Generated by OpenCode Loopper. Do not add secrets.\n");
            values.forEach((key, value) -> content.append(key).append('=').append(value).append('\n'));
            Files.writeString(temporary, content.toString(), StandardCharsets.UTF_8);
            try {
                Files.setPosixFilePermissions(temporary, Set.of(PosixFilePermission.OWNER_READ,
                        PosixFilePermission.OWNER_WRITE));
            } catch (UnsupportedOperationException ignored) {
                // Windows does not expose POSIX permissions.
            }
            return new Prepared(target, temporary, previous);
        } catch (IOException failure) {
            throw new ServiceUnavailableException("STARTUP_SETTINGS_WRITE_FAILED",
                    "Startup settings could not be prepared: " + failure.getMessage());
        }
    }

    public static final class Prepared {
        private final Path target;
        private final Path temporary;
        private final byte[] previous;
        private boolean committed;

        private Prepared(Path target, Path temporary, byte[] previous) {
            this.target = target;
            this.temporary = temporary;
            this.previous = previous;
        }

        public void commit() {
            try {
                move(temporary, target);
                committed = true;
            } catch (IOException failure) {
                throw new ServiceUnavailableException("STARTUP_SETTINGS_WRITE_FAILED",
                        "Startup settings could not be activated: " + failure.getMessage());
            }
        }

        public void rollback() {
            try {
                if (committed) {
                    if (previous == null) Files.deleteIfExists(target);
                    else {
                        Path restore = Files.createTempFile(target.getParent(), "startup-overrides-restore-", ".tmp");
                        Files.write(restore, previous);
                        move(restore, target);
                    }
                }
                Files.deleteIfExists(temporary);
            } catch (IOException rollbackFailure) {
                throw new IllegalStateException("Startup settings rollback failed: " + rollbackFailure.getMessage(), rollbackFailure);
            }
        }

        private static void move(Path source, Path target) throws IOException {
            try {
                Files.move(source, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (AtomicMoveNotSupportedException ignored) {
                Files.move(source, target, StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }
}
